### ISSUE TITLE
[Pager] paggerState.currentPage updates with delay (600-800 MS)

### ISSUE THREAD

**Issue by Festak** [google/accompanist#1008]
Description:
If you have Horizontal Pager and scroll fast between the items, everything goes well and no problems, page updates immediately.
However, let's say, you scroll too slow and want to see all possible animations of custom pager indicators and etc. So you touch the item, scroll slowly to another one, see the second item, and put your finger up. The paggerState.currentPage update comes with a huge delay (it might come after 800 ms sometimes).

To reproduce:
Create the Pager,
Add logs to display the currentPage.
Scroll slowly from item 1 to item 2. 
When you can see item 2 (full item), put your finger up.
Check the logs.

Expected behavior:
The current page must be updated immediately: the same as for fast scrolling.

You can use my piece of code:
`

                val pagerState = rememberPagerState()

                val endPadding = 40.dp
                val startPadding = 40.dp
                val contentPadding = 20.dp

                HorizontalPager(
                    state = pagerState,
                    contentPadding = PaddingValues(
                        start = startPadding,
                        end = endPadding
                    ),
                    itemSpacing = contentPadding,
                    count = 6,
                    modifier = Modifier
                ) {
                    Card(
                        Modifier
                            .padding(all = 16.dp)
                            .fillMaxWidth()
                            .height(300.dp)
                    ) {

                        Text(
                            text = pagerState.currentPage.toString(),
                            textAlign = TextAlign.Center,
                            modifier = Modifier
                                .fillMaxSize()
                                .align(Alignment.CenterHorizontally)
                                .background(Color.Cyan)
                        )
                    }
                }
            }
`

**Comment by andkulikov** [comment]
What version of accompanist do you use?

**Comment by Festak** [comment]
@andkulikov Sorry mate.
Accompanist: 0.22.0-rc
Compose: 1.1.0-rc01

**Comment by ThankRain** [comment]
My temporarily solution is taking the currentPageOffset into consideration.Before the currentPage updating,the currentPageOffset is always great than 1.0 or less than -1.0,
try to plus the currentPageOffset after rounding can get the correct currentPage
