### ISSUE TITLE
[Navigation] Suggestion: Finish activity when BottomSheet is dismissed and there is nothing else on the backstack

### ISSUE THREAD

**Issue by alexstyl** [google/accompanist#1010]
**Description**
I am implementing DeepLinks into my app and in one of my use cases I am deepLinking into a bottomSheet() destination.
When I tap outside of the bottom sheet, then the bottom sheet is animated away but the scrim never goes away and the activity is not finished.

**Steps to reproduce**
1. DeepLink into a `bottomSheet()` destination.
2. Tap outside of the bottom sheet.

**Expected behavior** 
The activity holding the Composables to be `finish()`ed, given that nothing else is in the backstack.

**Additional context**
I am not sure if this is a responsibility of navigation-material or not, or whether it should do it automaticallly. I found it weird that I had to do this manually. Plus I had to do some digging in order to figure out how to do this (searched for some sort of bottomSheet state first, but there is none).

As a workaround I am doing:

In my bottomSheet() destination:
```kotlin
backstackEntry.OnDestroy {
    if (navController.previousBackStackEntry == null) {
        finish()
    }
}
```

OnDestroy implementation : 
```kotlin

@Composable
private fun NavBackStackEntry.OnDestroy(action: () -> Unit) {
    DisposableEffect(this) {
        val observer = LifecycleEventObserver { _, event ->
            if (event == Lifecycle.Event.ON_DESTROY) {
                action()
            }
        }
        lifecycle.addObserver(observer)
        onDispose {
            lifecycle.removeObserver(observer)
        }
    }
}

```

**Comment by ianhanniballake** [comment]
As per [the docs](https://developer.android.com/guide/navigation/navigation-navigate#back-stack), Navigation will never `finish()` your activity for you: the activity back stack is **not** part of the Navigation back stack.

You'll note that Navigation already correctly does **not** intercept the system back button when there is only one destination on the back stack - i.e., swiping back will close your activity (i.e., do the default behavior of the system back button).

I would strongly recommend reconsidering whether deep linking to a `FloatingWindow` destination, such as a bottom sheet makes any sense whatsoever: having your destination above whatever global UI you have outside of your `NavHost` and an empty `NavHost` underneath is what you are asking for, what you are getting, and exactly not what a user wants to see.

If you want a dialog styled activity that appears above another app, you'll want to create a separate activity for that deep link.
