### ISSUE TITLE
[Pager] Pager Cannot slide

### ISSUE THREAD

**Issue by huaweikai** [google/accompanist#1011]
**Description**
I tried to use the official infinite sliding example, but I found that when my count is set to 50 or 100, I can slide normally, but if it is set to Int.MAX_VALUE, I can only slide once, and the random sliding will be automatically bounced back to the previous page.
And when I use the CoroutineScope process to turn the page, there is no problem.
**Steps to reproduce**
Set cout to Int.MAX_VALUE
**Expected behavior** 
I can scroll all the way to the end
**Additional context**
 ``` kotlin
Column(Modifier.fillMaxSize()) {
            val pageCount = 10
            val startIndex = Int.MAX_VALUE / 2
            val pagerState = rememberPagerState(initialPage = startIndex)
            HorizontalPager(
                count = Int.MAX_VALUE,
                state = pagerState,
                contentPadding = PaddingValues(horizontal = 32.dp),
                itemSpacing = 4.dp,
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth()
            ) { index ->
                val page = (index - startIndex).floorMod(pageCount)
                PagerSampleItem(
                    page = page,
                    modifier = Modifier
                        .fillMaxWidth()
                        .aspectRatio(1f)
                )
            }

            ActionsRow(
                pagerState = pagerState,
                modifier = Modifier.align(Alignment.CenterHorizontally)
            )
        }
```

**Comment by huaweikai** [comment]
This problem exists in versions greater than 0.20.3

**Comment by andkulikov** [comment]
Seems similar to https://github.com/google/accompanist/issues/945. please try to use some smaller than Int.MAX_VALUE but still large value

**Comment by andkulikov** [comment]
Should be fixed by https://github.com/google/accompanist/pull/1058
