### ISSUE TITLE
[Insets] When UI is rendered behind top and bottom bar content - landscape mode will block UI

### ISSUE THREAD

**Issue by spacecowboy** [google/accompanist#1014]
**Description**

I am using the insets `Scaffold` to render my app behind the navigation bar. When rotating the app to landscape, the app still renders behind the navigation bar but because the navigation bar is now on the side it blocks the overflow menu button and other UI components.

In my opinion the library should have some default behavior to handle this.

**Steps to reproduce**

On a phone where the navigation bar moves to the side in landscape (not sure when Android started doing this??), rotate to Landscape with the UI rendered behind bottom navigation bar.

**Expected behavior** 

UI is not obscured by the navigation bar.

**Additional context**

Here are some screenshots of portrait vs landscape

![Portrait](https://user-images.githubusercontent.com/223655/153748791-bc5f1999-dff9-47c3-afcd-a58a7021ea79.png)

vs

![Landscape](https://user-images.githubusercontent.com/223655/153748815-6b4edba6-7505-4393-8299-7003b9709210.png)

**Comment by alexvanyo** [comment]
Hi, what code are you using to apply the insets to the app bar?

Does `systemBarsPadding(bottom = false)` meet your needs?

**Comment by spacecowboy** [comment]
Thanks for your answer.

I am using the same as in your sample: https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/insets/InsetsBasicSample.kt

```
TopAppBar(
  contentPadding = rememberInsetsPaddingValues(
    LocalWindowInsets.current.statusBars,
    applyBottom = false,
  ),
  [...]
)
```

After your comment, changing it to `LocalWindowInsets.current.systemBars` fixes the issue for the top app bar.

And adding contentPadding to Scaffold as

```
Scaffold(
  scaffoldState = scaffoldState,
  // In case device is rotated to landscape and navigation bar ends up on the side
  contentPadding = rememberInsetsPaddingValues(
    insets = LocalWindowInsets.current.navigationBars,
    applyBottom = false,
    applyTop = false,
  ),
  [...]
)
```

fixes the content within. Maybe the samples should be updated so they're useful even if the content is rotated?
