### ISSUE TITLE
[Insets] conflict between accompanist and androidx.compose.foundation.layout

### ISSUE THREAD

**Issue by ThankRain** [google/accompanist#1016]
**Description**
The `androidx.compose.foundation.layout package` contains the same function `imePadding()` `systemBarsPadding()`,etc. So if anyone<del>(such as me)</del> use these functions in different package , the functions in accompanist didn't works,especially the functions about ime,I don't consider it as a bug that need to be fixed,but I think it's necessary to remind people in the guide book

**Steps to reproduce**

import androidx.compose.foundation.layout.systemBarsPadding // usually AS would convey it to `import androidx.compose.foundation.layout.*`
import com.google.accompanist.insets.imePadding
        Modifier
            .imePadding()
            .systemBarsPadding()

**Expected behavior** 

**Additional context**

**Comment by alexvanyo** [comment]
Yep, this is expected! The `androidx` version of insets is currently in development, which should eventually replace accompanist/insets. Migration guidance will be coming, but in the meantime I'd recommend using one or the other since they won't interop that nicely.
