### ISSUE TITLE
[Pager] HorizontalPager scroll with a swipe gesture can't be disabled

### ISSUE THREAD

**Issue by PavloZoria** [google/accompanist#1018]
**Description**
I have a use case where I want to have a view pager that should be controlled only programmatically.

In a previous version of the library(0.17.0) we could disable manual scrolling by passing a `dragEnabled` parameter to the `HorizontalPager` but after an update to the 0.23.0 version, this parameter was removed.

**Expected behavior** 
To be able to disable scrolling of the `HorizontalPager` with a gesture

**Comment by andkulikov** [comment]
This parameter was re-added in v0.24.1-alpha with the userScrollEnabled name. Note that it uses Compose 1.2.0-alpha under the hood
