### ISSUE TITLE
[System UI Controller] rememberSystemUiController setStatusBarColor flicker

### ISSUE THREAD

**Issue by gaohomway** [google/accompanist#1026]
I have two pages A and B with white and black background colors.

I need to change the status bar color when switching between two pages.

I use `rememberSystemUiController` to change the status bar color, but there is flickering, jerky, and the transition is not smooth.

[Blink effect YouTube][1]

```
@Composable
fun APager() {
    val systemUiController = rememberSystemUiController()
    val background = MaterialTheme.colorScheme.background

    SideEffect {
        systemUiController.setStatusBarColor(background)
    }

    // ...
}

@Composable
fun BPager() {
    val systemUiController = rememberSystemUiController()
    val black = MaterialTheme.colorScheme.black

    SideEffect {
        systemUiController.setStatusBarColor(black)
    }

    // ...
}

```

  [1]: https://youtu.be/pD2LiJ0Y5wc

**Comment by alexvanyo** [comment]
Do you have a signal available for which `Pager` is the "target" one in the animation?

What might be happening is that the two `SideEffect`s are fighting each other, when both pagers are visible during the transition.

If only the "target" pager tries to update the status bar color (the one that will end up being shown when the animation is done), that might fix the flickering.

**Comment by gaohomway** [comment]
[has been resolved](https://stackoverflow.com/questions/71137571/jetpack-compose-remembersystemuicontroller-setstatusbarcolor-flicker)

**Comment by alexvanyo** [comment]
Excellent, glad to hear!
