### ISSUE TITLE
[Pager] Duplicate content root (sharedTest) results in no code insight in Android instrumentation tests

### ISSUE THREAD

**Issue by ChrisSawczukMSM** [google/accompanist#1032]
**Description**
The use of the following Gradle configuration:

```groovy
    sourceSets {
        test {
            java.srcDirs += 'src/sharedTest/kotlin'
            res.srcDirs += 'src/sharedTest/res'
        }
        androidTest {
            java.srcDirs += 'src/sharedTest/kotlin'
            res.srcDirs += 'src/sharedTest/res'
        }
    }
```

Allows a Gradle build to include the source code and resources in both the Unit Test and Android Instrumentation Test builds but results in an error in Android Studio Chipmunk and later.

Opening `InstrumentedVerticalPagerTest` in Android Studio Chipmunk results in `BaseVerticalPagerTest` to be highlighted as an error.

**Steps to reproduce**

1. Import the project in Android Studio Chipmunk
2. Observe popup in the bottom right informing you that a duplicate content root has been identified and removed
3. Open `InstrumentedVerticalPagerTest`
4. Observe `BaseVerticalPagerTest` symbol being highlighted as an error

**Expected behavior** 
Importing the project and opening the `InstrumentedVerticalPagerTest` should not result in `BaseVerticalPagerTest` being highlighted as an error.

**Additional context**
This seems to be the fallout from the following issues highlighted on the the Jetbrains YouTrack system:

[IDEA-211101](https://youtrack.jetbrains.com/issue/IDEA-211101)
[IDEA-210908](https://youtrack.jetbrains.com/issue/IDEA-210908)
[IDEA-173265](https://youtrack.jetbrains.com/issue/IDEA-173265)
[IDEA-210311](https://youtrack.jetbrains.com/issue/IDEA-210311)

**Comment by andkulikov** [comment]
It is not the bug in the library that the IDE you are using to open the sources of it is working incorrectly. Please file a bug on Android Studio/Intellij Idea if you think the bugs you are already linked are not covering everything.
