### ISSUE TITLE
[Pager] Item scroll effects

### ISSUE THREAD

**Issue by eglogis** [google/accompanist#1033]
**Description**
Hi! I want to do something like this https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerTransitionSample.kt

But I'm having problems with the PaddingValue of the HorizontalPager. In the example, the PaddingValue always has a value of 32.dp, but I need the first page to have a PaddingValue(start = 24.dp, end = 42.dp) and the following pages to have PaddingValue(42.dp).
I'm trying to do something like this: 
![image](https://user-images.githubusercontent.com/45403730/154665376-dd5ced1d-f159-4475-b02f-54aa93b1bd70.png)
But it doesn't work well
if you can help me I would be very grateful.

**Comment by andkulikov** [comment]
Hey. I added a demo how use case like this could be solved
