### ISSUE TITLE
[Web] Load data with `rememberWebViewStateWithHTMLData` always fails when providing a baseUrl

### ISSUE THREAD

**Issue by TonnyL** [google/accompanist#1037]
## Describe the bug
Run code below, and `WebView` says `Webpage not available ... net::ERR_FILE_NOT_FOUND`

## To Reproduce (if applicable)
```kotlin
class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                // A surface container using the 'background' color from the theme
                Surface(color = MaterialTheme.colors.background) {
                    val state = rememberWebViewStateWithHTMLData(
                        data = "",
                        baseUrl = "file:///android_asset/"
                    )
                    WebView(state = state)
                }
            }
        }
    }
}
```

## Expected behavior (if applicable)
Load the webpage data properly

## Screenshots? (if applicable)
![2022-02-20 17 06 42](https://user-images.githubusercontent.com/13329148/154835726-11780c8d-85f5-4059-93b6-25f2e641f76e.jpg)

## Environment: (if applicable)
 - Android OS version: 11
 - Device: OnePlus 8T
 - Accompanist version: 0.24.2-alpha

## Additional context
I had a glance at the source code, and I think the here is the problem:

```kotlin
override fun doUpdateVisitedHistory(
    view: WebView?,
    url: String?,
    isReload: Boolean
) {
    super.doUpdateVisitedHistory(view, url, isReload)
    // WebView will often update the current url itself.
    // This happens in situations like redirects and navigating through
    // history. We capture this change and update our state holder url.
    // On older APIs (28 and lower), this method is called when loading
    // html data. We don't want to update the state in this case as that will
    // overwrite the html being loaded.
    if (url != null &&
        !url.startsWith("data:text/html") &&
        state.content.getCurrentUrl() != url
    ) {
        // state.content = WebContent.Url(url) // <------ Here if I comment out this line, the problem was gone.
    }
}
```

**Comment by bentrengrove** [comment]
I'm a bit confused about what you are trying to load sorry. That method was basically designed for loading HTML strings but you are passing in an empty string?

**Comment by TonnyL** [comment]
You could pass any html string, it has the same result.

**Comment by bentrengrove** [comment]
Do you have image files in android_assets or something you are trying to base it on?

**Comment by bentrengrove** [comment]
Ah I see now, if you provide a baseUrl it always fails. Thanks for the report. I will get this fixed.
