### ISSUE TITLE
[Pager] PagerState.currentPage snapshotFlow emits multiple times on init

### ISSUE THREAD

**Issue by maggud** [google/accompanist#1038]
**Description**
When I try to copy the [Reacting to page changes](https://google.github.io/accompanist/pager/#reacting-to-page-changes) to add logs on page changed, it logs too often.

**Steps to reproduce**
Sample code:
```kotlin
@Composable
@OptIn(ExperimentalPagerApi::class)
private fun PagerLogTest() {
    val pageCount = 10
    val pagerState = rememberPagerState(initialPage = pageCount - 1)

    LaunchedEffect(pagerState) {
        snapshotFlow { pagerState.currentPage }.collect { pageIndex ->
            Log.d("Logger test", "PageIndex: $pageIndex")
        }
    }

    HorizontalPager(
        count = pageCount,
        state = pagerState,
    ) { page ->
        Text(text = "Page: $page")
    }
}
```

1. Open the view and observe the logs

**Expected behavior** 

I expect to see the following output: 

```
Logger test: PageIndex: 9
```

Actual output is:
```
Logger test: PageIndex: 9
Logger test: PageIndex: 0
Logger test: PageIndex: 9
```

**Additional context**
Ideally I would like to have some way to only react to actual changes, not the initial state, similar to how an `onPageChangedListener` would work. I'm not entirely sure how to achieve this with the current state of the library.

Tested on version `0.22.1-rc` and `0.23.0`

**Comment by ege-ah** [comment]
any update on this? it looks like it logs in first initialization, before page change too

**Comment by pstambrecht** [comment]
I'm facing the same problem. Please fix it.

**Comment by andkulikov** [comment]
Just tested with all the recent changes and it is not reproducible anymore
