### ISSUE TITLE
[Pager] Circular bi-directional view pager support

### ISSUE THREAD

**Issue by iamutkarshtiwari** [google/accompanist#1041]
**Description**

This is not a bug but a feature request. I am trying to create a circular view pager that supports endless scroll in both directions.

Let's say I have 5 items in the view pager, and if after reaching to the 5th item, if I try to scroll right, I see the first item but in continuation as if it was appended in front of it.

<img width="501" alt="view pager" src="https://user-images.githubusercontent.com/6258810/155068863-f4b38e0a-98fa-45b7-94ef-a49554fb7cf2.png">

https://user-images.githubusercontent.com/6258810/155082057-59578177-226d-4991-a0c6-30e6121cb0dc.mp4

I don't think it's possible to achieve this continuous flow with the current api. It can work but user will see the viewpager scrolling all the way back to the front which kind of breaks the flow.
Or I have to create my own custom implementation by using accompanis's `HorizontalPager` code which I don't think would be easily maintainable.

**Comment by andkulikov** [comment]
Please check out this sample https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerLoopingSample.kt

**Comment by iamutkarshtiwari** [comment]
@andkulikov Sorry if I don't understand it well enough, but what would happen if the user ends up scrolling continuously in one direction towards right until Integer.MAX_VALUE? 🤔 

Doesn't it seem like a hack?: https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerLoopingSample.kt#L79

**Comment by andkulikov** [comment]
I don't think it is practically possible for a real user to scroll your pager for so long so they face the end of it

**Comment by iamutkarshtiwari** [comment]
Makes sense. Thank you for helping me out 🙇
