### ISSUE TITLE
[Permissions] - PermissionUsageHelper causes memory leak on configuration change (rotation)

### ISSUE THREAD

**Issue by austinduran** [google/accompanist#1044]
**Description**

LeakCanary has notified us of a Memory Leak that is triggered by the PermissionUsageHelper which is implemented by AppOpsManager when we rotate the device mutliple times. As far as we can tell we're using our rememberPermissionState() and .launchPermissionRequest() in a way that matches the docs here: https://google.github.io/accompanist/permissions/

**Steps to reproduce**
1. In a view that requires permissions (Camera, Map) launch the permissions onClick, onNavigation... etc. 
2. Once permissions have been granted, proceed to use your granted feature (Camera, Map).
3. Rotate the device numerous times (at least 10-20 times)
4. A LeakCanary notification will arise with the Heap Dump info.
5. View the Log
6. Log looks something like:
```
    ====================================
    HEAP ANALYSIS RESULT
    ====================================
    1 APPLICATION LEAKS

    References underlined with "~~~" are likely causes.
    Learn more at https://squ.re/leaks.

    16646334 bytes retained by leaking objects
    Displaying only 1 leak trace out of 4 with the same signature
    Signature: b7c81aff62fcf437fefb4ace2f786ab2fa9ed657
    ┬───
    │ GC Root: Global variable in native code
    │
    ├─ android.app.AppOpsManager$3 instance
    │    Leaking: UNKNOWN
    │    Retaining 536 B in 1 objects
    │    Anonymous subclass of com.android.internal.app.IAppOpsActiveCallback$Stub
    │    ↓ AppOpsManager$3.val$callback
    │                      ~~~~~~~~~~~~
    ├─ android.permission.PermissionUsageHelper instance
    │    Leaking: UNKNOWN
    │    Retaining 126 B in 5 objects
    │    mContext instance of com.jobnimbus.leadssalesprojects.ui.main.MainActivity with mDestroyed = true
    │    ↓ PermissionUsageHelper.mContext
    │                            ~~~~~~~~
    ╰→ com.jobnimbus.leadssalesprojects.ui.main.MainActivity instance
    ​     Leaking: YES (ObjectWatcher was watching this because com.jobnimbus.leadssalesprojects.ui.main.MainActivity
    ​     received Activity#onDestroy() callback and Activity#mDestroyed is true)
    ​     Retaining 4.6 MB in 29884 objects
    ​     key = d719c118-f1f7-4a7d-8415-eb887c3a1ca3
    ​     watchDurationMillis = 26488
    ​     retainedDurationMillis = 21487
    ​     mApplication instance of com.jobnimbus.leadssalesprojects.JNApplication
    ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper
    ====================================
```
**Expected behavior** 
No memory leak happens on configuration change (rotation)
**Additional context**

**Comment by austinduran** [comment]
Curious if this has been prioritized at all @manuelvicnt

**Comment by manuelvicnt** [comment]
Hi! It looks like the happens in `android.permission.PermissionUsageHelper` which isn't a class part of the Accompanist library. Do you know if the same leak happens _without_ using Accompanist?

**Comment by rmoon6** [comment]
I am getting this exact same error in a codebase that does not use Accompanist (or compose at all). It is using the EasyPermissions library for runtime permissions.

Initially, I thought that the EasyPermissions library might be the cause of the leak, but it looks like they're happening regardless.

**Comment by alexvanyo** [comment]
Closing this issue as this is related to platform methods which Accompanist has no control over.

FWIW, [this commit](https://cs.android.com/android/_/android/platform/frameworks/base/+/0d47a03bfa8f4ca54b883ff3c664cd4ea4a624d9) might have fixed the leak you were seeing.
