### ISSUE TITLE
[Insets] Switching to official Compose API

### ISSUE THREAD

**Issue by dovahkiin98** [google/accompanist#1051]
Not that Compose has an official Insets API, I was wondering whether Accompanist will switch to using that API instead or will it keep using the custom one?

I tried using both, but it seems to get confused when you use both sides of the Insets (for example, `navigationBarPadding` with `windowInsets(NavigationBars)`)

**Comment by alexvanyo** [comment]
Yes, the migration process is underway!

You can see an in-progress PR with under-review migration steps here: #1034
