### ISSUE TITLE
[Web] WebView as lazy list item cannot load webpage properly

### ISSUE THREAD

**Issue by TonnyL** [google/accompanist#1063]
### Discussed in https://github.com/google/accompanist/discussions/1053

<div type='discussions-op-text'>

<sup>Originally posted by **TonnyL** February 26, 2022</sup>
```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                val lists = listOf(
                    "https://google.github.io/accompanist/",
                    "https://github.com",
                    "https://www.youtube.com/"
                )
                LazyColumn {
                    items(lists.size) {
                        val state = rememberWebViewState(lists[it])
                        WebView(state = state)
                    }
                }
            }
        }
    }
}
```

Code above cannot load webpage properly. Anybody has some ideas?</div>

Run code above on a physical device, it has two main problems:
1. the webpage content are flashing sometimes;
2. user cannot scroll list to bottom

**Comment by TonnyL** [comment]
I don't think setting the webview a fixed size could solve my problem. Take the github issue timeline page (https://github.com/google/accompanist/issues/1063) as an example, every comment here is in html format, if I set the webview a fixed size, the whole ui will look odd.

**Comment by bentrengrove** [comment]
What is your expected behaviour? That the webview wraps the content loaded within it and then all of them scroll together in a LazyList?

**Comment by TonnyL** [comment]
> What is your expected behaviour? That the webview wraps the content loaded within it and then all of them scroll together in a LazyList?

Yes, exactly.
