### ISSUE TITLE
[Permissions] nothing happens on calling launchMultiplePermissionRequest.

### ISSUE THREAD

**Issue by divyanshu-in** [google/accompanist#1064]
**Description**
Api level - 31
aaccompanist-permissions version - 0.24.3-alpha

I've added these permissions to manifest as well, but when button is clicked nothing happens, although when I remove  ACCESS_BACKGROUND_LOCATION from the list, it works as intended.

```
@Composable
fun MapView() {

    val permissionList = arrayListOf(Manifest.permission.ACCESS_FINE_LOCATION,
        Manifest.permission.ACCESS_COARSE_LOCATION)



    if (Build.VERSION.SDK_INT >= Q) permissionList.add(Manifest.permission.ACCESS_BACKGROUND_LOCATION)

    val rememberPermissionState = rememberMultiplePermissionsState(permissions = permissionList)

    Button(onClick = {
        rememberPermissionState.launchMultiplePermissionRequest()
    }) {
    }
}
```

**Comment by ianhanniballake** [comment]
This is how the Location permissions work as per [the documentation](https://developer.android.com/training/location/permissions#request-only-foreground):

> **Caution:** If your app targets Android 11 (API level 30) or higher, the system enforces this best practice. If you request a foreground location permission and the background location permission at the same time, the system ignores the request and doesn't grant your app either permission.
