### ISSUE TITLE
[Navigation] isSkipHalfExpanded for bottomSheetNavigator

### ISSUE THREAD

**Issue by ThatsMeJavad** [google/accompanist#1070]
**Description**
jetpack compose version 1.2.0-alpha01 now has ModalBottomSheetState that has an isSkipHalfExpanded flag. It can be either set through the constructor or updated later on by setting ModalBottomSheetState's isSkipHalfExpanded property to true.

I need that feature in the accompanist with bottomSheetNavigator.

does someone working on it or in the near future plan it is to be done?

**Comment by PhilipDukhov** [comment]
This issue should be re-opened
