### ISSUE TITLE
[WebView] Backport to Accompanist 0.23

### ISSUE THREAD

**Issue by svenjacobs** [google/accompanist#1083]
Please backport [WebView](https://google.github.io/accompanist/webview/) to Accompanist 0.23. WebView is currently only available in 0.24, which is based on Compose 1.2.0-alpha.

PS: What happened to GitHub Discussions? It seems they have been disabled for this project 😢

**Comment by bentrengrove** [comment]
WebView was not put in to the Compose 1.1 branch as it's under active development and the API is changing which means it doesn't meet the criteria for a stable release unfortunately. As a workaround you could look how it is implemented and wrap `WebView` with `AndroidView` yourself to meet your requirements. Sorry I don't have a better option for you.

As for GitHub discussions, we decided to turn them off as they were going neglected and to focus our efforts on the issues for when people need support.
