### ISSUE TITLE
[Pager] Improve current page detection?

### ISSUE THREAD

**Issue by Tolriq** [google/accompanist#1087]
**Description**

Currently current page is determined by the item with the largest visible area on screen. 
This means that when there's a single item visible at most the page change when scrolling at 50,x %.
While this sounds like a normal default, for my use case this is not perfect, since users may want to peek at the next item without actually changing to it and 50% is short distance to see the next item.
(A now playing carrousel showing currently playing items and next/previous ones)

**Steps to reproduce**

Normal usage of the pager.

**Expected behavior** 

Current behavior can be expected, so this is more a feature request to support other behaviors.

**Additional context**

I have no idea how to hack this currently as the mostVisiblePageLayoutInfo is lacking the scroll direction to be able to determine the current page properly without keeping a reference to it and possible side effects on lazylist content change.

**Comment by andkulikov** [comment]
Is this what you want to achieve? https://github.com/google/accompanist/pull/1047#issuecomment-1050948926

**Comment by Tolriq** [comment]
Exactly and working perfectly. I searched in issues, did not thought about PR / commits.

I think this may be a relatively common need, maybe add a note somewhere in the doc?

Anyway thanks for the fast answer.

**Comment by Tolriq** [comment]
Actually after reading again the code this trigger my additional context question.

If we are currently scrolling and the pager content change, the settledCurrentPage might have a wrong value causing issues.

**Comment by andkulikov** [comment]
Please try to explain your requirements in more details then. When exactly do you want this property to be updated

**Comment by Tolriq** [comment]
The need is as you understood have the property updated when the scroll end, but the underlying data might be changing too.

To better explain the current usage:
One screen with an horizontal pager, the pager shows 1 full screen image of the currently playing item.
When the current song change the pager scroll `pagerState.animateScrollToPage(playbackCurrentIndex)`

When the user drag & drop the image and it reaches the next position the player start playing the new song. Current behavior make the new song start as soon as the user have scrolled half way this is too soon.

But on further testing the proposed code works, there's a completely different issue with the Pager.

If you are dragging the pager and call ` pagerState.scrollToPage(playbackCurrentIndex)` the call never ends / returns blocking the rest of the code in that coroutine.
Should I open another issue?

**Comment by andkulikov** [comment]
> If you are dragging the pager and call pagerState.scrollToPage(playbackCurrentIndex) the call never ends / returns blocking the rest of the code in that coroutine.
Should I open another issue?

Yes, please file it as a separate issue, thanks. Also worth checking if it works the same with just LazyRow, so it can be filed in the Compose tracker
