### ISSUE TITLE
[Placeholder] Placeholdered UI is still clickable

### ISSUE THREAD

**Issue by Skeletonxf** [google/accompanist#1098]
## Describe the bug
When using the `Modifier.placeholder` function, the UI the modifier draws as skeleton UI can still be interacted with.

## To Reproduce
Use the placeholder modifier on a Composable function which contains an interactable element such as a button or something with the clickable modifier.

Sample code
```kotlin
@Composable
fun Sample() {
    var clicks by remember { mutableStateOf(0) }
    Column() {
        Text(text = "Clicks: $clicks")
        Button(
            onClick = { clicks += 1 },
            modifier = Modifier.placeholder(true)
        ) {
            Text(text = "Click me")
        }
    }
}
```

## Expected behavior
This is confusing because the skeleton UI does not have the usual visible interactions such as ripples and the user cannot see the UI to know that there is actually something clickable there. This might also pose a problem for screen readers if a piece of UI is in a placeholder skeleton state but still appears as clickable to the screen reader.

I would expect the placeholder modifier to disable taps/clicks when `visible` is true.

## Environment:
 - Accompanist version: 0.23.1

**Comment by bentrengrove** [comment]
I can definitely imagine use cases for wanting to click on a placeholder so this suggested feature would be too restrictive. I think in your case you should use the same state that is determining the placeholder as state for if the button is enabled.
