### ISSUE TITLE
[Pager] Make PagerScope a ViewModelScopeOwner and LifecycleOwner

### ISSUE THREAD

**Issue by yschimke** [google/accompanist#1105]
For Wear apps we need to manage the FocusRequestor when navigation destination or pager changes.

With Navigation 2.5.0-alpha this works well for Navigation.

```
public open class NavScaffoldViewModel(
...
) : ViewModel() {
...
``` 

or in the destination.

```
    composable(route, arguments, deepLinks) {
        val lifecycle = LocalLifecycleOwner.current.lifecycle
        
        LaunchedEffect(lifecycle) {
            lifecycle.repeatOnLifecycle(Lifecycle.State.RESUMED) {
                focusRequester.requestFocus()
            }
        }
```

It would be nice if a similar pattern was possible for pager.  

Pause, Resume would be great if they fired when the page changed.

**Comment by andkulikov** [comment]
Pager is not a navigational component on its own. So it shouldn't know anything about the lifecycles. But you can build something which does the needed wiring on top of it.
Maybe something like this is what you need?
 ```
            val pagerState = rememberPagerState()

            LaunchedEffect(pagerState) {
                snapshotFlow { pagerState.currentPage }
                    .collect {
                        .. do focus
                    }
            }
```

**Comment by andkulikov** [comment]
Sorry, but I don't really understand how this should work in your opinion. Again, I am pretty confident that Pager should stay "just" a layout which does the scrolling and not be aware about anything navigation related, has no dependencies on ViewModels, etc.
Maybe you want to build your own navigation solution on top of Pager - ok. Like I remember we have a navigation host which displays its "screens" as Dialogs, this could be something similar.

**Comment by yschimke** [comment]
@andkulikov That makes sense and works. I'll wrap pager in my case and implement the bits I'm suggesting.

I think my core disconnect is that Pager breaks the assumptions that hold in various other places like Activities and Navigation, so code working there can break and require other wiring to get it working again.  That was what I was struggling with and why I suggested this.

But as you say, it can be implemented on top, it doesn't have to live in Pager, which can remain a simple un-opinionated UI component.
