### ISSUE TITLE
[System UI Controller] Support using Window from Dialog

### ISSUE THREAD

**Issue by lhwdev** [google/accompanist#1110]
**Description**
Using `rememberSystemUiController` inside does not work well when in the `Dialog`.
I am trying to implement full screen dialog where dialog expands below system ui, but `SystemUiController` seems to refer the
`Window` of `Activity` below the `Dialog`.

**Steps to reproduce**
Use `rememberSystemUiController` inside any Dialog.

**Expected behavior** 
It should be able to control, for example, `statusBarDarkContentEnabled` etc.
``` kotlin
// code fragment from accompanist
 private fun Context.findWindow(): Window? {
        var context = this
        while (context is ContextWrapper) {
            if (context is Activity) return context.window
            context = context.baseContext
        }
        return null
    }
```
When calling `rememberSystemUiController()`, it lookup Window from `LocalView`. Unfortunately this only pulls Window from
Activity. [DialogLayout implements `DialogWindowProvider`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/window/AndroidDialog.android.kt;l=203), but LocalView itself becomes `AndroidComposeView`, so in dialog you should do below to get Window.
``` kotlin
(LocalView.current.parent as DialogWindowProvider).window
```
But it would be dirty to do this and maybe quite fragile. Adding `window` parameter to `rememberSystemUiController` also seems to feasible. Support for dialog may not exist, (seems to be rare case) but at least one should be able to customize it, such as making `AndroidSystemUiController` public and adding window parameter to it.

**Additional context**
(none)

**Comment by alexvanyo** [comment]
This makes sense, and I was not aware of `DialogWindowProvider`!

I have a pending feature request of https://issuetracker.google.com/issues/221889664 which would impact what this looks like, but in the meantime I think a decent API would be to add a `Window` parameter to `rememberSystemUiController`, with a default value that first tries to fetch the `DialogWindowProvider`'s `Window` as you described, and then falls back to finding the `Activity` `Window` (the current behavior).

By making a parameter, you could also manually specify the correct `Window` in cases where the default behavior isn't correct (perhaps passing a `Dialog` `Window` for a `Dialog` that isn't controlled directly by `Compose` in a Fragment interop case)
