### ISSUE TITLE
[Permissions] "Call requires permission which may be rejected by user"

### ISSUE THREAD

**Issue by WebTiger89** [google/accompanist#1111]
It's more of a question rather a bug of accompanist. It might be a bug with android lint. Since API 31 some of androids Bluetooth API is marked red:

> Call requires permission which may be rejected by user:  code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException

For example in my viewmodel:
```
    fun enableBluetooth() {
        bluetoothAdapter.enable()
    }
```
is marked red. Options are `@SuppressLint("MissingPermission")` or
```
    @RequiresApi(Build.VERSION_CODES.S)
    @RequiresPermission(BLUETOOTH_CONNECT)
    fun enableBluetooth() {
        bluetoothAdapter.enable()
    }
```
or sorround it with `checkSelfPermission`, but this belongs to compose part of code.

The 2nd approach propagates the warning to the calling code, so the compose part. And although I do this:
```
PermissionStatus.Granted -> {
    viewmodel.enableBluetooth() // marked red with warning message above
}
```
the call is still marked red. The code build and runs fine because _Permissions_ library handle the check in the background properly, so what do I miss here? Is it an android lint bug? Should I file an issue at android bug tracker?

**Comment by Sushant-1999** [comment]
Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException

How to remove this error ?
