### ISSUE TITLE
HorizontalPager with FlingBehavior does nto snap to item when stop...

### ISSUE THREAD

**Issue by LilMoke** [google/accompanist#1116]
## Describe the bug
When you use a HorizontalPage with a FlingBehavior:  
```
	HorizontalPager(
		state = pagerState,
		count = count,
		contentPadding = PaddingValues(horizontal = horizontalPadding, vertical = verticalPadding),
		flingBehavior = ScrollableDefaults.flingBehavior()

```

AND, the fling stops it does not snap to the item.

## To Reproduce
1. Create a HorizontalPage with a FlingBehavior
2. Use finger to scroll to an item

## Expected behavior
When user stops scrolling it should snap to the item

## Environment:
 - Android OS version: [e.g. Android 5.0]
 - Device: Google Pixel 4 Emiulator and Samsung S10 Physical Device
 - Accompanist version: 0.19

## Additional context
If you do not add a FlingBehavior then you need to pause when scrolling through items

**Comment by bentrengrove** [comment]
Have you verified this is occurring on a more recent version of Accompanist?

**Comment by LilMoke** [comment]
I have only tried it on the latest 0.19 version.  I have not tried it on any of the alpha releases.  I do know it does not happen on earlier versions, but that was before the rewrite that models Pager after LazyRow and LazyColumn.  I was assuming that adding a flingBahavior would make it snap, but that does not seem to be the case.  In the earlier version you could use your finger and swipe quickly and it snapped on stopping the swipe.

Does that answer your question?

**Comment by bentrengrove** [comment]
0.19 is not the latest stable version. 0.23.1 is to match with Compose 1.1.1

**Comment by LilMoke** [comment]
Ahh, ok, I did not know that.  I will try it with 0.23.1 and report back.  I will try it with and without the flingBehavior.  If it does not work, I will also post a code snippet.

**Comment by LilMoke** [comment]
Ben,

Yes, using 0.23.1 corrects the issue.  Thank you.  Both with and without flingBehavior.
