### ISSUE TITLE
LocalWindowInsets.current.ime.isVisible returns true by default on resume

### ISSUE THREAD

**Issue by LukeKall** [google/accompanist#1121]
## Describe the bug
LocalWindowInsets.current.ime.isVisible returns true on resume screen before to return false after some time.

## Expected behavior
After inspecting code, i saw "true" is the default value before the real value is set. Keyboard is most of the time closed on resume screen, so maybe the default value should be false.

## Environment:
 - Android OS version: Android 11
 - Device: OnePlus 6
 - Accompanist version: 0.23.1
 - Compose version: 1.1.1

## Additional context
I use this value to detect keyboard opening/closing events, so the value beging true then false, i detect a false closing event.

**Comment by alexvanyo** [comment]
Hi, thank you for the report!

accompanist/insets is now deprecated in favor of insets support built-in to `androidx.compose.foundation`, so there's no plan to continue to improve accompanist/insets. Support for `isVisible` was just merged in upstream, so once that's available I'd recommend migrating, and see if you encounter the same issues there. If you do, please raise a bug on the androidx issue tracker!
