### ISSUE TITLE
WebView - `loadingState` is initialized with the `LoadingState.Finished`

### ISSUE THREAD

**Issue by anvukelic** [google/accompanist#1122]
Considering this could be used for showing some spinner or animating WebView when the content is loaded for the first time, should you consider changing `loadingState` to be initialized with the `LoadingState.Loading` or `null`?

There is not much data I can provide to you, but my observation is visible just by looking at the initial value of `loadingState` property.

P.S. - I wanted to place this as an Open Discussion but GitHub is throwing a 404 when selecting that option.

Let me know what you think.

**Comment by bentrengrove** [comment]
This makes sense to me. I will make that fix for you

**Comment by anvukelic** [comment]
@bentrengrove thanks for this change 👍
