### ISSUE TITLE
[Web] Idea: Use RecycledViewPool to cache WebView instances

### ISSUE THREAD

**Issue by alexvanyo** [google/accompanist#1123]
This is just an idea, I have not prototyped it or anything.

Right now the `WebView` `View` is recreated every time the `WebView` composable leaves and re-enters composition.

There's a potential to avoid this recreation via using something like a hoisted `RecycledViewPool`, to re-use `WebView` instances if possible. This approach could also be useful for other expensive `View`s, such as a `MapView`.

**Comment by bentrengrove** [comment]
Cool idea, and definitely something that could be good to develop into a general practice for things like this as you say

**Comment by arriolac** [comment]
Still valid
