### ISSUE TITLE
[Pager] View remains scrollable when swipping between pages

### ISSUE THREAD

**Issue by Doomsdayrs** [google/accompanist#1128]
**Description**
As the title describes, this happens specifically with a vertical pager.
This also makes it difficult to swap between pages (I presume?), as it becomes a struggle to swipe.

**Steps to reproduce**
Manage to get two pages of webviews stuck in the middle

**Expected behavior** 
View does not remain scroll-able & pager completes swipe

**Additional context**
#1063 seems related

[Video1] of one of my users doing this. Stuck between two web views.

[Video1]: https://user-images.githubusercontent.com/38189170/163311985-eb00503d-5260-455b-b47e-b024689c88f0.mp4

**Comment by Doomsdayrs** [comment]
https://github.com/google/accompanist/issues/1127#issuecomment-1132432416

Following instructions here, without the removal of code will show the issue

**Comment by Doomsdayrs** [comment]
This is likely related to how nestedScroll is handled.

Having as stated [here](https://developer.android.com/reference/kotlin/androidx/compose/ui/input/nestedscroll/package-summary#(androidx.compose.ui.Modifier).nestedScroll(androidx.compose.ui.input.nestedscroll.NestedScrollConnection,androidx.compose.ui.input.nestedscroll.NestedScrollDispatcher)), I think this would solve the issue?

**Comment by Doomsdayrs** [comment]
I have attempted to add a connection via NestedScrollConnection & NestedScrollDispatcher

I realized that the functionality does not seem to work well with verticalScroll components. Thus I am now stuck.

**Comment by Doomsdayrs** [comment]
Bump.

**Comment by andkulikov** [comment]
Seems like issue with a WebView similarly to 1127?

**Comment by Doomsdayrs** [comment]
> Seems like issue with a WebView similarly to 1127?

#1127 is due to the webview not constraining properly, instead just matching the max height possible at any time. Which can lead to an infinite page.

**Comment by Doomsdayrs** [comment]
Ehm, bump to reopen

**Comment by Doomsdayrs** [comment]
Sigh, bump as still occurs

**Comment by Doomsdayrs** [comment]
silly github, this is not stale

**Comment by Palloxin** [comment]
Bump, it still occours.
