### ISSUE TITLE
Using systemuicontroller 0.24.6-alpha version, cannot preview normally in library

### ISSUE THREAD

**Issue by huanglinqing123** [google/accompanist#1130]
## Describe the bug
Using systemuicontroller 0.24.6-alpha version, cannot preview normally in library

## To Reproduce
1. Create a new Android library
2. Configure compsoe support in the library
3. Create a new preview function, which can be previewed normally
4. Add library: implementation "com.google.accompanist:accompanist-systemuicontroller:0.24.6-alpha"
5. After changing the content in the preview, it cannot be previewed normally
6. Reduce the systemuicontroller version to 0.19.0, which can be previewed normally

**Comment by alexvanyo** [comment]
Hi, what error are you seeing in the preview window?

**Comment by huanglinqing123** [comment]
Hello, the error is shown in the figure。





---Original---
From: "Alex ***@***.***&gt;
Date: Sat, Apr 16, 2022 01:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [google/accompanist] Using systemuicontroller 0.24.6-alphaversion, cannot preview normally in library (Issue #1130)




 
Hi, what error are you seeing in the preview window?

**Comment by alexvanyo** [comment]
It doesn't look like there's an image or error attached to your last comment.

**Comment by huanglinqing123** [comment]
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/14090613/163902378-477eafe8-6411-49aa-b2ae-4ca94e50a14f.png">

**Comment by alexvanyo** [comment]
Could you include the full exception? Does the stacktrace lead to a line in accompanist/systemuicontroller?
