### ISSUE TITLE
[Pager] using last update makes my app crash

### ISSUE THREAD

**Issue by razaghimahdi** [google/accompanist#1136]
version of dependency that I tried:
implementation("com.google.accompanist:accompanist-pager:0.24.7-alpha")
implementation("com.google.accompanist:accompanist-pager-indicators:0.24.6-alpha")
which it makes my app crash and log says:
log:
    java.lang.NoSuchMethodError: No static method AnimatedContent(Landroidx/compose/animation/core/Transition;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~MEuw0DR6WO8YWpEkTr6PlQ==/com.razzaghi.myshop-DhmZB6NOqGjssuZ5Hado5w==/base.apk)

also it points me to this line of my project:
```kotlin
AnimatedNavHost(
                        navController = navController,
                        startDestination = Screen.Splash.route,
                        builder = {

                            addSplashScreen(
                                navController = navController,
                                width = constraints.maxWidth / 2,
                            )
                            addMainScreen(
                                width = constraints.maxWidth / 2,
                            )
                        }
                    )
```

even I tried this version of dependency:
implementation("com.google.accompanist:accompanist-pager:0.23.1")
implementation("com.google.accompanist:accompanist-pager-indicators:0.23.1")
Which also makes my app crash

BUT if I use this version:
implementation("com.google.accompanist:accompanist-pager:0.12.0")
implementation("com.google.accompanist:accompanist-pager-indicators:0.12.0")
 there will be no crash

WHAT SHOULD I DO?

**Comment by jbw0033** [comment]
What version of compose is your app using?

As seen [here](https://github.com/google/accompanist#compose-versions) Accompanist `0.24.7` requires at least Compose `1.2.x`.

That particular API was added in Compose Animation `1.1.0-beta01`. So this error should only be possible if you are using a version prior to that.

**Comment by razaghimahdi** [comment]
thank u sir, I missed that part, thanks again :)
