### ISSUE TITLE
[System UI Controller] Can't preview composables in version 0.23.1

### ISSUE THREAD

**Issue by labreu-bc** [google/accompanist#1138]
**Description**

Version 0.23.1 breaks composable previews

**Steps to reproduce**
Create a composable that uses rememberSystemUiController() and create a Preview for that composable

**Expected behavior** 
Previews should be previewable 😄 

**Additional context**
Stack trace in the screenshot below
⬇️ 
<img width="991" alt="Screenshot 2022-04-22 at 13 54 30" src="https://user-images.githubusercontent.com/97444041/164734883-e4664289-127f-4691-a257-84b096a9cbf4.png">

**Comment by alexvanyo** [comment]
Ah, it looks like the `1.1` branch had the version of code that didn't work with previews. This was also reported in #918 and fixed, but only on the `1.2` alpha branches.
