### ISSUE TITLE
[Navigation Animation] Decorate window content during transitions

### ISSUE THREAD

**Issue by bmcpt** [google/accompanist#1143]
**Description**

I need to render an overlay on the navigation target contents while a transition is happening. Is it possible to do this in compose?

**Comment by bmcpt** [comment]
This is still relevant.

**Comment by doris4lt** [comment]
Could you share a mock or a video to help us understand better what you are trying to build with the overlay?

**Comment by bmcpt** [comment]
@doris4lt I need to change the color tone of a screen as it is fading away.

**Comment by bmcpt** [comment]
bump
