### ISSUE TITLE
[Pager] Scroll to top of nested content on tab click

### ISSUE THREAD

**Issue by acarlsen** [google/accompanist#1152]
**Description**
I have a HorizontalPager with 2 tabs (using TabRow). When I click a tab I would like to scroll to the top of the content page for that tab, no matter the scroll position of the existing page. What I see is that the scroll position of the new page is the same as the previous page. Is there any solution to this? 

**Steps to reproduce**
Have a HorizontalPager with two content pages (long enough to be scrolled). Scroll down in page 0, when swiping or click tab to change to page 1, the scroll position is the same as in page 0.

**Expected behavior** 
When changing page in HorizontalPager I would like content of new page to be scrolled to position 0 (top).

**Comment by acarlsen** [comment]
The parent to my HorizontalPager is a LazyColumn, so that may be the problem. I would probably need to scroll that when changing tab to the top of the pager since I am actually scrolling in the LazyColumn and not in the pager composable. I was probably wrongly thinking the scrolling was handled internally in the HorizontalPager.

**Comment by andkulikov** [comment]
Ah, yes, Pager knows nothing in what parent it is located. You would need to scroll it on your own
