### ISSUE TITLE
[System UI Controller] Request - Add support for calling setDecorFitsSystemWindows

### ISSUE THREAD

**Issue by headsvk** [google/accompanist#1157]
**Description**
There's no easy way to get a reference to the current `Window` in Compose so it would be useful to have a method inside  `SystemUiController` that can call `WindowCompat.setDecorFitsSystemWindows(Window, Boolean)`. 

My use case is in tests that use `ComposeContentTestRule` which doesn't expose its Activity:
```
    @get:Rule
    val composeTestRule = createComposeRule()
    
    @Test
    fun testEdgeToEdge() {
        composeTestRule.setContent {
            val systemUiController = rememberSystemUiController()
            systemUiController.setDecorFitsSystemWindows(false)

            // This box displays under system bars
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .background(Color.Red),
            )
        }
    }
```

I could create a PR if you think this should be supported 🙂

**Comment by ryanholden8** [comment]
This was fixed in this Compose ticket: https://issuetracker.google.com/issues/229378542 

`DialogProperties.decorFitsSystemWindows` needs to be set to false.

Note using `.imePadding()` from `accompanist` has been deprecated. - https://google.github.io/accompanist/insets/#migration

How to use: 

```kotlin
Dialog(
    onDismissRequest = {}
    DialogProperties(
        usePlatformDefaultWidth = false,
        // Allows .imePadding() to be used
        // https://issuetracker.google.com/issues/229378542
        decorFitsSystemWindows = false,
    )
) {
    val scrollState = rememberScrollState()

    Box(
        Modifier
            .background(MaterialTheme.colors.background)
            .fillMaxSize()
    ) {
        Column(
            Modifier
                .verticalScroll(state = scrollState)
                .background(MaterialTheme.colors.background)
                // Reduce column height when keyboard is shown
                .imePadding())
        {
            // Content that will adjust to keyboard height here
        }
    }
}
```

This was added in Compose `1.3.0-beta01` - https://developer.android.com/jetpack/androidx/releases/compose-ui#1.3.0-beta01

**Comment by alexvanyo** [comment]
For an intermediate solution for the test use-case, you can get the activity (and the window) if you have an `AndroidComposeTestRule`:

```kotlin
   @get:Rule
    val composeTestRule = createAndroidComposeRule<ComponentActivity>()
    
    @Test
    fun testEdgeToEdge() {
        composeTestRule.activityRule.scenario.onActivity {
            WindowCompat.setDecorFitsSystemWindow(window, false)
        }
    }
```

**Comment by bentrengrove** [comment]
Unfortunately Accompanist SystemUIController has been deprecated and won't be supported going forwards. I am closing this issue. For more information please see our [update blog](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)
