### ISSUE TITLE
[Navigation Animation] Provide identity transition 

### ISSUE THREAD

**Issue by PhilipDukhov** [google/accompanist#1159]
I need current screen to stay on its place until appearing screen transition finishes.

Both when I use `ExitTransition.None` or `slideOutVertically` with `targetOffsetY` returning zero, the screen disappears instantly, without waiting appearing transition to end. For now I return `-1` from `targetOffsetY`, which only animates a single pixel change which is not noticeable with a fast transition, but this is kind of a hack.
```kotlin
object Destinations {
    const val Login = "login"
    const val Home = "home"
}

@Composable
fun NavTestScreen(
) {
    val navController = rememberAnimatedNavController()
    AnimatedNavHost(
        navController = navController,
        startDestination = Destinations.Login,
        modifier = Modifier.fillMaxSize()
    ) {
        composable(
            Destinations.Login,
            exitTransition = { NavigationTransition.IdentityExit },
        ) {
            Button(onClick = {
                navController.navigate(Destinations.Home)
            }) {
                Text(text = "Next")
            }
        }
        composable(
            route = Destinations.Home,
            enterTransition = { NavigationTransition.slideInBottomAnimation },
        ) {
            Button(
                onClick = {
                },
                colors = ButtonDefaults.buttonColors(backgroundColor = Color.Yellow)
            ) {
                Text(text = "label")
            }
        }
    }
}

object NavigationTransition {
    private val animation: FiniteAnimationSpec<IntOffset> = tween(
        easing = LinearOutSlowInEasing,
        durationMillis = 2000,
    )

    val IdentityExit = slideOutVertically (
        targetOffsetY = { 0 }, // -1 works here
        animationSpec = animation
    )

    var slideInBottomAnimation = slideInVertically (
        initialOffsetY = { fullHeight -> fullHeight },
        animationSpec = animation
    )
}
```

**Comment by ianhanniballake** [comment]
`AnimatedNavHost` uses `AnimatedContent` internally, so this will automatically be available once the ability to hold content in place is done as part of [b/192993290](https://issuetracker.google.com/issues/192993290).

**Comment by svenjacobs** [comment]
I'm unable to get this working properly, even with the [code](https://github.com/google/accompanist/blob/c7306a3ddaf845ce2d1c2cd7f6dfcab017f26b1e/sample/src/main/java/com/google/accompanist/sample/navigation/animation/AnimatedNavHostSample.kt#L408) from the samples.

While the slide out navigation works correctly, slide in navigation slides into a white screen. Really looking forward to [192993290](https://issuetracker.google.com/issues/192993290) being fixed.

Compose version: 1.3.3
Compose compiler version: 1.4.0
Accompanist version: 0.28.0
