### ISSUE TITLE
[System UI Controller] Showing dialog in fullscreen view shows navigation bar

### ISSUE THREAD

**Issue by josias-milkinteractive** [google/accompanist#1167]
**Description**
When the navigation bar is hidden with `systemUiController.isNavigationBarVisible = false` and a dialog is shown, the navigation bar appears and the content of the screen is resized to make room for the navigation bar.

**Steps to reproduce**
Use this sample code:
```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            val systemUiController = rememberSystemUiController()
            systemUiController.isStatusBarVisible = false
            systemUiController.isNavigationBarVisible = false
            var isDialogVisible by remember { mutableStateOf(false) }
            ComposeDialogTestTheme {
                Box(modifier = Modifier.fillMaxSize()) {

                    Text(text = "Click here to open dialog", modifier = Modifier
                        .align(Alignment.Center)
                        .padding(32.dp)
                        .clickable {
                            isDialogVisible = true
                        })

                    Text(text = "Text at bottom", modifier = Modifier.align(Alignment.BottomCenter))

                    if (isDialogVisible) {
                        AlertDialog(
                            onDismissRequest = {},
                            confirmButton = {
                                TextButton(onClick = { isDialogVisible = false })
                                { Text(text = "OK") }
                            },
                            title = { Text(text = "Title") },
                            text = { Text(text = "Message") }
                        )
                    }
                }
            }
        }
    }
}

```
**Expected behavior** 
When the dialog is opened, the navigation bar should not be visible, and the text "Text at bottom" should be at the very bottom of the screen.

**Actual behavior** 
When running this, the view first looks like this:
![Screenshot_20220516_100040](https://user-images.githubusercontent.com/55796582/168548087-4ef5195f-00ae-4db4-9746-449cd5591e13.png)
Clicking on the text opens the dialog and it looks like this:
![Screenshot_20220516_100058](https://user-images.githubusercontent.com/55796582/168548185-cc9b9e54-4f41-40ee-97b9-41fd08080f1c.png)
The navigation bar is now visible and the content of the screen is resized, so the text "Text at bottom" jumps up which is undesired.

**Additional context**
SystemUiController version: 0.24.8-beta
Compose version: 1.2.0-beta01
Android version: 12

**Comment by josias-milkinteractive** [comment]
Indeed, when I do this from within the dialog content, it works. 
I actually tried this before and it didn't work, but now I found out that I was using SystemUIController 0.23.1 at that time. With version 0.24.8-beta it works, so I'm closing this issue.
Thank you for your help!

**Comment by alexvanyo** [comment]
No problem! And yes, that support within dialogs is new to support cases like this. Glad to hear it worked!

**Comment by mathankumar-dotworld** [comment]
@josias-milkinteractive @alexvanyo 

Can you please share the sample code?

**Comment by wiryadev** [comment]
While i managed to hide the navigation bar, it shows up every time i touch the dialog. Any idea why it happens? @alexvanyo
