### ISSUE TITLE
[Navigation Animation]  Pop transitions performed are not what was expected

### ISSUE THREAD

**Issue by LouisFn** [google/accompanist#1172]
**Description**

https://user-images.githubusercontent.com/54979514/169891310-c3d33164-1b53-4d64-b824-740e2b8b8315.mp4

The pop transitions performed are not what was expected. Screen B (Popular) should only slide to the right and not fade out. However, Screen A (Discover) should fade in.

Here the code
```
AnimatedNavHost(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colors.background),
        navController = navController,
        startDestination = startDestination.route,
        enterTransition = { slideIntoContainer(Left, tween(durationMillis)) },
        exitTransition = { fadeOut(tween(durationMillis)) },
        popEnterTransition = { fadeIn(tween(durationMillis)) },
        popExitTransition = { slideOutOfContainer(Right, tween(durationMillis)) },
    ) 
```

**Compose:**  1.2.0-beta02
**Accompanist:** 0.24.9-beta

**Comment by LouisFn** [comment]
Any update ?

**Comment by bentrengrove** [comment]
Reopened for @jbw0033 to have a look at
