### ISSUE TITLE
[Pager] Interop with AndroidViewBinding fragments

### ISSUE THREAD

**Issue by mariusmorabosch** [google/accompanist#1173]
**Description**
Trying to add a fragment via AndroidViewBinding to a pager will the fragment to be re-created semi-randomly because of the nature of lazy row.
**Steps to reproduce**
Just create a pager and add a couple of fragments as content via AndroidViewBinding composable, then start swiping back and forth
**Expected behavior** 
Ideally we would have a way to support this for projects that are migrating to compose but still have heavy fragment usage as a way to integrate fragments into the new UI.
**Additional context**

**Comment by andkulikov** [comment]
Sorry, but I don't think it is feasible with Compose. Probably you will have to stay on ViewPager2 while you are migrating from the Fragments
