### ISSUE TITLE
[Idea] Support size change transition for bottom sheet

### ISSUE THREAD

**Issue by giangpham96** [google/accompanist#1176]
**Is your feature request related to a problem? Please describe.**
Navigating from one bottom sheet to another bottom sheet is a valid use case. Motion designers are really keen on having a size change transition between the two. Something looks like this
![giphy](https://user-images.githubusercontent.com/23420470/170360005-d945768d-a54d-4dad-963b-3924c12c73e7.gif)

**Describe the solution you'd like**
Currently, we have `AnimatedNavHost` that allows devs to specific enterTransition and exitTransition in `NavGraphBuilder.composable` function. It would be nice to have the same done for `NavGraphBuilder.bottomSheet` with a built-in size change transition.

**Describe alternatives you've considered**
It is also possible that we have a `AnimatedNavHost` nested inside a bottom sheet, but it still requires such a transition to animate the content change.

**Comment by giangpham96** [comment]
is there anyway to keep the issue open without commenting every month 😅

**Comment by jossiwolf** [comment]
Agree that this is a desirable feature, thanks for the request :)  tracking in #1317
