### ISSUE TITLE
[WebView] Suggestion for persistent WebView upon configuration change or navigating to/from WebView composable

### ISSUE THREAD

**Issue by jacobmichaelis** [google/accompanist#1178]
## Describe the bug
Android Bug: When rotating the screen, or navigating to another composable and back, the WebView recomposes with no way to show an existing stored WebView. 

## To Reproduce
* Implement Accompanist WebView
* Show a web page on the mobile device
* Rotate the screen
* See the web page reload

## Expected behavior
The website shown in the WebView doesn't reload upon configuration change/navigating back to WebView.
Suggestion:
I am storing my WebView on the ViewModel, but there is no way to just show the existing cached WebView I have when recomposing the WebView by Accompanist. My suggestion is that you add an `existingWebView: WebView? = null` to the WebView composable and then change `var webView by remember { mutableStateOf<WebView?>(null) }` to be `mutableStateOf(existingWebView)`. Then in the AndroidView do `webView ?: WebView(context).apply { ...`. I have tested this in my project by copying your code and altering it and it worked as I had hoped.
This is just a suggestion, I'm sure you will have a much more brilliant way of doing what I suggested, but I hope it will be available in one way or another in the future.

## Environment:
 - Android OS version: 24+
 - Device: Pixel 4a Emulator
 - Accompanist version: 0.24.7-alpha (though I'm pretty sure this is still an issue in current versions)

**Comment by bentrengrove** [comment]
Thanks for the report, this is definitely something we need to improve.

Just as a side note, I wouldn't store a view in the viewmodel, so be careful. That sounds like an almost certain memory leak on rotation as that view will be holding on to a context reference. The proper way to handle this is by saving and restoring state, there isn't a great way to do that right now unfortunately.

One thing that might help though, if you are in a fully Compose app you can pretty safely opt out of rotation by adding
```
android:configChanges="orientation|screenSize|screenLayout"
```

to your activity in your AndroidManifest. That should help this issue.

**Comment by bharath1997** [comment]
Hey guys,
I wanted to avoid the reload of webview after navigation, I don't think storing it in ViewModel would be a proper solution too, but this is kind of a serious problem as we are currently developing a hybrid app similar to amazon(native and webview)completely with compose, the main content will be shown in webview, don't want to show it within bottom sheet or fullscreen dialog as it would be the main content to be shown to user after launch, can someone please recommend some other solution or a workaround for this if possible?

**Comment by workspace** [comment]
I tried to solve this issue with caching WebView instance for each route in navigation. It worked well as I wanted, however, I'm not sure it is the best solution.

**Comment by bharath1997** [comment]
@workspace can you provide the solution for this in simple code or can you elaborate on what you did?

**Comment by nevenisnoob** [comment]
@bentrengrove 
(Sorry for the direct mention)
he bot closed this unsolved issue, please reopen it.

**Comment by darienalvarez** [comment]
Hello. Any solution to this issue?
This is very important for apps who handle hybrid features.

**Comment by wogg** [comment]
RescueTime is also struggling with this problem, in a hybrid view.
An example of smuggling a handle to webview by "caching WebView instance for each route in navigation" would be very help to see @workspace

**Comment by darienalvarez** [comment]
@wogg  I ended creating an Activity with a WebView

```
<activity
            android:name=".ui.WebActivity"
            android:launchMode="singleInstance"
            android:configChanges="orientation|screenSize"
            android:theme="@style/Theme.WebActivity"
            android:exported="false" />
```

in the oncreate
```
 if (savedInstanceState != null) {
            webView.restoreState(savedInstanceState.getBundle(WEB_VIEW_KEY) ?: bundleOf())

            webView.reload()
        } else {
            webView.load(url)
        }
```        

and also
```
override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)

        Timber.i("onSaveInstanceState")

        val bundle = bundleOf()
        webView.saveState(bundle)
        outState.putBundle(WEB_VIEW_KEY, bundle)
    }
```

**Comment by wogg** [comment]
We are using jetpack compose and I am unsure how you would mix that approach in with a tabbed composable view, where the webview is on one of the tabs. Thank you for the example though.

**Comment by bentrengrove** [comment]
So there is a workaround now available at least for things like Pagers. You can now hoist the `WebView` instance above your Pager.

Very rough pseudocode, you'll probably have to improve it for your situation for instance making the WebView allocation lazy.
```
@Composable
fun Screen() {
   val pageCount = 5
   val context = LocalContext.current
   val webViews = remember { List(pageCount) { WebView(context) } }
   val webViewState = List(pageCount) { rememberWebViewState("YOUR_URL") }
   
   Pager(totalPages = pageCount) { page ->
      WebView(
         state = webViewState[page]
         factory = { webViews[page] }
      )
   }
}
```

**Comment by yanzm** [comment]
I used rememberSaveable to store/restore WebView state.

```kotlin
@Composable
fun AccompanistWebSample() {
    val initialUrl = "https://google.github.io/accompanist/web/"

    var lastUrl by rememberSaveable { mutableStateOf<String?>(null) }
    var bundle by rememberSaveable { mutableStateOf<Bundle?>(null) }

    val url = lastUrl ?: initialUrl

    val state = rememberWebViewState(url = url)

    WebView(
        state = state,
        modifier = Modifier.fillMaxSize(),
        onCreated = { webView ->
            bundle?.let {
                webView.restoreState(it)
                bundle = null
            }
        },
        onDispose = { webView ->
            bundle = Bundle().apply {
                webView.saveState(this)
            }
            lastUrl = webView.url
        }
    )
}
```

**Comment by YugeCse** [comment]
Yeah, I also think it's important to use a webview in a hybird app. But now, the webview cannot save the state.  Is there another way to keep webview's state?

**Comment by darienalvarez** [comment]
@bentrengrove Do you have any progress on this issue??

**Comment by bentrengrove** [comment]
No progress, there isn't much we can do about this from the WebView wrapper. This fix needs to come from Compose itself adding a method to do this which I am pushing for. I am keeping this issue open as I know it's a common problem.

**Comment by bentrengrove** [comment]
Thank you for your honest feedback @darienalvarez . I agree we definitely have room for improvement in those areas. I have passed this on to the wider team for discussion.

We also have an upstream issue for tracking the mechanism needed to fix this WebView issue. https://issuetracker.google.com/252891031

**Comment by musilto7** [comment]
I had this problem also. I ended up with solution, which Uses standart WebView inside composable function.

`
 var webView: WebView? by remember {
                mutableStateOf(null)
            }
AndroidView(
                modifier = Modifier
                    .fillMaxWidth()
                    .fillMaxHeight(),
                factory = { context ->
                    webView = WebView(context).apply {
                        this.setInitialScale(1)
                        this.settings.domStorageEnabled = true
                        @SuppressLint("SetJavaScriptEnabled")
                        this.settings.javaScriptEnabled = true
                        this.settings.loadWithOverviewMode = true
                        this.settings.useWideViewPort = true,

                        val bundle: Bundle? = savedBundle
                        if (bundle != null) {
                            restoreState(bundle)
                        } else {
                            model.orderCreated?.paymentGatewayUrl?.let {
                                loadUrl(it)
                            }
                        }
                    }
                    webView!!
                }
            )
`
Then I am using Disposable effect for saving state.
`
var savedBundle: Bundle? by rememberSaveable {
                mutableStateOf(null)
            }
 DisposableEffect(lifecycleOwner.lifecycle) {
                val observer = LifecycleEventObserver { _, event ->
                    if (event == Lifecycle.Event.ON_STOP
                        || event == Lifecycle.Event.ON_PAUSE
                    ) {
                        val bundle = Bundle()
                        webView?.saveState(bundle)
                        savedBundle = bundle
                    }
                }

                lifecycleOwner.lifecycle.addObserver(observer)

                onDispose {
                    lifecycleOwner.lifecycle.removeObserver(observer)
                }
            }
`

**Comment by alirahimpour89** [comment]
As some mentioned, could this be a option until the real fix comes? If so I can send you a PR.
https://github.com/google/accompanist/commit/98aadd9dd5385ca47aaf064fa53e9cc61745b215

**Comment by Killer232323** [comment]
@bentrengrove How long to wait for a fix? Is there a temporary solution to the problem?
