### ISSUE TITLE
[Pager] Combining pagerState.currentPage and animateScrollToPage 

### ISSUE THREAD

**Issue by Guimareshh** [google/accompanist#1181]
**Description**
I have a simple map Screen with markers and a Pager at the bottom at the screen (similar to what AirBnB used to have):
- A click on a marker update the selectedIndex in the viewModel, and then with a LaunchedEffect inside the screen we animateScrollToPage
- A scroll on the Pager update the currentPage and it updates the selected marker on the map

On the first few pager scroll and marker click it's working properly. But after it starts to behave strangely (pager not updated after a marker click)

**Steps to reproduce**
Here is the code snippet about the pagerState
```kotlin
val pagerState = rememberPagerState()
LaunchedEffect(pagerState) {
        snapshotFlow { pagerState.currentPage }.collect { page ->
            viewModel.update(page)
        }
    }
    LaunchedEffect(pagerState) {
        viewModel.selectedIndex.collect { index ->
            pagerState.animateScrollToPage(index)
        }
    }
```

**Comment by andkulikov** [comment]
animateScrollToPage can throw CancellationException if the user tries to scroll while the animated scroll is executed. Probably you need to wrap it into try { } catch (cancel: CancellationException) { }

**Comment by Guimareshh** [comment]
Thanks for the info, BTW I fixed my issue just by using the `scrollToPage` instead of `animateScrollToPage` API, as I need a perfect match between the current page of the pager and the associated selected marker.
