### ISSUE TITLE
[Pager] Support snapIndex in fling behavior

### ISSUE THREAD

**Issue by golottie-jens** [google/accompanist#1184]
**Description**
It is currently not possible to define when the pager should snap to which page. The Snapper library makes that possible with the snapIndex Lambda in the fling behavior ( https://chrisbanes.github.io/snapper/api/lib/dev.chrisbanes.snapper/-snapper-fling-behavior/index.html).

Since the lazyListState in the PagerState is currently not public, it's not possible to create a custom flingBehavior with a custom snapIndex for a Pager, because a layoutInfo of the list is required.

**Steps to reproduce**
Try to implement a Pager where the user doesn't need to scroll so much to switch pages.

**Expected behavior** 
It is possible to define the "distance" that need to be scrolled before the pager snaps to the next/previous page.

**Comment by andkulikov** [comment]
Pager is intended for the cases when there is one current page and each swipe is always swiping to the next page. If you want to swipe by multiple items at once you should just use LazyRow with Snapper directly, what you want is not really a Pager in this sense

**Comment by andkulikov** [comment]
Have you seen this api - https://github.com/google/accompanist/blob/2248e5efc788f7dc0c0be26239d6020bc888f127/pager/src/main/java/com/google/accompanist/pager/Pager.kt#L152
I think this should allow you to customize the snapper params.
However if there is hard to swipe pager with the default configs on tablet probably the defaults are wrong. Does it default come from Snapper or from Pager?

**Comment by golottie-jens** [comment]
Ahhh sorry! This is exactly what I was looking for. I had an older version without this variant of flingBehavior().
Thank you!

**Comment by lukaspieper** [comment]
Hi,

I just want to confirm that swiping on a tablet in landscape is kind of impossible (takes four to five tries) with just your thumb from a side of the screen.  Forefinger is easier but still not comparable to swiping on a phone. 

I would agree to @andkulikov that the defaults should be adjusted. However, if someone (maybe @golottie-jens) can provide a sample using flingBehavior that would be helpful too.

Thanks.

**Comment by golottie-jens** [comment]
Hej @lukaspieper ,
I ended up with a solution like this (change minFlingDistanceDp  to modify fling-sensitivity):

`HorizontalPager(
            modifier = Modifier.fillMaxSize(),
            state = pagerState,
            count = noOfPages,
            flingBehavior = flingBehavior(pagerState = pagerState, noOfPages = noOfPages)
        ) { page ->
			//Content
		}


val minFlingDistanceDp = 150.dp

@OptIn(ExperimentalPagerApi::class, dev.chrisbanes.snapper.ExperimentalSnapperApi::class)
@Composable
fun flingBehavior(pagerState: PagerState, noOfPages: Int): FlingBehavior {
    var currentPageIndex = remember { pagerState.currentPage }
    return PagerDefaults.flingBehavior(
        state = pagerState,
        snapIndex = { layoutInfo, _, _ ->
            val distanceToStartSnap = layoutInfo.distanceToIndexSnap(currentPageIndex)
            currentPageIndex = when {
                distanceToStartSnap < -(minFlingDistanceDp.value) -> {
                    (currentPageIndex + 1).coerceAtMost(noOfPages - 1)
                }
                distanceToStartSnap > minFlingDistanceDp.value -> {
                    (currentPageIndex - 1).coerceAtLeast(0)
                }
                else -> {
                    currentPageIndex
                }
            }
            currentPageIndex
        }
    )
}`

Hop that helps. Have a nice weekend.

**Comment by lukaspieper** [comment]
Thanks. Working great. `150.dp` also seems quite reasonable.

Have a nice weekend too.
