### ISSUE TITLE
pagerState.interactionSource reporting the wrong page

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#1185]
## Describe the bug
I'm trying to use pagerState.interactionSource as a way to decide if the pager page has updated programatically vs user interaction. I have a use case where I only want to trigger an event if the pager update is done via a user gesture. I found this [bug report](https://github.com/google/accompanist/issues/651) that made it seem like pagerState.interactionSource is what I actually want.

So in an effort of trying to figure out if the page has been updated via a user I wrote

```
  LaunchedEffect(pagerState) {
    launch {
      pagerState.interactionSource.interactions.collect {
        when (it) {
          else -> {
            Log.e("TESTING", "${it.javaClass.simpleName} | ${pagerState.currentPage}")
          }
        }
      }
    }
```

The output of the above is:

```
2022-05-31 16:03:38.193  6297-6297  TESTING E  Start | 5501
2022-05-31 16:03:38.815  6297-6297  TESTING E  Stop | 5501
2022-05-31 16:03:39.629  6297-6297  TESTING E  Start | 5501
2022-05-31 16:03:40.105  6297-6297  TESTING E  Stop | 5501
2022-05-31 16:03:40.809  6297-6297  TESTING E  Start | 5501
2022-05-31 16:03:41.240  6297-6297  TESTING E  Stop | 5501
2022-05-31 16:03:41.939  6297-6297  TESTING E  Start | 5501
2022-05-31 16:03:42.376  6297-6297  TESTING E  Stop | 5501
2022-05-31 16:03:43.762  6297-6297  TESTING E  Start | 5501
2022-05-31 16:03:44.779  6297-6297  TESTING E  Stop | 5501
```

What I did was touch and hold the current page (5501) and then just kinda wiggle back and forth very slightly (almost like an indecisive user) and then when I finally swipe forward (the last Start and Stop combo) you can see that the page is reported as 5501.

Seems fairly easy to repro using my code snippet above

## Environment:
 - Android OS version: 13 beta 2.1
 - Device: Pixel 6
 - Accompanist version: v0.24.9-beta

## Additional context
This is only an issue because I found the issue while trying to do my initial use case of "trying to figure out if the page has been updated via a user gesture". If this is the wrong way to do it... then please let me know and maybe this issue is completely invalid. Thanks!

**Comment by ColtonIdle** [comment]
Hm. I'm still a bit confused. 

So if I wanted to act on the end state of the scroll is completed by a user, what would I do?

```
val isDragged by pagerState.interactionSource.collectIsDraggedAsState()
            var isScrolledByUser by remember { mutableStateOf(false) }
            LaunchedEffect(pagerState) {
                snapshotFlow { pagerState.isScrollInProgress }.collect { isScrolling ->
                    isScrolledByUser = isScrolling && isDragged
                }
            }
            
if (isScrolledByUser) { //do something ?}


```

In my example above, wouldn't that be called before it actually settled? All I really want is a "onPageChanged" event but I need to be able to tell if it was programatic or a user.

**Comment by andkulikov** [comment]
This should work
```
            val isDragged by pagerState.interactionSource.collectIsDraggedAsState()
            var isScrolledByUser by remember { mutableStateOf(false) }
            LaunchedEffect(pagerState) {
                snapshotFlow { pagerState.isScrollInProgress }.collect { isScrolling ->
                    if (isScrolledByUser && !isScrolling) {
                         ... do something
                    }
                    isScrolledByUser = isScrolling && isDragged
                }
            }
```

**Comment by ColtonIdle** [comment]
Wow thank you @andkulikov 
I've been using compose for a while but its safe to say that I would not have ended up at the above answer without your help. Cheers
