### ISSUE TITLE
[Swipe to refresh] Swipe gesture won't work if the child composable is not scrollable.

### ISSUE THREAD

**Issue by AagitoEx** [google/accompanist#1191]
**Description**
Swipe to refresh doesn't work if the child composable is not scrollable.

**Steps to reproduce**
```kotlin
SwipeRefresh(state = swipeRefreshState, onRefresh = { viewmodel.refresh() }) {
    ErrorMessage(text = "Error message", modifier = Modifier.fillMaxSize())
}
```

**Expected behavior** 

**Additional context**

**Comment by bentrengrove** [comment]
This is working as intended and documented at https://google.github.io/accompanist/swiperefresh/

**Comment by sunnykraditya** [comment]
Quoting the link 

> The content needs to be 'vertically scrollable' for SwipeRefresh() to be able to react to swipe gestures. Layouts such as [LazyColumn](https://developer.android.com/reference/kotlin/androidx/compose/foundation/lazy/package-summary#LazyColumn(androidx.compose.ui.Modifier,androidx.compose.foundation.lazy.LazyListState,androidx.compose.foundation.layout.PaddingValues,kotlin.Boolean,androidx.compose.foundation.layout.Arrangement.Vertical,androidx.compose.ui.Alignment.Horizontal,androidx.compose.foundation.gestures.FlingBehavior,kotlin.Function1)) are automatically vertically scrollable, but others such as [Column](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#Column(androidx.compose.ui.Modifier,androidx.compose.foundation.layout.Arrangement.Vertical,androidx.compose.ui.Alignment.Horizontal,kotlin.Function1)) or [LazyRow](https://developer.android.com/reference/kotlin/androidx/compose/foundation/lazy/package-summary#LazyRow(androidx.compose.ui.Modifier,androidx.compose.foundation.lazy.LazyListState,androidx.compose.foundation.layout.PaddingValues,kotlin.Boolean,androidx.compose.foundation.layout.Arrangement.Horizontal,androidx.compose.ui.Alignment.Vertical,androidx.compose.foundation.gestures.FlingBehavior,kotlin.Function1)) are not. In those instances, you can provide a [Modifier.verticalScroll](https://developer.android.com/jetpack/compose/gestures#scroll-modifiers)
