### ISSUE TITLE
[Pager] Pager doesn't save state previous page

### ISSUE THREAD

**Issue by VasiliZ** [google/accompanist#1202]
**Description**
I used accompanist pager version `0.22.0-rc`. I displayed video content and image content together in one pager. I have a controller in video view.  When I click on video. this video should be on pause. And when I change page and go back this state was saved. 

Now I upgraded version to `0.24.10-beta` and state of my video didn't save. Every time when i change page. View is redraw and creates new objects my video player. For example video with previous behavior 

https://user-images.githubusercontent.com/10958540/174011527-17f6fef2-88b8-4dc0-ac7c-6e0b818414f2.mp4

And new behavior

https://user-images.githubusercontent.com/10958540/174012419-63da2ece-4afe-4b8b-b300-94c81794f2d8.mp4

Is this normal behavior now?

**Comment by andkulikov** [comment]
Hey. How exactly do you define this state which is not saved? Could you please show a bit of the code?
Like, for example if it is just a 
var isPaused = remember { mutableStateOf(false) }
try to switch to rememberSaveable

**Comment by VasiliZ** [comment]
Hey, thanks for your answer 
I have next solution 
`@Composable
fun VideoView(){
val videoController = remember{
MyVideoController() \\without composable scope
}
}`
in my controller i change options for playback and other options for my player
In this case i should put my video controller in rememberSaveble but i can't :(
Is it wrong way?

**Comment by VasiliZ** [comment]
Thank you for your help. Excuse for troubling.
