### ISSUE TITLE
[Pager] HorizontalPager handles screen rotation poorly

### ISSUE THREAD

**Issue by bubenheimer** [google/accompanist#1204]
Accompanist 0.24.11-rc
Compose 1.2.0-rc01
Kotlin 1.6.21

**Description**
When letting Compose handle screen rotation (instead of letting Activity recreate), HorizontalPager does not stay on the last page after rotation, when that was the current page prior to rotation.

It also tends to lose page centering after screen rotation; the exact manifestation of page centering state after rotation depends on screen size, selected page, etc.

**Steps to reproduce**

In Accompanist sample app, add the following line in AndroidManifest.xml to ".pager.HorizontalPagerBasicSample" activity:

`android:configChanges="density|fontScale|keyboard|keyboardHidden|layoutDirection|locale|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode"`

Run modified sample app, pick Basic Horizontal Pager, and go to final page. Trigger screen rotation. Observe screen changing to prior page. Page also may not be centered.

**Expected behavior** 

Final page is centered on screen after rotation.

**Comment by andkulikov** [comment]
Thanks for filing the bug! I was able to confirm it is not a Pager specific issue and filed a bug for LazyRow in the Compose UI bug tracker here - https://issuetracker.google.com/issues/236391559.

**Comment by bubenheimer** [comment]
Thanks. Is this only a bug in LazyRow, though, or is it also a problem with the specialized semantics of HorizontalPager?

1. Let's assume we have a plain LazyRow. If I rotate back and forth and an item position shifts over time, yeah, looks like a bug in LazyRow.
2. Let's assume we're somewhere at the start, end, or in the middle of a HorizontalPager, page is snapped. We rotate and the page is no longer snapped. Is LazyRow actually the one responsible for snapping?

**Comment by andkulikov** [comment]
it is not directly related to snapping, as I mentioned in the linked bug it is not that hard to reproduce the same issue with LazyRow. Easy way to test if it is a big you found: if the fact we add manifest flags or not affects how the scroll position is maintained, then it should be fixed

**Comment by aconda-mercari** [comment]
Hi, did you find any workaround for this issue?
