### ISSUE TITLE
[System UI Controller] I want full screen, but is not work

### ISSUE THREAD

**Issue by GCZeng** [google/accompanist#1205]
**Description**
# I want full screen in my app, following code:

```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            JetpackComposeDemoTheme {
                var isDialogVisible = remember { mutableStateOf(false) }
                JetpackComposeDemoTheme() {
                    val systemUiController: SystemUiController = rememberSystemUiController()
                    systemUiController.isSystemBarsVisible = false 

                    Box(modifier = Modifier.fillMaxSize()) {
                        Text(text = "Click here to open dialog", modifier = Modifier
                            .align(Alignment.Center)
                            .padding(32.dp)
                            .clickable {
                                isDialogVisible.value = true
                            })

                        Text(text = "Text at bottom", modifier = Modifier.align(Alignment.BottomCenter))

                        if (isDialogVisible.value) {
                            AlertDialog(
                                onDismissRequest = {},
                                confirmButton = {
                                    TextButton(onClick = { isDialogVisible.value = false })
                                    { Text(text = "OK") }
                                },
                                title = { Text(text = "Title") },
                                text = { Text(text = "Message") }
                            )
                        }

                    }
                }

            }
        }
    }
}```


![device-2022-06-17-145543](https://user-images.githubusercontent.com/3079863/174244842-b72d5423-75ba-4294-8b65-479ff2a1a505.gif)

**Comment by GCZeng** [comment]
![device-2022-06-17-145543](https://user-images.githubusercontent.com/3079863/174245198-60a754da-ae35-45e1-8320-22b020b4774b.gif)

**Comment by GCZeng** [comment]
This is a recording screen
![device-2022-06-17-145543](https://user-images.githubusercontent.com/3079863/174245344-04eb0f3b-71ff-4bbb-9cd3-322a2965e424.gif)

**Comment by LozariaVinok** [comment]
I have this issue too. Have you fixed it?

**Comment by alexvanyo** [comment]
Hi, could you provide a bit more information about what you're expecting to happen, and what's happening instead? It's not clear to me from the GIF what the issue is.

**Comment by LozariaVinok** [comment]
In my case It is android 28. com.google.accompanist:accompanist-systemuicontroller:0.24.13-rc

**Comment by LozariaVinok** [comment]
In my case I have this issue on Samsung Galaxy S8+ android 28. 
com.google.accompanist:accompanist-systemuicontroller:0.24.13-rc

I am trying to remove navigation and status bar. I put this code in my compose surface:
`val systemUiController = rememberSystemUiController()
            systemUiController.isStatusBarVisible = false // Status bar
            systemUiController.isNavigationBarVisible = false // Navigation bar
            systemUiController.isSystemBarsVisible = false // Status & Navigation bars
            systemUiController.navigationBarDarkContentEnabled =false`

As a result, the app starts without a status and navigation bars, as I expect. But when you start interacting with the screen status bar and navigation bar show again. And only after that you can truly interact with the screen. 
So what I see in this gif and what I am experiencing. App starts in full screen. Person tries to click on button, but instead of showing the dialog it shows naviagation and status bar first. And dialog opens only after second click. I was trying to remove a status and naviagation bars in a dialog, and I have the same issue: to close the dialog I have to click twise and it shows status bar and navigation bar after first click.

I have also tried it on emulator with 29. The same issue. It works fine in the emulator with 32 android thought.

**Comment by LozariaVinok** [comment]
In my case the issue is on Samsung S8+ sdk 28
com.google.accompanist:accompanist-systemuicontroller:0.24.13-rc

I am trying to remove navigation and status bar. I put this code:
` val systemUiController = rememberSystemUiController()
            
systemUiController.isStatusBarVisible = false // Status bar
          
systemUiController.isNavigationBarVisible = false // Navigation bar

systemUiController.isSystemBarsVisible = false // Status & Navigation bars

systemUiController.navigationBarDarkContentEnabled =false`

As a result, the app starts without a status and navigation bars, as I expect. But when you start interacting with the screen status bar and navigation bar show again. And only after that you can truly interact with the screen. 
So what I see in this gif and what I am experiencing. App starts in full screen. Person tries to click on button, but instead of showing the dialog it shows naviagation and status bar first. And dialog opens only after second click. I was trying to remove a status and naviagation bars in a dialog, and I have the same issue: to close the dialog I have to click twise and it shows status bar and navigation bar after first click.

I've checked on emulator with sdk 29: The same issue. It works fine in the emulator with sdk 32 android thought.

**Comment by alexvanyo** [comment]
Hi, thanks for the additional information!

It looks like the `SystemUiController` is currently missing a feature to allow adjusting the `systemBarsBehavior`, which allows configuring the behavior here for when the system bars re-appear:
https://developer.android.com/reference/androidx/core/view/WindowInsetsControllerCompat#setSystemBarsBehavior(int)

For your case, you'll probably want [`BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE`](https://developer.android.com/reference/androidx/core/view/WindowInsetsControllerCompat#BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE()). As a workaround before that's implemented in accompanist, you can set that directly on a `windowInsetsControllerCompat` that's constructed in the same manner as accompanist does.

**Comment by LozariaVinok** [comment]
Hi!
 Thank you!
 Workaround is working. It shows navigation bar for a moment while dialog is opening but it doesn't affect any animations so I think it's acceptable.

**Comment by GCZeng** [comment]
> Hi! Thank you! Workaround is working. It shows navigation bar for a moment while dialog is opening but it doesn't affect any animations so I think it's acceptable.

How to implement, can you give me the sample code

**Comment by LozariaVinok** [comment]
I've put this code instead of accompanist usage

```
val window = (LocalView.current.parent as? DialogWindowProvider)?.window?:LocalView.current.context.findWindow()
if (window != null) {
WindowCompat.setDecorFitsSystemWindows(window, false)
val windowInsetsController = WindowCompat.getInsetsController(window, window.decorView)
// Configure the behavior of the hidden system bars
windowInsetsController.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
// Hide both the status bar and the navigation bar
windowInsetsController.hide(WindowInsetsCompat.Type.statusBars())
windowInsetsController.hide(WindowInsetsCompat.Type.navigationBars())
window.statusBarColor = android.graphics.Color.TRANSPARENT
window.navigationBarColor = android.graphics.Color.TRANSPARENT
}

```

And to find window I copied this method from accompanist 

```
private tailrec fun Context.findWindow(): Window? =
    when (this) {
        is Activity -> window
        is ContextWrapper -> baseContext.findWindow()
        else -> null
    }

```

If you want to remove a status and navigation bar from dialog too you'll have to call this inside of Dialog content.

**Comment by GCZeng** [comment]
> I've put this code instead of accompanist usage
> 
> ```
> val window = (LocalView.current.parent as? DialogWindowProvider)?.window?:LocalView.current.context.findWindow()
> if (window != null) {
> WindowCompat.setDecorFitsSystemWindows(window, false)
> val windowInsetsController = WindowCompat.getInsetsController(window, window.decorView)
> // Configure the behavior of the hidden system bars
> windowInsetsController.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
> // Hide both the status bar and the navigation bar
> windowInsetsController.hide(WindowInsetsCompat.Type.statusBars())
> windowInsetsController.hide(WindowInsetsCompat.Type.navigationBars())
> window.statusBarColor = android.graphics.Color.TRANSPARENT
> window.navigationBarColor = android.graphics.Color.TRANSPARENT
> }
> ```
> 
> And to find window I copied this method from accompanist
> 
> ```
> private tailrec fun Context.findWindow(): Window? =
>     when (this) {
>         is Activity -> window
>         is ContextWrapper -> baseContext.findWindow()
>         else -> null
>     }
> ```
> 
> If you want to remove a status and navigation bar from dialog too you'll have to call this inside of Dialog content.

`class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            JetpackComposeDemoTheme {
                var isDialogVisible = remember { mutableStateOf(false) }
                JetpackComposeDemoTheme() {
//                    val systemUiController: SystemUiController = rememberSystemUiController()
//                    systemUiController.isSystemBarsVisible = false // Status & Navigation bars
                    val window = (LocalView.current.parent as? DialogWindowProvider)?.window ?: LocalView.current.context.findWindow()
                    if (window != null) {
                        WindowCompat.setDecorFitsSystemWindows(window, false)
                        val windowInsetsController = WindowCompat.getInsetsController(window, window.decorView)
                        // Configure the behavior of the hidden system bars
                        windowInsetsController.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
                        // Hide both the status bar and the navigation bar
                        windowInsetsController.hide(WindowInsetsCompat.Type.statusBars())
                        windowInsetsController.hide(WindowInsetsCompat.Type.navigationBars())
                        window.statusBarColor = android.graphics.Color.TRANSPARENT
                        window.navigationBarColor = android.graphics.Color.TRANSPARENT
                    }


                    Box(modifier = Modifier.fillMaxSize()) {
                        Text(text = "Click here to open dialog", modifier = Modifier
                            .align(Alignment.Center)
                            .padding(32.dp)
                            .clickable {
                                isDialogVisible.value = true
                            })

                        Text(text = "Text at bottom", modifier = Modifier.align(Alignment.BottomCenter))


                        if (isDialogVisible.value) {
                            AlertDialog(
                                onDismissRequest = {},
                                confirmButton = {
                                    TextButton(onClick = { isDialogVisible.value = false })
                                    { Text(text = "OK") }
                                },
                                title = { Text(text = "Title") },
                                text = { Text(text = "Message") }
                            )
                        }
                    }
                }

            }
        }
    }
}`

> I've put this code instead of accompanist usage
> 
> ```
> val window = (LocalView.current.parent as? DialogWindowProvider)?.window?:LocalView.current.context.findWindow()
> if (window != null) {
> WindowCompat.setDecorFitsSystemWindows(window, false)
> val windowInsetsController = WindowCompat.getInsetsController(window, window.decorView)
> // Configure the behavior of the hidden system bars
> windowInsetsController.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
> // Hide both the status bar and the navigation bar
> windowInsetsController.hide(WindowInsetsCompat.Type.statusBars())
> windowInsetsController.hide(WindowInsetsCompat.Type.navigationBars())
> window.statusBarColor = android.graphics.Color.TRANSPARENT
> window.navigationBarColor = android.graphics.Color.TRANSPARENT
> }
> ```
> 
> And to find window I copied this method from accompanist
> 
> ```
> private tailrec fun Context.findWindow(): Window? =
>     when (this) {
>         is Activity -> window
>         is ContextWrapper -> baseContext.findWindow()
>         else -> null
>     }
> ```
> 
> If you want to remove a status and navigation bar from dialog too you'll have to call this inside of Dialog content.

Thank you very mush!
That solved my problem!

**Comment by alexvanyo** [comment]
Access to `systemBarsBehavior` should be supported in the next release, although one heads up at the moment is that retrieving the `systemBarsBehavior` is currently only working on API 30 and above due to an upstream androidx.core issue: https://issuetracker.google.com/issues/189366125. Setting it should work though across all APIs!
