### ISSUE TITLE
[Navigation Material] Routing does not work when string parameter includes line breaks

### ISSUE THREAD

**Issue by alixwar** [google/accompanist#1206]
**Description**
I used a Base64 encoder to encode a url and pass it as an argument to build a route.
Similar to how it's done in the Tivi sample app: 

```kotlin
    object ShowDetails : LeafScreen("show/{showId}") {
        fun createRoute(root: Screen, showId: Long): String {
            return "${root.route}/show/$showId"
        }
    }
```
https://github.com/chrisbanes/tivi/blob/main/app/src/main/java/app/tivi/AppNavigation.kt

But instead of "showId" I pass an encoded URL as string argument:

```kotlin
    object MyScreen: LeafScreen("mynavigation?firstparam={firstParam}&url={url}") {

        fun createRoute(firstParam: String, base64EncodedUrlWithUtf8: String): String =
            "mynavigation?firstparam=${firstParam}&url=${base64EncodedUrlWithUtf8.trim()}"

    }
```

Since URLs contain tricky reserved characters so I use a Base 64 encoder to encode the string first to avoid unpleasant surprises.
I used the encoder from Google and did this:

```
com.google.android.gms.common.util`.Base64Utils.encode(url.toByteArray(Charsets.UTF_8))
```

For some URLs this would result in strings with just a trailing line break, which seems to work fine. But for others (longer URLs?) line breaks are added in between blocks of encoded data which would cause an exception if trying to navigate to a route with this string argument.

Example URL with this problem (after being encoded):
"https://aaa-bbbcccccapp-lab-remote.abcdefg.bb.se/ABCDRemote"

The resulting string:
"
aHR0cHM6Ly9hYWEtYmJiY2NjY2NhcHAtbGFiLXJlbW90ZS5hYmNkZWZnLmJiLnNlL0FCQ0RSZW1v
dGU=

"

When attempting to navigate to a route with this string argument the exception is very unclear:

```kotlin
navController.navigate(LeafScreen.MyScreen.createRoute(firstparam = "something", url = base64EncodedUrlWithUtf8))
```

```
java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/mynavigation?firstparam=something&url=aHR0cHM6Ly9hYWEtYmJiY2NjY2NhcHAtbGFiLXJlbW90ZS5hYmNkZWZnLmJiLnNlL0FCQ0RSZW1v    dGU=
 } cannot be found in the navigation graph 
```

**Steps to reproduce**
A string argument with line breaks in between non-white space characters

**Expected behavior**
Either:
1. That it works fine to have line breaks (makes most sense in my opinion)
2. That the nav graph throws a more clear exception regarding illegal characters or similar error when trying to pass a string argument with line break characters

**Additional context**
Versions used:
- Accompanist 0.24.7-alpha
- Activity-compose 1.5.0-rc01
- Compose 1.2.0-beta02
- Navigation-compose 2.5.0-rc01

**Comment by bigfarid** [comment]
for Url encoding you should use Uri.encode (as you should for intents in general). This should work just fine.

**Comment by alixwar** [comment]
> for Url encoding you should use Uri.encode (as you should for intents in general). This should work just fine.

That makes a lot of sense. I will definitely switch to this method. 

I still think the createRoute API could be improved and fail fast on invalid characters, so I think this issue is still valid.

**Comment by bigfarid** [comment]
> > for Url encoding you should use Uri.encode (as you should for intents in general). This should work just fine.
> 
> That makes a lot of sense. I will definitely switch to this method.
> 
> I still think the navigate API could be improved and fail fast on invalid characters, so I think this issue is still valid.

What kind of failure would you expect? They can only fail when the variable has an actual value. When you construct the route it is encoded as a String and can have any value. As long as you don't use forbidden characters this works fine. The only possible solution would be to always encode strings as URI but this would have a performance cost.

**Comment by alixwar** [comment]
> What kind of failure would you expect? They can only fail when the variable has an actual value. When you construct the route it is encoded as a String and can have any value. 

I do have a value. It's just that the value consists of normal characters with line breaks in between, which the navigate API cannot match to a single string argument

**Comment by bigfarid** [comment]
> > What kind of failure would you expect? They can only fail when the variable has an actual value. When you construct the route it is encoded as a String and can have any value.
> 
> I do have a value. It's just that the value consists of normal characters with line breaks in between, which the navigate API cannot match to a single string argument

I mean that the value is only assigned at runtime, not compile-time, hence you don't have a value at compile time so that your build would fail.

**Comment by alixwar** [comment]
> I mean that the value is only assigned at runtime, not compile-time, hence you don't have a value at compile time so that your build would fail.

Right. I'm fine with a runtime exception, but it would be good to get a hint on why the route matching was not successful. My findings suggest that any route matching would fail if there is a line break character included. So a runtime exception stating that fact would be very helpful for the developer when this happens. In my case the same code worked fine for some string values but not for others.

**Comment by ianhanniballake** [comment]
`Uri.encode` is indeed the correct approach. The [feature request for Safe Args support in Navigation Compose](https://issuetracker.google.com/issues/188693139) is expected to take care of this core you.
