### ISSUE TITLE
Drawer opened initially when using navigation animation

### ISSUE THREAD

**Issue by Debdutta-Panda** [google/accompanist#1209]
## Describe the bug
When I using Drawer with navigation animation the drawer seems to be opened initially and goes out during navigation animation.

## To Reproduce
Create a simple project with 2 pages, let's say splash and home.
Put a drawer in home.
Make splash as start destination.
Navigate to home from splash after 2 to 3 seconds.
Then you can see the visual glitch

## Expected behavior
The expected behavior is drawer will be closed initially. But here drawer seems to be opened.

## Screenshots?
![drawer_with_navigation_animation_glitch](https://user-images.githubusercontent.com/92369023/174515569-7ecb9906-e2be-491f-9fd2-cb7b857d5bc5.gif)

## Environment:
 - Android OS version: 12(31)
 - Device: Emulator(12) and Samsung Galaxy M52(12)
 - Accompanist version: 0.24.11-rc
 - Compose Version 1.1.1
 - Kotlin Version 1.6.10

**Comment by ianhanniballake** [comment]
The drawer isn't 'open' - the drawer just displays its contents off screen (to the left) when it is closed.

You shouldn't ever being using a splash screen as your start destination of your app (instead, use the [API specifically designed for splash screens](https://developer.android.com/guide/topics/ui/splash-screen)) as per the [Principles of Navigation[(https://developer.android.com/guide/navigation/navigation-principles#fixed_start_destination).

**Comment by Debdutta-Panda** [comment]
But what about screen1 to screen2 navigation with animation where screen2 has a drawer?

**Comment by Debdutta-Panda** [comment]
The problem remains the same right?
