### ISSUE TITLE
[Pager] Recomposed all the time when part of a LazyColumn

### ISSUE THREAD

**Issue by MobileSam** [google/accompanist#1211]
**Description**
When I put an HorizontalPager inside a LazyColumn, the pager recomposes all its pages even if the item did not change.
Example: I have a list of strings and only the last string change over time.

```kotlin
@Composable
fun RecomposeTest(state: State<List<String>>) {
    LazyColumn(modifier = Modifier.fillMaxSize()) {
        items(state.value) { name ->
            HorizontalPager(
                count = 1,
                key = { name }
            ) {
                Text(text = name)
            }
        }
    }
}
```

If I replace the HorizontalPager with a LazyRow, only the last item is ever recomposed

**Steps to reproduce**
Here is a simple project that shows the problem by comparing both HorizontalPager and LazyRow
[RecomposePager.zip](https://github.com/google/accompanist/files/8967520/RecomposePager.zip)

**Expected behavior** 
Only the last HorizontalPager should be recomposed.

**Additional context**
I'm using `Compose 1.2.0-rc02` and `Pager 0.24.11-rc`

**Comment by andkulikov** [comment]
Filed it as a Compose bug: https://issuetracker.google.com/issues/251161851

**Comment by hm-tamim** [comment]
Any update on this?
