### ISSUE TITLE
[System UI Controller] statusbar icons hidden in light mode after app is restarted

### ISSUE THREAD

**Issue by ber4444** [google/accompanist#1213]
**Description**
Icons in the status bar are invisible beyond the initial launch.

**Steps to reproduce**
Our status bar icons color is black but as we close (via task manager) and relaunch the app, the icons color changes to white  and it's happening over white background so the icons are not visible.

The code we have is 
```
// in the Activity, this is called before setContent:
fun setStatusBarGradiant(activity: Activity) {
    val window: Window = activity.window
    val background = ContextCompat.getDrawable(activity, R.drawable.gradient_theme)
    window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)

    window.statusBarColor = ContextCompat.getColor(activity,android.R.color.transparent)
    window.setBackgroundDrawable(background)
}

// in the Composable screen:
    val systemUiController = rememberSystemUiController()
    systemUiController.setStatusBarColor(color =
    if (isSystemInDarkTheme()) MaterialTheme.colorScheme.background else Color.White)
```
Using `darkIcons` does not fix the issue.

**Expected behavior** 
The `setStatusBarGradient` is needed for this effect:
![rounded corners and tablet view](https://user-images.githubusercontent.com/205867/175667533-651bd810-afe1-48ed-a608-b75568ead826.png)
Screenshots showing the difference between initial and subsequent launches on the login screen (we have a single Activity app so it still has the same parent activity):
![Screenshot_20220624_140242](https://user-images.githubusercontent.com/205867/175667712-424d2055-b901-4e98-9cad-71c94b27daa0.png)
![Screenshot_20220624_140138](https://user-images.githubusercontent.com/205867/175667728-57bb0518-29e6-4883-b664-487fefca8399.png)

**Additional context**
This bug is specific to Android 12 (Samsung, Pixel, etc). Works fine on OS 13 and 11 and below. Strangely, the bug is not there in dark mode either, only in light mode.

**Comment by alexvanyo** [comment]
Which version of `androidx.core` are you on? Can you update to the latest version and see if that fixes the issue?

This behavior sounds quite similar to an issue that was fixed upstream fairly recently.

**Comment by ber4444** [comment]
I was on 1.8.0-beta01, upgraded to 1.8.0 and 1.9.0-alpha05 and in both cases the status bar is completely white, even on first launch. So it got _more broken_ than it was. 

using
```
compose = "1.2.0-rc02" 
accompanist = "0.24.12-rc"
```

**Comment by alexvanyo** [comment]
That's interesting, would it be possible to share a sample to help reproduce the issue?

**Comment by alexvanyo** [comment]
In the sample you linked, it looks like you are changing the `isAppearanceLightStatusBars` in two places: once in `MyApplicationTheme`, and once in `MainActivity`.

I'd make sure that there's only one place where you are making the changes, otherwise they might conflict against each other and lead to unintuitive behavior.

**Comment by ber4444** [comment]
It works on some Samsung phones on OS 12 like the Fold (shows a gradient background in the status bar with white icons), and on Pixel with OS 13 (shows a white background in the status bar with black icons), but many phones will show a white background with _white icons_ on OS 12, including some cheaper Samsung phones.

**Comment by alexvanyo** [comment]
Could you provide an updated sample where you are seeing the issue, and setting the dark icons in one place?
