### ISSUE TITLE
[Permissions] Denied permission behavior

### ISSUE THREAD

**Issue by sed0** [google/accompanist#1214]
**Description**
Suggested behavior seems to be unintuitive to users.

**Steps to reproduce**
Deny permission with "dont ask again" checked or deny permission once on newer Androids. Click "grant" and nothing will happen.

**Expected behavior** 
We should send user to settings because it's the only way for them to grant permissions.

**Additional context**
I've seen it's been discussed a little bit and that it's a UX team decision but I feel like it's unintuitive to users.
I've seen that it's also related to some technical issues but still feel like doing nothing is worse than sending user to settings even if it's not necessary in some cases.
I also tested this in Google Maps and it seems to be working properly. Maps recognizes if permission was actually denied or user just closed permissions dialog (Android 11). When permission is actually denied it's suggesting user to grant permission via settings.If no private API is used it means that it's possible to make UX a lot better and not sending user to settings when it's not necessary.
But I still feel like in cases where the only option to grant permissions is via settings it's a lot better to send user to app settings then doing nothing. It saves a couple minutes of searching the app in full app list, it doesn't require user to know how to grant denied permission, it doesn't force user to google if they don't know how to do it.

**Comment by xuhaoyang** [comment]
quite agree !!
