### ISSUE TITLE
[Pager] Horizontal Pager with list of images doesn't work as intended

### ISSUE THREAD

**Issue by mehul4795** [google/accompanist#1222]
**Description**

Currently, I am using the `HorizontalPager` to load a list of images. In the latest version of accompanist (0.24.12-rc), I read that the page is considered to be the next page when the swipe distance is equal to or greater than half of the screen width . I am using  `AsyncImage()` from the Coil library to load the image. When the user swipes the images quickly, everything works fine but the issue occurs when the swipe is slow. During a slow swipe, it can be seen that the image is getting changed halfway which appears janky as shown in the attached video. 

**Steps to reproduce**

Just load the list of images in the `HorizontalPager` using the `AsyncImage()` from the Coil library. I am attaching the code that I am using to load the images.

``` kotlin
HorizontalPager(
                count = args.images.size,
                itemSpacing = 16.dp
            ) {
                AsyncImage(
                    modifier = modifier,
                    model = images[this.currentPage].uri
                )
            }
```

**Expected behavior** 

The swipe should feel natural without abruptly loading the next image.

https://user-images.githubusercontent.com/13131390/176727207-1536e7c0-bf8f-4834-8d83-074576068876.mp4

**Comment by andkulikov** [comment]
Pager can compose multiple pages at one, there is an int parameter in the HorizontalPager lambda which is a page number. You need to use it instead of the same current page on all composed pages

**Comment by mehul4795** [comment]
I am sorry but I can't find it. I also checked the documentation and the sample app of Accompanist and can't find its usage. It would be very helpful if you can share the code snippet or the link to the page if available.

**Comment by andkulikov** [comment]
Instead of

`            HorizontalPager(
                count = ...
            ) {
                AsyncImage(
                    model = images[this.currentPage].uri
                )
            }`
do
`            HorizontalPager(
                count = ...
            ) { page ->
                AsyncImage(
                    model = images[page].uri
                )
            }`

**Comment by mehul4795** [comment]
Thank you. Works like charm.
