### ISSUE TITLE
Webview not properly sized Jetpack compose (Autosizable Webview)

### ISSUE THREAD

**Issue by ShreyashKore** [google/accompanist#1224]
## Webview without fixed dimension won't size properly. Sometimes it won't even show up.
When using WebView (to display complex text and maths); size of the WebView will depend on amount of content. WebView takes time to load the content so the size of the webview in first composition is calculated as zero. Later when recomposition occurs through some interaction or animation; then only size of WebView is properly calculated. This problem can be seen more prominently when Instrinsic size is given to the parent.

## To Reproduce
Place WebView composable in Box, Column or Row.

``` kotlin
Surface() {
    Row(
        modifier = Modifier.height(IntrinsicSize.Max)
    ) {
        WebView(state = WebViewState(WebContent.Data("Dynamic Data")))
        Spacer(modifier = Modifier.width(10.dp).fillMaxHeight())
    }
}
```
## Expected behavior
Size of the webview should depend on the amount of content present in it. Recomposition should occur once WebVew has loaded its content and has properly sized itself.

## Environment:
 - Accompanist version: 0.24.9-beta

**Comment by cj1098** [comment]
Want to second this. Happens to me as well. I'm on 0.24.3 so it goes back there. 
Setting a size on the webview, does work because lazyColumn actually has a size to display. Otherwise, it won't recalculate. Unfortunately mine needs to be a dynamic size.

**Comment by bentrengrove** [comment]
I have reproduced this and agree. I think this should be fixed upstream though so have filed a bug and will follow up with the team. I will keep this open for now as we could possibly work around it in Accompanist.

https://issuetracker.google.com/issues/238245846
