### ISSUE TITLE
[Accessibility for HorizontalPager using bluetooth switch controls.]

### ISSUE THREAD

**Issue by Bhagyarajreddy** [google/accompanist#1226]
**Description**: 

1. Requirement is accessibility for compose HorizontalPager.
2. Testing HorizontalPager with phone keypad/switch control
3. Framework supported arrow button appear on top of horizontal pager (as attached screenshot), it is not focusable.

User is not able to navigate the HorizontalPager using keypad/bluetooth switch controls in Accessibility

**Steps to reproduce**: Connect the bluetooth switch and try to navigate between the HorizontalPager screens using switch control without swiping with finger and observe arrows not focussing.

**Expected behavior**: User should able to  navigate between the HorizontalPager screens using switch controls.

**Additional context:** Accessibility for HorizontalPager using bluetooth switch controls.

**Comment by andkulikov** [comment]
Filed as a Compose UI issue: https://issuetracker.google.com/issues/251159580
