### ISSUE TITLE
[Pager] HorizontalPager goes to previous/next page on vertical scroll 

### ISSUE THREAD

**Issue by miduch** [google/accompanist#1233]
**Description**
Trying to use WebView composable (from Accompanist) inside HorizontalPager, when webpage is scrolled (vertically), pager tries to go to next page/ sometime even does go to next page.

**Steps to reproduce**
Run attached sample project and vertically scroll opened webpage in webview.  

```
@OptIn(ExperimentalPagerApi::class)
@SuppressLint("SetJavaScriptEnabled")
@Composable
fun WebViewPager() {
    val pagerState = rememberPagerState()
    HorizontalPager(
        count = 5,
        state = pagerState,
    ) { page ->
        val webViewState = rememberWebViewState("https://duckduckgo.com/?q=${page.inc()}")
        WebView(
            state = webViewState,
            modifier = Modifier.fillMaxSize(),
            onCreated = { it.settings.javaScriptEnabled = true }
        )
    }
}
``` 

**Expected behavior** 
When webview/ webpage is scrolled vertically,  HorizontalPager shouldn't try to go to previous/next page

**Additional context**

```
        compose_compiler_version = '1.2.0'
        compose_ui_version = '1.2.0-rc03'
        accompanist_version = '0.24.13-rc'
        kotlin 1.7.0
```

[WebViewPager.zip](https://github.com/google/accompanist/files/9067569/WebViewPager.zip)

**Comment by miduch** [comment]
https://user-images.githubusercontent.com/22243296/177878788-10bd97ac-90aa-42ce-afc1-45000f57ac9b.mp4

**Comment by miduch** [comment]
when doing same with only compose  without any AndroidView/WebView then it works fine e.g. any vertical scroll on following doesn't cause HorizontalPager trying to open page when its not wanted, one has to clearly do horizontal scroll to go to next page. 

```
@OptIn(ExperimentalPagerApi::class)
@Composable
fun ComposePager() {
    val pagerState = rememberPagerState()
    HorizontalPager(
        count = 5,
        state = pagerState,
    ) { page ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(state = rememberScrollState())
        ) {
            repeat(30) {
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 8.dp, vertical = 12.dp)
                        .wrapContentHeight()
                ) {
                    Text(
                        text ="Item $it",
                        fontSize = MaterialTheme.typography.h3.fontSize
                    )
                }
            }
        }
    }
}
```

**Comment by Nek-12** [comment]
I'm facing the same issue in a layout that includes a LazyColumn inside a pager inside a BackdropScaffold

**Comment by alitahabundle** [comment]
anything possible that the possible couse of this? I am facing the same issue too like @Nek-12 with a scaffold containing horizontal view pager including lazy column

**Comment by Nek-12** [comment]
Not stale

**Comment by Acorde** [comment]
I have same issue. Is there a solution?

**Comment by Zhuinden** [comment]
> I have same issue. Is there a solution?

Did you try foundation pager? Maybe they fixed it there, even if it was abandoned here.

**Comment by leinardi** [comment]
I'm using the foundation pager and this issue is still present, is there any know workaround?

**Comment by andkulikov** [comment]
Please file a bug in the main compose bug tracker with a reproducible sample. Thanks!

**Comment by leinardi** [comment]
Couldn't this be an issue related to the WebView accompanist wrapper? In the end the issue happens with the WebView wrapper with both the old and new pager.

Shouldn't I file a WebView issue here instead?

**Comment by andkulikov** [comment]
Right, sorry. It is indeed a WebView related issue most likely

**Comment by GXBaum** [comment]
hey everyone, does anyone have a solution for this?
Thank you.
