### ISSUE TITLE
[Pager] Unwanted scrolling during configuration updates

### ISSUE THREAD

**Issue by jan-berge-ommedal** [google/accompanist#1237]
**Description**

When using a pager in an activity that handles orientation configuration changes, the pager is unable to maintain its scroll position and may even change its current page.

[pager.webm](https://user-images.githubusercontent.com/2139274/178061618-b45993b8-5d1d-47f4-b40f-13db93d6f2e6.webm)

**Steps to reproduce**

Add `android:configChanges="orientation"` to the activity declaration in the manifest.

Minimal repro:
```
class LauncherActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            HorizontalPager(2, Modifier, rememberPagerState(2)) { page ->
                BasicText(page.toString(), Modifier, TextStyle.Default.copy(fontSize = 50.sp))
            }
        }
    }

}
```

**Expected behavior** 

The pager should retain its offset and page across orientation changes

**Comment by andkulikov** [comment]
Thank you. We are tracking it as a bug in Compose UI here - https://issuetracker.google.com/issues/236391559
