### ISSUE TITLE
[Pager]HorizontalPager cannot save the AndroidView state. 

### ISSUE THREAD

**Issue by wilinz** [google/accompanist#1238]
HorizontalPager cannot save the AndroidView state. When switching pages, the AndroidView factory will be triggered, resulting in view recreate. If WebView is used in HorizontalPager, the webpage will be reloaded when switching pages.

**Comment by agent10** [comment]
I have the same issue with WebView. It keeps reloading every time I switch my tabs. Very annoying.

**Comment by David-Development** [comment]
Starting with Version 0.19 there was a switch from the previous HorizontalPager to a LazyRow implementation. By definition a LazyRow only shows views inside the viewport thus the WebView keeps reloading every time. 

> both HorizontalPager and VerticalPager were re-written to be based on LazyRow and LazyColumn respectively https://google.github.io/accompanist/pager/#changes-in-v0190

This is also related to https://github.com/google/accompanist/issues/899 where the support for `offscreenPageLimit` is discussed. 

I noticed myself that in a setup with a Horizontal Pager with only 3 Tabs the tabs on the right hand side are kept and are recycled while tabs on the left are disposed immediately when they leave the viewport.

**Comment by tengyeekong** [comment]
Seems like Pager don't save the state of the pages and recreate everything in the page when switching pages.
Is there any solution for this?

**Comment by lectricas** [comment]
I think its rather obvious that there should be an option to keep the pages in memory. Why google keep making my life complicated? Do they like it?

**Comment by Nek-12** [comment]
Using foundation pager you can specify an offscreen page limit. No need to vent here.

**Comment by rs5173** [comment]
Jetpack Compose is a piece of shit 💩💩💩!!!

BIGGGGGGGGGG 💩💩💩 !!!

**Comment by jasonjiicloud** [comment]
In my version, HorizontalPager has a parameter: `beyondBoundsPageCount`,  which can specify the number of pages you want to preload before or after the visible ones. When switching pages, the specified one will not reload, it keeps alive.

**Comment by savvasenok** [comment]
> In my version, HorizontalPager has a parameter: `beyondBoundsPageCount`, which can specify the number of pages you want to preload before or after the visible ones. When switching pages, the specified one will not reload, it keeps alive.

This worked for me! Thanks
