### ISSUE TITLE
Is it possible to disable user interaction but only from a state?

### ISSUE THREAD

**Issue by nuhkoca** [google/accompanist#1239]
**Description**

Sorry, this is not a bug but rather a question if it is possible or not. Is it possible to disable user interaction and to only show the swipe refresh depending on a flag? I don't want users to manually refresh. Thanks.

**Comment by bentrengrove** [comment]
There is a `swipeEnabled` parameter. Setting it to false should do what you need.

**Comment by nuhkoca** [comment]
Thank you!
