### ISSUE TITLE
[Navigation Material] Bottom sheet disappears when navigating up without animation

### ISSUE THREAD

**Issue by gregnuvo** [google/accompanist#1246]
**Description**

Current behavior: When my app does a navigateUp or otherwise navigates away when a bottom sheet is showing, the bottom sheet just disappears.
Desired behavior: When the navigation graph pops the bottom sheet or otherwise navigates away, the bottom sheet should do a show a smooth transition. By default it should show the same animation in reverse that it did when it slid into view.

**Comment by Nek-12** [comment]
Duplicate of #724

**Comment by ianhanniballake** [comment]
Yep, same issue.
