### ISSUE TITLE
Gradle Sync issue because of incompatible version of the Android Gradle plugin

### ISSUE THREAD

**Issue by Kaaveh** [google/accompanist#1247]
## Describe the bug
I forked project and tried to build locally. Gradle can't sync successfully and said:

```
The project is using an incompatible version (AGP 7.3.0-beta01) of the Android Gradle plugin. Latest supported version is AGP 7.2.1
```

**Comment by bentrengrove** [comment]
We are building on Android Studio Dolphin at the moment. You can safely change the AGP version to match the version of Android Studio you are using.

**Comment by Kaaveh** [comment]
Got it, Thanks.
