### ISSUE TITLE
[Navigation Material] Bottom sheet destination remains in visibleEntries forever

### ISSUE THREAD

**Issue by joharei** [google/accompanist#1252]
**Description**
When popping the back stack or navigating to another destination from a bottom sheet, the bottom sheet destination remains in `navController.visibleEntries`, in the `CREATED` state forever. 

Related to #724 perhaps?

**Steps to reproduce**
Run my [minimal repro app](https://github.com/joharei/NavigationMaterialVisualEntries).
1. Click the button to open a bottom sheet
2. Click the button in the bottom sheet to pop back
3. Observe the list of `visibleEntries` on the first page
4. Repeat the process to fill the list with even more entries

**Expected behavior** 
The entry should be removed from the list of `visibleEntries` after it is gone (after its exit animation as soon as that is implemented)

**Comment by ianhanniballake** [comment]
Dup of #978, which was just fixed and will be in the next Accompanist release.
