### ISSUE TITLE
Readme: Clarify whether accompanist has to match compose lib or compiler version

### ISSUE THREAD

**Issue by carstenhag** [google/accompanist#1253]
## Describe the bug
As per the current readme it's unclear whether I have to match accompanist's version with the compose libs or the compose compiler.

I guess it's the compiler, but it should be specifically mentioned. 

## Additional context
https://android-developers.googleblog.com/2022/06/independent-versioning-of-Jetpack-Compose-libraries.html

**Comment by bentrengrove** [comment]
This is a great point, thanks for raising it.

It's actually whatever compose library the accompanist library you are pulling in, uses. Taking [FlowLayout as an example](https://github.com/google/accompanist/blob/f619020174239f49e1ae7c2907a0a8f4f1eb986d/flowlayout/build.gradle#L85) it uses UI and Foundation. So between your app and the version of Accompanist you pull in, whatever version of UI and Foundation is higher will be the version gradle resolves.

If you are on Compose 1.1 and you pull in Accompanist FlowLayout that uses 1.2 you are effectively upgrading your project to 1.2. This is a concept we have struggled to get across in the readme so I would love your input on what wording would have made this more understandable?

**Comment by carstenhag** [comment]
To be honest, I did not completely get your comment. Using FlowLayout as example: UI and Foundation's version would be set via FlowLayout, but the compiler version is independant of that?

The sentence "If you are on Compose 1.1 and you pull in Accompanist FlowLayout that uses 1.2 you are effectively upgrading your project to 1.2." is hard to understand for me because I don't know what "Compose 1.2" means - is that the same as compiler 1.2 and libs 1.2, or is that something else?

**Comment by bentrengrove** [comment]
Libraries, not the compiler.

**Comment by bentrengrove** [comment]
Readme has been updated to better explain this

**Comment by carstenhag** [comment]
Just read through the changed parts and it makes sense to me. Thanks!
