### ISSUE TITLE
[Pager] Option for pages to wrap their content's size

### ISSUE THREAD

**Issue by cvb941** [google/accompanist#1256]
**Description**
I'm looking to create a scrollable monthly calendar, with Month composables that are of a fixed size. Pager shows a single page by default, but the screen is big enough to display multiple months simultaneously. This can currently be achieved by specifying the contentPadding attribute.

I need to pass in a certain value to the contentPadding if I want to display the months exactly back-to-back, and this value is dependent on the total size of the Pager. So right now, you have to know the size of the Pager and the Month composables and subtract those two in order to get the correct contentPadding.

I'm essentially looking for the classic LazyList behavior in this regard. However, I would still like to use Pagers for their scrolling behavior, etc.

A way of achieving this would be that the pages could optionally wrap the size of their contents, instead of inheriting their size from the Pager, as they currently do.

**Comment by andkulikov** [comment]
If you essentially only need a lazy list with snapping, you don't need a Pager. Just use a lazy list and apply https://github.com/chrisbanes/snapper for it. It is essentially what Pager does, but Pager is dedicated to the case where you have only one main page
