### ISSUE TITLE
Webview does not support loading url which is identical to the previous one.

### ISSUE THREAD

**Issue by TomasBlazej** [google/accompanist#1257]
I have a case, where some highly secure banking site loads the url twice in a quick succession - do not know if it is a bug on their side or some backend trick. First load of the url shows just a blank page and only the second load shows the actual content. 

I'm not able to do this with accompaninst webview as it is prevented in two places. 
It overrides all urls and sets content url, which should launch the update block and load the url - but not for the same url as it is not counted as state change. And then also in the update block, there is a check for url change to prevent reloading when only other parts of state changed. Both of these could probably be solved by some kind of a url-set-timestamp as part of the state, something like:
![image](https://user-images.githubusercontent.com/26979467/180209965-4f6cddaf-5569-4bd9-9902-0d0e929eb983.png)

I'd think it should be generally possible to load the same url again.

**Comment by Vad-mik** [comment]
I'm facing the same issue. When clicking a button in info window of a bank page i'm getting eternal loading. However, usual WebView in this case loads a page with same url.
Is there some workaround? Thanks!

**Comment by bentrengrove** [comment]
I'm hoping #1344 also will fix this issue but not confident. Once it's merged, I would love for you to test your use case please.

**Comment by Vad-mik** [comment]
@bentrengrove  Now it is working ok (using v0.26.5-rc), at least in my case! Thanks!
