### ISSUE TITLE
TopAppBar does not collapse with WebView

### ISSUE THREAD

**Issue by jaredsburrows** [google/accompanist#1260]
## Describe the bug
The Accompanist Webview "content" does scroll with the `TopAppBar` but the `TopAppBar` does not collapse on scroll. `TopAppBar` does collapse with other views, for example - https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary.

# Repo
https://github.com/jaredsburrows/android-gif-example

# Code
https://github.com/jaredsburrows/android-gif-example/blob/32d96e6d5b1575141c7b4ae57ec2a7c199303c33/app/src/main/java/com/burrowsapps/example/gif/ui/license/LicenseActivity.kt#L110

```kotlin
@Composable
fun DefaultPreview() {
  val navController = rememberNavController()
  val scrollBehavior = TopAppBarDefaults.enterAlwaysScrollBehavior(rememberTopAppBarScrollState())

  Scaffold(
    modifier = Modifier.nestedScroll(scrollBehavior.nestedScrollConnection),
    topBar = { TheToolbar(navController = navController, scrollBehavior = scrollBehavior) },
    content = { paddingValues ->

      val context = LocalContext.current
      val state =
        rememberWebViewState("https://appassets.androidplatform.net/assets/open_source_licenses.html")

      com.google.accompanist.web.WebView(
        state,
        modifier = Modifier.padding(innerPadding).nestedScroll(scrollBehavior.nestedScrollConnection),
        onCreated = { webView ->
        },
        client =  { }
      )
      
    }
  )
}
```

If I use a different view other than `WebView`, it will scroll like the example in the documentation.

**Comment by jaredsburrows** [comment]
Wrapping this in a `Box` with `Modifier.verticalScroll(rememberScrollState())` gives the desired collapsing `TopAppBar`. But now prevents "clicks" in the `WebView`.


```kotlin
@Composable
fun DefaultPreview() {
  val navController = rememberNavController()
  val scrollBehavior = TopAppBarDefaults.enterAlwaysScrollBehavior(rememberTopAppBarScrollState())

  Scaffold(
    modifier = Modifier.nestedScroll(scrollBehavior.nestedScrollConnection),
    topBar = { TheToolbar(navController = navController, scrollBehavior = scrollBehavior) },
    content = { paddingValues ->

      val context = LocalContext.current
      val state =
        rememberWebViewState("https://appassets.androidplatform.net/assets/open_source_licenses.html")

      Box(modifier = Modifier.verticalScroll(rememberScrollState())) {
        com.google.accompanist.web.WebView(
          state,
          modifier = Modifier.padding(innerPadding).nestedScroll(scrollBehavior.nestedScrollConnection),
          onCreated = { webView ->
          },
          client =  { }
        )
      }
      
    }
  )
}
```

**Comment by bentrengrove** [comment]
Nothing unfortunately, my attempted fix caused other issues. We haven't made any progress on this yet, it remains an open issue. If you do work anything out, please feel free to submit a PR.

**Comment by alitahabundle** [comment]
@bentrengrove I just added a rememberScrollState and added it after the modifier clipToBounds in your implementation. and it works perfectly. However, don't know if it will create any further issues.

**Comment by jaredsburrows** [comment]
I actually have this working in my repo now: https://github.com/jaredsburrows/android-gif-example/blob/b2b4bcf0c240cdd463930b399089eca0700da489/app/src/main/java/com/burrowsapps/example/gif/ui/license/LicenseScreen.kt#L128.
