### ISSUE TITLE
[Pager]  HorizontalPagerLoopingIndicatorSample.kt , when i press  ,  pagerState.interactionSource.interactions.collect no invoke

### ISSUE THREAD

**Issue by 309152665** [google/accompanist#1263]
version : 0.24.13-rc

desc : 
我想使用 HorizontalPager 实现个轮播图效果 , 它可以无限轮训 , 可以进行定时
这是我的代码 : 

<img width="1745" alt="image" src="https://user-images.githubusercontent.com/7857673/180752889-b5281076-3485-40b1-b876-cccf37056ed0.png">

但是 我有问题 , 比如我手指操作的时候 , 我想把自动轮播暂停 , 等我把手拿开 , 继续轮播 
我这边使用的是  pagerState.interactionSource.interactions.collect  去监听当前的事件 , 但是这个监听 PressInteraction.Press 不触发 , 我点击的时候 , 没有回调 , 所以这个轮播图目前对手势的支持很差.

**Comment by xiaozhikang0916** [comment]
`interactionSource` in PagerState only `dispatches drag events`, as described in its comment.

Try to use `detectTapGestures` with `Modifier.pointerInput` to detect press and up actions.

**Comment by 309152665** [comment]
> 

我尝试过你说的这个 detectTapGestures , 还有其他各种手势进行拦截 , 例如 AwaitPointerEventScope 等 , 一开始是可以获取到 press and up actions , 但是  当我给  HorizontalPager 里的组件 , 例如 Image 或是 Text 设置了Modifier.clickable 之后 , 我就收不到 up action .

**Comment by 309152665** [comment]
> 我尝试过你说的这个 detectTapGestures , 还有其他各种手势进行拦截 , 例如 AwaitPointerEventScope 等 , 一开始是可以获取到 press and up actions , 但是 当我给 HorizontalPager 里的组件 , 例如 Image 或是 Text 设置了Modifier.clickable 之后 , 我就收不到 up action .
