### ISSUE TITLE
[Insets] Bottom Padding Do not transition to 0 when keyboard hide

### ISSUE THREAD

**Issue by trieutranIncepIT** [google/accompanist#1266]
**Description**

**Steps to reproduce**
1. Click on TextFieldd
2. Edit text
3. Call LocalKeyboard hide
4. the keyboard hide but leave a blank

**Expected behavior** 
No blank, the view expand like before keyboard showup
**Additional context**

**Comment by alexvanyo** [comment]
At this point accompanist/insets is deprecated, with support upstreamed to Compose and released in 1.2.0.

If you are running into the same issue with the built-in insets APIs, please file a bug on the main Compose issue tracker.

Thanks!
