### ISSUE TITLE
[Pager] pagerTabIndicatorOffset unresolved

### ISSUE THREAD

**Issue by DanteAndroid** [google/accompanist#1267]
**Description**
Cannot find pagerTabIndicatorOffset method

**Steps to reproduce**
        compose_version = '1.2.0'
        accompanist_version = '0.25.0'

**Comment by andkulikov** [comment]
hey. it wasn't moved or renamed - https://github.com/google/accompanist/blob/f619020174239f49e1ae7c2907a0a8f4f1eb986d/pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt#L34.
The dependency you need is described on the page of the module: https://github.com/google/accompanist/tree/main/pager-indicators
