### ISSUE TITLE
[Placeholder] Why placeholder never disappear

### ISSUE THREAD

**Issue by DanteAndroid** [google/accompanist#1268]
I don't understand, the document doesn't say how to dismiss the placehold so I think it dismisses by itself. But it never does.

<img width="830" alt="截屏2022-07-31 03 36 06" src="https://user-images.githubusercontent.com/10005563/182007260-76c20995-69d8-4560-aefc-2fa3af084dae.png">

**Comment by bentrengrove** [comment]
I can only advice on Accompanist, you have to set `visible` to false when you want it to disappear.

I am not sure how to get that working with Coil sorry.
