### ISSUE TITLE
[Navigation Animation] Support for container transform/shared element transition?

### ISSUE THREAD

**Issue by Ikuzzz** [google/accompanist#1273]
**Description**

Will it support container transform in the future?

**Comment by ianhanniballake** [comment]
[Yes.](https://twitter.com/ianhlake/status/1548666355892703232):

> Yes, the Navigation team is working directly with Doris to ensure that shared elements work great in Navigation Compose.

As per [this](https://twitter.com/ianhlake/status/1548674127673733120):

> AnimatedNavHost is already built on top of AnimatedContent - that's the layer that is next up for a shared element revision
