### ISSUE TITLE
[System UI Controller] SystemUiController is annotated with @Stable but doesn't adhere to the contract

### ISSUE THREAD

**Issue by alexvanyo** [google/accompanist#1277]
`SystemUiController` is annotated with `@Stable`, but doesn't adhere to the contract. Specifically, it has public properties that aren't state aware and won't notify composition when they change, since they're backed by direct platform API calls.

**Comment by Nek-12** [comment]
@bentrengrove I like how people are having to remove the stale label every month, but you keep refusing to disable that bot. This time, it seems to be a record - 7 times with no other activity.

**Comment by Nek-12** [comment]
...
