### ISSUE TITLE
[Feature Request] Add SearchView support

### ISSUE THREAD

**Issue by jaredsburrows** [google/accompanist#1283]
## Describe the issue
Add easy UI support for `SearchView`, similar to the usage with the AndroidX Toolbar. Maybe adding extensions for `TopAppBar`(Material) and `SmallTopAppBar`(Material3). Ideally handle the animation and callbacks for `setOnActionExpandListener` and `setOnQueryTextListener`.

**Comment by bentrengrove** [comment]
This feature request might be better suited for Material to add a compose version of SearchView. You could try file it at goo.gle/compose-feedback. We don't have any plans to add a SearchView wrapper at this time.

**Comment by jaredsburrows** [comment]
I have created a bug here: https://issuetracker.google.com/issues/245736831.
