### ISSUE TITLE
[Navigation Material] bottomSheet destination is not shown in case of dynamic Text height

### ISSUE THREAD

**Issue by Ridje** [google/accompanist#1292]
**Description**
Hello.
I have a bottom sheet destination which has a content with Text composable inside.
In case of Text has more than 1 line - bottom sheet is not shown at all. It's avoidable with fixed layout height or Text height. Also it is possible to workaround it with Scaffold container or fillMaxHeight() layout's modifier.

**Steps to reproduce**
Add a bottom destination with Text(title, style = MaterialTheme.typography.h6, maxLines = Int.MAX_VALUE) composable which should take more than 1 line for sure. Then try to navigate to this destination. Screen is not shown.
It is reproducing both on physical and emulator devices. 
```kotlin
@Composable
fun ItemBottomScreen(
    id: Int,
    title: String,
) {
    Text(title, style = MaterialTheme.typography.h6, maxLines = Int.MAX_VALUE)
}
```
It is not reproducing if I keep title by remember inside of a composable:
```kotlin
@Composable
fun ItemBottomScreen(
    id: Int,
) {
    // works as should - bottom sheet is expanding
    val title = remember { "VERY VERY VERY VERY VERY VERY VERY VERY VERY LONG TITLE" }
    Text(title, style = MaterialTheme.typography.h6, maxLines = Int.MAX_VALUE)
}
```
**Seems like the problem with changing title value. Initial value for title is "Loading". Then if I am changing title to really long string - lines amount is changing and for some reason bottom sheet layout is not showing.
I have the same problem if an initial value like a "VERY VERY VERY VERY VERY VERY VERY VERY VERY LONG TITLE" and then I change title to something like "Loading".**

**Expected behavior** 
Bottom navigation should expand as expected without any workarounds.

**Additional context**
accompanist navigation material 0.26.1-alpha

**Comment by jossiwolf** [comment]
Tracking this in #772.
