### ISSUE TITLE
WebView created with html data always takes up the whole screen

### ISSUE THREAD

**Issue by dorotatomczak** [google/accompanist#1297]
## Describe the bug
As of right now the LayoutParams are created inside the WebView composable and cannot be changed. The layoutParams are MATCH_PARENT, so the result is that no matter how big is the html content is, it will always take up the whole screen.

## To Reproduce
1. Embed WebView inside ModalBottomSheetLayout
2. Create state by using rememberWebViewStateWithHTMLData with data equal to some small html content and pass the state to the WebVIew
3. Run the project, open the bottom sheet with webview and see that it takes up the whole screen

## Expected behavior
The bottom sheet should be the height of the html content that was passed into the WebView. 

## Environment:
 - Android OS version: Android 11.0
 - Device: Emulator
 - Accompanist version: 0.24.13-rc

## Additional context
My proposal is to pass the LayoutParams as the argument to the WebView, so the programmers would be able to configure it according to their needs.

**Comment by bentrengrove** [comment]
Have you tried using a modifier on the composable? If so, which one?

**Comment by dorotatomczak** [comment]
> Have you tried using a modifier on the composable? If so, which one?

Yes, I tried using `Modifier.wrapContentHeight()` and `Modifier.weight(1f, false)`
