### ISSUE TITLE
[Pager] Hairline not extending full width when using `fullMaxWidth` modifier

### ISSUE THREAD

**Issue by ghostbear** [google/accompanist#1298]
**Description**

The hairline is not extending across the whole screen even though the `fullMaxWidth` modifier is used

**Steps to reproduce**

```
ScrollableTabRow(
  modifier = Modifier.fillMaxWidth(),
  selectedTabIndex = state.currentPage,
)
```

**Expected behavior** 

Hairline being across the full screen width

**Additional context**

![image](https://user-images.githubusercontent.com/6576096/185198524-71dbd569-ab9d-49f9-a114-e9d60b572f3b.png)

**Comment by alitahabundle** [comment]
seems like a parent size issue rather than view pager. can you also share the code section where you put the scrollable row?

**Comment by andkulikov** [comment]
It is a bug for ScrollableTabRow, which is located in the material compose library, so please file it here: https://issuetracker.google.com/issues/new?component=742043&template=1590761
