### ISSUE TITLE
Documentation out of sync

### ISSUE THREAD

**Issue by bpappin** [google/accompanist#1299]
## Describe the bug
The documentation on the versions that match compose, is out of sync between the main site and the github site.

See "Compose versions" on both these pages: 
https://google.github.io/accompanist/
https://github.com/google/accompanist

## Expected behavior (if applicable)
I expect clear documentation about which library to use with which version of Compose.

**Comment by bentrengrove** [comment]
Thanks for the report. That should be fixed now
