### ISSUE TITLE
[Pager] HorizontalPager behaving like a Row on fast scroll

### ISSUE THREAD

**Issue by YusufbekIbragimov** [google/accompanist#1304]
** I use compose 1.2.1 version but I have still this issue

** If you use a fast horizontalpager, it will not work and you receive an error

**Comment by andkulikov** [comment]
Could you please add more details on what do you mean by "fast horizontalpager" and what error do you receive

**Comment by YusufbekIbragimov** [comment]
> 

Hi, If I use the horizontal pager fastly, it wouldn't work or it may be freeze

**Comment by YusufbekIbragimov** [comment]
I found the solving

**Comment by jeffy5** [comment]
@YusufbekIbragimov How do you slove this problem finally? I have the same problem now. Hope there is a solution. Thanks!
