### ISSUE TITLE
[Question/Feature request] Open Source Notices for Accompanist?

### ISSUE THREAD

**Issue by alixwar** [google/accompanist#1314]
## Describe the bug
With the [OSS Licenses Gradle Plugin](https://github.com/google/play-services-plugins/blob/master/oss-licenses-plugin/README.md) it is possible to trigger an activity that shows the apps currently used open source libraries and their licenses. 

However, the activity is not styled according to the currently selected theme.

Would it make sense to create a new accompanist library that wraps this plugin?

**Comment by alexvanyo** [comment]
Just to clarify, is this an issue of Accompanist libraries not showing up in the list of licenses, or the feature request to have `OssLicensesMenuActivity` be themed by or written in Compose?

**Comment by alixwar** [comment]
> Just to clarify, is this an issue of Accompanist libraries not showing up in the list of licenses, or the feature request to have `OssLicensesMenuActivity` be themed by or written in Compose?

The latter

**Comment by alixwar** [comment]
I do think this is still relevant... Reopening

**Comment by langsmith** [comment]
Would love more Compose support for this plugin.

**Comment by langsmith** [comment]
and/or more styling support for the plugin's Activity in general
