### ISSUE TITLE
[WebView] doesn't load local html files

### ISSUE THREAD

**Issue by saenic** [google/accompanist#1318]
## Describe the bug
Wenn using the Accompanist WebView Wrapper with a local file url (e.g. `file:///data/user/0/com.example.application/files/something/root/imprint.html`) it doesn't load and prints out a chrome net::ERR_ACCESS_DENIED.

It works when I use an `AndroidView()` with a `android.webkit.WebView` inside

## To Reproduce
1. Create a local html file which can be accessed by your app
2. Use the Accompanist WebView and try to load the file `WebView(state = rememberWebViewState("file:///...something.html")`
3. Run the App and open the View

## Expected behavior
The WebView Wrapper should load the url like the `android.webkit.WebView` does

## Screenshots?
<img width="476" src="https://user-images.githubusercontent.com/5129239/187910712-7102b03e-6823-45a1-a52d-475990eb686f.png">

## Environment:
 - Android OS version: Android 9
 - Device: Nokia 8
 - Accompanist version: 0.25.0

**Comment by alwa** [comment]
It works fine for me. I use versoin 0.26.2-beta.
My URL looks slightly different:

```
file:///android_asset/somefile.html
```

Then something like this:
```
 val state = rememberWebViewState(url)
    WebView(
        modifier = Modifier.contentDescription("Document Web View"), state = state
    )
```

**Comment by bentrengrove** [comment]
Unable to reproduce, I suspect a permissions problem where you are trying to access a file you don't have the rights to. As the comment above shows, that is the correct form to access a file from your assets.

**Comment by saenic** [comment]
It is not a file from assets, it is a file we download and unzip. If it was a permission problem, why does it work using `android.webkit.WebView`?

**Comment by saenic** [comment]
I got it running. We were applying the setting `webView.settings.allowFileAccess` and I didn't do this in Accompanist WebView Wrapper... so when I use

```
WebView(
      onCreated = { it.settings.allowFileAccess = true },
      state = rememberWebViewState(imprintUrl)
)
```
it works
