### ISSUE TITLE
[Pager] HorizontalPagerIndicator displays indicator even if pager is empty

### ISSUE THREAD

**Issue by koral--** [google/accompanist#1319]
**Description**

I'm not sure if it is a bug or an intended behavior/simplification.
If there are no pages then I would expect that HorizontalPagerIndicator displays nothing rather than a single dot.

**Steps to reproduce**
Use the following code snippet:

```kotlin
val pagerState = rememberPagerState()
    HorizontalPager(
        count = 0,
        state = pagerState,
    ) { }

    HorizontalPagerIndicator(pagerState = pagerState)
```

**Expected behavior** 

HorizontalPagerIndicator displays a single dot.

**Additional context**

Nothing is displayed.

**Environment**

        composeCompiler          version 1.3.0
        compose                   version 1.2.1
        accompanist              version 0.25.1

**Comment by andkulikov** [comment]
Yes, I think displaying nothing will be more correct. Feel free to contribute the fix!

**Comment by koral--** [comment]
There is an activity in linked PR.
