### ISSUE TITLE
[System UI Controller] getter for SystemUiController.isSystemBarsVisible is inconsistent with WindowInsets.areSystemBarsVisible

### ISSUE THREAD

**Issue by alexvanyo** [google/accompanist#1323]
The relationship between [`val WindowInsets.areSystemBarsVisible`](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#(androidx.compose.foundation.layout.WindowInsets.Companion).areSystemBarsVisible()) that is now included as part of the upstreamed insets implementation and the property `val SystemUiController.isSystemBarsVisible` is awkward.

The former matches the API of the underlying window insets APIs and is observable, whereas the latter is only a combination of the status bars and the navigation bars, and is not snapshot state backed (related to #1277)

**Comment by alexvanyo** [comment]
See also: https://issuetracker.google.com/issues/244824909

**Comment by alexvanyo** [comment]
As part of the solution to #1277 , it might make sense to deprecate the getter in accompanist.

**Comment by bentrengrove** [comment]
Unfortunately Accompanist SystemUIController has been deprecated and won't be supported going forwards. I am closing this issue. For more information please see our [update blog](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)
