### ISSUE TITLE
[Swipe to refresh]

### ISSUE THREAD

**Issue by dalewking** [google/accompanist#1327]
**Description**

Need semantics to be able to verify if the view is refreshing. There is no good way to test this.

**Comment by dalewking** [comment]
For reference, here is how I worked around it by creating this  wrapper:

```
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.SemanticsPropertyKey
import androidx.compose.ui.semantics.SemanticsPropertyReceiver
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.google.accompanist.swiperefresh.SwipeRefresh
import com.google.accompanist.swiperefresh.SwipeRefreshIndicator
import com.google.accompanist.swiperefresh.SwipeRefreshState

val IsRefreshingKey = SemanticsPropertyKey<Boolean>("isRefreshing")
val IsSwipeEnabledKey = SemanticsPropertyKey<Boolean>("isSwipeEnabled")

private var SemanticsPropertyReceiver.isRefreshing by IsRefreshingKey
private var SemanticsPropertyReceiver.isSwipeEnabled by IsSwipeEnabledKey

@Composable
fun SemanticSwipeRefresh(
    state: SwipeRefreshState,
    onRefresh: () -> Unit,
    modifier: Modifier = Modifier,
    swipeEnabled: Boolean = true,
    refreshTriggerDistance: Dp = 80.dp,
    indicatorAlignment: Alignment = Alignment.TopCenter,
    indicatorPadding: PaddingValues = PaddingValues(0.dp),
    indicator: @Composable (state: SwipeRefreshState, refreshTrigger: Dp) -> Unit =
        { s, trigger -> SwipeRefreshIndicator(s, trigger) },
    clipIndicatorToPadding: Boolean = true,
    content: @Composable () -> Unit,
)  {
    SwipeRefresh(
        state = state,
        onRefresh = onRefresh,
        modifier = modifier.semantics {
            isRefreshing = state.isRefreshing
            isSwipeEnabled = swipeEnabled
        },
        swipeEnabled = swipeEnabled,
        refreshTriggerDistance = refreshTriggerDistance,
        indicatorAlignment = indicatorAlignment,
        indicatorPadding = indicatorPadding,
        indicator = indicator,
        clipIndicatorToPadding = clipIndicatorToPadding,
        content = content,
    )
}

```

**Comment by bentrengrove** [comment]
I'm not 100% sure what you mean sorry. You just extract the state and then assert on it?

There are multiple examples of testing isRefreshing in our tests for SwipeRefresh
https://github.com/google/accompanist/blob/main/swiperefresh/src/sharedTest/kotlin/com/google/accompanist/swiperefresh/SwipeRefreshTest.kt

**Comment by dalewking** [comment]
I swear that what is in the examples is what I tried but could not make it work. Owl have to look at it again next week.

**Comment by dalewking** [comment]
Finally got around to looking at this and find that what you have in place is not sufficient. What you are suggesting is to add a tag to the refresh indicator and see if it is displayed using assertIsDisplayed or assertIsNotDisplayed. There are a number of problems with this:
- It requires you to put a tag on the refresh indicator to use as way to get the node
- The display or removal of the refresh indicator is delayed with respect to the refreshing status due to animation, leading to flaky tests. For example, I switch refreshing to false. the indicator is still displayed until the animation is done.
- If refresh has never been activated then the refresh indicator will not be created. Any assertions on it are going to fail because it does not exist so assertIsNotDisplayed is not sufficient
- So what you have to do is basically assert that it doesn't exist or  is not displayed.

Providing a simple semantic property whether ti is refreshing is much simpler and fixes all these issues
