### ISSUE TITLE
[Permissions] Feature Request - Make `rememberPermissionState` returns `PermissionStatus.Granted` when permission not supported

### ISSUE THREAD

**Issue by igorescodro** [google/accompanist#1328]
While implementing support for `POST_NOTIFICATIONS`, I noticed that the `rememberPermissionState` returns `PermissionStatus.Denied` when called on devices API < 33. Although this is expected behavior since `ContextCompat.checkSelfPermission()` returns `-1` on these cases, I was wondering if there is some way for Accompanist to handle it gracefully. 
IMHO, it's weird to have `if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU)` inside Composable code.

The alternative that I found was to hoist this check for another function, like this:

```kotlin
@Composable
internal fun MyComposableWithPermissionRequest(
    ...
    shouldAskForNotificationPermission: () -> Boolean
) {
    val permissionState = if (shouldAskForNotificationPermission()) {
        rememberPermissionState(permission = POST_NOTIFICATIONS)
    } else {
        object : PermissionState {
            override val permission: String
                get() = POST_NOTIFICATIONS

            override val status: PermissionStatus
                get() = PermissionStatus.Granted

            override fun launchPermissionRequest() {
                // Do nothing
            }
        }
    }
```
As you can see, this is not very scalable and  I need to "fake" a `PermissionState` to allow the app to work properly in previous versions.

I'm sorry if this request does not make sense or even I didn't see a better solution by myself, but I believe that this would be a great addition to the library. 🙂

**Comment by manuelvicnt** [comment]
Hi Igor! I don't think this information should be provided or handled by the `PermissionStatus` itself since the permission doesn't exist / isn't available.

Let me check internally to see if there's anyone who would be interested in providing some sort of `isPermissionAvailable()` API that maintains a list of which permissions are available in which API levels.

Would that help?

**Comment by igorescodro** [comment]
Hello, Manuel!
Definitely would help, if possible!
Thanks for the feedback. ❤️

**Comment by Feinate** [comment]
Any solution ?
