### ISSUE TITLE
Drawable Painter doesn't render vector drawables anymore

### ISSUE THREAD

**Issue by ubuntudroid** [google/accompanist#1343]
## Describe the bug
Since 0.26.3-beta Drawable Painter doesn't render vector drawables.

## To Reproduce (if applicable)
1. Get a vector drawable
2. Reference it in a Drawable Painter, e.g. like so:
```kotlin
                Image(
                    painter = rememberDrawablePainter(
                        drawable = AppCompatResources.getDrawable(LocalContext.current, R.drawable.vector)
                    ),
                    contentDescription = null,
                    contentScale = ContentScale.Inside,
                    modifier = Modifier
                        .height(32.dp)
                        .width(32.dp)
                        .align(Alignment.CenterHorizontally)
                )
```
3. The Drawable won't be drawn, but the image bounding box is there.

## Expected behavior (if applicable)
Vector drawables should be drawn, just like in the previous versions.

## Screenshots? (if applicable)
![image](https://user-images.githubusercontent.com/519867/191007003-ba4da541-fa70-453d-8f0b-9bc810826ad8.png)

## Environment: (if applicable)
 - Android OS version: all Android versions as well as Compose preview in Android Studio
 - Device: all
 - Accompanist version: 0.26.3-beta

## Additional context
This PR might be related to or even causing the issue: https://github.com/google/accompanist/pull/1322

**Comment by bentrengrove** [comment]
Thanks for the report, I haven't been able to reproduce this. Could you possible attach a vector that doesn't work?

Also, out of interest, what about your vector means you have to use drawable painter rather than just `rememberVectorPainter()`?

My reproduce attempt:
<img width="125" alt="Screen Shot 2022-09-19 at 6 45 15 pm" src="https://user-images.githubusercontent.com/19445/191080519-61ac5235-aa65-4e7e-8516-3b78194d07b3.png">

**Comment by ubuntudroid** [comment]
@bentrengrove the vector is nothing I can share publicly - can I somehow sent it to you directly?

`rememberVectorPainter()` works just fine indeed. I'm still wondering why `rememberDrawablePainter()` seized to work with that release. 🤔

**Comment by andkulikov** [comment]
The change (https://github.com/google/accompanist/pull/1322) was reverted
