### ISSUE TITLE
[Pager] Add a selectedPage property?

### ISSUE THREAD

**Issue by badoualy** [google/accompanist#1347]
**Description**
`currentPage`'s value is set with the most visible item. 
This behavior is different from the `getCurrentItem` accessor in `ViewPager` and might not be what dev expect when using it.

I used the following to get the ViewPager's behavior:

```kotlin
val PagerState.selectedPage: State<Int>
    @Composable
    get() {
        // Pager is setting currentPage based on most visible item
        // We actually want to use it only if scroll finished        
        return produceState(currentPage) {
            combine(
                snapshotFlow { currentPage },
                snapshotFlow { isScrollInProgress }
            ) { currentPage, isScrollInProgress -> currentPage to isScrollInProgress }
                .filter { (_, isScrollInProgress) -> !isScrollInProgress }
                .collect { (currentPage, _) ->
                    value = currentPage
                }
        }
    }
```

Open question whether we should have this property in the lib.
Having both `selectedPage/currentPage` would "force" devs to check which one they actually want to use, but could also be confusing I guess.

This might be related the recent changes with `targetPage`? I was curious whether the lack of this API was a conscious choice or not.

Thanks!

**Comment by zoltish** [comment]
**+1** 

```
    LaunchedEffect(state) {
        snapshotFlow(state::isScrollInProgress)
            .drop(1)
            .collect { scrollInProgress ->
                if (!scrollInProgress) {
                    updatedOnSelected(state.currentPage)
                }
            }
    }
```

**Comment by andkulikov** [comment]
Thanks. We are not planning to change anything in the Accompanist Pager implementation, but we filed a bug to explore it again in the new implementation in Compose UI : https://issuetracker.google.com/issues/251157565
