### ISSUE TITLE
[Pager] Scrolling to next page is removing+adding previous one from composition

### ISSUE THREAD

**Issue by badoualy** [google/accompanist#1348]
**Description**

When scrolling to the next page, the previous one seems to be removed from composition then re-added.

**Steps to reproduce**

* Add following log in the `PagerScope` content
```kotlin
DisposableEffect(Unit) {
    Log.e("Pager", "Create $pageIndex")
    onDispose {
        Log.e("Pager", "Dispose $pageIndex")
    }
}
```
* Swipe from page 0 to page 1
* We can see that `Dispose 0` and `Create 0` are called 

**Expected behavior** 

I guess the page should not be removed/re-added to the composition, this can lead to weird effect with remembered values being destroyed/recreated.

**Additional context**

I tried to test whether it was our usage that was causing this, but I think it might be related to how `LazyList` works and might be out of your hands.

**Comment by andkulikov** [comment]
Thanks. I filed it as a lazy list bug: https://issuetracker.google.com/issues/251155606
