### ISSUE TITLE
[Navigation Material] Underlying view(with a nested graph) state isn't stored properly 

### ISSUE THREAD

**Issue by PavloZoria** [google/accompanist#1349]
## Describe the bug
I have the next navigation:

BottomNavigation:
1. First Screen
2. ModalBottomSheet
3. Second Screen

Each of the First/Second is a screen with nested navigation which is built with a `public fun NavGraphBuilder.navigation`

The navigation looks like: 
```
ModalBottomSheetLayout(
        bottomSheetNavigator = bottomSheetNavigator,
        sheetShape = RoundedCornerShape(topStart = 20.dp, topEnd = 20.dp),
        sheetBackgroundColor = MaterialTheme.colors.background
    ) {
        NavHost(
            navController,
            startDestination = Screen_1,
            modifier = modifier
        ) {

            navigation(route = Screen_1, startDestination = Screen_1_1) {
                composable(Screen_1_1) {

                }
                composable(Screen_1_2) {

                }
            }
            bottomSheet(
                BottomSheet,
            ) {
                AddScreen(featureNavigator)
            }
            navigation(route = Screen_2, startDestination = Screen_2_1) {
                composable(Screen_2_1) {

                }
                composable(Screen_2_2) {

                }
            }
        }
    }
```

## To Reproduce
*`Screen_1_1` is a start destination for the `Screen_1`
1. Open `Screen_1`(from the bottom navigation). It opens `Screen_1_1` as it's a start destination for the subgraph
2. Navigate to the `Screen_1_2`
3. Open `BottomSheet`

Current behavior: `Screen_1` is getting restored and `Screen_1_1` displayed instead of `Screen_1_2`

## Expected behavior
The state of the underlying subgraph should be stored and the user has to see `Screen_1_2` under the bottom navigation

## Environment:
 - Android OS version: Android 13
 - Device: [e.g. Emulator, Google Pixel 4]
 - Accompanist version:
"com.google.accompanist:accompanist-navigation-material:0.26.3-beta"

## Additional context

https://user-images.githubusercontent.com/38030130/191519383-e353d2eb-a5f3-4b90-8ebf-0a905935c8ba.mp4

**Comment by jbw0033** [comment]
Can you provide a sample project that reproduces this?

I believe this has to do with how your back stack is being built. Are you popping off `screen_2_1` when  you navigate to `bottomsheet`?

**Comment by PavloZoria** [comment]
@jbw0033 during the creation of the sample, I found an issue in my own code. Thanks a lot for your help and sorry for the interruption
