### ISSUE TITLE
navController.BackQueue returns 2 entries on fresh app start 

### ISSUE THREAD

**Issue by froz3nice** [google/accompanist#1351]
NavController should have only 1 screen in backstack, which is startDestination. However after initializing AnimatedNavHost, some initial backStackEntry is added. 

```
class MainActivity : ComponentActivity() {
    @OptIn(ExperimentalAnimationApi::class)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            val scaffoldState = rememberScaffoldState()
            val navController = rememberAnimatedNavController()
            Scaffold(
                scaffoldState = scaffoldState,
            ) { contentPadding ->
                AnimatedNavHost(
                    modifier = Modifier
                        .padding(contentPadding)
                        .fillMaxSize(),
                    navController = navController,
                    startDestination = "screen",
                    builder = {
                        composable(route = "screen") {
                            ScreenTest(navController)
                        }
                    }
                )
            }
        }
    }

    @Composable
    fun ScreenTest(navController: NavController) {
        Column {
            Text("")
        }
    }
}
```

 just put a breakpoint in ScreenTest and check navController.backQueue, it should contain only 1 backStackEntry.

Theres is a specific issue. After splash screen ends, you can see white screen before start destination is loaded. This causes white flickers. Issues started with accompanist 0.24.8-beta. Here are some more examples 

https://stackoverflow.com/questions/73195177/jetpack-compose-accompanist-navigation-blank-screen-after-splash-screen?noredirect=1#comment130341846_73195177

**Comment by jbw0033** [comment]
The 2nd backStackEntry is your graph which is part of the path to the start destination. That behavior is intended.

Are you waiting for the start destination to be loaded before hiding your splash screen? That is something that needs to be managed outside of Navigation. What seems to be happening here is that the app is showing the splash screen, and then attempting to go to the NavHost, but before the start destination has had the opportunity to be composed, the slash screen disappears and show the background for a frame while the NavHost composes.

You will need to address this on the application side as there is nothing we can do in Navigation.

**Comment by personshelldon** [comment]
And this causes some problems. Because if You call `navController.popBackStack()` manually it will return `false` but the back stack entry count will be 1. If You try to navigate somewhere after that, You will see crash because `navGraph` is missing in these entries, and can not navigate to destinations that do not exist. The problem is in this code in `navController`:
```
@MainThread
    public open fun popBackStack(): Boolean {
        return if (backQueue.isEmpty()) {
            // Nothing to pop if the back stack is empty
            false
        } else {
            popBackStack(currentDestination!!.id, true)
        }
    }
```
