### ISSUE TITLE
HorizontalPager work uncorrectly when closing all animation

### ISSUE THREAD

**Issue by Wintheshow** [google/accompanist#1353]
https://user-images.githubusercontent.com/34152960/192244235-7e2dfcdc-798e-4b8b-8257-5ae77eeffe2e.mp4

I close all animation in Developer options, then I find horizontalPager work uncorrectly. 
It will slide many pages very quickly and end up on the next page.
It worked correctly on accompanist-pager:0.23.1 and compose 1.1.1, problem occur when upgrade either one of them.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/34152960/192243740-59c03a0e-34e1-45fc-8dc1-a14d61fff537.png">

**Comment by andkulikov** [comment]
Thanks. we are tracking it as a Compose bug here: https://issuetracker.google.com/issues/241460890
