### ISSUE TITLE
[Pager] How to impl dynamic `contentPadding` for page item of HorizontalPager?

### ISSUE THREAD

**Issue by rockyoung** [google/accompanist#1354]
**Description**
I want 1st page with end contentPadding by 48dp, so the 2nd page will show a little left content, BUT, when scroll and stop at 2rd page, I want it's width fill (no left and right sibling item' s content can show, no contentPadding any more), and when scroll to 3rd page and stop at it, it's start contentPadding is 48dp too, so the 2nd page will show a little right content.

have tried many ways but no one successed, really need some help please :(

**Comment by rockyoung** [comment]
> Maybe an approach similar to this one can help? https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerDifferentPaddingsSample.kt

really thanks for the quick response, i tried the approach but not the effect i want. my goal is 1st page only have some end contentpadding, 3rd page only have some start contentpadding, and the 2nd have no contentpadding.

**Comment by andkulikov** [comment]
Does it mean that pages will have different size? The Pager is designed for items of the same page size, if it is not what you need you can just use LazyRow with snapping fling behavior

**Comment by andkulikov** [comment]
As I said we do not consider it to be a Pager as items are not of the same size. Try to use LazyRow and apply https://github.com/chrisbanes/snapper or recently added experimental SnapFlingBehavior

**Comment by rockyoung** [comment]
> As I said we do not consider it to be a Pager as items are not of the same size. Try to use LazyRow and apply https://github.com/chrisbanes/snapper or recently added experimental SnapFlingBehavior

ok, i'm checking the source code of `HorizontalPager` now, thank you any way!
