### ISSUE TITLE
[Navigation Material] Unexpected behavior when navigate to bottom sheet and hide keyboard

### ISSUE THREAD

**Issue by imholynx** [google/accompanist#1356]
**Description**
What I have:

- Home Screen with TextField
- Bottom sheet
- `android:windowSoftInputMode="adjustResize"` for activity
- `LocalSoftwareKeyboardController.current` to hide keyboard

**Steps to reproduce**

1. Tap on TextField to open keyboard
2. Navigate to bottom sheet and hide keyboard in same time (onTap)
3. Keyboard is hided but Bottom sheet is invisible

**Expected behavior** 

Keyboard is hidden
Bottom sheet is visible

**Additional context**
    ```implementation "com.google.accompanist:accompanist-navigation-material:0.23.1"```

Sample: https://github.com/imholynx/AccompanistNavigationBugSample

Source code to reproduce:
```
class MainActivity : ComponentActivity() {
    @OptIn(ExperimentalMaterialNavigationApi::class)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme() {
                val bottomSheetNavigator = rememberBottomSheetNavigator()
                val navController = rememberNavController(bottomSheetNavigator)

                ModalBottomSheetLayout(bottomSheetNavigator) {
                    NavHost(navController, "home") {
                        composable("home") { Home(navController) }
                        bottomSheet("bottom_sheet") { BottomSheet() }
                    }
                }
            }
        }
    }
}

@OptIn(ExperimentalComposeUiApi::class)
@Composable
private fun Home(navController: NavController) {
    val keyboardController = LocalSoftwareKeyboardController.current

    LazyColumn {
        item { TextField(value = "", onValueChange = {}) }
        repeat(99) {
            item {
                Text(text = it.toString(),
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(16.dp)
                        .clickable {
                            keyboardController?.hide()
                            navController.navigate("bottom_sheet")
                        })
            }
        }
    }
}

@Composable
private fun BottomSheet() {
    LazyColumn {
        repeat(9) {
            item { Text(text = it.toString()) }
        }
    }
}
```

https://user-images.githubusercontent.com/1606106/192773388-c7e5e47f-2cfa-4d54-9c8b-c3d85214d835.mp4

**Comment by jossiwolf** [comment]
Thanks for the report! There is no fix or workaround for the time being, unfortunately. This is blocked by this upstream issue: https://issuetracker.google.com/167966118

I will update here when I have new information.

**Comment by jossiwolf** [comment]
v0.28.1 addresses this issue. Please let us know if you can still reproduce it with this version.
