### ISSUE TITLE
[Navigation Animation] 

### ISSUE THREAD

**Issue by jv-lee** [google/accompanist#1358]
Use SimpleAnimatedNavHost to add two pages and set a jump animation similar to ios page exitTransition : slideOutHorizontally( targetOffsetX = { fullWidth -> (-(fullWidth * 0.1)).toInt() }, animationSpec = tween(animationDuration) ) popEnterTransition: slideInHorizontally( initialOffsetX = { fullWidth -> (-(fullWidth * 0.1)).toInt() }, animationSpec = tween(animationDuration) ) 2. Route to the second page, perform pop in the second page, then you will see that the first page covers the second page to perform the entry animation, and the second page will perform the exit animation at the bottom.

video url:
[https://issuetracker.google.com/action/issues/246664224/attachments/38881411?download=true](url)

**Comment by jbw0033** [comment]
This has to do with z-order which is a dup of #1160
