### ISSUE TITLE
[WebView] Position on the page is not saved after rotating

### ISSUE THREAD

**Issue by proninyaroslav** [google/accompanist#1360]
**Description**
I think it's similar to this issue, but I'm not sure: https://github.com/google/accompanist/issues/1178.
When I add WebView to any scrollable composable, the scroll position is not saved when the screen is rotated. I think this is because when compose takes measurements, it doesn't know the height of the WebView yet, since the page hasn't been rendered yet. In this case, after the screen is rotated, it will scroll to the position closest to the beginning of the WebView. Is there an idea how to fix this? I tried disabling screen rotation in the manifest as suggested in [#1178 (comment)](https://github.com/google/accompanist/issues/1178#issuecomment-1149558173) but that didn't help either:
```
android:configChanges="orientation|screenSize|screenLayout"
```

https://user-images.githubusercontent.com/7840559/193403739-059d8d1a-571d-4b0d-ae86-634dd1869c59.mp4

Example:
```Kotlin
class MainActivity : ComponentActivity() {
    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                val scrollState = rememberScrollState()
                val webViewState = rememberWebViewState(url = "https://medium.com/")
                Row(
                    modifier = Modifier.verticalScroll(scrollState)
                ) {
                    WebView(
                        state = webViewState,
                        onCreated = {
                            it.settings.apply {
                                javaScriptEnabled = true
                            }
                        },
                        modifier = Modifier.fillMaxSize(),
                    )
                }
            }
        }
    }
}
```

**Steps to reproduce**
1. Wrap WebView in any scrollable composable
2. Make a scroll on the page and rotate the device

**Expected behavior** 
The position must be saved after rotation or any other configuration change.

**Comment by bentrengrove** [comment]
Fixed in #1557
