### ISSUE TITLE
[Pager] HorizontalPager Swipe Screen Flicker

### ISSUE THREAD

**Issue by isaialvarado** [google/accompanist#1365]
**Device:** Pixel 2 Android 11 (physical device)
**Library:** I tried accompanist-pager:0.25.1 and accompanist-pager:0.26.4-beta

**Problem:** When I use HorizontalPager and swipe left to go from page 1 to page 2, the screen flickers and momentarily shows page 3 before showing page 2. The same thing happens when swiping right to go from page 3 to page 2: page 1 will appear and disappear very quickly before showing page 2. This issue doesn't happen on my Pixel 2 API 30 emulator in Android Studio.

I included code below that causes the issue. If I swipe from Red to Black, Yellow will flicker on the screen first. If I swipe from Yellow to Black, Red will flicker on the screen first.

```
class MainActivity : ComponentActivity() {
    @OptIn(ExperimentalPagerApi::class)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            val pagerState = rememberPagerState()

            val colors = remember {
                listOf(Color.Red, Color.Black, Color.Yellow)
            }

            HorizontalPager(
                count = colors.size,
                modifier = Modifier.fillMaxSize(),
                state = pagerState,
            ) { page ->
                Column(
                    Modifier
                        .fillMaxSize()
                        .background(colors[page])
                ) {

                }
            }
        }
    }
}
```

**Comment by isaialvarado** [comment]
I found out that this issue happens when the animation scales are set to "animation off" in the Developer Options. When I set them to 1x, the problem goes away.

**Comment by andkulikov** [comment]
Yes, it is a general Compose UI issue, we track it here: https://issuetracker.google.com/issues/241460890
