### ISSUE TITLE
[DrawablePainter] Ignores Image ContentScale and Alignment since ~v0.26

### ISSUE THREAD

**Issue by gajicm93** [google/accompanist#1366]
## Describe the bug
DrawablePainter only respects its intrinsic size while ignoring Image ContentScale and Alignment

## To Reproduce
1. Create an Image of random size and set to it a DrawablePainter with a drawable of different intrinsic size (different from Image size)
2. Try to set either ContentScale or Alignment on Image
3. See that DrawablePaint completely ignores them and keeps displaying its intrinsic size

## Expected behavior
DrawablePainter should follow Image ContentScale and Alignment

## Screenshots?
/

## Environment:
 - Android OS version: Android 13
 - Device: Pixel 4a
 - Accompanist version: v0.26.5-rc

## Additional context
My drawable is layer-list with items..

**Comment by bentrengrove** [comment]
Fixed in #1368
