### ISSUE TITLE
[Swipe to refresh] Slowly swipe down, SwipeRefresh not working.

### ISSUE THREAD

**Issue by KingsleyWu** [google/accompanist#1371]
**Description**
Slowly swipe down, SwipeRefresh not working. 
**Steps to reproduce**
Just add the code in AS and run, then you slowly swipe down the view, and now you will find the SwipeRefresh not working. this "not working" action is that right?
Use this accompanist project demo is the same.
```
class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        WindowCompat.setDecorFitsSystemWindows(window, false)
        setContent {
            var isRefreshing by remember { mutableStateOf(false) }
            val coroutineScope = rememberCoroutineScope()
            val refreshState = rememberSwipeRefreshState(isRefreshing)
            val lazyListState = remember { LazyListState() }
            SwipeRefresh(
                state = refreshState,
                onRefresh = {
                    isRefreshing = true
                    coroutineScope.launch {
                        if (isRefreshing) {
                            delay(2000)
                            isRefreshing = false
                        }
                    }
                }
            ) {
                LazyColumn(
                    modifier = Modifier.fillMaxSize(),
                    state = lazyListState
                ) {
                    items(100) { index ->
                        Text(text = "index = $index")
                    }
                }
            }
        }
    }
}
```

**Expected behavior** 
SwipeRefresh working.
**Additional context**
implementation "com.google.accompanist:accompanist-swiperefresh:0.25.1"

**Comment by KingsleyWu** [comment]
@bentrengrove

**Comment by bentrengrove** [comment]
With the release of Compose 1.3, Accompanist SwipeRefresh is actually about to be deprecated as this functionality is now available in Compose. We are just writing the migration guide now. There won't be any more bug fixes here so I will close this issue.

If you would like to get ahead of the migration, here is a sample of the new PullRefresh in the Material Compose library.
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/samples/src/main/java/androidx/compose/material/samples/PullRefreshSamples.kt;l=1
