### ISSUE TITLE
[Pager] - deprecated targetPage

### ISSUE THREAD

**Issue by ldev6** [google/accompanist#1372]
**Description**

I'm reporting that targetPage is useful for complex animation.

I'm writing to you to let you know that I'm using the targetPage in addition of the currentPage to be able to handle height animation while scrolling. 

Having only the currentPage doesn't let me known which way I'm scrolling and what will be the height of the next page. 

**Additional context**
```
 // Array of each pageHeight
 val heightArray: MutableState<Array<Int>>  = remember { mutableStateOf(Array<Int>(2) { 300.dp, 500.dp}) 
 LaunchedEffect(pagerState) {
        // Collect from the pager state a snapshotFlow the currentPageOffset
        snapshotFlow { pagerState.currentPageOffset }.collectLatest {
            if (currentPageHeight.value != 0 && heightArray.value[pagerState.currentPage] != -1 && heightArray.value[pagerState.targetPage] != -1) {

                var targetHeight = heightArray.value[pagerState.targetPage]
                if (pagerState.currentPage == pagerState.targetPage) {
                    targetHeight = heightArray.value[1]
                }

                val heightFactor = lerp(
                    start = ScaleFactor(0f, heightArray.value[pagerState.currentPage].toFloat()),
                    stop = ScaleFactor(0f, targetHeight.toFloat()),
                    fraction = pagerState.currentPageOffset.absoluteValue
                )
                pagerHeight.value = heightFactor.scaleY
            }
```

**Comment by Dambakk** [comment]
I'm also using `targetPage`. 

My exact use case is that I want to run some method when user scrolls the pager but not when my state is updated which causes the pager to animateScroll to another page. To do this I collect the interactions and on `DragInteraction.Stop` I run my method with the `targetPage` as input.

Using `currentPage` will work if user scrolls until the page changes to the next (scrolled more than half way to the next page?), but if the user flings to the next page `currentPage` will most probably still be the same page (if the user didn't had a long fling gesture, long enough for the pager to switch to the next page). When using `targetPage` I get my desired behaviour.

**Comment by ldev6** [comment]
@andkulikov or @Levi-Moreira  do you have any other solutions for our problem or can you please let us know if you will still remove the targetPage or not. Thanks

**Comment by andkulikov** [comment]
Hey. We considered multiple options and we will not remove targetPage in the end. We are currently working on a new Pager which will live right in compose.foundation library and it will have targetPage property as well
