### ISSUE TITLE
[Navigation Animation] White flicker while navigating to screen to screen

### ISSUE THREAD

**Issue by yosuke65** [google/accompanist#1380]
**Description**
n dark mode, when I navigate to another screen, there is a white background glimpsing making the transition a bit weird.

**Steps to reproduce**
https://user-images.githubusercontent.com/32787553/197248160-95c8de55-3e4f-4a6a-8dcf-5298893cbf05.mov
One is a vertical transition the white background showing up in dark mode.

https://user-images.githubusercontent.com/32787553/197248338-7775005c-92e7-4e0b-91c6-cc11e26c058f.mov
Another one horizontal transition there is white flicker happening in the bottom of the screen.

**Expected behavior** 

**Additional context**

**Comment by ianhanniballake** [comment]
This is the `windowBackground` of your activity showing through when there is no composable content covering it up; this has nothing to do with Navigation. You should make sure that you have set up your `windowBackground` to change based on when you are in dark mode or not.

**Comment by mrzbn** [comment]
@ianhanniballake I have a project that uses old xml and views. One fragment is refactored using Jetpack Compose. When I try to navigate between fragments, android:windowBackground is displayed for a second and disappears. I have tried applying background color to my composables, but windowBackground displays anyway.

**Comment by mrzbn** [comment]
@ianhanniballake I have a project that uses old xml and views. One fragment is refactored using Jetpack Compose. When I try to navigate between fragments, android:windowBackground is displayed for a second and disappears. I have tried applying background color to my composables, but windowBackground displays anyway.

Even when I set visibility of ComposeView to gone, this window background is shown.

[related SO link](https://stackoverflow.com/questions/75160680/window-background-appears-on-jetpack-compose-screens)

**Comment by ThinClient** [comment]
@ianhanniballake, your comment saved me a lot of headache. I have added a Spacer composable with height equivalent to app bar size and set it to background color. Then nested I the nav controller inside a Box composable. Each screen has its own app bar. Now the flicker is gone.
