### ISSUE TITLE
accompanist for compose 1.4

### ISSUE THREAD

**Issue by miduch** [google/accompanist#1382]
## Describe the bug
No Accompanist version available for compose 1.4.x. 
https://github.com/google/accompanist#compose-versions

## Environment: (if applicable)
 - Android OS version: [e.g. Android 5.0]
 - Device: [e.g. Emulator, Google Pixel 4]
 - Accompanist version: [e.g. v0.X]

**Comment by bentrengrove** [comment]
Until we are using a Compose 1.4 feature, there is no need to create a version of Accompanist specifically for 1.4. You can safely use the current accompanist version.

I will update the readme to make this clear
