### ISSUE TITLE
[Pager] Pacge change triggered twice in fragments

### ISSUE THREAD

**Issue by lolo-io** [google/accompanist#1387]
**Description**

When used in a Fragment, PagerState triggers two times a page change when implemented as the doc says here  : https://google.github.io/accompanist/pager/#reacting-to-page-changes
```
val pagerState = rememberPagerState()

LaunchedEffect(pagerState) {
    // Collect from the pager state a snapshotFlow reading the currentPage
    snapshotFlow { pagerState.currentPage }.collect { page ->
        AnalyticsService.sendPageSelectedEvent(page)
    }
}

VerticalPager(
    count = 10,
    state = pagerState,
) { page ->
    Text(text = "Page: $page")
}
```

**Steps to reproduce**

This is my implementation in a newly created project. I inflate a Compose view in onCreateView : 
```
@OptIn(ExperimentalPagerApi::class)
override fun onCreateView(
    inflater: LayoutInflater,
    container: ViewGroup?,
    savedInstanceState: Bundle?
): View {
    return ComposeView(requireContext()).apply {
        setContent {
            val pagerState = rememberPagerState(3)
            pagerState.let { pagerState ->
                LaunchedEffect(pagerState) {
                    snapshotFlow { pagerState.currentPage }.collect() { page ->
                        Log.d("PagerTest", "Page $page")
                    }
                }
                HorizontalPager(
                    count = 4,
                    state = pagerState,
                    itemSpacing = 0.dp,
                ) { page ->
                    Text("Page $page", color = Color(0xFF000000), fontSize = 28.sp)
                }
            }
        }
    }
}
```
This outoutes in the console : (see `Log.d("PagerTest", "Page $page")` in the SideEffect) : 
`> PagerTest Page 3`
`> PagerTest Page 0`

**Expected behavior** 

Expected output is 
`> PagerTest Page 3`

Expected output is obtained if used in a full compose app. but unfortunately this project still has fragments in the codebase.

**Additional infos** 

Same behavior is observed when using `.distinctUntilChanged()`

**Comment by andkulikov** [comment]
To be honest it is not clear to my why the page will change to 0 when used in the Fragment. Maybe it depends on how your Fragment is used? I am not sure I can reproduce it without having the whole project. 
But the issue is not that observation doesn't work, but because the current page is really reset to 0

**Comment by lolo-io** [comment]
You don't need the whole project. I tested the code snippet I posted in a new project freshly created from Android Studio.
In a project that doesn't use fragments => No problem.
In a project that uses fragments, the bug is present.
I created a "Bottom Navigation Activity" project from Android studio.

**Comment by andkulikov** [comment]
Hey. I just tried to create "Bottom Navigation Activity" project and put your code inside DashboardFragment and run it on emulator and only see  Page 3 being printed. 
Could you please try to first update the latest versions of compose and accompanist and share the whole project which you use to reproduce and on what device you are running it

**Comment by lolo-io** [comment]
Hey I'm really sorry for this I was 100% sure I used the latest accompanist version but it turns out I was using 0.19.0.
I felt I double checked it before creating the issue and posting the snippet.
It works well with the latest version.
Sorry again for this.
I'm closing the issue.
