### ISSUE TITLE
[Navigation Animation] viewmodel leaks when screen forces certain orientation (rotation)

### ISSUE THREAD

**Issue by valeriyo** [google/accompanist#1391]
**Description**
Following up on https://github.com/google/accompanist/issues/1265 which was closed due to inaction. The problem is real and is still reproducible with latest version.

**Steps to reproduce**
1) trigger a configuration change while navigating back. For example, the new destination can do `activity.requestedOrientation = SCREEN_ORIENTATION_LANDSCAPE`, so that current Activity is destroyed, and a new one is created.
2) the ViewModel of the outgoing screen will never receive the `onCleared` callback. 

**Expected behavior** 
ViewModel's onCleared is always called when the view model is no longer needed.

**Additional context**

**Comment by ianhanniballake** [comment]
Do you have a complete sample project that reproduces your issue?

**Comment by arunjoseph-tomtom** [comment]
> 
@ianhanniballake 
I had this sample here -
https://github.com/google/accompanist/issues/1265#issue-1320485235
