### ISSUE TITLE
[WebView] Whole screen white for a while

### ISSUE THREAD

**Issue by KristapsKrumins** [google/accompanist#1393]
WebView blocks UI, the whole screen is white for a while.

**Steps to reproduce**
In BasicWebViewSample.kt replace `https://google.com` with `https://demo.leadtools.com/JavaScript/DocumentViewer/index.html`

**Expected behavior**
TopAppBar is visible instantly.

Comment out the WebView and TopAppBar is visible instantly.

**Comment by bentrengrove** [comment]
There isn't anything we can do about this from Accompanist unfortunately. This is the webview loading the chromium engine and a lot of that work seems to happen on the main thread. This would need to be fixed at the WebView level, any fix here would just be a work around.

<img width="853" alt="Screen Shot 2022-11-14 at 11 29 21 am" src="https://user-images.githubusercontent.com/19445/201552928-ce0a8ec2-0a80-4b50-9e55-5f9b900b7717.png">

**Comment by LaoHuan** [comment]
> 在 WebView 上设置`.alpha(0.99f)`，TopAppBar 立即可见。

 this setting is ok
