### ISSUE TITLE
[Pager] click TabRow to  switch page will Recompose

### ISSUE THREAD

**Issue by happyjun** [google/accompanist#1404]
**Description**

HorizontalPager have two page, after  I  switch  page0 to page1 , when  I again click  tabrow pagerState.scrollToPage to back page0, I found page0 still Recompose 

**Steps to reproduce**

@Composable
private fun Sample() {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.horiz_pager_title_tabs)) },
                backgroundColor = MaterialTheme.colors.surface,
            )
        },
        modifier = Modifier.fillMaxSize()
    ) { padding ->
        val pages = remember {
            listOf("Home", "Shows")
        }
        Column(
            Modifier
                .fillMaxSize()
                .padding(padding)) {
            val coroutineScope = rememberCoroutineScope()

            // Remember a PagerState
            val pagerState = rememberPagerState()

            ScrollableTabRow(
                // Our selected tab is our current page
                selectedTabIndex = pagerState.currentPage,
            ) {
                // Add tabs for all of our pages
                pages.forEachIndexed { index, title ->
                    Tab(
                        text = { Text(title) },
                        selected = pagerState.currentPage == index,
                        onClick = {
                            // Animate to the selected page when clicked
                            coroutineScope.launch {
                                pagerState.scrollToPage(index)
                            }
                        }
                    )
                }
            }
            HorizontalPager(
                count = pages.size,
                state = pagerState,
                // Add 16.dp padding to 'center' the pages
                userScrollEnabled = true,
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth()
            ) { page ->
                // Our content for each page
                if(page == 0){
                    Page0(title = pages[page])
                }else{
                    Page1(title = pages[page])
                }

            }
        }
    }
}

@Composable
fun Page0(title: String) {
    Card {
        Box(Modifier.fillMaxSize()) {
            Text(
                text = "this is  Page: $title",
                style = MaterialTheme.typography.h4,
                modifier = Modifier.align(Alignment.Center)
            )
        }
    }
}

@Composable
fun Page1(title: String) {
    Card {
        Box(Modifier.fillMaxSize()) {
            Text(
                text = "this is  Page: $title",
                style = MaterialTheme.typography.h4,
                modifier = Modifier.align(Alignment.Center)
            )
        }
    }
}

**Expected behavior** 

click tabrow pagerState.scrollToPage back to page0 , page0 can't recompose

**Additional context**

**Comment by andkulikov** [comment]
We only compose the visible page. Which means that when you move to page 1 the previous page will not be composed anymore. Then you go back to page and we compose it again. Why do you think it is not the intended behavior?
