### ISSUE TITLE
[WebView] pageTitle is not restored when reload

### ISSUE THREAD

**Issue by yanzm** [google/accompanist#1407]
**Description**

After `WebViewNavigator.reload()` is called the `WebViewState.pageTitle` is reset to null with `AccompanistWebViewClient.onPageStarted()` but `AccompanistWebChromeClient.onReceivedTitle()` is not called with `WebView.reload()` so pageTitle stay null.

**Steps to reproduce**

```kotlin
@Composable
fun AccompanistWebSample() {
    val state = rememberWebViewState(url = "https://google.github.io/accompanist/web/")
    val navigator = rememberWebViewNavigator()

    Column {
        TopAppBar(
            title = {
                Text(text = state.pageTitle ?: "")
            },
            actions = {
                IconButton(onClick = { navigator.reload() }) {
                    Icon(imageVector = Icons.Default.Refresh, contentDescription = "reload")
                }
            }
        )

        WebView(
            state = state,
            navigator = navigator,
            modifier = Modifier.fillMaxSize()
        )
    }
}
```

**Expected behavior** 

pageTitle should stay same string when reload.

**Comment by bentrengrove** [comment]
I haven't managed to get to this one yet sorry. If you do find a fix, I would happily accept a PR
