### ISSUE TITLE
[Pager] migrate off chrisbanes:snapper

### ISSUE THREAD

**Issue by yschimke** [google/accompanist#1419]
**Description**

Migrate off chrisbanes:snapper, since it's deprecated.

**Additional context**

https://github.com/chrisbanes/snapper

> Snapper is now deprecated, due to it's functionality being replaced by [SnapFlingBehavior](https://developer.android.com/reference/kotlin/androidx/compose/foundation/gestures/snapping/SnapFlingBehavior) which is available in Jetpack Compose 1.3.0.
> The SnapFlingBehavior API is very similar to Snapper, so migration should be very easy. I haven't provided an automatic migration path, as I feel that it's important to learn the new API by performing the migration yourself.

**Comment by andkulikov** [comment]
I will let Levi decide. He is currently working on a new Pager for compose-foundation and it will be public pretty soon I guess. Maybe we can skip this as the ultimate goal is to deprecate Pager from accompanist as well

**Comment by yschimke** [comment]
Makes sense.  Is that Compose 1.4 timeframe? Maybe worth a note in the docs if that's the plan.

https://google.github.io/accompanist/pager/
