### ISSUE TITLE
[Navigation Material] Composable content is Hidden Behind Bottom Sheet 

### ISSUE THREAD

**Issue by levinzonr** [google/accompanist#1420]
**Description**
Composable is hidden behind bottom sheet when using nested navigation and `dialog` as its start destination

**Steps to reproduce**
- Have nested navigation with dialog as a start destination
- Navigate from bottom sheet to this graph, and then to another composable within is this graph

In sample:
- Click Show Sheet 
- Click Open Dialog
- Click Open Feed
- Dialog is dismissed, but bottom sheet is still displayed

**Expected behavior** 
The last composable we've navigated to is visible

**Additional context**
Reproduced in forked sample
https://github.com/levinzonr/accompanist/commit/0c12e6e34ec32003235d075b6765e6b2af7523e3

**Comment by jossiwolf** [comment]
Thanks for the issue, I will check this out next week!
