### ISSUE TITLE
[Pager] Zoomable Content In Pager

### ISSUE THREAD

**Issue by wakaztahir** [google/accompanist#1422]
**Description**
Not a bug but mostly Horizontal pager is used to display images and I want them to be zoomable individually inside the horizontal pager which led me to ~research and I found this solution

https://stackoverflow.com/questions/71156016/how-to-use-detecttransformgestures-but-not-consuming-all-pointer-event

which is like a hack to make pager zoomable with each image in it. The problem is some solutions cut some of the image and some mess with the way pager scrolls and make it worse.

I would love it If you guys could provide a proper solution on how to use pager with zooming. To disable scrolling a state is being used and some are using screen width to prevent image from getting out of the bounds , I think these solutions could be improved , Could you please provide a solution for this.

**Comment by wakaztahir** [comment]
Not stale

**Comment by wakaztahir** [comment]
Alo Hamora

**Comment by bentrengrove** [comment]
Accompanist Pager has now been deprecated as we have upstreamed it to the main Compose library and so I am closing this request sorry. We won't be updating the documentation here but you can file a request for this at [goo.gle/compose-feedback](https://goo.gle/compose-feedback) if it's still needed when using the Compose Foundation Pager.
