### ISSUE TITLE
[Pager]

### ISSUE THREAD

**Issue by Daeng96** [google/accompanist#1423]
**how to make ```Scrollable Tab View``` in sync with ```Horizontal Pager``` in ```reverse``` mode?**

**Comment by andkulikov** [comment]
Yes, probably Modifier.pagerTabIndicatorOffset() should accept reverseLayout param and do inversions internally if it is set. Feel free to contribute that if you want

**Comment by Daeng96** [comment]
> Yes, probably Modifier.pagerTabIndicatorOffset() should accept reverseLayout param and do inversions internally if it is set. Feel free to contribute that if you want

I have done that but the tab offset is always faster than the Pager, the greater the value of PagerState#currentPage the greater the tab offset, as a result the selected tab is increasingly invisible when the page is scrolled (±10 pages and above)
