### ISSUE TITLE
[PagerState][LazyListState should be public]

### ISSUE THREAD

**Issue by AntoineMarchaud** [google/accompanist#1424]
## Describe the bug

Is it possible to make lazyListState public ?
I need this value, and currently i get it by dirty reflexion code.

The other solution is to copy-paste the entire code.

**Comment by bentrengrove** [comment]
Thanks for the issue. Can you please tell us why you need it? A concrete example of what you are trying to do would be helpful.

**Comment by AntoineMarchaud** [comment]
I need the firstVisibleItemIndex property.
In my case, I have to tweak the animation of the HorizontalViewPager, by applying a parallax effect on the current card sliding.
The only way i found if to deal with that property and make some maths.

Maybe a Modifier exists on HorizontalViewPager to reach that behavior ?
