### ISSUE TITLE
[Pager] issue with lazy layouts.

### ISSUE THREAD

**Issue by pejman-74** [google/accompanist#1430]
HorizontalPager + LazyHorizontalGrid doesn't work smoothly, is very laggy, and sometimes the swipe fails.

**Comment by hbb20** [comment]
were you able to solve this? This is going to force me to go back to Views 😢

**Comment by pejman-74** [comment]
Simple version of Grid(without lazy).

**Comment by andkulikov** [comment]
Thanks. We track this issue here: https://issuetracker.google.com/issues/252846775
