### ISSUE TITLE
[Swipe to refresh] The PullRefreshIndicator in Compose Material does not work with Compose Material 3

### ISSUE THREAD

**Issue by Omico** [google/accompanist#1446]
The surface will continue to display after a refresh.

I have created a simple project as a quick workaround by replacing all MD2 components with MD3, and it works perfectly.

Now I really hope that the official team will consider solving this problem.

Here is my simple project: https://github.com/Omico/androidx-compose-material3-pullrefresh

Also, I copied the entire sources instead of creating a new implementation under the original pull refresh library because the `PullRefreshState.refreshing` and `PullRefreshState.position` are internal.

**Comment by bentrengrove** [comment]
I believe the surface getting stuck was fixed in the last release of Compose Material.

If the issue continues, please file the bug at [goo.gle/compose-feedback](goo.gle/compose-feedback) as that is where bugs for that component are tracked. We cannot fix it from here.

**Comment by Omico** [comment]
@bentrengrove Thank you for telling me that. This issues move to https://issuetracker.google.com/issues/262183520
