### ISSUE TITLE
launchPermissionRequest() for ACCESS_NOTIFICATION_POLICY not working

### ISSUE THREAD

**Issue by dsb92** [google/accompanist#1447]
`   val permissionState = rememberPermissionState(
        permission = Manifest.permission.ACCESS_NOTIFICATION_POLICY
    )`
....
```
    SideEffect {
        if (uiState.toggleNotifications) {
            permissionState.launchPermissionRequest()
        }
    }
```

Does not prompt system dialog. It works with other permissions like CAMERA.

## Environment:
 - Android OS version: Android 12
 - Device: Emulator
 - Accompanist version: 0.25.1

**Comment by ianhanniballake** [comment]
[`ACCESS_NOTIFICATION_POLICY`](https://developer.android.com/reference/android/Manifest.permission#ACCESS_NOTIFICATION_POLICY) is not a dangerous permission you request using the runtime permissions APIs.

Normal permissions don't have to be requested at all.
