### ISSUE TITLE
[WebView] Does not report HTTP errors

### ISSUE THREAD

**Issue by danielesegato** [google/accompanist#1448]
**Description**
When loading a web page the `state.errorsForCurrentRequest` does not report HTTP errors with the page being loaded (ex. a 404 or a 403).

**Steps to reproduce**

```kotlin
@Composable
fun ReproduceError() {
  val state = rememberWebViewState("https://www.google.com/404") // or any url returning an HTTP error
  WebView(
    state = state,
    modifier = Modifier
        .fillMaxSize(),
  )
  println("${
                state.errorsForCurrentRequest
                    .joinToString(separator = "\n") { "[${it.error.errorCode}] ${it.error.description}" }
            }")
}
```

nothing will be print, no error despite the page having a 404

**Expected behavior** 
http errors of the main page should be reported somehow by the state

**Additional context**
It is relatively easy to "fix" by extending `AccompanistWebViewClient` with your own state for the error which is provided by the `onReceivedHttpError()` method.

but I think it should be part of the errors exposed by default by the library.

**Comment by danielesegato** [comment]
Was coming to ask if you had a chance to check this out, and I see you removed the stale label already! Thank you :-)

**Comment by bentrengrove** [comment]
Yes sorry! I will implement this, I just haven't had a chance yet

**Comment by danielesegato** [comment]
I guess there's no plan to do this?
