### ISSUE TITLE
[Navigation Animation]  Parts of Composable are not reachable when keyboard is open while animation running

### ISSUE THREAD

**Issue by philip-haspa** [google/accompanist#1452]
**Description**
When using the AnimatedNav Host to create a transition between two composables there is a bug when the second screen has scrollable content and is requesting the focus before the transition animation is done. When the keyboard enters before the animation finished, the screen scrolled automaticly and its not possible to reach the top of the screen.

**Steps to reproduce**
1 Create two composable screens and add them into the AnimatedNavHost.
2. Add a Lazy Column with several elements and a Textfield to the second screen. 
3. Request the focus of the Textfield.
4. Create a enter Transition(e.g. SlideIntoContainer with Up and a tween of 2000) for the second screen.
5. link the two screens together to start the transition

**Expected behavior** 
The second screen should stay on the top no matter if the keyboard is visible or not.

**Additional context**
I created a simple Example App that shows the mentioned Bug. It can be found here: 
https://github.com/haspa-next/ComposeNavigationAnimationBug

**Comment by jbw0033** [comment]
This seems related to how animations work vs anything that navigation is doing. Adding @doris4lt to see if she has more context on the animation/focus relationship.

**Comment by doris4lt** [comment]
@philip-haspa Thanks for the repro. Could you share a video of what you see vs. what you expect? See the video below for what I get when trying to repro. It seems the 2nd screen had no problem reaching the top of the screen. I might be missing something.

https://user-images.githubusercontent.com/12000161/211676165-167ccf58-bf3a-4cc4-8824-23bfab099c35.mp4

**Comment by philip-haspa** [comment]
@doris4lt 
Sure here it is:
[device-2023-01-11-112528.webm](https://user-images.githubusercontent.com/38906694/211782352-dc392d69-fbed-4e68-b4e4-5697eb3d4948.webm)

As you can see, when the overlay appears its automatic scrolled and its not possible to rearch the top (field 0) before closing the keyboard. I have to admit that this is not happening everytime. Sometimes the first time is fine and the next clicks leading to the bug. is also not always the same size. I tried on a real google Pixel 3 Device with with android 12
and with an Android 3 Emulator Api Version 29.
