### ISSUE TITLE
[Pager] The PagerState.kt->lazyListState should be public

### ISSUE THREAD

**Issue by qazxcs113** [google/accompanist#1454]
**Description**
I see the code inside.
PagerState.kt . The member lazyListState should be public .

**Expected behavior** 
I wish pager can exist more page in a screen.
May be I need the items width and height to calculate.

It like use adapter.setOffscreenPageLimit() and setPageTransformer.
I have the view object. 

**Additional context**
Like this:
![20221221152810](https://user-images.githubusercontent.com/49807330/208845909-457939f4-086b-4c56-bc9c-e8d6953f5d2e.png)

**Comment by andkulikov** [comment]
We are not going to add analogue of setOffscreenPageLimit in Accompanist Pager, however we just released a new Pager in compose-foundation and it has such functionality
