### ISSUE TITLE
Make HorizontalPager central item on top of other elements

### ISSUE THREAD

**Issue by rafaelasobralguerra** [google/accompanist#1457]
## Describe the bug
Central item on horizontal pager his behind the right items and it's impossible to applying a z-index to the modifier because Box container modifier it's not exposed (`| Box[Page] | Box[Page] | Box[Page]`).

Applying `.zIndex(if (page == currentPage) 1f else 0f)` to the Page doesn't work 

## To Reproduce
![image](https://user-images.githubusercontent.com/80817553/209177624-1363796b-adfe-41f5-8300-03c3227063c0.png)

```
@Suppress("CorrectDpValuesDetector")
@Composable
private fun SquaresCodesPager(state: SquaresGroupState, onSelectedListener: (Int) -> Unit, onClickedListener: (Int) -> Unit) {
    val pagerState = rememberPagerState(initialPage = 0)
    LaunchedEffect(pagerState) {
        snapshotFlow { pagerState.currentPage }.collect { page ->
            onSelectedListener(page)
        }
    }
    HorizontalPager(
        itemSpacing = -Grid.DP_40,
        contentPadding = PaddingValues(horizontal = (LocalConfiguration.current.screenWidthDp.dp - QR_SIZE) / 2),
        count = state.items.size,
        state = pagerState
    ) { page ->
        Square(pagerState.currentPage, page, state.items[page].square, onClickedListener)
    }
}

@Composable
private fun PagerScope.Square(currentPage: Int, page: Int, bitmap: Bitmap, onClickListener: (Int) -> Unit) {
    Image(
        modifier = Modifier
            .graphicsLayer(animation(page))
            .background(Background.BgSecondary)
            .size(SQUARE_SIZE),
        bitmap = ...
        contentDescription = ...
    )
}
```
## Expected behavior
Blue square should be on top of other items once it's the viewpager item selected (square focused)

## Screenshots?
Blue square = items[0] is the item selected on the viewpager
![image](https://user-images.githubusercontent.com/80817553/209177788-d526e727-32ce-4d2a-aab0-a7054a7e9881.png)

## Environment:
 - Accompanist version: v0.27.1

**Comment by bentrengrove** [comment]
Accompanist Pager has now been deprecated as we have upstreamed it to the main Compose library and so I am closing this bug.

Please retest your issue using Compose Foundation Pager in the March release. You can see our [migration guide](https://google.github.io/accompanist/pager/) for help and if this is still an issue, please file a bug at [goo.gle/compose-feedback](https://goo.gle/compose-feedback).
