### ISSUE TITLE
Text of Text Component That Relies on Some State Does Not Reflect the Most Recent Value of Said State

### ISSUE THREAD

**Issue by nick-e** [google/accompanist#1458]
## Describe the bug
When the text of a text material component relies on some state and the component is not clickable then the text will not reflect the most recent value of that state. This can be resolved by removing accompanist-systemuicontroller as a dependency.

## To Reproduce
1. Create a new project in Android Studio using the `Empty Compose Activity` template and setting the API to 33.
3. Define `MainActivity`:
```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                val x = remember { mutableStateOf(0) }
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    Column {
                        // This text component will NOT render the most recent value of `x` when it should.
                        // Instead, it always renders the initial value of `x` which is "0".
                        Text(text = x.value.toString())
                        // This text component will render the most recent value of `x`.
                        Text(modifier = Modifier.clickable(onClick = {  x.value += 1 }), text = x.value.toString())
                    }
                }
            }
        }
    }
}
```
4. Add accompanist-systemuicontroller as a dependency in `build.gradle`:
```groovy
// If this dependency is removed then the bug goes away.
implementation "com.google.accompanist:accompanist-systemuicontroller:0.28.0"
```

## Screenshots
Pressing the text once when accompanist is a dependency:

![image](https://user-images.githubusercontent.com/20048491/209579970-6cb53476-0482-4b04-86fd-53395843886d.png)

Pressing the text once when accompanist is a not dependency:

![image](https://user-images.githubusercontent.com/20048491/209580023-ecf4bb51-860a-482b-89da-8ed6e6ce50f1.png)

## Expected behavior
If the text of a text material component depends on some state then the text should reflect the most recent value of that state.

## Environment:
 - Android OS version: API 33
 - Device:  Google Pixel 7 & emulated Google Pixel 6
 - Accompanist version: 0.28

**Comment by alexvanyo** [comment]
Would it be possible to upload a sample project to reproduce?

Adding a dependency like accompanist shouldn't have any runtime effect changes here, and I'm unable to reproduce.
