### ISSUE TITLE
[WebView] WebView contents inside of the bottom sheet of the ModalBottomSheetLayout is not scrollable

### ISSUE THREAD

**Issue by Pardip235** [google/accompanist#1462]
**Description**
webView contents inside of the bottom sheet of the ModalBottomSheetLayout is not scrollable
**Steps to reproduce**
- Implement Accompanist WebView in accompanist `ModalBottomSheetLayout`
- Check the web page, web page contents is not scrolling by default. 
- Adding `Modifier.verticalScroll(rememberScrollState())` not working in all web pages. 
(Note: It works fine in normal compose view without adding `verticalScroll`). 

**Expected behavior** 

- All the web page contents should be visible and also can scrollable without adding any code, if web view `isVerticalScrollBarEnabled` is enabled.  

**Additional context**
I found same type of question is raised [here](https://github.com/google/accompanist/issues/1260#issuecomment-1334016763). Although ticket is closed.

**Comment by JiangHongTiao** [comment]
I also experience the same issue. Does anyone know about any workaround?

**Comment by macxtor** [comment]
I'm facing the same issue. I had a workaround by doing but then once you move forward in web views the scroll state remains the same. eg if you scroll down to the middle of page, next webview page will be in the middle of the page.:

```kotlin 
Column(
    modifier = modifier
        .fillMaxSize()
        .verticalScroll(rememberScrollState())
) {
    AndroidView(factory = {
        WebView(it).apply {
            webViewClient = WebViewClient()
            layoutParams = ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT
            )
            loadUrl(url)
        }
    }, update = {
        it.loadUrl(url)
    }
    )
}

**Comment by wavecos** [comment]
facing the same issue.

**Comment by Yiran001** [comment]
I am facing similar issues. But some pages are not even visible when adding scrolling to the WebView. Since the webViewState has isLoaded = true and pageTitle contains a string, I think it's a visibility problem.

**Comment by Mwhite69** [comment]
What do i do

**Comment by lukaszreszetow** [comment]
Facing the same issue

**Comment by OleksandrGrument** [comment]
This issue belongs to accompanist ModalBottomSheetLayout not to WebView, I have tested it with regular AndroidView interop with regular WebView and same issue

**Comment by Yiran001** [comment]
Just as an info. I saw today that Accompanist WebView will be deprecated see: https://google.github.io/accompanist/web/

**Comment by hoantd-2455** [comment]
I am facing similar issues
