### ISSUE TITLE
[Navigation Animation] There's no way to provide no transition

### ISSUE THREAD

**Issue by MarcelReiter** [google/accompanist#1464]
**Description**
I'm trying to build a list/detail screen.
- The list screen should just "stay as it is" - no animation.
- The detail screen should slide over the list screen.

I have attached two videos. 
- one depicting my real layout: [device-2023-01-05-110645.webm](https://user-images.githubusercontent.com/60610643/210764510-f5d670b8-9759-4b24-a94a-aeef96e013f4.webm)
- one depicting the minimal reproducible sample: [device-2023-01-05-113156.webm](https://user-images.githubusercontent.com/60610643/210764559-18c2d834-44c9-434b-ad41-346548b72cce.webm)

In both cases you'll notice:
- When navigating from list to detail the list fades out. (hard to see)
- When navigating from detail to list the list fades in. (easier to see)

I now want to avoid this fade-animation:
- I therefore set `exitTransition = null` & `popEnterTransition = null`.
- This does not skip the animation, but rather seems to play `AnimatedNavHosts` default animation?
- However, i can't provide `null` to `AnimatedNavHosts` default animations.

**Steps to reproduce**

My minimal reproducible sample looks like :
```
AnimatedNavHost(
    navController = rememberAnimatedNavController(),
    startDestination = infoNavGraph,
    modifier = Modifier.fillMaxSize(),
    builder = {
        infoNavGraph(navController)
    }
)

fun NavGraphBuilder.infoNavGraph(navController: NavController) {
    navigation(
        startDestination = infoMainScreen,
        route = infoNavGraph
    ) {

        composable(infoMainScreen) {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .background(Color.Gray)
            ) {
                Text(
                    text = "List Screen. Navigate to Detail via click here ",
                    modifier = Modifier.clickable { navController.navigate(infoDetailScreen) }
                )
            }
        }

        horizontalSlide(infoDetailScreen) {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .background(Color.LightGray)
                    .clickable { navController.popBackStack() }
            ) {
                Text(
                    text = "Detail. Navigate back to List via click here",
                    modifier = Modifier.clickable { navController.popBackStack() }
                )
            }
        }
    }
}

fun NavGraphBuilder.horizontalSlide(
    route: String,
    arguments: List<NamedNavArgument> = emptyList(),
    deepLinks: List<NavDeepLink> = emptyList(),
    content: @Composable AnimatedVisibilityScope.(NavBackStackEntry) -> Unit,
) = composable(
    route = route,
    arguments = arguments,
    deepLinks = deepLinks,
    enterTransition = { slideIntoContainer(towards = Left, animationSpec = tween(ANIMATION_SLIDE_DURATION)) },
    exitTransition = null, // <- note the null here
    popExitTransition = { slideOutOfContainer(towards = Right, animationSpec = tween(ANIMATION_SLIDE_DURATION)) },
    popEnterTransition = null, // <- note the null here
    content = content
)

```

**Suggested solution**

I don't think "provide a null to a `composable`s animation to show no animations" is a good idea, since "provide null to a composables animation to show default animation" is a nice usecase.
I'd therefore suggest a "noop" animation for this case, but i'm not sure how this would work

**Comment by Feinate** [comment]
Hi, you can solve this by putting `{ fadeIn(initialAlpha = 1f) }` on `enterTransition`, and `{ fadeOut(targetAlpha = 1f) }` on `exitTransition.`

Here is an exemple -> `composable(
        route = Screen.Home.route,
        enterTransition = { fadeIn(initialAlpha = 1f) },
        exitTransition = { fadeOut(targetAlpha = 1f) }
    ) {
        Home(paddingValues = paddingValues)
    }`

Glad to help !

**Comment by ianhanniballake** [comment]
As per #807, use `EnterTransition.None` and `ExitTransition.None`.
