### ISSUE TITLE
[Navigation Animation] Back button press does not close on a nested NavHost

### ISSUE THREAD

**Issue by mkano9** [google/accompanist#1468]
**Description**
Video: https://user-images.githubusercontent.com/3074663/211236231-b46c7889-ac66-4e7a-a8db-de6354fc5f1b.mov

Given a setup of:
```
NavHost {
    Nested NavGraph {
        composable("one") {
             NavHost {
                  composable("nested_1") {...}
                  composable("nested_2") {...}
             }
        }
    }
    Nested NavGraph {
        composable("two") {
            ... 
        }
    }
}
```
Navigating in the following sequence:
`"one"(Root navController),  "nested_1" -> "nested_2" ->  "two"(Root navController)`

And then pressing the back button to pop each screen, the first screen pops after pressing the back button twice.

Debugging into the code, what seems to happen is the following:
In the video, navigate all the way to the screen "two" and press the back button.

1: `addCancellableCallback` on `OnBackPressedDispatcher` gets called via `onStateChanged`. This adds the original instance of the nested navController's `OnBackPressedCallback`.
2: `AnimatedNavHost` on the composable "one" registers a new instance of a restored NavController. This registers an extra `OnBackPressedCallback`. 
3: When I back out of the backstack(`backQueue`), instead of exiting the screen, it makes me pop through another backstack. This causes it to require the extra back button press in the video.

What is the expected behavior here?

Version 0.28.0
Tried the Sun Jan 08 23:22:41 UTC 2023 0.28.1-SNAPSHOT
It works fine on `"androidx.navigation:navigation-compose:2.5.3"`, so I am reporting this bug here for this library.

**Steps to reproduce**
Code: https://github.com/mkano9/compose-nav-backpress-bug/blob/master/app/src/main/java/com/example/onbackpressedbug/MainActivity.kt

See the attached video

**Expected behavior** 
Each back button press should pop each screen

**Comment by saharvx9** [comment]
happened to me too,
there where a bug that realy simalar to this in the regular navigation :

**Comment by mkano9** [comment]
@jbw0033 Any thoughts on this one?

**Comment by mkano9** [comment]
This is not stale. Still happens.

**Comment by claraf3** [comment]
Hi, the issue has been fixed and will be available in the next accompanist release.

Alternatively, you can depend on the latest androidx `navigation-compose 2.7.0-alpha01` which already implements animations support in accompanist navigation.
