### ISSUE TITLE
[Navigation Material] (0.29.0-alpha) With BottomSheetNavigator.navigatorSheetState.offset removed, there doesn't seem to be a way to access sheet offset/position

### ISSUE THREAD

**Issue by MarcLFJ** [google/accompanist#1472]
**Description**
We were using `bottomSheetNavigator.navigatorSheetState.offset.value` to reposition a "sticky" content view inside the content.
Is this a wrong approach or is there a way to derive this with the new update? :)

**Steps to reproduce**
`bottomSheetNavigator.navigatorSheetState.offset` annotated as error now.

**Expected behavior** 
Handle to access the BottomSheets current offset/drag position on screen.

**Additional context**
None

**Comment by miduch** [comment]
also crash happens in 0.29.0-alpha when bottom sheet is being closed 

```
java.lang.NoSuchMethodError: No virtual method snapTo(Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object; in class Landroidx/compose/material/ModalBottomSheetState; or its super classes (declaration of 'androidx.compose.material.ModalBottomSheetState' appears in /data/app/~~Zr5_rXdHi-owlzeQxukd5w==/com.example.myapp.debug-uTDaE_no6JsJGsnvmnYZBg==/base.apk)
                 	at com.google.accompanist.navigation.material.SheetContentHostKt.internalHide(SheetContentHost.kt:182)
                 	at com.google.accompanist.navigation.material.SheetContentHostKt.access$internalHide(SheetContentHost.kt:1)
                 	at com.google.accompanist.navigation.material.SheetContentHostKt$SheetContentHost$2$2$1.invokeSuspend(SheetContentHost.kt:142)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7872)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by jossiwolf** [comment]
@MarcLFJ Do you have a code example of what you were doing before, and possibly a mockup of the use case?

**Comment by MarcLFJ** [comment]
@jossiwolf Sorry about the delayed reply, our intention is to have a button be sticky to the bottom of the window, so if the sheet starts half expanded, the button is still visible and when the user drags the sheet to top, the footer sticks to the bottom of the window. 
Here is a barebone example of what we were doing in `0.28.0`, let me know if it's too barebone. 😅 
```
@OptIn(ExperimentalMaterialNavigationApi::class)
@Composable
fun SheetWithSticky(
    bottomSheetNavigator: BottomSheetNavigator,
    stickyFooter: (@Composable () -> Unit)? = null,
    content: @Composable () -> Unit
) {
    val bottomSheetOffset = bottomSheetNavigator.navigatorSheetState.offset.value
    var stickyContainerHeight by remember { mutableStateOf(0) }

    Box(
        Modifier.heightIn(max = LocalConfiguration.current.screenHeightDp.dp)
    ) {
        Column(
            // Ensure content is padded above sticky footer height
            modifier = Modifier.padding(
                bottom = with(LocalDensity.current) { stickyContainerHeight.toDp() }
            )
        ) {
            /*Generic header view and other views here ...*/
            content()
        }

        stickyFooter?.let { footer ->
            Box(
                modifier = Modifier
                    .onGloballyPositioned { stickyContainerHeight = it.size.height }
                    .offset { IntOffset(0, -bottomSheetOffset.toInt()) }
                    .align(Alignment.BottomCenter)
            ) {
                footer()
            }
        }
    }
}
```

Edited screenshot from design:
![Screenshot 2023-02-01 at 15 05 10](https://user-images.githubusercontent.com/42405065/216066205-ae5f3018-2df3-4186-80f7-240e6d828c53.png)

Using the following accompanist dependencies:
`com.google.accompanist:accompanist-navigation-material`
and Material3: `androidx.compose.material3:material3:1.1.0-alpha03`

**Comment by MarcLFJ** [comment]
@jossiwolf Any update on this? :)
Is it not an intended usecase or is there a better way? 
Mainly the problem trying to be solved is listening to the actual offset position of the bottomsheet and react to it. 👍

**Comment by Nek-12** [comment]
Same issue here, but a different usecase. Want to animate certain elements of the laout based on the sheet offset to create a smooth animation

**Comment by AhmedNader7** [comment]
Same issue here

**Comment by fedor7peaks** [comment]
This looks like a really important feature, should provide some way to migrate, not the best way to downgrade Compose version.

**Comment by Nek-12** [comment]
Not stale

**Comment by fedor7peaks** [comment]
While we're all waiting for Google for a solution, I came with a super ugly hack to make offset work in newer Compose version, since I cannot wait for this as all dependencies are going to get outdated.
```
@Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")
@OptIn(ExperimentalMaterialNavigationApi::class, ExperimentalMaterialApi::class)
fun BottomSheetNavigatorSheetState.getOffset() = sheetState.requireOffset()
```
Hope this helps people in this thread.

**Comment by MarcLFJ** [comment]
Not stale

**Comment by Nek-12** [comment]
.

**Comment by Nek-12** [comment]
.

**Comment by Nek-12** [comment]
How is this closed if I left a comment

**Comment by Nek-12** [comment]
@jossiwolf Please reopen

**Comment by MarcLFJ** [comment]
@ianhanniballake Could you reopen, since this was referred in #1582 as being the issue to track progress on. :)

**Comment by LouisCAD** [comment]
Hello, has what's the state of this issue, if some work pr research has been done on it?

**Comment by rcht007** [comment]
@Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")  
var offset = Float.POSITIVE_INFINITY
                            try {
                               offset = sheetState.requireOffset()
                            } catch (e: IllegalStateException) {
                                log.d("MODAL BOTTOM SHEET", "${e.printStackTrace()}")
                            }
// offset is 1568.9
val outside = it.y < offset
this works for me

**Comment by ianhanniballake** [comment]
With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: `androidx.compose.material:material-navigation`, which fully replaces Accompanist Navigation Material.

As such, we are closing all issues here on Accompanist and will be fully deprecating Accompanist Navigation Material in an upcoming release.

This issue was not fixed as part of the migration, so if you're still interested in this, please [file an issue](https://issuetracker.google.com/issues/new?component=742043) and the Material team will take a look.

Include the link here so that others can star it!
