### ISSUE TITLE
Status bar color is not changing

### ISSUE THREAD

**Issue by AbdullahJaved-dev** [google/accompanist#1484]
I am using SystemUiController library to update the system bars color but it working only for navigation bar, not for status bar.

Using this code to update color to black
```
val systemUiController = rememberSystemUiController()
    val useDarkIcons = !isSystemInDarkTheme()

    DisposableEffect(systemUiController, useDarkIcons) {
        systemUiController.setSystemBarsColor(
            color = Color.Black,
            darkIcons = useDarkIcons
        )
        onDispose {}
    }
```

Status bar color should be black. 

Device:
Samsung S10+
Android version 12

![Screenshot_20230118_163254_1_30](https://user-images.githubusercontent.com/66158133/213161854-a47e4873-457f-4a21-a278-94a8821805e2.png)

**Comment by AbdullahJaved-dev** [comment]
Commented default status bar code from Theme.kt. and it's working now.

**Comment by AbdullahJaved-dev** [comment]
Yes. I had commented the Android Studio template status bar color code in `Theme.kt` file. And then SystemUIController was working fine.

**Comment by mslalith** [comment]
Still seeing this. Also the icons are fading away

> Commented default status bar code from Theme.kt. and it's working now.

What do you mean by this?

here's my [Theme.kt](https://github.com/mslalith/focus_launcher/blob/housekeeping/app/src/main/kotlin/dev/mslalith/focuslauncher/ui/theme/Theme.kt)

[status_bar.webm](https://user-images.githubusercontent.com/15076234/234452083-8315758f-0e85-4b38-910c-9d8c9c4f93dc.webm)

**Comment by mslalith** [comment]
I believe it's how it is in Android S. Seems to be fine in Android R. I'll have to check with some other versions
