### ISSUE TITLE
[Permissions] SYSTEM_ALERT_WINDOW permission launcher not working

### ISSUE THREAD

**Issue by Chandu4221** [google/accompanist#1486]
**Description**
I am trying to request `SYSTEM_ALERT_WINDOW` permission using `launchPermissionRequest()` but the `permissionState.status` is always `Denied(shouldShowRationale=false)`. 

I have added the ` <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />` in **AndroidManifest.xml**

**Comment by alexvanyo** [comment]
Accompanist uses the underlying permissions APIs, so the same platform rules apply for which permissions you can request in what manner.

In particular, `android.permissions.SYSTEM_ALERT_WINDOW` has some different behavior compared to other permission, as mentioned in [its docs](https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW) and for [some updates in Android 11](https://developer.android.com/about/versions/11/privacy/permissions#system-alert) as well.
