### ISSUE TITLE
TextStyles are not properly matching with xml styles

### ISSUE THREAD

**Issue by mrzbn** [google/accompanist#1490]
**Description**

**textAppearanceHeadline1** style attribute and other text appearances are not fully matching with Jetpack Compose **h1** TextStyle.

my textAppearanceHeadline1 style in xml:
```
<style name="TextNormal.Black">
        <item name="fontFamily">@font/font_medium</item>
        <item name="android:textColor">@color/text_color_black</item>
        <item name="android:textSize">@dimen/text_size</item>
    </style>
```

generated h1 TextStyle:

`TextStyle(color=Color(0.0, 0.0, 0.0, 0.0, None), brush=null, alpha=NaN, fontSize=12.0.sp, fontWeight=FontWeight(weight=700), fontStyle=Italic, fontSynthesis=null, fontFamily=FontListFontFamily(fonts=[ResourceFont(resId=2131296261, weight=FontWeight(weight=400), style=Normal, loadingStrategy=Blocking)]))`

I don't know where **fontStyle=Italic** and **fontWeight=FontWeight(weight=700)** values are read from, so I can change them.

**Expected behavior** 

fontStyle and fontWeight values should be read from xml values.

**Additional context**

I also tried changing following attributes in xml, but nothing changed:
fontWeight, fontStyle, android:fontWeight, android:fontStyle.

**Comment by bentrengrove** [comment]
Thanks for the report. Can you please attach a sample project? If that is too much we would at least need to know the ThemeAdapter you are using and also the base XML theme.

**Comment by mrzbn** [comment]
I am using `Theme.MaterialComponents.DayNight.NoActionBar`
as base theme and `com.google.android.material:compose-theme-adapter:1.2.0` as theme adapter.

**Comment by mrzbn** [comment]
I am using `com.google.accompanist:accompanist-themeadapter-material` and `Theme.MaterialComponents.DayNight.NoActionBar`.
