### ISSUE TITLE
New lib to support Showcases and tutorials

### ISSUE THREAD

**Issue by MattyOliveira** [google/accompanist#1492]
## Additional context
A suggestion for the accompanist lib is to implement a showcase module, to help with the highlights/tutorials. Focusing on items and components.

This lib can facilitate tutorial processes and highlights in several projects.

**Comment by bentrengrove** [comment]
Thanks for the suggestion. I don't think we'll be able to develop this in accompanist due to time constraints but I agree it sounds like a good idea.
