### ISSUE TITLE
[Navigation Animation] Going back using slideOutHorizontally triggers the Drawer to be shown for a split second.

### ISSUE THREAD

**Issue by viktorilievski** [google/accompanist#1510]
**Description**

I just found out by using the slideOutHorizontally (screen appears from left to right), it actually triggers the Drawer to be shown for a split second. Here's the code I used for the screen:
```
popExitTransition = {
      slideOutHorizontally(targetOffsetX = { it })
    }
```

I can upload a video also showing this bug. Here it is, you can see it as soon as I press the back button from the OS. Also using Android 11, stock Android. Cause file is too big, here's a link from Google Drive: https://drive.google.com/file/d/15v_cJ-ywIHkYL6M2Os7O5U4Hrrn78tfD/view

**Steps to reproduce**

Use slideOutHorizontally or slideOutOfContainer with direction Right and have a Drawer Implemented in your app.

**Expected behavior** 

Drawer should not be shown.

**Additional context**
None.

**Comment by viktorilievski** [comment]
I just tested it out using Logs whether the Drawer really opens or no. It does not say anything until I intentionally click it. Does this mean that it's the library issue? Can someone try to reproduce this bug?

**Comment by ianhanniballake** [comment]
Dup of #1209
