### ISSUE TITLE
[Pager] Horizontal Pager compose page twice when has exact 2 pages

### ISSUE THREAD

**Issue by debbiefu** [google/accompanist#1511]
Reproduce: 
1. run Horizontal Pager: Looping with indicators
2. com/google/accompanist/sample/pager/HorizontalPagerLoopingIndicatorSample.kt
`val pageCount = 2`
```
     HorizontalPager(
                // Set the raw page count to a really large number
                count = loopingCount,
                state = pagerState,
                // Add 32.dp horizontal padding to 'center' the pages
                contentPadding = PaddingValues(horizontal = 32.dp),
                // Add some horizontal spacing between items
                itemSpacing = 4.dp,
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth()
            ) { index ->
                // We calculate the page from the given index
                val page = pageMapper(index)
                Log.d("pager", "compose index: $index for page $page at ${System.currentTimeMillis()} ")
                PagerSampleItem(
                    page = page,
                    modifier = Modifier
                        .fillMaxWidth()
                        .aspectRatio(1f)
                )
            }
```

4. The log shows compose each page twice:
![image](https://user-images.githubusercontent.com/4798528/218077102-49597c28-025a-4412-a71b-45abe60ff0cd.png)

Note: It only happens when pager has exact 2 pages

**Comment by bentrengrove** [comment]
Accompanist Pager has now been deprecated as we have upstreamed it to the main Compose library and so I am closing this bug. 

Please retest your issue using Compose Foundation Pager in the March release. You can see our [migration guide](https://google.github.io/accompanist/pager/) for help and if this is still an issue, please file a bug at [goo.gle/compose-feedback](https://goo.gle/compose-feedback)
