### ISSUE TITLE
[Navigation Material] Disable dismissing a bottom sheet route

### ISSUE THREAD

**Issue by mkano9** [google/accompanist#1512]
**Description**
Is there a way to make a certain bottom sheet route not dismissible when tapping on the area outside the sheet?

**Comment by ReenaYouCan** [comment]
I'm also looking out for this kind of implementation.

**Comment by Mukhammaddin6567** [comment]
I'm also looking out

**Comment by mkano3** [comment]
Hi @jossiwolf, does this seem like something you guys can help with?

**Comment by jossiwolf** [comment]
This is a duplicate of #730, please follow along. Unfortunately, we are working on other high-priority items at the moment and can not provide an ETA.
