### ISSUE TITLE
[WebView] Navigating back after a redirect with JS enabled doesn't work and simply reloads the redirect

### ISSUE THREAD

**Issue by tfcporciuncula** [google/accompanist#1516]
**Description**
When JS is enabled and we load a redirect URL, it becomes impossible to navigate back since tapping back simply reloads the redirect URL. The behavior is different in a regular webview and navigating back after loading a redirect URL works.

**Steps to reproduce**
- Clone https://github.com/tfcporciuncula/accompanist-webview-issue, which has a webview that loads a redirect URL
- Run the app and try to navigate back, observe you can't back out of the webview
- Comment out [Accompanist's webview](https://github.com/tfcporciuncula/accompanist-webview-issue/blob/bd9b9ce6ba6badd0d28aa8e0438da5b39a4097d9/app/src/main/java/com/fredporciuncula/accompanist/webviewissue/MainActivity.kt#L31-L36) and uncomment [the regular webview](https://github.com/tfcporciuncula/accompanist-webview-issue/blob/bd9b9ce6ba6badd0d28aa8e0438da5b39a4097d9/app/src/main/java/com/fredporciuncula/accompanist/webviewissue/MainActivity.kt#L39-L51), run the app again, and observe navigating back works

**Expected behavior** 
Accompanist's webview behaves like a regular webview, where navigating back after a redirect works instead of reloading the redirect.

**Additional context**
N/A

**Comment by tfcporciuncula** [comment]
Right after I opened this I saw https://github.com/google/accompanist/pull/1398 😅 

Tested on the latest version and it's all fine there. I apologize for not checking before opening the issue 🦆

**Comment by bentrengrove** [comment]
I'm glad to hear it worked!
