### ISSUE TITLE
[WebView] make WebViewState open class? 

### ISSUE THREAD

**Issue by miduch** [google/accompanist#1520]
**Description**
Is it possible to make WebViewState an open class? From my custom WebChromeClient (subclass of  AccompanistWebChromeClient) i want to be able to update state with some extra data e.g. alertMessage/ customView e.t.c. 

**Steps to reproduce**

**Expected behavior** 

**Additional context**

**Comment by bentrengrove** [comment]
Where would you then use your custom state class? What would this allow that isn't possible now?

**Comment by miduch** [comment]
```
@Stable
class MyWebViewState(webContent: WebContent) : com.google.accompanist.web.WebViewState(webContent) {
    var alertMessage: String? by mutableStateOf(null)
        internal set

    var chooseFilePathCallback: ValueCallback<Array<Uri>>? by mutableStateOf(null)
        internal set

}

class MyWebChromeClient : AccompanistWebChromeClient() {
    override fun onJsAlert(view: WebView?, url: String?, message: String?, result: JsResult?): Boolean {
        (state as? MyWebViewState)?.alertMessage = message
        result?.confirm()
        return true
    }

    override fun onShowFileChooser(
        webView: WebView?,
        filePathCallback: ValueCallback<Array<Uri>>?,
        fileChooserParams: FileChooserParams?
    ): Boolean {
        (state as? InkWebViewState)?.let {
            it.chooseFilePathCallback?.onReceiveValue(null)
            it.chooseFilePathCallback = filePathCallback
        }
        return true
    }

    // onShowCustomView, onHideCustomView e.t.c. 
}
```

I can pass MyWebViewState/MyWebChromeClient to WebView composable and e.g. show native alert, use photoPicker to select file e.t.c using state only. Otherwise i would need to use callbacks on MyWebChromeClient to do the same?

**Comment by bentrengrove** [comment]
I might be missing something but can't you just do

```
class MyWebChromeClient(val otherState: CustomState): AccompanistWebChromeClient() {
   ...
}
```

**Comment by miduch** [comment]
> I might be missing something but can't you just do
> 
> ```
> class MyWebChromeClient(val otherState: CustomState): AccompanistWebChromeClient() {
>    ...
> }
> ```

so your proposal is to use a different state for "extra stuff" and WebViewState for "normal stuff"?

**Comment by bentrengrove** [comment]
Yes. We try to avoid opening classes if possible. I will close this one for now but if you do find something you aren't able to achieve, please let me know.
