### ISSUE TITLE
[Navigation Animation] With compose 1.4.0-beta02 keyboard has extra padding that overlaps the content

### ISSUE THREAD

**Issue by polivmi1** [google/accompanist#1531]
**Description**
- Jetpack Compose version: 1.4.0-beta02 or material3 1.1.0-alpha07 (latest working is 1.1.0-alpha06 and 1.4.0-beta01)
- Jetpack Compose component used: OutlinedTextField
- Android Studio Build: EE 2022.1.1 Patch 1
- Kotlin version: 1.8.10
- Devices/Android versions reproduced on: emulator, any
- Keyboard (i.e. Gboard, Samsung, etc): default

With the new Compose release, there is a bug when contentAlignment = Alignment.TopCenter is added to the AnimatedNavHost.
It will cause after 1 screen transition there to be space above the keyboard. Removing it or downgrading compose would fix the problem.

Here is a sample project to reproduce:
- set screen type to native: true = use only native navigation with accompanist
- click on "two" to transition to next screen
- click into the OutlinedTextField
https://github.com/polivmi1/Bug270656245

Here is a screenshot https://github.com/polivmi1/Bug270656245/blob/master/app/src/Screenshot%202023-03-02%20at%2021.52.10.png (happens both for the library and accompanist version as the library only wraps the accompanist)

Here are the findings where I thought other library is a problem:

https://github.com/raamcosta/compose-destinations/issues/375

**Comment by alexvanyo** [comment]
The main `insets` library in accompanist is deprecated, as it has been superceded by support in `androidx` directly, so if there's an issue with the underlying insets behavior please report an issue there.

Are you calling both `WindowCompat.setDecorFitsSystemWindows(window, false)` and using `windowSoftInputMode` of `adjustResize`?

**Comment by polivmi1** [comment]
@alexvanyo this is not using the deprecated inset. It might be confusing because of the title.
This is just a specific bug on the keyboard that is related to insets.
There is no need to call anything insets related in this case as it does work correctly in previous compose release or without the contentAlignment = Alignment.TopCenter set on the AnimatedNavHost. It seems that accompanist animation internally uses something to set some animation inset that later causes this weird behavior that only happens after at least one screen transition with contentAlignment = Alignment.TopCenter happens.

Please see the sample project which reproduces it.

**Comment by alexvanyo** [comment]
Thanks for adding information, reopening and assigning over to navigation.

**Comment by jbw0033** [comment]
The only thing that AnimatedNavHost does is pass the `contentAlignment` directly to the `AnimatedContent`, which is no longer experimental in Compose 1.5, please file a bug against the Compose Animation library in androidx.
