### ISSUE TITLE
[System UI Controller] Set system bar colors not working inside compose dialog

### ISSUE THREAD

**Issue by joakimtall** [google/accompanist#1535]
Code like the following works well outside of a dialog, but when showing a dialog it does nothing, even if run inside the dialog composable (to get the correct window ref)

```
val systemUiController = rememberSystemUiController()
SideEffect {
    systemUiController.setSystemBarsColor(Color.Green)
}
```

**Steps to reproduce**

Just show a compose `Dialog` and use system ui controller to change system bar colors

Here is a complete repro project:
https://github.com/joakimtall/repro-dialog-bugs/tree/set-systembar-colors-does-nothing-in-compose-dialog

Repro project not showing dialog (bar color change works)
![image](https://user-images.githubusercontent.com/118445979/222955181-872a4cf6-dfd8-44ca-a099-86e1a32bfd97.png)

Repro project showing dialog (bar color is reset to some dialog default, even with system ui controller inside dialog)
![image](https://user-images.githubusercontent.com/118445979/222955258-861b4644-2467-47df-abf4-2e30a6196b86.png)

**Comment by joakimtall** [comment]
Hmm I guess the bars are green but shaded like everything else? I didnt notice this with my attempt at full screen dialog

**Comment by joakimtall** [comment]
No, the only workaround I have is to build a new navigation component with
a custom full screen dialog system that does not use the compose dialog at
all. A very heavy workaround.

We seem to have the exact same usecase

**Comment by Josh-Owen** [comment]
It seems that we do! And that's unfortunate, well, at least I know that it's not just me that was having this issue as I was close to giving up anyways, just frustrating to get so far to just end up excluding it for now.

In my code base, we have a generic full-screen dialog implemented in a similar way in XML already where we override `Dialog` with a custom layout and theme applied and use the builder pattern to build this dialog and instantiate it. This dialog only has one button which is often used to just dismiss the page, but I have a new requirement to add an additional button to re-direct elsewhere in the app and I was hoping to use this time to migrate this part of our code base to compose and handle both use cases, but I guess I will have to just extend the existing functionality.

**Comment by alexvanyo** [comment]
The sample project has an example of usage in a Compose `Dialog`:

https://github.com/google/accompanist/blob/b179a13c131baad19cdc0167afd2efa0e004d593/sample/src/main/java/com/google/accompanist/sample/systemuicontroller/DialogSystemBarsColorSample.kt

That might be useful as a guide?

**Comment by joakimtall** [comment]
Wow, that actually works! 

Things like this might be the secret 😮 

```
// Update the light and dark status bar state for both the Activity's SystemUiController and
// the Dialog's. If we just updated the Dialog's things wouldn't work properly for unknown
// reasons.
LaunchedEffect(parentSystemUiController, statusBarDarkIcons, navigationBarDarkIcons) {
    systemUiController.statusBarDarkContentEnabled = statusBarDarkIcons
    systemUiController.navigationBarDarkContentEnabled = navigationBarDarkIcons
    parentSystemUiController.statusBarDarkContentEnabled = statusBarDarkIcons
    parentSystemUiController.navigationBarDarkContentEnabled = navigationBarDarkIcons
}
```

Thanks!

Maybe this should be more obvious or better documented but that would be another issue
