### ISSUE TITLE
[WebView] Test/try out the new AndroidView in 1.4.0-rc01

### ISSUE THREAD

**Issue by arriolac** [google/accompanist#1536]
The new `AndroidView` introduced in 1.4.0-rc01 is optimized to reuse the underlying View when used within a lazy list. WebView usage within lazy lists (LazyColumn, LazyRow, Pager, etc.) could see some performance gains with this new change. 

See https://developer.android.com/jetpack/androidx/releases/compose-ui#1.4.0-rc01

**Comment by bentrengrove** [comment]
Tried it out but it isn't good for our use case in the 1.4 form. I will try again with 1.5.

https://review.android.com/c/platform/frameworks/support/+/2498315

**Comment by drpbprateek** [comment]
The provided link is broken @bentrengrove
