### ISSUE TITLE
[Swipe to refresh] Enhancement: Support for Material3

### ISSUE THREAD

**Issue by annaarroyo** [google/accompanist#1537]
**Description**
With material3 now, is there an opportunity here to add a Pull-to-refresh library for m3? I saw [Omico's project ](https://github.com/Omico/androidx-compose-material3-pullrefresh) and figured it was worth seeing about. 

**Additional context**
Ideally I would just like to use m3 in my project but pull-to-refresh isn't implemented there yet and from the sounds of it won't be till later in the year: [https://issuetracker.google.com/issues/261760718](https://issuetracker.google.com/issues/261760718).

**Comment by bentrengrove** [comment]
Unfortunately not. We are focussed on fixing this problem at the androidX level so won't be doing the work here.
