### ISSUE TITLE
[Permissions] Special permissions support

### ISSUE THREAD

**Issue by zoranigic** [google/accompanist#1542]
Does accompanist support special permissions like https://developer.android.com/reference/android/Manifest.permission#WRITE_SETTINGS
?
In onPermissionResult lambda within rememberPermissionState(Manifest.permission.WRITE_SETTINGS) { isGranted ->  }

isGranted is allways false, after calling writeSettingsPermissionState.launchPermissionRequest(), and WRITE_SETTINGS window is never showed.

**Comment by manuelvicnt** [comment]
It doesn't at the moment. But thanks for the issue, this would be a good feature request to implement (albeit complicated to maintain) :D Thanks!
