### ISSUE TITLE
[Navigation Material] Multiple BottomSheets on top of each other

### ISSUE THREAD

**Issue by MarcLFJ** [google/accompanist#1548]
**Description**
When navigating from BottomSheet to BottomSheet, I can't find a handle to display the new sheet on top of the old one. Currently the old sheet animates as if dismissed and then the new destination is shown. Looking into the source code, it seems like the in BottomSheet i reused and content is swapped, when it's off screen. 
Are there any plans on supporting multiple BottomSheets on top of each other (e.g not animating it out) or is this out of scope/not the intended usecase for navigation in material3? 

**Steps to reproduce**
Setup Navigation Graph with multiple bottomsheet and navigate from one bottomsheet destination to another.

**Expected behavior** 
The new BottomSheet destination to be displayed on top of the old one, instead of the old destination animating out.

**Additional context**

**Comment by gabrielittner** [comment]
This is still relevant

**Comment by MarcLFJ** [comment]
@jossiwolf this is still relevant

**Comment by Mwhite69** [comment]
How do i fix the problem mark whit3

**Comment by victor-munoz** [comment]
can we open this ticket?
