### ISSUE TITLE
[Navigation Material] Current release 0.30.0 ships navigation-compose alpha

### ISSUE THREAD

**Issue by nilsjr** [google/accompanist#1552]
**Description**
Current accompanist stable release 0.30.0 ships the navigation-compose:2.6.0-alpha07. We have an internal policy that we dont want to alpha versions without an important reason. This includes also transitive dependencies.

Was this commit intended and what was the reason?
https://github.com/google/accompanist/commit/c1ac4cb0a1bf4d2e01e7def6a3479204805f48d0

**Steps to reproduce**

**Expected behavior** 
Stable releases only ships stable transitive dependencies or has a valid reason to depend on beta/alpha versions.

**Additional context**

**Comment by raamcosta** [comment]
I came here to create this same issue.
Especially because the alpha version seems to have an annoying bug where it always adds parent nav graphs multiple times to the back stack.

So, totally agree let's have stable accompanist use stable 2.5.3 compose navigation 🙂
