### ISSUE TITLE
[Pager Indicators] HorizontalPagerIndicator, PagerState param type mismatch

### ISSUE THREAD

**Issue by es0329** [google/accompanist#1559]
**Description**
Type mismatch at `pagerState` param when attempting to use [`HorizontalPagerIndicator`](https://github.com/google/accompanist/blob/main/pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt#L143-L154).

**Steps to reproduce**
1. Begin with a simple implementation of the now-deprecated Accompanist `HorizontalPager` and `HorizontalPagerIndicator`.
2. Follow the [`Pager` migration](https://google.github.io/accompanist/pager/#migration) guidance.
3. Reference the new `rememberPagerState()` to pass a `androidx.compose.foundation.pager.PagerState` param into Accompanist's `HorizontalPagerIndicator`.
4. Compilation error.
```bash
> Task :app:compileDevDebugKotlin FAILED
e: Type mismatch: inferred type is androidx.compose.foundation.pager.PagerState but com.google.accompanist.pager.PagerState was expected
```

**Expected behavior** 
Overloaded support for AndroidX `PagerState` according to [migration table](https://google.github.io/accompanist/pager/#migration-table).

**Additional context**
`androidx.compose.foundation:foundation:1.4.0`
`com.google.accompanist:accompanist-pager-indicators:0.30.0`

<img width="689" alt="Screenshot 2023-03-24 at 10 36 20 PM" src="https://user-images.githubusercontent.com/819901/227688876-4ed71e3c-a45e-4e20-825e-dac3dd4a8d66.png">

**Comment by bentrengrove** [comment]
Just a guess while I triage this issue, try deleting any import for HorizontalPagerIndictor and also I think you have to include a pageCount in the foundation compatible version

**Comment by es0329** [comment]
Thanks @bentrengrove, these items were completed. The param `pageCount` was present since my prior (Accompanist) implementation, and the indicator was brought in via `import com.google.accompanist.pager.HorizontalPagerIndicator`.

**Comment by kostascollctiv** [comment]
> Just a guess while I triage this issue, try deleting any import for HorizontalPagerIndictor and also I think you have to include a pageCount in the foundation compatible version

Can confirm this worked. I've deleted the import of the HorizontalPagerIndictor and the HorizontalPagerIndictor function, then the new variation appeared.

**Comment by gaohomway** [comment]
I don't understand, how to solve this problem of inconsistent state types?

`Required:com.google.accompanist.pager.PagerState`

`Found:androidx.compose.foundation.pager.PagerState`

**Comment by kostascollctiv** [comment]
> I don't understand, how to solve this problem of inconsistent state types?
> 
> `Required:com.google.accompanist.pager.PagerState`
> 
> `Found:androidx.compose.foundation.pager.PagerState`

1. Delete the accompanist import
2. Delete HorizontalPager from your code
3. Try typing HorizontalPager and the autofill should give you 2 options, one of them takes androidx.compose.foundation.pager.PagerState as a pager type

**Comment by es0329** [comment]
My apologies @bentrengrove, I misunderstood [your guidance](https://github.com/google/accompanist/issues/1559#issuecomment-1484381610). It was my `HorizontalPager` that had a pre-existing `pageCount` param, but you were directing me to also add that param to `HorizontalPagerIndicator`.

Adding that newly required param to `HorizontalPagerIndicator` does indeed resolve its overloaded signature, which works with the Compose `PagerState`. Closing this issue; thank you for taking a look. 🙌🏽

**Comment by gaohomway** [comment]
@kostascollctiv  What I need to address is the `HorizontalPagerIndicator`

<img width="733" alt="截屏2023-03-29 12 45 52" src="https://user-images.githubusercontent.com/5456137/228429529-3931dc8c-84b5-4fb5-a0df-29be857a7b43.png">

**Comment by kostascollctiv** [comment]
> @kostascollctiv What I need to address is the `HorizontalPagerIndicator`
> 
> <img alt="截屏2023-03-29 12 45 52" width="733" src="https://user-images.githubusercontent.com/5456137/228429529-3931dc8c-84b5-4fb5-a0df-29be857a7b43.png">

Ah sorry! The solution is the same though.
![Screenshot 2023-03-29 at 11 13 23](https://user-images.githubusercontent.com/78222091/228470265-0b73b2ef-446c-48cb-b035-0b9033095cc2.png)

**Comment by es0329** [comment]
@gaohomway We had the same mistake. `HorizontalPagerIndicator` now needs [a `pageCount` param](https://github.com/google/accompanist/issues/1559#issuecomment-1487933141) for the overload we want to resolve. This differs slightly from the prior way [you](https://github.com/google/accompanist/issues/1559#issuecomment-1487939469) and [I](https://github.com/google/accompanist/issues/1559#issue-1640344817) had done it.

The legacy method [defaults pageCount by accessing `pagerState.pageCount`](https://github.com/google/accompanist/blob/cb7344a8db43ba57007bfe15d3e2c4266cf8a1f6/pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt#L80). 
The new method worked for me after I [explicitly supply the pageCount param](https://github.com/google/accompanist/blob/cb7344a8db43ba57007bfe15d3e2c4266cf8a1f6/pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt#L142-L143).

```kotlin
HorizontalPagerIndicator(
    pagerState = pagerState,
    pageCount = viewModel.data.size,
    modifier = Modifier.padding(0.dp, 8.dp)
)
```

**Comment by gaohomway** [comment]
@es0329 You are right. I have solved this problem. Thank you for replying to me.
Thank you also to @kostascollctiv
