### ISSUE TITLE
[WebView] Double page loading during first composition

### ISSUE THREAD

**Issue by cosminstefanxp** [google/accompanist#1563]
**Description**
The WebView composable seems to not be taking proper care of _when_ the launched effects run. This causes launched effects to be run multiple times, with same values, causing multiple loads of the initial page.

**Steps to reproduce**
1. Create a screen with the WebView composable that just loads a simple URL:
`WebView(state = WebViewState(WebContent.Url(url = "https://example.com")))`

**Expected behavior** 
1. The URL is only loaded once;
2. The launched effects are executed with right values; 

**Actual behvior**
Please see the logs below. You'll notice a few things:
1. Composition of the WebView starts; - OK
2. Composition of AndroidView and creation of WebView - OK;
3. Since everything has been on main thread, the **launched effect** coroutines start up **only after the WebView is created**. This causes the issue, due to the captured values: both `LaunchedEffects` run now, after the `webView` as been instantiated, so the `webView` is not null inside anymore, even though they were "composed" when the `webView` was `null`.
4. Problem is that: we attach to the 2 flows (both the `navigator.navigationEvents` and the `state.content`) twice and load the URL twice.

**Proposed solution**
Only compose the `LaunchedEffect` if the `webView` is not null _and_ capture & use correct value:
```
    webView?.let { wv ->
        LaunchedEffect(wv, navigator) {
            with(navigator) { wv.handleNavigationEvents() }
        }
    }
```
or at least use the captured value
```
val currentWebView = webView
    LaunchedEffect(currentWebView, navigator) {
        with(navigator) { currentWebView?.handleNavigationEvents() }
    }
```

**Additional context**
Here's are logs with certain events. Please notice that the LaunchedEffects run _after_ the WebView has been initialized, so they run with the same arguments twice. 
```
14:51:33.386 32001-32001 Composing AccompanistWebView
14:51:33.395 32001-32001 Composing AndroidView
14:51:33.398 32001-32001 Creating WebView via Factory...
...
14:51:33.421 32001-32001 Created WebView: android.webkit.WebView{3aeafb5 VFEDHVC.. ......I. 0,0-0,0}
14:51:33.441 32001-32001 WebView+Navigator LaunchedEffect: android.webkit.WebView{3aeafb5 VFEDHVC.. ......ID 0,0-1080,0} io.shortcut.wrappkit.core.webview.WebViewNavigator@a6f533
14:51:33.443 32001-32001 WebView+State LaunchedEffect: android.webkit.WebView{3aeafb5 VFEDHVC.. ......ID 0,0-1080,0} io.shortcut.wrappkit.core.webview.WebViewState@e3e20f0
14:51:33.446 32001-32001 Loading url: Url(url=https://example.com, additionalHttpHeaders={})
14:51:33.454 32001-32001 Composing AccompanistWebView
14:51:33.462 32001-32001 OnProgressChanged: 10
14:51:33.463 32001-32001 WebView+Navigator LaunchedEffect: android.webkit.WebView{3aeafb5 VFEDHVC.. ......ID 0,0-1080,0} io.shortcut.wrappkit.core.webview.WebViewNavigator@a6f533
14:51:33.464 32001-32001 WebView+State LaunchedEffect: android.webkit.WebView{3aeafb5 VFEDHVC.. ......ID 0,0-1080,0} io.shortcut.wrappkit.core.webview.WebViewState@e3e20f0
14:51:33.465 32001-32001 Loading url: Url(url=https://example.com, additionalHttpHeaders={})
14:51:33.472 32001-32001 Composing AndroidView
14:51:33.479 32001-32001 OnPageFinished: https://example.com/
14:51:33.564 32001-32001 OnPageStarted: https://example.com/
14:51:33.568 32001-32001 OnProgressChanged: 100
14:51:33.568 32001-32001 OnProgressChanged: 100
14:51:33.569 32001-32001 OnPageFinished: https://example.com/
```

**Comment by dostalleos** [comment]
I have the same experience. It affected our production app, unfortunately. Please, fix it asap. We had to revert back to v0.28.0.
