### ISSUE TITLE
[Pager] Migration to Foundation Pager

### ISSUE THREAD

**Issue by alejandroaap** [google/accompanist#1567]
**Description**

After migrating the accompanist pager to the foundation pager, we have detected an error when it comes to detecting when the pager is being scrolled. With the foundation pager, the isScrollInProgress variable has an wrong value when scrolling in a direction other than the one configured in the pager, that is, with a HorizontalPager the variable takes the value true when doing a vertical scroll, and that shouldn't to be his behaviour. However, with the accompanist pager this does not happen and it works correctly. Why does this happen with the accompanist pager?

**Steps to reproduce**

`val pagerState = rememberPagerState()`

`LaunchedEffect(pagerState) {
  snapshotFlow { pagerState.isScrollInProgress }.collect {
    print("isScrollInProgress $it")
  }
}`

`HorizontalPager(pageCount = 10, state = pagerState) { page ->
    // Our page content
    Text(
        text = "Page: $page",
        modifier = Modifier
            .fillMaxWidth()
            .height(100.dp)
    )
}`

**Expected behavior** 
The print function only runs when the user scrolls horizontally

**Additional context**
Print function is running when user scrolls horizontally and vertically

implementation platform('androidx.compose:compose-bom:2023.03.00')
compose version --> 1.4.0

**Comment by bentrengrove** [comment]
Sorry, please file bugs for foundation pager at https://goo.gle/compose-feedback
