### ISSUE TITLE
[Navigation Animation] Is there a way to remove crossfade when navigating ?

### ISSUE THREAD

**Issue by gastsail** [google/accompanist#1575]
**Description**
Currently when I navigate from one place to another adding  either **exitTransition** or **enterTransition** as   

 ```
slideOutOfContainer(
                AnimatedContentScope.SlideDirection.Right, animationSpec = tween(300)
            )
```
I get a fade effect meanwhile the animation is taking place, this does not look good for UX in the app and overlaps the current navigated view with the one making the navigation request.

Is there any way of removing the fade before navigating ?

**Comment by jbw0033** [comment]
You can us the Animation compose `EnterTransition.None` and `ExitTransition.None` APIs to avoid the default crossfade.
