### ISSUE TITLE
[Suggestion] Migrate gradle files from Groovy to Kotlin DSL

### ISSUE THREAD

**Issue by oas004** [google/accompanist#1578]
Hey!

First of all, thanks for a great library! 

This is just a suggestion and I wanted to know what you guys thought about it. Feel free to close it, if it does not make sense.

I noticed that all the gradle files are in Groovy, what do you guys think about converting it to Kotlin DSL? Is there a reason for not migrating or any downside to migrating? :) 

I would love to help out and contribute if this is okay :)

One suggested approach to this as we did when migrating in the [horologist project](https://github.com/google/horologist) is the following:

1. Go module by module prepare the Groovy scripts following the steps described [here](https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html#prepare_your_groovy_scripts). Then make a PR for each module to keep it easy to review.
2.  Do the actual conversion of the file to `.kts` and check that it compiles and that everything works as expected. Then make a PR for each module, to make it easy to review.

One tool that might help migrate is [this](https://github.com/bernaferrari/GradleKotlinConverter) script to convert Groovy to Kotlin DSL.  I have not tried it myself though.

**Comment by bentrengrove** [comment]
Thanks for the suggestion. We would definitely accept this as a contribution if you are open to doing it!

I agree with your plan to do it module by module.

**Comment by oas004** [comment]
I would love to! :) I will try to prioritize this :)

**Comment by bentrengrove** [comment]
I guess stalebot can't see all the PRs

**Comment by oas004** [comment]
Just to give a status update here is that currently  22/27 groovy files are not in Kotlin DSL :) We have PRs up on the rest except the project grades. I will do that when everything else is in. When that is done my thoughts where to set the target and source java versions to 11 and to update the plugins to using version catalog correctly :) Then I think we can also bump the AGP version as of #1617

**Comment by bentrengrove** [comment]
Thank you for all your effort!
