### ISSUE TITLE
[Navigation Animation] No API to handle unhandled deeplinks, navigates to a random destination

### ISSUE THREAD

**Issue by Nek-12** [google/accompanist#1583]
**Description**
There is no way to deal with unhandled / not found deeplinks in the library. Upon encountering an unhandled deeplink, the app navigates to a random screen, probably the one that got added to the graph last. 
Regular compose navigation allows to provide a `onDeepLinkRequest` block in the `NavHost` composable. What's the replacement for the animated accompanist navigator?

**Steps to reproduce**
1. Define multiple destinations
2. Try to open a deeplink for which a route is not found
3. Random destination is opened

**Expected behavior** 
An app allows to specify a route to take for unhandled deeplinks and / or a custom logic

**Additional context**
Accompanist 0.31.0-alpha

**Comment by ianhanniballake** [comment]
> `onDeepLinkRequest` block in the `NavHost` composable.

This isn't a thing.

> the app navigates to a random screen, probably the one that got added to the graph last.

If there is no valid deep link to handle, nothing gets navigated to. If you're [following the documentation](https://developer.android.com/guide/navigation/navigation-deep-link#handle) and always using the default `launchMode` of `standard`, then you'll be on the start destination of your app, just as if your app was opened from the launcher icon.

> An app allows to specify a route to take for unhandled deeplinks and / or a custom logic

This is exactly what the [existing feature request](https://issuetracker.google.com/issues/257343603) is for. Feel free to star that feature request to follow along.

**Comment by Nek-12** [comment]
Thanks for the answer. `onDeepLinkRequest` is not a thing, the AI tricked me! Sorry for the confusion.
