### ISSUE TITLE
[Navigation Material] Please add the option to skip the bottom sheet close animation

### ISSUE THREAD

**Issue by Monabr** [google/accompanist#1600]
HI! Please add more options to customize the animation, such as the ability to turn off the bottom sheet closing animation.

It would help me a lot and I can't find a way to do it myself unfortunately.

**Comment by ianhanniballake** [comment]
You want the bottom sheet to just...disappear completely via a jump cut?

**Comment by ianhanniballake** [comment]
Bottom sheets are [Material 2 spec](https://m2.material.io/components/sheets-bottom#usage) and [Material3 spec](https://m3.material.io/components/bottom-sheets/overview), which is very opinionated on how they animate, so the lack of customization for bottom sheet animations is working as intended.

I'd suggest filing any performance issues against the [Compose Material library directly](https://issuetracker.google.com/issues/new?component=742043&template=1590761) with a sample project that shows your laggy animation. Accompanist is not writing any animation code at all, just using what the Compose Material library is providing, so any fixes in the animation lag would need to be done at that level.
