### ISSUE TITLE
[Navigation Material] 

### ISSUE THREAD

**Issue by whatiamdoing** [google/accompanist#1635]
**Description**
Re-selecting BottomNavigationItem recreates a new instance of an existing viewmodel. In version 0.28.0 everything works fine)

**Steps to reproduce**
1) Updating the accompanist library from version 0.28.0 to version 0.31.2-alpha.
2) Add BottomNavigation with multiple screens that have a viewmodel.
3) Re-select tab.

**Expected behavior** 
Return to existing destination

**Additional context**
Tab selection function: 
navController.navigate(
                        route = news.destination.route
                    ) {
                        // Pop up to the start destination of the graph to
                        // avoid building up a large stack of destinations
                        // on the back stack as users select items
                        popUpTo(navController.graph.findStartDestination().id) {
                            saveState = true
                        }

                        // Avoid multiple copies of the same destination when
                        // reselecting the same item
                        launchSingleTop = true

                        // Restore state when reselecting a previously selected item
                        restoreState = true
                    }

ViewModel creation: 
val viewModel: ChatsViewModel = hiltViewModel()

**Comment by FunkyMuse** [comment]
This might help you, had similar problem https://issuetracker.google.com/issues/265838050
