### ISSUE TITLE
Error in app after update to latest release of accompanist

### ISSUE THREAD

**Issue by joyner-perez** [google/accompanist#1643]
## Describe the bug
When adding the latest version, 0.31.3-beta, BottomDrawer gives me the following exception: java.lang.NoSuchMethodError: No static method SnapLayoutInfoProvider.

## To Reproduce
1. Go to add latest version(0.31.3-beta)
2. Click on sync project
3. Run app

## Environment:
 - Android OS version: Android 11 and Android 13
 - Device: Emulator, Xiaomi 9 NFC, Samsung Galaxy A13 
 - Accompanist version: 0.31.3-beta

**Comment by ianhanniballake** [comment]
There's no `BottomDrawer` integration in Accompanist, so this isn't something that is fixable at the Accompanist level.

Accompanist 0.31.3-beta is built against Compose 1.5.0-beta01, so make sure you've upgrade all other dependencies (such as Compose Material) to use 1.5.0-beta01 as well - this kind of error occurs when you've mismatched your Compose versions.
