### ISSUE TITLE
[Navigation Material] bottomSheet() onSheetShown and onSheetDismissed issues

### ISSUE THREAD

**Issue by newmanw** [google/accompanist#1644]
**Description**
Noticed after upgrade from 0.28.0 to 0.30.1 navigation stack was not being popped correctly causing issues with state,

**Steps to reproduce**
open a few bottom sheets and click on scrim to close

**Expected behavior** 
Digging into the code I think this is what is happening, but not an expert here.

onSheetShown should be called here for every sheet, in some cases this is not called

https://github.com/google/accompanist/blob/main/navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt#L227

When onSheetShown is not called, the transitionInProgressEntries still contains an entry and marks the transition as complete without pop'ing the navigation stack.

https://github.com/google/accompanist/blob/main/navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt#L232

**Additional context**
I need to know when the bottom sheet is dismissed on scrim click, as such I am relying on the navigation stack to change to detect this.  When I click on the scrim the navigation stack is no longer changed to route/content that was under the scrim.

**Comment by spectrl** [comment]
I think this _may_ be an issue with Compose Material `1.5.0-beta01` because I've noticed some issues with the scrim staying displayed (but the sheet dismissing), and also weird back button behaviour as well...

**Comment by newmanw** [comment]
I seeing this in 1.4.x.  Was working in 1.3.x, trying to downgrade now to confirm.

**Comment by newmanw** [comment]
If it helps, this is how I am verifying.

```
val navController = rememberNavController(bottomSheetNavigator)
navController.addOnDestinationChangedListener { _: NavController, destination: NavDestination, _: Bundle? ->
   Log.i("Debug", "navigation destination changed $destination")
}
```

I am not seeing the navigation destination change on scrim tap.  The bottom sheet does dismiss.

**Comment by newmanw** [comment]
This seems to be an issue with no bottom sheet content, 0 height until content is ready.  I have forked the repo and modified the bottomsheet sample that shows the issue with the above logging I mentioned.  Simply just added some live data to delay loading the bottom sheet content.

Latest commit on the main branch.

https://github.com/newmanw/accompanist/commits/main

**Comment by tymen-schiphol** [comment]
I've encountered this same issue.

**Comment by Mwhite69** [comment]
What can i do now?

**Comment by lita-kornilova-comodule** [comment]
still encountering the same issue with accompanist 0.32.0 and compose material 1.5.4. It is indeed caused by the bottom sheet having 0 height at first

**Comment by paktalin** [comment]
still encountering the same issue with accompanist 0.32.0 and compose material 1.5.4. It is indeed caused by the bottom sheet having 0 height at first

**Comment by chriswiesner** [comment]
issue is still happening - any way to workaround that?

**Comment by newmanw** [comment]
As a workaround you wrap the dynamic content in something that has a height.  Not optimal if you want your height to be dynamic based on content.  You could resize after data is loaded.

Instead of: 
```
@Composable
fun BottomSheet() {
    val viewModel: BottomSheetViewModel = viewModel()
    val isLoading by viewModel.isLoading.collectAsState()
    viewModel.load()

    isLoading?.let {
        Column(Modifier.fillMaxWidth()) {
         ...
        }
    }
}
```

```
@Composable
fun BottomSheet() {
    val viewModel: BottomSheetViewModel = viewModel()
    val isLoading by viewModel.isLoading.collectAsState()
    viewModel.load()

    Column(Modifier.height(400.dp)) {
        isLoading?.let {
           // Your content here
        }
     }
}
```
