### ISSUE TITLE
[Navigation Material] Bottom sheet popped when navigating to a non-bottomsheet screen 

### ISSUE THREAD

**Issue by mkano9** [google/accompanist#1647]
**Description**
When navigating from bottom sheet A to bottom sheet B and then pressing the back button, bottom sheet A appears again which is expected. But when navigating from bottom sheet A to a full screen composable A and pressing the back button, bottom sheet A
does not appear. 

Is this a bug? Also, is there a plan to support this library's functionality in jetpack navigation in the future?

**Comment by ianhanniballake** [comment]
This is intentional as per [the documentation](https://developer.android.com/guide/navigation/use-graph/navigate#back-stack):

> [these] destinations implement the [FloatingWindow](https://developer.android.com/reference/androidx/navigation/FloatingWindow) interface, indicating that they overlay other destinations on the back stack. As such, one or more FloatingWindow destinations can be present only on the top of the navigation back stack. Navigating to a destination that does not implement FloatingWindow automatically pops all FloatingWindow destinations off of the top of the stack. This ensures that the current destination is always fully visible above other destinations on the back stack.
