### ISSUE TITLE
[WebView] WebView wrapContent and static size not working

### ISSUE THREAD

**Issue by ashiqfury** [google/accompanist#1650]
**Description**
I have rendered a webpage, and I have set the WebView size to 150 dp, but the content takes full width. Likewise, wrapContentWidth is also not working; the content takes up the whole width. WebView always takes full width, whether it is set as wrapContentSize or static size.

**Steps to reproduce**
```kotlin
Surface {
    val state = rememberWebViewState("https://www.github.com/")
    WebView(
        state = state,
        modifier = Modifier
            .size(150.dp)
    )
}
```

**Expected behavior** 
I want the WebView to take width based on the content present in it, and when I set a static width or height, it should not overflow.

**Additional context**
Accompanist - 0.31.3-beta
kotlin - 1.8.10
compose - 1.4.0

**Comment by V-Abhilash-1999** [comment]
I am also facing the same issue. Any update on this? @bentrengrove
