### ISSUE TITLE
[WebView] WebView loading delay in LazyColumn

### ISSUE THREAD

**Issue by ashiqfury** [google/accompanist#1651]
**Description**
I have placed WebViews in LazyColumns, where each WebView has a dynamic height. Every time I scroll the list, the WebView loads with a significant delay that looks flickering. I can see only the white screen for 2 seconds after scrolling.

**Steps to reproduce**
```kotlin
LazyColumn(
    modifier = Modifier
        .fillMaxWidth()
) {
    items(
        count = 100,
        key = {
            it
        }
    ) {
        val state = rememberWebViewStateWithHTMLData(data = "<strong>Strong text $it</strong>")
        WebView(
            state = state,
            modifier = Modifier
                .padding(20.dp),
        )
    }
}
```

**Expected behavior** 
The WebView should render fast when inside LazyColumn.

**Comment by KevinnZou** [comment]
Hi, I am wondering did you try it with Recyclerview? Since I think it is reasonable to have delay under such situation.

**Comment by mouli-011** [comment]
did anyone find a solution?

**Comment by trevorwang** [comment]
same issue here.

**Comment by YugeCse** [comment]
I think that google don't have any plan to resolve the androidview's state question. They gave up to develope the compose webview library. The webView's state restore behavior alway be slow than others.
