### ISSUE TITLE
Active bullet offset is calculated wrong - Again

### ISSUE THREAD

**Issue by arlm1** [google/accompanist#1653]
**Description**
An error that previously was reported on https://github.com/google/accompanist/issues/623 is happening again (see attached screenshot):

![last dot error](https://github.com/google/accompanist/assets/1093296/6a13ff17-f9af-4db1-9a07-9cf7c861dbe2)

The issue only happens with the last dot. All other dots (first + the ones in the middle) are correctly aligned with the active dot.
I am using androidx.compose.foundation.pager.HorizontalPager + com.google.accompanist.pager.HorizontalPagerIndicator. These are the versions I have:

kotlin = "1.8.21"
compose = "1.4.3"
composeCompiler = "1.4.7"
accompanist = "0.30.1"

I am running on a Galaxy S23 Ultra with Android 13

A fix was implemented previously with this PR: https://github.com/google/accompanist/pull/624 but it seems it is happening again

**Comment by andkulikov** [comment]
Feel free to contribute the fix if you don't mind
