### ISSUE TITLE
[Flow layouts] Compose Foundation new APIs doesn't allow SpaceEvenly + spacing

### ISSUE THREAD

**Issue by LouisCAD** [google/accompanist#1654]
Hello, the `FlowRow` in accompanist is getting deprecated, but feature parity isn't there.

In the `FlowRow` from Compose Foundation `1.5.0-beta01` (currently the latest), there's no equivalent to `mainAxisSpacing` when you want `SpaceEvenly` arrangement/alignement since `spacedBy` cannot be used it at the moment.

Can you revert the deprecation of `FlowRow` in Accompanist until this is supported in Compose Foundation?
I'm personally passing the following parameters to my `FlowRow`s and haven't found a viable alternative:

```kotlin
FlowRow(
    Modifier.fillMaxWidth(),
    mainAxisAlignment = MainAxisAlignment.SpaceEvenly,
    mainAxisSpacing = 16.dp
) {
    // content
}
```

Thank you and have a great day!

**Comment by bentrengrove** [comment]
Thanks for filling the issue. I would definitely encourage you to file that as a feature request at goo.gle/compose-feedback and I will tag in @uchennafokoye here to see it.

We won't be reverting the deprecation as it is an important signal to people to start moving to the Compose Foundation version but it won't be removed from Accompanist for a long time so you can continue to use the Accompanist version if it meets your needs.
