### ISSUE TITLE
Page Recomposition in Horizontal Pager

### ISSUE THREAD

**Issue by ashutosh-sharechat** [google/accompanist#1656]
**Bug Description**
While using HorizontalPager, the pages(current+adjacent) get recomposed every time a page is scrolled. I have static data in all the pages and I don't want them to recompose. I tried providing the key to the HorizontalPager but it didn't work.

**Steps to reproduce**
- Create a HorizontalPager with multiple pages
- Scroll the pages and check Layout Inspector

**Additional Information**
library version used: `0.25.0

**Comment by bentrengrove** [comment]
Hello

Accompanist Pager is now deprecated as there is a [Pager](https://developer.android.com/jetpack/compose/layouts/pager) composable available in Compose Foundation. Can you please retest your issue using the Compose Foundation Pager and if it still exists, file an issue at https://goo.gle/compose-feedback.

Thank you.
