### ISSUE TITLE
[Navigation Material] Prevent closing Bottom Sheet

### ISSUE THREAD

**Issue by danieldaeschle** [google/accompanist#1657]
I'm using a migrated version of [`ModalBottomSheetLayout`](https://google.github.io/accompanist/navigation-material/) for material3.

Everything works fine so far. But there is a use-case where I want to prevent the user from closing the BottomSheet.

**Description**
I have a form in my BottomSheet.
1. User fills out that form
2. User forgets to click save
3. User either _presses back_ from phone, _clicks into the grey area_, _clicks close icon_ inside BottomSheet or lastly _drags the BottomSheet down_.
4. The BottomSheet closes without data being saved.

Interrupting _back press_ and _clicking the close icon _ is easy but the other two ways to close the BottomSheet are not so easy to solve. I would like to display a Dialog to the user which asks him if he want to discard the data. If he presses yes, the BottomSheet can close, otherwise it should stay open (or reopen if the user dragged it down).

Is there a way to achieve my use-case without modifying the internal code too much?

**Comment by joakimtall** [comment]
I came here to post exactly this issue! 

- I have several use cases where I want to prevent the bottom sheet from being closed (like displaying progress indicator for a pending network action, or cancelling form like above)
- I have a use case where I want it to be dismissed but control the navigation as this happens

**Comment by danieldaeschle** [comment]
Is there an update if there is a workaround or will be worked on any time soon?

**Comment by danieldaeschle** [comment]
ping

**Comment by danieldaeschle** [comment]
wtf, why did it get closed?

**Comment by joakimtall** [comment]
I guess the bot is buggy. Anyway, working on more bottom sheet stuff right now so still a priority issue for me

**Comment by danieldaeschle** [comment]
Any news on this?

**Comment by joakimtall** [comment]
Might need to make a new issue and link to this one? This process is frustrating to say the least 😅
