### ISSUE TITLE
[Flow layouts] Migration Guide is not accurate

### ISSUE THREAD

**Issue by TurKurT656** [google/accompanist#1658]
**Description**
I'm trying to migrate `appcompanist FlowRow` to `foundationlayout FlowRow`. in the migration guide it says that instead of `mainAxisSpacing` and `crossAxisSpacing` we must use 
`horizontalArrangement = HorizontalArrangement.spacedBy(50.dp, Alignment.Start)`
and 
`verticalArrangement = VerticalArrangement.spacedBy(50.dp, Alignment.Top)` like this:
```
FlowRow(
    modifier = Modifier,
    horizontalArrangement = HorizontalArrangement.spacedBy(50.dp, Alignment.Start),
    verticalArrangement = VerticalArrangement.spacedBy(50.dp, Alignment.Top),
    content = content
)
```
For `horizontalArrangement` parameter there isn't any provider named `HorizontalArrangement` so I replaced it with `Arrangement.spacedBy(50.dp, Alignment.Start)` and it fixed the issue but there isn't any parameter named `verticalArrangement` in `FlowRow`. `FlowRow` has `verticalAlignment` and for that parameter there isn't any provider like `Alignment.spacedBy(50.dp, Alignment.Top)`.
So have can I have `crossAxisSpacing` in new `FlowRow`?

**Comment by bentrengrove** [comment]
Thanks for filing that issue, sorry about that error in the migration guide. I will fix that up.

Cross axis spacing was added in [Compose 1.5](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.5.0-alpha04) which is currently in beta. The verticalArrangement should be there and let you achieve what you are trying to do. 

Your fix of using `Arrangement` not `HorizontalArrangement` is correct and will work with vertical as well in 1.5.

**Comment by cliuff** [comment]
I am migrating from `accompanist-flowlayout:0.28.0` to `fundation:1.5.4`, the migration guide from Accompanist website states that 
> For `FlowRow`
>   `mainAxisAlignment` is now `horizontalArrangement`
>   `crossAxisAlignment` is now `verticalArrangement`

The `crossAxisAlignment` in Accompanist `FlowRow` behaves like the one in `Row`. However fundation `FlowRow` only provides `verticalArrangement` but no `verticalAlignment`. According to [Flow layouts docs](https://developer.android.com/jetpack/compose/layouts/flow#individual-item), we need to use `Modifier.align()` on row items.


Thus the following code
```kotlin
FlowRow(crossAxisAlignment = FlowCrossAxisAlignment.Center) {
    Item()
    Item()
}
```
should be migrated to
```kotlin
FlowRow {
    Item(modifier = Modifier.align(Alignment.CenterVertically))
    Item(modifier = Modifier.align(Alignment.CenterVertically))
}
```

**Comment by eric-labelle** [comment]
The migration guide seems to be gone or I can't find it. Why deleting a guide for the migration when we need it to bump on `0.37`?

**Comment by alexvanyo** [comment]
We've been removing libraries that have been deprecated for a while now, you can still find the migrations guides in the older history of the project: https://github.com/google/accompanist/blob/compose-1.6/docs/flowlayout.md
