### ISSUE TITLE
[WebView] how to enable debug mode for accompanist webview

### ISSUE THREAD

**Issue by maanuanubhav999** [google/accompanist#1662]
**Description**
Due to a use case I want to debug the web-view, which could easily be accomplished using `                        WebView.setWebContentsDebuggingEnabled(true)` for general web-view but I am unable to figure out how to do for accompanist webview

**Steps to reproduce**
1. write code for web-view initlisation
2. try to debug it

**Expected behavior** 
we should easily be able to debug it

**Additional context**

**Comment by bentrengrove** [comment]
The same code should work for the Accompanist WebView.
The easiest spot to add it would be in your Activity onCreate.

**Comment by maanuanubhav999** [comment]
Thanks a  lot @bentrengrove I was placing it on the composable function itself.
