### ISSUE TITLE
Support Compose 1.6.x

### ISSUE THREAD

**Issue by OliverRhyme** [google/accompanist#1665]
## Describe the bug
Currently accompanist only uses up to 1.5.x. Compose 1.6.x has now been released and it would be good if we release an accompanist version for 1.6.x for transitive dependencies

## Expected behavior
Release a new version that uses compose 1.6.x

**Comment by bentrengrove** [comment]
We normally do this once the previous version goes stable. There shouldn't be any issue using the current version of accompanist with Compose 1.6, if there is a specific crash or issue please let me know.

**Comment by bentrengrove** [comment]
Issue #1671 needs Compose 1.6 so I will get the new version ready
