### ISSUE TITLE
[System UI Controller] SystemUiController.navigationBarDarkContentEnabled isn't working in API 34 emulator

### ISSUE THREAD

**Issue by Omico** [google/accompanist#1681]
## To Reproduce
```
    val systemUiController = rememberSystemUiController()
    LaunchedEffect(systemUiController) {
        systemUiController.setSystemBarsColor(
            color = Color.Transparent,
            darkIcons = true,
        )
    }
```

## Screenshots?
<img src="https://github.com/google/accompanist/assets/14316223/e3d1671a-396f-4c01-bcd3-ebe303bb2e7c" width="400">
<img src="https://github.com/google/accompanist/assets/14316223/c0081848-3242-4939-8c1c-d8e202b2860f" width="400">

## Environment:
 - Android OS version: Android 14
 - Device: Emulator, Resizable (Experimental)
 - Accompanist version: 0.30.1

**Comment by alexvanyo** [comment]
This lines up with behavior on a Pixel Tablet running Android 14 with the "3 button" navigation mode.

In that case, the color of the taskbar is controlled entirely by the system's theme, and not by the application through the window APIs (which systemuicontroller wraps).

So nothing applicable to accompanist here.
