### ISSUE TITLE
Webview client not able to capture onpagefinished callback 

### ISSUE THREAD

**Issue by RizwanAtNvest** [google/accompanist#1689]
val state = rememberWebViewState("https://example.com/Login/LoginEXA")
                        WebView(
                            state = state,
                            onCreated = {
                                it.webViewClient = WebViewClients(object : WebViewClients.PageLoaderStatus {
                                    override fun onPageLoaded() {
                                        loadingState = false

                                    }
                                })
                                it.settings.javaScriptEnabled = true
                                it.settings.domStorageEnabled = true
                                it.clearCache(true)

                            })

**Comment by bentrengrove** [comment]
You need to use the Accompanist web view clients. Have a look at the sample app in accompanist for an example
