### ISSUE TITLE
[WebView] 

### ISSUE THREAD

**Issue by mouli-011** [google/accompanist#1692]
**Description**
I am using a AndroidView WebView inside LazyColumn. When I scroll, because of the autosizing of the WebView, the scroll seems to flicker. When give a constant height to the WebView the issue is resolved. But as we cannot give a fixed height to WebView could you suggest me some solution to solve this.

**Comment by bentrengrove** [comment]
Unfortunately Accompanist WebView has been deprecated and won't be supported going forwards. I am closing this issue. We recommend you fork the implemenation here and customise it to your needs. For more information please see our [update blog](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)
