### ISSUE TITLE
[Permissions] A better way to handle permissions easier.

### ISSUE THREAD

**Issue by ErfanSn** [google/accompanist#1694]
### Description
Unfortunately, the current API is not something that makes the work of programmers easier, and everyone should rewrite the logic based on possible scenarios. Based on the topics that were raised in previous issues, I have a [new solution](https://gist.github.com/ErfanSn/24f86473af544951bef23532ee3b53c6) to propose, which is based on callback work. and handles the following scenarios correctly, and if approved, I will create the corresponding pull request:

- [Touch the outside of the permission dialog](https://github.com/google/accompanist/issues/549#issuecomment-878168092)
  - No matter how many times this action occurs, nothing happens until the permission status is explicitly set by the user.
  - When the permission status is specified and **Denied** is selected, the callback corresponding to rationale show will be called.

- [Granting partial or all permissions from the app settings before the first run](https://github.com/google/accompanist/issues/549#issuecomment-943665066)

- [Being clear about what permissions have been explicitly granted in the first place](https://github.com/google/accompanist/issues/819)

- [Make a distinction between whether permissions have been permanently denied or are being requested for the first time](https://github.com/google/accompanist/pull/990#issuecomment-1204138779)

**Comment by bentrengrove** [comment]
We aren't looking to change how Accompanist permissions works at this time. I would encourage you to release your own library with this idea. Thanks for the submission.

**Comment by akardas16** [comment]
> ### Description
> Unfortunately, the current API is not something that makes the work of programmers easier, and everyone should rewrite the logic based on possible scenarios. Based on the topics that were raised in previous issues, I have a [new solution](https://gist.github.com/ErfanSn/24f86473af544951bef23532ee3b53c6) to propose, which is based on callback work. and handles the following scenarios correctly, and if approved, I will create the corresponding pull request:
> 
> * [Touch the outside of the permission dialog](https://github.com/google/accompanist/issues/549#issuecomment-878168092)
>   
>   * No matter how many times this action occurs, nothing happens until the permission status is explicitly set by the user.
>   * When the permission status is specified and **Denied** is selected, the callback corresponding to rationale show will be called.
> * [Granting partial or all permissions from the app settings before the first run](https://github.com/google/accompanist/issues/549#issuecomment-943665066)
> * [Being clear about what permissions have been explicitly granted in the first place](https://github.com/google/accompanist/issues/819)
> * [Make a distinction between whether permissions have been permanently denied or are being requested for the first time](https://github.com/google/accompanist/pull/990#issuecomment-1204138779)

I am using similar to your solution in android view system, there are some cases which android remove all permissions if app is not used in long time by user but values stored in shared preferences won't change. How will this affect solution you described?
