### ISSUE TITLE
[Navigation Material] 

### ISSUE THREAD

**Issue by anastas-makar** [google/accompanist#1697]
**Description**

Error: `java.lang.IllegalStateException: The offset was read before being initialized. Did you access the offset in a phase before layout, like effects or composition?` updating to `androidx.compose.material:material:1.6.0-alpha03` (in `androidx.compose.material:material:1.5.0-beta01` works fine)

**Steps to reproduce**

Update to `androidx.compose.material:material:1.6.0-alpha03`. I have not found any reference to my code, so I don't know which element caused the issue. So I've attached the full stacktrace in text file.
[stacktrace.txt](https://github.com/google/accompanist/files/12332834/stacktrace.txt)

**Comment by leinardi** [comment]
This is probably related to this upstream issue: https://issuetracker.google.com/issues/295536718

**Comment by ianhanniballake** [comment]
Crashes in Material components should be reported [in the issue tracker](https://issuetracker.google.com/issues/new?component=742043&template=1590761).

**Comment by anastas-makar** [comment]
I've updated to `androidx.compose.foundation:foundation:1.6.0-alpha08` and the issue is not reproducing. Most likely it was fixed in one the latest versions.
