### ISSUE TITLE
Deprecate insets-ui?

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#1700]
https://android-review.googlesource.com/c/platform/frameworks/support/+/2667875

**Comment by alexvanyo** [comment]
Already done in #1693 😄

**Comment by kenshin171** [comment]
this migration guide stll states 

`Continue using the non-deprecated [insets-ui](https://google.github.io/accompanist/insets/#inset-aware-layouts-insets-ui) for now.`

at https://google.github.io/accompanist/insets/#migration-steps though...

and is there any migration guide for migrating away from insets-ui?

**Comment by alexvanyo** [comment]
We should remove that line from the migration steps, it is out of date.

Both material3 and material2 have support built-in to components now, as documented here: https://developer.android.com/jetpack/compose/layouts/insets#material3-components
