### ISSUE TITLE
[Pager] Pages do not get disposed.

### ISSUE THREAD

**Issue by V-Abhilash-1999** [google/accompanist#1705]
**Description**
Pages do not get disposed.

**Steps to reproduce**
1. Create a simple Pager with page count as 100
2. Create a Disposable side effect inside each page
3. The onDispose callback does not get called in any page

**Expected behavior** 
onDispose callback should be called when pages get disposed.

**Comment by bentrengrove** [comment]
Pager is now deprecated. Please use the Pager that is available in the main Compose libraries.

More details here https://developer.android.com/jetpack/compose/layouts/pager
