### ISSUE TITLE
[System UI Controller] Can calls to show/hide system ui be idempotent?

### ISSUE THREAD

**Issue by saket** [google/accompanist#1708]
```kotlin
val systemUi = rememberSystemUiController()
systemUi.isSystemBarsVisible = zoomState.zoomFraction == 0f
```

If the above code is recomposed twice, the system bars play their entry animation twice. Can accompanist check whether the system bars are visible before actually setting the value?

**Comment by bentrengrove** [comment]
Unfortunately Accompanist SystemUIController has been deprecated and won't be supported going forwards. I am closing this issue. For more information please see our [update blog](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)
