### ISSUE TITLE
[Navigation Material] bottomSheet backstack not work

### ISSUE THREAD

**Issue by javacl** [google/accompanist#1712]
When upgrading `androidx.navigation:navigation-compose:2.6.0` to `androidx.navigation:navigation-compose:2.7.2` bottomSheet backstack does not work.

**Comment by Dikyashi** [comment]
Hi, i have got the same issue.

**Comment by ianhanniballake** [comment]
This was fixed in [d1b2afd3a9bd7923b13bbbc1b04d3ccc4ee7bdaf], which is part of [Accompanist 0.32.0](https://github.com/google/accompanist/releases/tag/v0.32.0) and higher. What version of Accompanist are you using?

**Comment by javacl** [comment]
> This was fixed in [[d1b2afd](https://github.com/google/accompanist/commit/d1b2afd3a9bd7923b13bbbc1b04d3ccc4ee7bdaf)], which is part of [Accompanist 0.32.0](https://github.com/google/accompanist/releases/tag/v0.32.0) and higher. What version of Accompanist are you using?

I am using the latest updated version. The problem is not the version, there is a bug.

**Comment by javacl** [comment]
> This was fixed in [[d1b2afd](https://github.com/google/accompanist/commit/d1b2afd3a9bd7923b13bbbc1b04d3ccc4ee7bdaf)], which is part of [Accompanist 0.32.0](https://github.com/google/accompanist/releases/tag/v0.32.0) and higher. What version of Accompanist are you using?

Thanks, fixed.
