### ISSUE TITLE
0.33.1-alpha is not compatible with compose 1.6.0-alpha06 or later

### ISSUE THREAD

**Issue by ZacSweers** [google/accompanist#1714]
All libraries using `mutableFloatStateOf()` and built against 1.6.0 alphas before alpha06 are broken when used with newer alphas due to an accidental breaking ABI change that was fixed in alpha06. As such, the latest current alpha is not usable with compose alpha06 and beyond.

Ref: https://issuetracker.google.com/issues/298810665

**Comment by bentrengrove** [comment]
Thanks for the report, Zac. I will do a release now

**Comment by ZacSweers** [comment]
Thanks!
