### ISSUE TITLE
[System UI Controller] Deprecation and Activity.enableEdgeToEdge

### ISSUE THREAD

**Issue by leinardi** [google/accompanist#1716]
I understand that, to properly deal with edge-to-edge and status/notification bar color changes we can now use the `Activity.enableEdgeToEdge` method, as explained [here](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1) but, what is the advised migration strategy for other features that System UI Controller is providing, like `SystemUiController.systemBarsBehavior` or `SystemUiController.isStatusBarVisible`?

**Comment by leinardi** [comment]
> comment or this will be closed in 5 days

**Comment by Mwhite69** [comment]
Help

**Comment by leinardi** [comment]
> comment or this will be closed in 5 days

**Comment by Digipom** [comment]
I'm having this issue too. Activity's edge-to-edge doesn't seem to have an equivalent to isNavigationBarContrastEnforced = false

**Comment by Digipom** [comment]
https://issuetracker.google.com/issues/324115590

**Comment by Digipom** [comment]
Workaround for isNavigationBarContrastEnforced: https://issuetracker.google.com/issues/324115590#comment3

**Comment by alexvanyo** [comment]
For the window flags that aren't controlled by the opinionated `enableEdgeToEdge`, you can read and write them directly using the relevant `Window`, or via the `WindowInsetsControllerCompat` for that `Window`.

For `isStatusBarVisible`, you should be able to use [`WindowInsets.areStatusBarsVisible`](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#(androidx.compose.foundation.layout.WindowInsets.Companion).areStatusBarsVisible())
