### ISSUE TITLE
Question: Dismiss bottom sheet programmatically?

### ISSUE THREAD

**Issue by JohanAlbrectsen** [google/accompanist#1717]
I can dismiss my bottom sheet by `navController.popBackStack()`, the issue is there's no animation. It's very rough and flashy, which is bad UX. Am I dismissing / popping the bottom sheet wrong?

**Comment by hrach** [comment]
Yes, this is not implemented properly. In PR for M3 I've posted our solution which does this properly: https://github.com/google/accompanist/pull/1543#discussion_r1143061950 - but you have to implement your own "destination" type to achieve this.

**Comment by ianhanniballake** [comment]
`navController.popBackStack()` is indeed how you dismiss a bottom sheet destination. However, Accompanist doesn't control what that looks like - it [just calls `sheetState.hide()`](https://github.com/google/accompanist/blob/1e2bb5b18cba8f9f48aebe0daed152a02274d99e/navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt#L171C25-L171C42).

If you can reproduce the same rough and flashy animation when hiding any bottom sheet that uses `ModalBottomSheetLayout`, you should [file an issue in the issue tracker](https://issuetracker.google.com/issues/new?component=742043&template=1590761).
