### ISSUE TITLE
[WebView] In Android 13, Compose Accompanist WebView is initially zoomed.

### ISSUE THREAD

**Issue by wilyyang** [google/accompanist#1718]
**Description**

In Android 13, Compose Accompanist WebView is initially zoomed. 
But after that, can't zoom. 

It operates independently of webviewzoom setting.

and only android 13 bug

**Steps to reproduce**

**Expected behavior** 

**Additional context**

**Comment by bentrengrove** [comment]
Thanks for the report.
Unfortunately, Accompanist WebView has been deprecated and we are no longer providing bug fixes for it.

**Comment by wilyyang** [comment]
Thank you for quick response.

**Comment by gaohomway** [comment]
What is the replacement after deprecation?

**Comment by wilyyang** [comment]
i replace "AndroidView {  WebView {  } }".

**Comment by KevinnZou** [comment]
> What is the replacement after deprecation?

@gaohomway https://github.com/KevinnZou/compose-webview

I have a forked version of it.
