### ISSUE TITLE
When view the dialog in Compose Immersive mode, the system bar appears.

### ISSUE THREAD

**Issue by reiarts** [google/accompanist#1720]
## Describe the bug

Since System UI Controller is deprecated, Immersive mode was implemented using WindowCompat and insertsController.

![image](https://github.com/google/accompanist/assets/12758553/3dff287e-97ed-4a62-8356-ca474b77fdf1)
![image](https://github.com/google/accompanist/assets/12758553/e9dc3e5c-3aaa-49bb-8f2e-6d9a6ebc1ef8)

When open the dialog, you will see the bottom system bar.

![image](https://github.com/google/accompanist/assets/12758553/72b570d5-7c4d-4684-a74b-b26226408e24)
![image](https://github.com/google/accompanist/assets/12758553/3199d7f2-78b6-4b8e-8798-a78a643dc71b)

Is there a way to hide the bottom system bar when the dialog is displayed?

## Environment:
 - Android OS version: Android 11
 - Device: Emulator or Samsung Galaxy
 - Accompanist version: 1.4.1

**Comment by Nek-12** [comment]
Because you hide the statusBars but not navigationBars or systemBars

**Comment by ianhanniballake** [comment]
You'll want to file an issue on [the issue tracker](https://issuetracker.google.com/issues/new?component=1070487&template=1667231) for any `Dialog` related issues you may run into since this behavior doesn't depend on Accompanist at all.
