### ISSUE TITLE
False positive deprecation message on pagerTabIndicatorOffset variant

### ISSUE THREAD

**Issue by PhilipDukhov** [google/accompanist#1739]
The deprecation message for the method indicates that the `androidx.compose.foundation.pager.PagerState` version should be used.

However, this applies to both versions of the modifier, including the one already using `androidx.compose.foundation.pager.PagerState`. The message seems to suggest an alternative that is essentially the same as the current implementation.

https://github.com/google/accompanist/blob/3af68c89ca6686b4b611f41e8d5e8cffe5f4b56e/pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt#L63-L73

**Comment by joshrvezy** [comment]
ive also noticed this as well

**Comment by bentrengrove** [comment]
This was deprecated on purpose. I will update the docs.

We won't be updating it going forwards so we recommend just copying the implementation to your own project.
