### ISSUE TITLE
onPermissionsResult isn't triggered on POST_NOTIFICATIONS permission request (API 33).

### ISSUE THREAD

**Issue by lupsyn** [google/accompanist#1740]
## Describe the bug
onPermissionsResult call back isn't triggered on android.permission.POST_NOTIFICATIONS on allow/deny (API 33)

## To Reproduce
Use a generic impl as the following one to trigger the permission request.

```
fun UiContent.toPermissionDialog(
    rationale: @Composable () -> Unit = { },
    onPermissionResultCallback: (allPermissionsGranted: Boolean) -> Unit = {},
) {
    val permissionState = rememberMultiplePermissionsState(
        permissions = permissions,
        onPermissionsResult = { permissionGrantMap ->
        
            onPermissionResultCallback(permissionGrantMap.values.all { it })
        }
    )

    if (permissionState.allPermissionsGranted) {
        onPermissionResultCallback(true)
    } else {
        if (permissionState.shouldShowRationale) {
            rationale.invoke()
        }
    
        LaunchedEffect(key1 = this) {
            permissionState.launchMultiplePermissionRequest()
        }
    }
}
```

## Expected behavior
onPermissionsResult should be triggered

## Environment:
 - Android OS version: [API 33]
 - Device: [every device]
 - Accompanist version: [0.33.2-alpha]

**Comment by chubecode** [comment]
how it's goin ?

**Comment by sprokipchyn** [comment]
same with CAMERA permission request. Is there any benefit of this library if I cannot get back any result of permission request?

**Comment by PrimoDev23** [comment]
This seems to work just fine for both permission types when using the attached code. Anyways the attached code is not following best practices, since you are calling a normal function in a compose context, which might result in calling it every recomposition.
You should prefer something like this

```kotlin
val permissionState = rememberMultiplePermissionsState(
      permissions = listOf(Manifest.permission.CAMERA),
      onPermissionsResult = { result ->
          val allGranted = result.values.all { it }
      
          if (allGranted) {
              println("GRANTED")
          } else {
              println("DENIED")
          }
      }
)
      
if (permissionState.shouldShowRationale) {
      Text(
          modifier = Modifier.clickable {
              permissionState.launchMultiplePermissionRequest()
          },
          text = "PLEASE OBI WAN, GIVE ME SOME POWER!"
      )
} else if (!permissionState.allPermissionsGranted) {
      LaunchedEffect(Unit) {
          permissionState.launchMultiplePermissionRequest()
      }
}
```

**Comment by sprokipchyn** [comment]
@PrimoDev23 I have the exact code and for some reason onPermissionsResult is not being called. So I see the standard permission popup (camera in my case). I click Allow for this time only and that's it: popup disappears, nothing happens, the callback is not triggered. Interesting fact: next time I call this code - permission is already granted and I can use the camera.

**Comment by PrimoDev23** [comment]
> @PrimoDev23 I have the exact code and for some reason onPermissionsResult is not being called. So I see the standard permission popup (camera in my case). I click Allow for this time only and that's it: popup disappears, nothing happens, the callback is not triggered. Interesting fact: next time I call this code - permission is already granted and I can use the camera.  

It's quite unclear why this is happening. Did you test this using the emulator? I tested this with API 34 and 33 and it worked just fine in both cases for me
