### ISSUE TITLE
Crash when using ProgressIndicator with `accompanist-permissions` 0.34.0

### ISSUE THREAD

**Issue by lukaszkalnik** [google/accompanist#1747]
## Describe the bug
There is a [crash](https://issuetracker.google.com/issues/322214617) in CircularProgressIndicator from `material3:1.1.2`, apparently caused by changes to `animations-core:1.6.0`.
`animations-core:1.6.0` is pulled into a project as a transitive dependency of `accompanist-permissions:0.34.0`, even though our project uses `animations-core:1.5.4` through `compose-bom:2023.10.01`.

## To Reproduce
1. Create project with dependencies
```
implementation(platform("androidx.compose:compose-bom:2023.10.01"))
implementation("androidx.compose.material3:material3")
implementation("com.google.accompanist:accompanist-permissions:0.34.0")
```
2. Use `CircularProgressIndicator` or `LinearProgressIndicator` without the `progress` argument (i.e. indefinite).
3. The app will crash, because `accompanist` pulled in the bugged `animations-core:1.6.0` transitive dependency.

Apparently the bug can be worked around by upgrading the `material3` dependency to `1.2.0-alpha10`, which accomodates the changes from `animations-core:1.6.0` correctly.

**Comment by bentrengrove** [comment]
This is a crash in Compose 1.6/BOM 2024.01.00. There is another release of Compose coming to address it.
