### ISSUE TITLE
[Navigation Material] Status bar not scrimmed when bottom sheet is shown

### ISSUE THREAD

**Issue by MarijanGazica** [google/accompanist#1751]
**Description**
When showing the bottom sheet with the code such as from the example, the bottom sheet scrim does not cover the status bar (such as in the screenshot). Apart from `edgeToEdge`, is there a good way of achieving the look that doesn't look like a bug?
<img height="500" alt="Screenshot 2024-02-06 at 10 59 07" src="https://github.com/google/accompanist/assets/12072773/6be6c177-49ff-4dfa-8505-b2673727ddc5">

**Steps to reproduce**
Run the [sample code](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/navigation/material/BottomSheetNavSample.kt)

**Expected behavior** 
<img height="512" alt="Screenshot 2024-02-06 at 13 14 55" src="https://github.com/google/accompanist/assets/12072773/3e7439a8-5283-4a73-9578-4ae56707c813">

The status bar is behind scrim, the same as when the native M3 bottom sheet is used:

**Comment by ianhanniballake** [comment]
With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: `androidx.compose.material:material-navigation`, which fully replaces Accompanist Navigation Material.

As such, we are closing all issues here on Accompanist and will be fully deprecating Accompanist Navigation Material in an upcoming release.

A number of issues were fixed as part of the migration, but if you're still seeing an issue, please [file an issue](https://issuetracker.google.com/issues/new?component=742043) with a sample project that reproduces your issue and the Material team will take a look.
