### ISSUE TITLE
[LazyColumn] scroll observation scope does not exist

### ISSUE THREAD

**Issue by BadKiko** [google/accompanist#1752]
## Describe the bug
In 0.35.0-alpha i get error java.lang.IllegalStateException: scroll observation scope does not exist if i use lazycolumn

## To Reproduce
1. Set accompanist 0.35.0-alpha
2. Use this code example or any another lazycolumn example:
    LazyColumn(){
        items(2){
            Text("fdssdf?")
        }
    }

## Expected behavior
Dont have a crash when i using lazycolumn :)

## Environment:
 - Android 14 Beta QPR3
 - Device: Pixel 6
 - Accompanist version: 0.35.0-alpha

**Comment by bentrengrove** [comment]
This doesn't look like an Accompanist issue. If this bug is still occuring, please file at https://goo.gle/compose-feedback

**Comment by BadKiko** [comment]
Idk, but I set 0.34.0 version of accompanist and this fix crash

**Comment by igorkos** [comment]
Having same issue reverted to 0.34.4  and no issues.
Probably becouse  0.35.0-alpha upgraded  Compose  to 1.7 and my project use 1.6.6
