### ISSUE TITLE
[Feature request] LazyTable with nested scrolling support

### ISSUE THREAD

**Issue by leinardi** [google/accompanist#1756]
Hey there, not sure if this is the right place to ask, but it'd be awesome if Accompanist could add a `LazyTable`. By that, I mean a `LazyLayout` that scrolls both horizontally and vertically.

There are some cool open-source versions out there like [this](https://github.com/oleksandrbalan/lazytable/) or [this](https://github.com/JackChen365/compose-table/tree/2188efb7e60ad1a1166c0dc0c5141628c998768a), but none of them nail nested scrolling. And we really need that for things like [collapsing TopAppBars](https://developer.android.com/reference/kotlin/androidx/compose/material3/TopAppBarDefaults#enterAlwaysScrollBehavior(androidx.compose.material3.TopAppBarState,kotlin.Function0,androidx.compose.animation.core.AnimationSpec,androidx.compose.animation.core.DecayAnimationSpec)) and [Pull to refresh](https://developer.android.com/reference/kotlin/androidx/compose/material/pullrefresh/package-summary). And trying to add nested scrolling to the existing libraries seems pretty complex, especially with all the fling gesture velocity calculations.

**Comment by bentrengrove** [comment]
Thanks for the request! I would submit this one at https://goo.gle/compose-feedback for a general Compose feature request.
