### ISSUE TITLE
[Navigation Material] Edge to edge jumping bug when migrating from 1.1.2 to 1.2.0.

### ISSUE THREAD

**Issue by Digipom** [google/accompanist#1759]
**Description**

On 0.35.0-alpha and 0.34.0, there is a "jumping" bug in edge to edge mode once migrating from Material 3 1.1.2 to 1.2.0.

**Steps to reproduce**

Please see the attached project.
[edge2edgebug.zip](https://github.com/google/accompanist/files/14462256/edge2edgebug.zip)

**Expected behavior** 

See the videos:

https://github.com/google/accompanist/assets/2005192/c648046b-479a-4f98-b804-d5228f787224

https://github.com/google/accompanist/assets/2005192/2d2907da-2cde-4b72-8ace-69d4174161e1

**Additional context**
https://issuetracker.google.com/issues/325960325

**Comment by ianhanniballake** [comment]
With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: `androidx.compose.material:material-navigation`, which fully replaces Accompanist Navigation Material.

As such, we are closing all issues here on Accompanist and will be fully deprecating Accompanist Navigation Material in an upcoming release.

A number of issues were fixed as part of the migration, but if you're still seeing an issue, please [file an issue](https://issuetracker.google.com/issues/new?component=742043) with a sample project that reproduces your issue and the Material team will take a look.
