### ISSUE TITLE
accompanist-drawablepainter: PictureDrawable doesn't scale

### ISSUE THREAD

**Issue by theojarrus** [google/accompanist#1766]
## Describe the bug
PictureDrawable displayed using Compose Image and Accompanist DrawablePainter doesn't scale

## To Reproduce
1. Create PictureDrawable
```kotlin
val picture = Picture()
val pictureCanvas = picture.beginRecording(100, 100)
pictureCanvas.drawCircle(50f, 50f, 50f, Paint())
picture.endRecording()
val drawable = PictureDrawable(picture)
``` 
2. Show using Compose Image and Accompanist DrawablePainter
```kotlin
Image(
   painter = rememberDrawablePainter(drawable),
   contentDescription = null,
   contentScale = ContentScale.FillHeight,
   modifier = Modifier.height(200.dp).border(2.dp, color = Color.Cyan)
)
``` 
3. See the image is not scaled

## Expected behavior
Image scales depending on available size and scale strategy

## Screenshots
| Actual | Expected (fixed using canvas#scale) |
|--------|--------|
| <img width="364" alt="Screenshot 2024-04-01 at 16 30 03" src="https://github.com/google/accompanist/assets/39097168/e6ce58c5-bbe6-42c5-a752-9c3a086a28e6"> | <img width="360" alt="Screenshot 2024-04-01 at 16 30 22" src="https://github.com/google/accompanist/assets/39097168/752f2207-6cd7-4bcc-aa56-3b2755893201"> |

## Environment
 - Android OS version: API 34
 - Device: Emulator, Google Pixel 4
 - Accompanist version: 0.34.0

#### Thoughts about fixing
In search of the reason why my image does not scale, I deepened into the source code. I found, that picture receives size in Picture#beginRecording, then getting long value from Picture#nativeBeginRecording, which also receives picture size, and saves this long value to PictureCanvas. After that, inside Picture#draw, which is called to draw picture on some canvas, Picture#nativeDraw is called. Don't know what magic happens then, but as the result picture is rendered using size recieved in Picture#beginRecording and not Drawable#setBounds. I managed to achieve the desired result using Canvas#scale, I don't know if that can cause performance problems, but at least it works. So, it can be fixed by overwriting DrawablePainter#onDraw for PictureDrawable, here's the example of working code:
```kotlin
// Create canvas with size bigger than picture size
Canvas(Modifier.height(200.dp).width(200.dp).border(2.dp, color = Color.Cyan)) {
   // Create simple PictureDrawable
   val picture = Picture()
   val pictureCanvas = picture.beginRecording(100, 100)
   pictureCanvas.drawCircle(50f, 50f, 50f, Paint())
   picture.endRecording()
   val drawable = PictureDrawable(picture)
   // Render PictureDrawable on canvas
   drawIntoCanvas { canvas ->
      // Set PictureDrawable bounds
      drawable.setBounds(0, 0, size.width.roundToInt(), size.height.roundToInt())
      // Scale canvas
      val scalex = size.width / drawable.intrinsicWidth
      val scaley = size.height / drawable.intrinsicHeight
      canvas.scale(scalex, scaley)
      // Draw PictureDrawable
      drawable.draw(canvas.nativeCanvas)
   }
}
``` 

#### Why found this bug
I'm writing library with runtime image generation, it uses Picture to render graphics and pass through app. As the result I want to show it somewhere using Compose Image, so I used accompanist-drawablepainter, but faced this issue.

**Comment by theojarrus** [comment]
@bentrengrove check this issue please

**Comment by theojarrus** [comment]
@bentrengrove

**Comment by af-llp** [comment]
@theojarrus I already created a PR for this https://github.com/google/accompanist/pull/1771
So basically it just needs review and merge

**Comment by bentrengrove** [comment]
I mentioned this in the PR, but it is up to the drawable implementation how it scales, not the painter. So in this example you shouldn't be using fixed coords for defining your picture, you should be using the sizing information.

Something like:

```
val halfWidth = width/2f
val pictureCanvas = picture.beginRecording(width, height)
pictureCanvas.drawCircle(halfWidth, halfWidth, halfWidth, Paint())
```

**Comment by theojarrus** [comment]
@bentrengrove
