### ISSUE TITLE
How do I remove the Navigation Bars space from the Keyboard?

### ISSUE THREAD

**Issue by jetberrocal** [google/accompanist#1772]
I have the same problem as [post:There's a space between content and keyboard when using imePadding](https://github.com/google/accompanist/issues/644).

The solution proposed to use navigationBarsWithImePadding only instead of imePadding & navigationBarsPadding no longer is available for current Compose version (2024).

How do I remove the Navigation Bars space from the Keyboard?

**Comment by felixlix45** [comment]
I got the same issue, did you already solved the issue?

**Comment by alexvanyo** [comment]
Insets support in accompanist has been replaced by upstream support. The equivalent to `Modifier.navigationBarsWithImePadding()` is `Modifier.navigationBarsPadding().imePadding()` using consumption, as described in the [migration guide](https://google.github.io/accompanist/insets/#migration-table).

**Comment by jetberrocal** [comment]
Actually that didn't work for me. It was worst, because it added more space.
