### ISSUE TITLE
Missing/incorrect migration documentation for insets-ui

### ISSUE THREAD

**Issue by adesentenac** [google/accompanist#1775]
The [migration documentation for insets](https://google.github.io/accompanist/insets/#migration-steps) still mentions:
` 6. Continue using the non-deprecated insets-ui for now.`
which isn't the case anymore, since insets-ui is deprecated.

And there is no migration guide for the composables that were available in insets-ui.

**Comment by alexvanyo** [comment]
This documentation is indeed out of date, thanks for reporting the issue.

For Material 2, opt-in inset support is available on many components, similar to the opt-out inset support available for Material 3 components: https://developer.android.com/develop/ui/compose/layouts/insets#material3-components
