### ISSUE TITLE
[Permissions] Not seeing permission request dialog

### ISSUE THREAD

**Issue by fluxxion82** [google/accompanist#1776]
**Description**
I'm not seeing the permission request dialog when invoking "launchMultiplePermissionRequest()". I'm not sure if I'm doing something wrong or if this is a bug (I'm guessing the former). `launchPermissionRequest() ` also doesn't work for me.

**Steps to reproduce**
Create new android project.
add accompanist permissions,
copy paste RequestMultiplePermissionsSample code.

repro project: https://github.com/fluxxion82/permission_test

**Expected behavior** 
User should see the permission request dialog.

**Additional context**
I've tested on a Pixel 4XL running Android 13, Pixel 8 running Android 14 and an emulated Pixel 7 running 14.

**Comment by ianhanniballake** [comment]
The [`READ_EXTERNAL_STORAGE`](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) and [`WRITE_EXTERNAL_STORAGE`](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE) permissions do not have any effect on Android 13+ devices. As explained in the [Android 13 behavior changes](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions), you need to use the granular media permissions if you need any permissions at all for your use case (see the [Storage Permissions page](https://developer.android.com/training/data-storage/shared/media#storage-permission) for more details).

Therefore you'd never see any permission request dialog for these permissions, whether you are using Accompanist or not.
