### ISSUE TITLE
BottomSheetState's progress on BottomSheetScaffold

### ISSUE THREAD

**Issue by honeywhisperer** [google/accompanist#1782]
## Describe the bug
`progress` value from `BottomSheetState` on `BottomSheetScaffold` is being continuously updating when bottom sheet is changing state from expanded to collapsed; while dragging bottom sheet to expand, `progress` only shows `1.0` once bottom sheet is fully expanded.

## To Reproduce (if applicable)
0. Add logger which will show the current `progress` value;
1. Go to page which has BottomSheetScaffold structure; bottom sheet is visible in both expanded and collapsed state;
2. Click on the bottom sheet while it is collapsed and drag it up with intention to expand it;
3. Observe the progress in the logger.
4. See error: 1.0 is shown on ly when bottom sheet is fully expanded, no intermediate values were provided.

## Expected behavior (if applicable)
When Bottom sheet is expanding, provide the same behavior as when it is collapsing -> show continuous updates of the progress value.

## Screenshots? (if applicable)
When expanding:
![image](https://github.com/google/accompanist/assets/71873523/28afa4bb-4daf-4c2e-8495-521b9979f0b6)

When collapsing:
![image](https://github.com/google/accompanist/assets/71873523/4165de9c-7d75-47a5-b0da-1935293e961b)

## Environment: (if applicable)
 - Android OS version: 14
 - Device: Emulator
 - Material lib version: 1.11.0

## Additional context
n/a

**Comment by bentrengrove** [comment]
Navigation material has been deprecated in Accompanist as the functionality has been moved to the main Compose libraries. If this bug persists there I suggest filing it at [goo.gle/compose-feedback]()
