### ISSUE TITLE
Supporting for AnimatedStateListDrawable

### ISSUE THREAD

**Issue by heesung6701** [google/accompanist#1784]
**Description**

with drawable painter, it doesn't support AnimatedStateListDrawable because transition is not working.

**Steps to reproduce**

1. use drawable painter with AnimatedStateListDrawable
2. GUI will be updated if drawable state updated but transition animation is not working.

**Expected behavior** 

support AnimatedStateListDrawable fully

**Additional context**

We hope that drawablePainter can support AnimatedStateListDrawable.

**Comment by bentrengrove** [comment]
Hello

We aren't planning to support `AnimatedStateListDrawable` unfortunately. We believe the Compose APIs provide a much better API for it's use case so we recommend you migrate to that instead.
