### ISSUE TITLE
Placeholder Library composed to Node migration?

### ISSUE THREAD

**Issue by rosamerinoclaros** [google/accompanist#1785]
The Placeholder library is deprecated, and it has been recommended to fork and customize it according to our needs. I have done this, but encountered an issue where our compose rules linter flagged Modifier.placeholder for using a composed block instead of a Node.

I attempted a migration, but it is very complex due to ten variables being remembered inside the composed block.

What are the plans for the Placeholder Modifier? Is Google handling this migration internally? Could you provide guidance on how we can accomplish this migration?

Thanks in advance!

**Comment by fargus9** [comment]
The library referenced as the replacement is only in the wear version of compose as far as I can tell, so the grounds for deprecating this seem invalid.

**Comment by bentrengrove** [comment]
We won't be handling the migration of placeholder unfortunately, for the reasons detailed [here](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)

If you are fine with the caveats listed and it works for your use case, I would suggest implementing a composable modifier factory as detailed in the [docs](https://developer.android.com/develop/ui/compose/custom-modifiers#create_a_custom_modifier_using_a_composable_modifier_factory). This will be a much easier migration.
