### ISSUE TITLE
[Contribution Offer] List item exit animations

### ISSUE THREAD

**Issue by distinctdan** [google/accompanist#1788]
Hi, I've developed a composable to keep items in a list until their exit animation finishes, and I've gotten permission to open source it if Accompanist would be interested in it. The technique works by computing the difference between the old list and the new list, then using that sequence of operations to figure out where removed items would go. This allows us to add them back in at the correct spot until their exit animation finishes. The diff is calculated using this library [Difference](https://andrewbailey.dev/post/2020/07/06/difference). Now, it's my understanding that the Compose team is working on list animations, so I expect this component would eventually be deprecated once they complete that work, but I think it could be useful in the meantime. So, is this something that Accompanist would potentially be interested in? I would be available to help with any needed updates.

Features include:
 - Works with any kind of animation.
 - Works with non-lazy lists.
 - Works with SwipeToDismiss by using a helper composable `rememberItemDismissState`.
 - Comprehensive tests. I've tested a lot of corner cases to make sure it works correctly, like if an item is re-added to the list while animation is in progress.

Example usage:
```kotlin
val listState = rememberLazyListState()
val (items, visStates) = rememberItemVisibility(
    items = state.value.items,
    getItemID = { it.id },
    lazyListState = listState,
)

LazyColumn(
    state = listState,
) {
    itemsIndexed(
        items = items.value,
        key = { _, item -> item.id },
    ) { index, item ->
        AnimatedVisibility(visibleState = visStates.value[index].value) {
            ItemCard(item = item)
        }
    }
}
```

Function signature:
```kotlin
/**
 * Creates visibility states to allow entrance and exit animations for list items. Keeps items in the
 * list until their exit animation finishes. Offscreen item animations are immediately finished.
 */
@Composable
fun <T, ItemID> rememberItemVisibility(
    /**
     * The list of items to be animated.
     */
    items: List<T>,
    /**
     * Must return a unique id for the item.
     */
    getItemID: (item: T) -> ItemID,
    /**
     * If a LazyListState is passed, it will be used to determine whether entering or exiting items
     * are visible.
     */
    lazyListState: LazyListState? = null,
    /**
     * The index of the first animated item within the lazy list. There may be other items in the
     * list above the animated items like headers. If so, we need to know about it so that we can
     * offset the visible indices from LazyList's layout.
     */
    itemsStartIndex: Int = 0,
    /**
     * Keys that will invalidate the cache if they change, just like a normal `remember(key1, key2)`
     */
    vararg rememberKeys: Any,
): RememberItemVisibilityResult<T>

@Immutable
data class RememberItemVisibilityResult<T> (
    /**
     * The items, but with exiting items kept in the list.
     */
    val animatedItems: ImmutableList<T>,
    /**
     * List of visibility states, corresponding to AnimatedItems. Each transition state is wrapped
     * in a State so that we can update it after the fact if necessary. This happens when an item
     * is rendered offscreen and we have to wait for LazyList to layout before we determine
     * whether to animate the item. We default to starting an animation, but if it turns out that
     * the item is offscreen, we'll replace that transition state with one that's already visible.
     */
    val visibilityStates: ImmutableList<VisState>,
)
```

**Comment by bentrengrove** [comment]
Hey this sounds like an awesome library! We added list animations in Compose 1.7 which is currently in beta so we wouldn't be able to support this in accompanist unfortunately. We also aren't accepting new libraries in general because we want the third party library ecosystem to grow. I encourage you to release it under your own repository!

Thanks for opening the request

**Comment by distinctdan** [comment]
Thanks Ben, sorry to hear that, but I do appreciate the response. For the list animations in 1.7, I'm excited to see some progress on that, but my understanding was that they're still limited to just fade in/out. Would you happen to know when they'll have support for any type of animation?
