### ISSUE TITLE
[Idea] New Pager library

### ISSUE THREAD

**Issue by chrisbanes** [google/accompanist#189]
This would be take the [`Pager`](https://github.com/android/compose-samples/blob/master/Jetcaster/app/src/main/java/com/example/jetcaster/util/Pager.kt) component from Jetcaster, and fix the issues around touch handling, flinging, etc.

It may even be a whole new implementation wrapping `LazyRow`.

**Comment by sjmueller** [comment]
Hi @chrisbanes, any progress on the pager or should we continue modifying the Jetcaster one?

**Comment by chrisbanes** [comment]
> Hi @chrisbanes, any progress on the pager or should we continue modifying the Jetcaster one?

Yep, see #209
