### ISSUE TITLE
[Idea] New SwipeRefresh library

### ISSUE THREAD

**Issue by ricknout** [google/accompanist#192]
This would take the [SwipeRefreshLayout](https://github.com/android/compose-samples/blob/main/JetNews/app/src/main/java/com/example/jetnews/ui/SwipeToRefresh.kt) component from JetNews, and fix the issues around state->event trampoline, nested scrolling, etc.

Things to note:
- There's an [issue](https://issuetracker.google.com/issues/160576011) for this to be added to Compose Material but there's currently no progress
- Technically swipe refresh isn't in the current Material Design spec, hence why we have [`androidx.swiperefreshlayout`](https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout)

**Comment by JustinBis** [comment]
@ricknout The linked issue doesn't appear to be public.

Considering its prevalence, wouldn't this be better to include as part of the official Compose Material UI rather than as part of Accompanist?

**Comment by ricknout** [comment]
> @ricknout The linked issue doesn't appear to be public.
> 
> Considering its prevalence, wouldn't this be better to include as part of the official Compose Material UI rather than as part of Accompanist?

Ah sorry about the internal issue, although there's not much more to it than what you see here.

The spec at material.io/components doesn't actually include a swipe refresh component. This is also why there's an `androidx.swiperefreshlayout` library at the moment.
