### ISSUE TITLE
Pluggable Fade Animation

### ISSUE THREAD

**Issue by sanvean** [google/accompanist#193]
Hi,

Thanks for the great library! 

In a future release would it be possible to allow for an easy override of the painter.fadeIn animation in MaterialImageLoader to allow for alternate fade animations whilst keeping access to the current built-in logic around skipping fades if the image is loaded from memory?

Thanks

**Comment by chrisbanes** [comment]
Thanks for the request! With the new Compose transition APIs, I'm currently thinking about how we can better support this use case.

**Comment by chrisbanes** [comment]
With #321 about to land, I'm going to close this. The API is now just a custom painter, which means that apps can implementation whatever transition/animation that they want!

**Comment by sanvean** [comment]
Thanks Chris sounds 👌
