### ISSUE TITLE
[Idea] Provide inset aware layouts

### ISSUE THREAD

**Issue by chrisbanes** [google/accompanist#207]
We could make it easier to support insets, through a custom `Scaffold` implementation, as well making `InsetAwareTopAppBar` a real thing ™️ 

Candidates:

- `Scaffold`
- `TopAppBar`
- `BottomNavigation`
- `ModalDrawerLayout`
- `BottomAppBar` (less priority)

**Comment by dovahkiin98** [comment]
I don't know if adding custom composables of already existing ones is a good idea. That would require alot of maintanance in the future. If `Scaffold` is changed, so will `InsetAwareScaffold` have to change.

Wouldn't a simple modifier that applies the insets to the any Composable? Something like `.padding(WindowInsets)` or `applyWindowInsets()`

**Comment by chrisbanes** [comment]
> If `Scaffold` is changed, so will `InsetAwareScaffold` have to change.

Compose’s API is now API stable, so there won’t be any API changes. This library isn’t designed to live forever either.

> Wouldn't a simple modifier that applies the insets to the any Composable? Something like `.padding(WindowInsets)` or `applyWindowInsets()`

We already have that: https://google.github.io/accompanist/insets/

**Comment by dovahkiin98** [comment]
From what I remember in Flutter, only the `Scaffold` was insets aware, and it passed those insets to its children. So maybe that's how it should be done in here as well?

**Comment by chrisbanes** [comment]
Sure, but we're not copying Flutter, or being limited to what Flutter provides.

**Comment by Omico** [comment]
Hi, I made a very early version of InsetAwareScaffold.
```
class InsetAwareState(
    var topBarSize: IntSize = IntSize.Zero,
    var bottomBarSize: IntSize = IntSize.Zero,
)

@Composable
fun rememberInsetAwareState(): InsetAwareState = remember { InsetAwareState() }

fun Modifier.padding(
    insetAwareState: InsetAwareState,
    additionalTop: Dp = 0.dp,
    additionalBottom: Dp = 0.dp,
) = composed {
    padding(
        LocalWindowInsets.current.systemBars.toPaddingValues(
            top = false,
            additionalTop = with(LocalDensity.current) { insetAwareState.topBarSize.height.toDp() + additionalTop },
            additionalBottom = with(LocalDensity.current) { insetAwareState.bottomBarSize.height.toDp() + additionalBottom },
        )
    )
}

@Composable
fun InsetAwareScaffold(
    modifier: Modifier = Modifier,
    insetAwareState: InsetAwareState = rememberInsetAwareState(),
    scaffoldState: ScaffoldState = rememberScaffoldState(),
    topBar: @Composable () -> Unit = {},
    bottomBar: @Composable () -> Unit = {},
    content: @Composable (PaddingValues) -> Unit = {},
) {
    Scaffold(
        modifier = modifier,
        scaffoldState = scaffoldState,
        bottomBar = {
            Box(
                modifier = Modifier
                    .onSizeChanged { insetAwareState.bottomBarSize = it },
                content = { bottomBar() }
            )
        },
        content = { innerPadding ->
            content(innerPadding)
            Box(
                modifier = Modifier
                    .onSizeChanged { insetAwareState.topBarSize = it },
                content = { topBar() }
            )
        }
    )
}
```
### Usage

```
  val insetAwareState = rememberInsetAwareState()
  InsetAwareScaffold(
        modifier = Modifier.fillMaxSize(),
        insetAwareState = insetAwareState,
        topBar = { TopAppBar() }
    ) {
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(insetAwareState = insetAwareState)
        ) {
        ..................
        }
    }
```

**Comment by moffpage** [comment]
Please no, that feels like adding unnecessary bloat (a little rude, excuse me). I don't want to have many theme / styles / layout implementations, that's a past thing which in my opinion should be

**Comment by chrisbanes** [comment]
> Please no, that feels like adding unnecessary bloat (a little rude, excuse me).

I get not wanting to bloat the main library, but this would be in an optional `insets-layouts` library (if we did it).

**Comment by moffpage** [comment]
Oh, that’d be nice for some people, my guess.

**Comment by moffpage** [comment]
The issue is still relevant.

**Comment by moffpage** [comment]
Oh, thank you!
