### ISSUE TITLE
[Insets] How to use navigationBarsWithImePadding with Column verticalScroll? 

### ISSUE THREAD

**Issue by radzio** [google/accompanist#210]
Hello! 

What is the best way to handle `Column` `verticalScroll` and `navigationBarsWithImePadding`? 

I have layout like this: 
<img src="https://user-images.githubusercontent.com/469111/108875356-62d16d80-75fd-11eb-924c-bbb6100457e5.png" width="30%" /> 

When keyboard is shown it looks like this:

<img src="https://user-images.githubusercontent.com/469111/108875458-80063c00-75fd-11eb-8727-288eece1e52f.png" width="30%" /> 

What I want to achieve (automatically scroll to given or focused composable when IME is shown) : 

<img src="https://user-images.githubusercontent.com/469111/108875517-914f4880-75fd-11eb-896c-3922929dbabc.png" width="30%"/> 

I was trying to play with `scrollState.smoothScrollTo` but without any reliable success :(. @chrisbanes  do you have any recommendations or best ways of doing so? 

Code:

```
class ExampleFragment: Fragment() {
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View = ComposeView(requireContext()).apply {
        layoutParams = ViewGroup.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.MATCH_PARENT
        )

        val windowInsets = ViewWindowInsetObserver(this).start(consumeWindowInsets = false)

        setContent {
            Providers(
                LocalWindowInsets provides windowInsets
            ) {

                val scrollState = rememberScrollState()
                var textValue = remember { TextFieldValue() }

                Column(
                    modifier = Modifier.fillMaxSize(1F)
                        .statusBarsPadding()
                        .navigationBarsWithImePadding()
                        .verticalScroll(scrollState)
                        .padding(horizontal = 16.dp),
                    verticalArrangement = Arrangement.Top,
                ) {

                    Text(
                        text = "Hi there ❤",
                        fontSize = 46.sp,
                        style = TextStyle(
                            fontWeight = FontWeight.Bold,
                            textAlign = TextAlign.Center
                        ),
                        modifier = Modifier.fillMaxWidth(1F)
                    )

                    Spacer(modifier = Modifier.height(250.dp))

                    Text(
                        text = "More content",
                        fontSize = 20.sp,
                        style = TextStyle(
                            fontWeight = FontWeight.Bold,
                            textAlign = TextAlign.Center
                        ),
                        modifier = Modifier.fillMaxWidth(1F)
                    )

                    Text(
                        text = "More content #2",
                        fontSize = 20.sp,
                        style = TextStyle(
                            fontWeight = FontWeight.Bold,
                            textAlign = TextAlign.Center
                        ),
                        modifier = Modifier.fillMaxWidth(1F)
                    )

                    TextField(value = textValue, onValueChange = { textValue = it })
                }
            }
        }
    }
}
```

**Comment by chrisbanes** [comment]
Hmmm, using `smoothScrollToItem()` is probably the right thing here. I don't think this will ever be automatic, since the `Modifier` has no idea about any other composables around it.

I think we might be missing a callback from the modifier to know _when_ to call `smoothScrollToItem` though.

FYI, I think you'll have better luck with laying out from the bottom:

``` kotlin
Column(
    modifier = Modifier
        // other modifiers
        .verticalScroll(scrollState, reverseScrolling = true),
    verticalArrangement = Arrangement.Bottom,
)
```

Laying out from the bottom means that the scroll position should remain the same as the `Column` changes size.

**Comment by qrezet** [comment]
Hi, I have an even problematic scenario about managing the same thing. 

The problem is that, my `TextField`s are inside `Column` which is inside `LazyColumn`'s `item()`.

I could call `LazyState.animateScrollToItem()` but I don't know how to get the correct `Offset` to properly position the focused `TextField`.

Do you guys have any idea how to do this?

**Comment by chrisbanes** [comment]
I don't think this is supported yet (but I'll ask the team later). I just saw that someone raised this [bug](https://issuetracker.google.com/181291788) which is very related.

**Comment by qrezet** [comment]
Thanks @chrisbanes

**Comment by radzio** [comment]
@qrezet  have you find any solution or workaround to your problem

**Comment by chrisbanes** [comment]
The recent `RelocationRequester` API should allow us to do this. Just spent 10 mins and come up with this:

``` kotlin
var textField by remember { mutableStateOf(TextFieldValue()) }

val imeInsets = LocalWindowInsets.current.ime
var focusState by remember { mutableStateOf<FocusState?>(null) }
val relocationRequester = remember { RelocationRequester() }

LaunchedEffect(
    imeInsets.isVisible,
    imeInsets.animationInProgress,
    focusState,
    relocationRequester
) {
    if (imeInsets.isVisible &&
        !imeInsets.animationInProgress &&
        focusState.value?.isFocused == true) {
        relocationRequester.bringIntoView()
    }
}

TextField(
    value = textField,
    onValueChange = { textField = it },
    modifier = Modifier
        .onFocusChanged { focusState = it }
        .relocationRequester(relocationRequester)
)
```

It's not perfect, but it should form the basis of a solution.

**Comment by burhankhanzada** [comment]
it doesn't work for me

**Comment by b95505017** [comment]
@chrisbanes It works with latest 1.0.0, but no effect with latest snapshot version. 😢

**Comment by chrisbanes** [comment]
I think something is currently broken with `RelocationRequester` & `LazyColumn`. Not much we can do at this point.
