### ISSUE TITLE
[suggestion] handle sized images

### ISSUE THREAD

**Issue by FrancoisBlavoet** [google/accompanist#224]
Hello there,

I am trying to use Accompanist in my project. However I am encountering a major hurdle : one of my use cases involves this config :
`MyCustomWidget { Box(modifier.size(40.dp) { CoilImage } ... }`

Where it gets hairy though, is that MyCustomWidget needs to make some intrinsic measurements in order to layout itself. So it's root node is a `Layout` which will call `min/maxIntrinsicWidth/Height` on its children. 
That's not a super uncommon use case, any widget which would have needed 2 layout passes (or more) in the legacy layouting system will very probably do the same here. 
The issue is that Accompanist uses `SubComposableLayout` (via `BoxWithConstraints`) internally for its image loading integration. 
And `SubComposableLayout` does not support Intrinsic measurements at the moment.  

What are your thoughts on supporting this use case in Accompanist ? 

Here I already have a known size for my widget (40.dp) and I just want the image to scale to fit that space, so I don't think subcomposition is actually needed (from what I can gather it is necessary for unknown image and widget sizes).

**Comment by chrisbanes** [comment]
Yep, makes sense. This is already being investigated in #220.

**Comment by FrancoisBlavoet** [comment]
Oh awesome, I did not realize this was already worked on. I can scratch my plans then (I started drafting how to just support my use case, but getting rid of BoxWithConstraints entirely is even better), I am happy to wait for Accompanist to support this.
Thanks for the quick answer !

**Comment by ColtonIdle** [comment]
@FrancoisBlavoet I worked around this by just setting requiredWidth and requiredHeight and it seemed to work as intended.

**Comment by FrancoisBlavoet** [comment]
@ColtonIdle thanks for the suggestion ! I will need to revisit this for beta 03 but some image sizes were crashing on me even with `requiredSize`

**Comment by ColtonIdle** [comment]
Interesting. Yeah, maybe chris banes knows better, but I've been using requiredSize and this for sizing images


   ```
 CoilImage(
        data = "",
        contentDescription = "",
        fadeIn = false,
        modifier = modifier,
        requestBuilder = { size: IntSize ->
            val builder = URLBuilder("cloudinary.com")
            val params: MutableMap<String, String> = HashMap()
            params["w"] = size.width.toString()
            params["h"] = size.height.toString()
            val cloudinaryUrl = builder.createURL(imageUrl, params)
            data(cloudinaryUrl)
        }
    )
```

So basically inside of CoilImage I get the width and height and thats what I use to generate a cloudinary (image resizer) url and I get an image of the exact size. I'm not sure if this is necessarily what you want (now that I re-read your question) but maybe it is. Again, maybe @chrisbanes knows whether my code above is actually incorrect for sizing images

**Comment by hlnstepanova** [comment]
Hi, has this been already modified? I have a question here that seems to be relevant to this issue https://stackoverflow.com/questions/67303271/jetpack-compose-intrinsicmeasurements-not-supported-loading-with-accompanist-co

**Comment by chrisbanes** [comment]
Commented on the question 😄
