### ISSUE TITLE
[Insets] Missing WindowInsets.navigationBarsWithIme

### ISSUE THREAD

**Issue by gustavkarlsson** [google/accompanist#239]
`Modifier.navigationBarsWithImePadding()` is extremely helpful, but there does not appear to exist any equivalent for `WindowInsets`.

To get correct content padding for my `LazyColumn` I had to do this to work around it:
```kotlin
    val imeInsets = LocalWindowInsets.current.ime
    val navigationBarsInsets = LocalWindowInsets.current.navigationBars
    val insets = if (imeInsets.isVisible) {
        imeInsets
    } else navigationBarsInsets
    LazyColumn(contentPadding = insets.toPaddingValues()) {
        // Content
    }
```
Or, for a reusable version:
```kotlin
val WindowInsets.navigationBarsWithIme: Insets
    get() = if (ime.isVisible) ime else navigationBars
```

**Comment by chrisbanes** [comment]
If you look at how `navigationBarsWithImePadding()`, it's actually just:

``` kotlin
val navigationBarsWithIme = LocalWindowInsets.current.let { 
    it.ime.coerceEachDimensionAtLeast(it.navigationBars)
}
```

[`coerceEachDimensionAtLeast()`](https://github.com/google/accompanist/blob/cd7d4993deed83825491cc7aafa620cbbf275684/insets/src/main/java/dev/chrisbanes/accompanist/insets/Insets.kt#L506) is currently an internal function, but we could make it public.

**Comment by gustavkarlsson** [comment]
That would make it easier, yeah. I just thought since `navigationBarsWithImePadding` exists as a modifier, adding an equivalent on `LocalWindowInsets.current` would make it consistent, but I might be misunderstanding things here :)

Adding own extension property is easy enough.

**Comment by chrisbanes** [comment]
The modifiers are different as it's difficult to compose custom logic in them (although still possible). They are also designed to cover common use-cases.

Reading `LocalWindowInsets` is definitely in the 'doing it manually' territory so I think the linked PR is fine. Similarly, I don't want to start creating combinations of insets in `WindowInsets` as it will lead to a combinational explosion.
