### ISSUE TITLE
AndroidX other Layouts

### ISSUE THREAD

**Issue by dovahkiin98** [google/accompanist#251]
I'm happy to see that Pager is in this repo. But there are other Views that I've been missing in Compose. Such as SwipeRefreshLayout and StaggeredGrid.

I know that both exist in the Jetpack Compose Samples. But here are the issues I noticed in each :
1- SwipeRefreshLayout doesn't keep the drawable up, you can swipe it back up.
2- StaggeredGrid is not Lazy, meaning for large data lists it will become slow.

What is the possiblity of adding these Composables to this repo?

**Comment by chrisbanes** [comment]
- `SwipeRefreshLayout` is covered by #192
- There are no plans for `StaggeredGrid`, and I think this would be better served as a [feature request](http://goo.gle/compose-feedback) for `VerticalLazyGrid` in Compose. That said @nickbutcher did create an implementation of this [here](https://github.com/android/compose-samples/blob/main/Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Grid.kt).
