### ISSUE TITLE
[Pager] Make item alignment configurable

### ISSUE THREAD

**Issue by RinOrz** [google/accompanist#255]
The item placement focus in the **Pager** should be configurable, not just centered, just like the focus of the **Google Play Store** list is on the left
![image](https://user-images.githubusercontent.com/58068445/111468398-78e7cf00-8760-11eb-9378-d8f5285163f3.png)

**Comment by chrisbanes** [comment]
I do plan on adding alignment to Pager, __but__ the example you show isn't a pager. The example from Google Play is a `LazyRow` with some snapping (which doesn't exist yet).

**Comment by RinOrz** [comment]
> **but** the example you show isn't a pager
Thanks for your correction

> `LazyRow` with some snapping (which doesn't exist yet).
Sounds very exciting!

**Comment by chrisbanes** [comment]
No problem! I didn't mean that to sound like a correction, just trying to say that `HorizontalPager` won't support that use case.

**Comment by RinOrz** [comment]
Yes, I understand what you mean, thank you for your excellent work~
