### ISSUE TITLE
[Pager] Should support the transition configuration between each page

### ISSUE THREAD

**Issue by RinOrz** [google/accompanist#256]
In fact, in the prototype provided by the designer, the switching between pages should have transition animations, and it will even be very complicated🙃 . So I hope that **Compose Pager** can have a better solution than **ViewPager2**

[![](https://drive.google.com/uc?export=download&id=0BxPO_UeS7wScVEZRbk5LaFVzUzQ)](https://dribbble.com/shots/2832006-Cinema-App)

**Comment by chrisbanes** [comment]
I'm open to ideas on this, but I think `PagerState` should expose everything you need to implement the carousel behavior.

I'll hack up a simple animation sample and see how it goes.

**Comment by RinOrz** [comment]
Like **Tab Indicator** widget, I think they should be called when the pager switching

**Comment by RinOrz** [comment]
ahhhh
