### ISSUE TITLE
navigationBarsWithImePadding not working correctly when child is wrapped with BoxWithConstraints

### ISSUE THREAD

**Issue by radzio** [google/accompanist#261]
## Describe the bug

I have a scrollable column 

```
Column(
    modifier = Modifier
        .fillMaxSize(1F)
        .statusBarsPadding()
        .navigationBarsWithImePadding()
        .verticalScroll(state = scrollState, reverseScrolling = true)
        .padding(horizontal = 16.dp),
    verticalArrangement = Arrangement.Top,
) {

// children 

}
```

When the keyboard is shown everything is scrolled to the top which is expected behavior. 

But when one of the children is wrapped by `BoxWithConstraints` it stops working.  

```
BoxWithConstraints() {
    Text(
        text = "More content #2",
        fontSize = 20.sp,
        style = TextStyle(
            fontWeight = FontWeight.Bold,
            textAlign = TextAlign.Center
        ),
        modifier = Modifier.fillMaxWidth(1F)
    )
}
```

See gifs below.

Not sure if this a Compose bug or not.  Works fine with normal `Box` so it might something `BoxWithConstraints` `SubcomposeLayout` usage.

## To Reproduce
Test project: 
[Flickering.zip](https://github.com/google/accompanist/files/6163547/Flickering.zip)

## Screenshots?
With `BoxWithConstraints`
<img src="https://user-images.githubusercontent.com/469111/111617341-459a5400-87e3-11eb-9154-b874f63a2836.gif" width="50%" />

Without `BoxWithConstraints`
<img src="https://user-images.githubusercontent.com/469111/111617348-47641780-87e3-11eb-8a6a-e0a98be82dd2.gif" width="50%" />

## Environment:
 - Android OS version: API 30
 - Device: Emulator
 - Accompanist version: 0.6.2

**Comment by chrisbanes** [comment]
I don't think this is a Insets library bug. All the library does is set/update the padding. It looks like the `Column`s padding is being updated, so the library is working as intended AFAICT.

I think it's worth raising a [Compose bug](https://goo.gle/compose-feedback) 🐛 , as it looks like the subcomposition is messing with the scroll position.
