### ISSUE TITLE
[CoilImage] color filter and fadeIn animation

### ISSUE THREAD

**Issue by amrro** [google/accompanist#262]
I was enabling the `fadeIn` in `CoilImage` composable. then applied `ColorFilter` to it. But it won't get applied. 
After some digging I found that if `fadeIn` is enabled, `ColorFilter` won't apply and vice versa. 

https://github.com/google/accompanist/blob/a9fb90c1fcbae12884a607c1d222803ec322e5d3/imageloading-core/src/main/java/com/google/accompanist/imageloading/MaterialLoadingImage.kt#L119-L133

I suggest to add this to the `CoilImage''s docs, I can make PR and add it. Or am I missing something?

**Comment by chrisbanes** [comment]
Sounds good, I'd happily accept a PR to make this clear from the docs.
