### ISSUE TITLE
[Idea] Pager and LazyColumn with collapsible Appbar content

### ISSUE THREAD

**Issue by Tlaster** [google/accompanist#265]
Some thing like Twitter's profile page, in Android xml we might use CoordinatorLayout+AppBarLayout+RecyclerView+ViewPager, and I've written a TabScaffold layout for Jetpack Compose and it's being used in [Twidere X](https://github.com/TwidereProject/TwidereX-Android/blob/develop/app/src/main/kotlin/com/twidere/twiderex/component/foundation/TabScaffold.kt) for a while. Maybe need some clean up before PR.

https://user-images.githubusercontent.com/8370277/111640347-13b2dd00-8837-11eb-9988-c391e93487c9.mp4

**Comment by chrisbanes** [comment]
Hi, thanks for the suggestion! I'm not sure this makes sense as a library component though. One of the things that I love about Compose is how easy it is to integrate things together, and I don't want that devs to avoid that. I'll close this for now I think.

**Comment by Tlaster** [comment]
For any who interested, I've created a NestedScrollView for it: https://github.com/Tlaster/NestedScrollView
