### ISSUE TITLE
[Idea] Zoomable Layout

### ISSUE THREAD

**Issue by Tlaster** [google/accompanist#266]
I've written a Zoomable layout that can zoom in and out with drag support and it's being used in [Twidere X](https://github.com/TwidereProject/TwidereX-Android/blob/develop/app/src/main/kotlin/com/twidere/twiderex/component/foundation/Zoomable.kt) for a while. Maybe need some clean up before PR.

https://user-images.githubusercontent.com/8370277/111637885-cc2b5180-8834-11eb-9343-febcc46fc138.mp4

**Comment by chrisbanes** [comment]
Mark this closed, as per #269
