### ISSUE TITLE
Navigation bar insets not working on API 21

### ISSUE THREAD

**Issue by grandstaish** [google/accompanist#267]
## Describe the bug
Navigation bar insets are always 0,0,0,0 on API 21. (Status bar insets work fine.) This is reproducible in the sample app for this project on an API 21 emulator. See screenshots below. 

## Screenshots?
API21|API29
-|-
![Screenshot_1616100820](https://user-images.githubusercontent.com/2288921/111696740-8f5b5c80-882c-11eb-93da-b66596ec7042.png)|![device-2021-03-18-205602](https://user-images.githubusercontent.com/2288921/111696748-92564d00-882c-11eb-8116-c6b1326ddad7.png)

## Environment:
 - Android OS version: 21
 - Device: Emulator (Google Pixel 4)
 - Accompanist version: 0.6.2

**Comment by chrisbanes** [comment]
Thanks for the report! I’ll take a look tomorrow, but initial guess is a bug in AndroidX Core.

Maybe bumping to 1.5.0-rc01 will fix it.

**Comment by grandstaish** [comment]
Solid guess—I just tried upgrading and it worked! Appreciate the quick reply 🚀

**Comment by chrisbanes** [comment]
Ha nice! I’ll bump the dependency for the next release.

**Comment by grandstaish** [comment]
Is 1.5.0-rc01 released? I don't see it on [maven.google.com](https://maven.google.com/web/index.html?q=androidx.core#androidx.core:core)

**Comment by chrisbanes** [comment]
Whoops, I meant beta03
