### ISSUE TITLE
[Pager] Dragging backwards instantly updates the state's current page

### ISSUE THREAD

**Issue by inorichi** [google/accompanist#280]
## Describe the bug
The current page of the pager is updated incorrectly while there's an active drag to the previous page, when dragging to the next page it works fine.

## Expected behavior
The currentPage should only be updated when the finger is released/the drag is settling.

## Environment:
 - Android OS version: 10
 - Device: OnePlus 5
 - Accompanist version: 0.6.3-SNAPSHOT (gradle sync done a few minutes ago)

## Additional context

Watch the tab indicator being updated when dragging backwards:

https://user-images.githubusercontent.com/3521738/112030009-1749ab00-8b3a-11eb-8c01-8ab0f8e7468f.mp4

This is the code used in the video above:

```kt
@OptIn(ExperimentalPagerApi::class)
@Composable
fun PagerDragBug() {
  val state = rememberPagerState(pageCount = 3, initialPage = 1)
  val pages = listOf(
    "A" to Color.Gray,
    "B" to Color.Black,
    "C" to Color.Gray
  )

  Column {
    TabRow(selectedTabIndex = state.currentPage) {
      pages.forEachIndexed { idx, page ->
        Tab(
          selected = state.currentPage == idx,
          text = { Text(page.first) },
          onClick = {}
        )
      }
    }
    HorizontalPager(state = state) { page ->
      Box(modifier = Modifier.fillMaxSize().background(pages[page].second))
    }
  }
}
```

I'm using your `Modifier.pagerTabIndicatorOffset` which is better to sync the tab indicator with the pager, but I've used this simpler approach to reproduce the issue. My actual issue is that I have a `LaunchedEffect(state.currentPage)` to notify my ViewModel when the active page changes, and this causes some glitches.

**Comment by chrisbanes** [comment]
Thanks for the report. This is due to our coalescing of `currentPageOffset` into the range `0..1f`. This has come up a few times so it is obviously causing issues.

**Comment by chrisbanes** [comment]
Also, you can use the new `pageChanges` flow from #278:

``` kotlin
LaunchedEffect(pagerState) {
    // Collect from the PageState's pageChanges, which emits when the
    // current page has changed
    pagerState.pageChanges.collect { page ->
        viewModel.fooBar(page)
    }
}
```

It's built in the `snapshot` branch though as it depends on something in Compose 1.0.0-beta03 (see [here](https://google.github.io/accompanist/using-snapshot-version/#using-jetpack-compose-snapshots) for how to use it)

**Comment by inorichi** [comment]
Thanks, it works fine with `pageChanges` on 0.7.0 :+1: 

I get notified twice but that's because I'm hoisting the state to the view model, so when the selected page changes, a new `PagerState` is created which also launches a new effect. Does this code make sense? I could only arrive to this solution to keep my SSOT on the view model:

```kt
val pagerState = remember(vm.categories.size, vm.selectedCategoryIndex) {
  PagerState(
    pageCount = vm.categories.size,
    currentPage = vm.selectedCategoryIndex
  )
}
LaunchedEffect(pagerState) {
  pagerState.pageChanges.collect { page ->
    vm.setSelectedPage(page)
  }
}
```

**Comment by chrisbanes** [comment]
Yep make sense! Any reason why you're not using `rememberPagerState()`?

**Comment by inorichi** [comment]
I thought it wasn't going to work because the parameter was called `initialPage`, I should have checked it first.

Yep, this looks much nicer:

```kt
val pagerState = rememberPagerState(vm.categories.size, vm.selectedCategoryIndex)
LaunchedEffect(pagerState) {
  pagerState.pageChanges.collect { page ->
    vm.setSelectedPage(page)
  }
}
```
