### ISSUE TITLE
[SystemUiController] Provide navigation bar type

### ISSUE THREAD

**Issue by Omico** [google/accompanist#281]
Hello, 

I want to dynamically set the navigation bar color according to the navigation bar type. I haven't found any method to achieve this yet. And I have written some [code](https://gist.github.com/Omico/2f3052ef579ff9cb225bbf0822d53bb7) for this, but I am not sure whether some manufacturers will modify this. Any suggestion for this?

**Comment by chrisbanes** [comment]
Apps shouldn’t be trying to detect the ‘nav bar type’. Instead they should be using window insets: https://google.github.io/accompanist/insets/

**Comment by Omico** [comment]
@chrisbanes I have use window insets to detect the navigation bar type, but maybe in the wrong way. I am not sure if you have seen my code. Let me paste it directly.

```
sealed class NavigationType {
    object Button : NavigationType()
    object Gesture : NavigationType()
    object Unknown : NavigationType()
}

@Composable
fun ProvideNavigationType(
        navigationType: NavigationType = navigationType(),
        content: @Composable () -> Unit,
) {
    CompositionLocalProvider(
            LocalNavigationType provides navigationType,
            content = content
    )
}

val LocalNavigationType = staticCompositionLocalOf<NavigationType> {
    error("LocalNavigationType value not available. Are you using ProvideNavigationType?")
}

@Composable
fun navigationType(default: NavigationType = NavigationType.Unknown): NavigationType =
        with(LocalDensity.current) {
            when (LocalWindowInsets.current.systemBars.bottom.toDp()) {
                56.dp -> NavigationType.Button
                16.dp -> NavigationType.Gesture
                else -> default
            }
        }
```

And this is how I use:

```
    ProvideSystemUiController {
        ProvideWindowInsets {
            val navigationType = navigationType()
            val systemUiController = LocalSystemUiController.current
            val useDarkIcons = MaterialTheme.colors.isLight
            val navigationBarColor = MaterialTheme.colors.surface.copy(0.9f)
            SideEffect {
                if (navigationType != NavigationType.Gesture)
                    systemUiController.setNavigationBarColor(navigationBarColor, darkIcons = useDarkIcons)
            }
        }
    }
```

**Comment by chrisbanes** [comment]
OK, so why do you need to know the `NavigationType`? This is something we specifically did not add to Android because it's an anti-pattern.

**Comment by Omico** [comment]
I made an InsetAwareBottomNavigation component inspired by your [InsetAwareTopAppBar](https://github.com/google/accompanist/blob/b40c3bdb84fbadd8814941336c29dca30d15b94a/sample/src/main/java/com/google/accompanist/sample/insets/EdgeToEdgeLazyColumn.kt#L152). It is translucent. I hope the navigation bar color can be consistent with the InsetAwareBottomNavigation component when the system uses the gesture navigation bar.

**Comment by Omico** [comment]
I get your point now. The color of the navigation bar should not be determined by its type but by its height. This code below is the only thing I should do. And ***no more navbar type detection!***

```
    ProvideSystemUiController {
        ProvideWindowInsets {
            val systemUiController = LocalSystemUiController.current
            val useDarkIcons = MaterialTheme.colors.isLight
            val systemBarsBottom = with(LocalDensity.current) {
                LocalWindowInsets.current.systemBars.bottom.toDp()
            }
            val navigationBarColor = when {
                systemBarsBottom > 16.dp -> MaterialTheme.colors.surface
                else -> Color.Transparent
            }
            SideEffect {
                systemUiController.setNavigationBarColor(navigationBarColor, darkIcons = useDarkIcons)
            }
        }
    }
```

**Comment by chrisbanes** [comment]
Ah I see what you’re trying to do. Well you shouldn’t need to do any detecting of the nav bar height, just set a transparent navigation bar color and the system will do the rest on API 29+:

https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e

I’d update your logic to:

```
val navigationBarColor = when {
                SDK_INT < 29 -> MaterialTheme.colors.surface
                else -> Color.Transparent
            }
```

**Comment by Omico** [comment]
If the version number can decide it, I won't think about how to get the navigation bar type. In my Oneplus 7 Pro (Oxygen OS, OP7Pro_O2_BETA_3, Android 11), we can change the navigation bar type in the Settings. Here is what happened to me if I only use the Android version to decide the color.

When I use:
```
val navigationBarColor = when {
    SDK_INT < 29 -> MaterialTheme.colors.surface
    else -> Color.Transparent
}
```
![image](https://user-images.githubusercontent.com/14316223/112142799-442aac00-8b94-11eb-83d3-b802959fe133.png)
![image](https://user-images.githubusercontent.com/14316223/112142824-4ab92380-8b94-11eb-805e-e8d6ea356a1f.png)


And it works perfectly decided by its height:
```
val navigationBarColor = when {
    systemBarsBottom > 16.dp -> MaterialTheme.colors.surface
    else -> Color.Transparent
}
```
![image](https://user-images.githubusercontent.com/14316223/112143629-64a73600-8b95-11eb-80a0-fbc532d630b8.png)
![image](https://user-images.githubusercontent.com/14316223/112143639-67a22680-8b95-11eb-9dc5-7483b54d242f.png)

**Comment by Omico** [comment]
I don’t think it’s a good way to make specific modifications based on manufacturers. So I want to find a common way to achieve this. That's why I want to get the navbar type before. Custom ROMs always mess up. We waste too much time overcoming these types of problems.
