### ISSUE TITLE
[Pager][Feature request] Item spacing

### ISSUE THREAD

**Issue by sindrenm** [google/accompanist#284]
Not sure if you're open to feature requests on this repo (only template was for bugs), but I'mma give it a shot anyway:

Similarly to `Arrangement.Horizontal` on rows, and `Arrangement.Vertical` on columns, I think it makes sense for `HorizontalPager` and `VerticalPager` to accept an `Arrangement.Horizontal` and `Arrangement.Vertical`, respectively. This is especially useful for using `Arrangement.spacedBy`.

**Comment by sindrenm** [comment]
I see. So the to add space between each item, would be to add a padding modifier or `Spacer` in between them? Or perhaps just having a parameter for spacing specifically would be a possibility. I can see how other `Arrangement` use-cases don't really apply. :slightly_smiling_face:

**Comment by chrisbanes** [comment]
We could just add a `itemSpacing` parameter? Feels like the simplest way.

**Comment by chrisbanes** [comment]
Added in #289

**Comment by sindrenm** [comment]
Awesome, thanks!

I've changed the title to more accurately reflect what I was _actually_ asking for. Feel free to change it back if it makes sense for you. :slightly_smiling_face:

**Comment by chrisbanes** [comment]
Cool, closing this 👍
