### ISSUE TITLE
[Pager] Better pointer input handling

### ISSUE THREAD

**Issue by Tlaster** [google/accompanist#285]
A usage is that using Pager inside a Pager, or using Pager in Scaffold with Drawer, both of these usages are buggy right now

**Comment by chrisbanes** [comment]
There is not enough information in this bug.

I've just tried a `VerticalPager { HoriztonalPager {} }` and it works fine.

**Comment by Tlaster** [comment]
Here is a quick example, both inner and outer `HorizontalPager` is quite wired, but this use case might not be very useful.
```Kotlin
val pagerState = rememberPagerState(pageCount = 10)
HorizontalPager(state = pagerState) { page1 ->
    val pagerState2 = rememberPagerState(pageCount = 2)
    HorizontalPager(state = pagerState2) { page2 ->
        Text(text = "$page1 $page2")
    }
}
```
Here is another example that can not drag the drawer out
```
Scaffold(
    drawerContent = {
        Column {
            ListItem {
                Text(text = "Drawer")
            }
        }
    }
) {
    val pagerState = rememberPagerState(pageCount = 10)
    HorizontalPager(state = pagerState) { page ->
        Text(
            modifier = Modifier.fillMaxSize(),
            text = page.toString()
        )
    }
}
```

**Comment by chrisbanes** [comment]
I'm not surprised at all that a `HorizontalPager` inside of a `HorizontalPager` doesn't work very well. We're using `scrollable()` which should give us some automatic nested scrolling support, but actually making this work nicely is a very low priority.

Re: Drawer. This is sounds like https://issuetracker.google.com/167408603 which is a bug in drawer.
