### ISSUE TITLE
[SystemUiController] Support full screen, hide status bar, navigation bar separately

### ISSUE THREAD

**Issue by RinOrz** [google/accompanist#291]
On some special screens, we may need to hide part of the system ui or even the full screen, so this should be included in the SystemUiController?

Currently I use:
```kotlin
ViewCompat.getWindowInsetsController(LocalView.current)!!.hide(WindowInsetsCompat.Type.systemBars())
```
But IMHO, this api is not elegant at all...

**Comment by chrisbanes** [comment]
PRs welcome!

**Comment by RinOrz** [comment]
Hahaha okay

**Comment by RinOrz** [comment]
Probably to add docs?
