### ISSUE TITLE
[Pager] reverseLayout = true doesn't scroll in the correct direction

### ISSUE THREAD

**Issue by danieldaeschle** [google/accompanist#298]
## Describe the bug
When swiping the left page the indicator changes immediately. Swiping to right it doesn't. The swipe to right behavior is better imo.

## To Reproduce
https://user-images.githubusercontent.com/30751516/113167868-68e1ec00-9244-11eb-963f-f481e6458fcc.mp4

## Expected behavior
When I swipe to left it should show the left page.
But reverseLayout should start on the right side with the first page.

## Environment:
 - Android OS version: Android 11
 - Device: Emulator, Pixel 5 and Pixel 3 real device
 - Accompanist version: 0.7.0

**Comment by chrisbanes** [comment]
The tab thing is covered by #280. Renaming this issue for the reverseLayout issue.

**Comment by chrisbanes** [comment]
Ah just saw #297. Closing this.
