### ISSUE TITLE
[Pager] HorizontalPager inside scrollable view incorrectly forms the height

### ISSUE THREAD

**Issue by X1opya** [google/accompanist#300]
## Describe the bug
HorizontalPager inside scrollable view incorrectly forms the height. But if we set fixed size it's work fine

## To Reproduce
Put Horizontal pager in scrollable container

## Expected behavior
pager automatically resized base on content

## Screenshots?
run code and uncomment key lines

## Additional context
  
```kotlin
val pages = listOf(
        "one",
        "two"
    )
    Column(Modifier.verticalScroll(rememberScrollState()))
    {
        val coroutineScope = rememberCoroutineScope()
        val pagerState = rememberPagerState(pageCount = 2, 1)
        TabRow(
            selectedTabIndex = pagerState.currentPage,
        ) {
            pages.forEachIndexed { index, title ->
                val isSelected = pagerState.currentPage == index
                Tab(
                    text = {
                        Text(
                            text = title,
                        )
                    },
                    selected = isSelected,
                    onClick = {
                        coroutineScope.launch {
                            pagerState.animateScrollToPage(index)
                        }
                    },
                )
            }
        }

        HorizontalPager(
            state = pagerState,
            Modifier
                .background(Color.Blue)
//                .height(1200.dp)  worked
//                .fillMaxHeight() not worker
        ) { index ->
            Column(
                Modifier
                    .fillMaxHeight()
                    .background(Color.Cyan)
            ) {
                repeat(50) {
                    Text(text = "aaaa")
                }
            }
        }
    }

```

**Comment by chrisbanes** [comment]
#302 updates Pager so that we still display content when we receive infinite constraints, by wrapping our content.

*But* using `fillMaxHeight()` in a vertically scrolling layout doesn't really work. I assume that you want the Pager to fill the visible height, but still be able to scroll? If so, that isn't supported by Compose.

**Comment by X1opya** [comment]
Thanks for reply. I need a pager so that it fills the content size and stay scrollable with all content on screen (include there tabs)

**Comment by chrisbanes** [comment]
Well `fillMaxHeight()` isn't going to do that for you unfortunately.

**Comment by X1opya** [comment]
maybe wrapContentSize() can do?

**Comment by chrisbanes** [comment]
That's similar to what we added in #302 as a fallback. 

You're basically looking for an equivalent of [`ScrollView.fillViewPort`](https://developer.android.com/reference/android/widget/ScrollView#setFillViewport(boolean)). This is worth raising as a bug on the Compose [issue tracker](https://goo.gle/compose-feedback).
