### ISSUE TITLE
[ImageLoad] The type of data should not be restricted.

### ISSUE THREAD

**Issue by RinOrz** [google/accompanist#307]
I need to load the icon from `ApplicationInfo`, which also means that the icon type is `Drawable`, but Accompanist prevented me. In fact, I can convert `Drawable` to `Painter` and load it with `Compose-Image`, but it means that I lost the `Coil` or `Glide` powerful, which is not what I want.

**Comment by chrisbanes** [comment]
Lol, just because this is ‘not what you want’ doesn’t mean we’re going to support this. The exception is there for a reason.

**Comment by RinOrz** [comment]
@chrisbanes In fact, coil supports loading drawable by default, I don’t understand why this type should be restricted
