### ISSUE TITLE
[Idea] [Pager] Emit page changes while scrolling

### ISSUE THREAD

**Issue by wrsx** [google/accompanist#313]
It would be useful to be able to subscribe to page changes while scrolling. Here is a side-by-side example of our current desired behaviour (left) vs accompanist (right):

https://user-images.githubusercontent.com/17993806/114008159-8a6e5380-9894-11eb-93e7-194e85042f33.mp4

**Comment by chrisbanes** [comment]
So this is actually what we had previously, but we changed it in #299 to only update the selected page after a scroll has finished.

Maybe we should add an option parameter for this, as different scenarios require different behaviors.

**Comment by chrisbanes** [comment]
On second thoughts, I'm not actually sure this is the behavior we want. The example above isn't really a pager, it's a carousel, and `VerticalPager` isn't really built for that use-case. For example, it's not really built to handle a continuous scroll which goes beyond the height (or width) of 1 item.

**Comment by wrsx** [comment]
No worries - totally agree. Any idea if theres plans for snapping support in LazyColumn/Row? Or alternatively would this library ever offer a carousel composable?

**Comment by chrisbanes** [comment]
I'm not aware of a public issue, so please go ahead and create one: https://goo.gle/compose-feedback.

> Or alternatively would this library ever offer a carousel composable?

Probably not. It's too similar to `LazyColumn` or `LazyRow` that it wouldn't be worth it imo. Note, you can do this yourself by suppling your own `flingBehavior` to `LazyColumn`, and scrolling the items are required. `LazyListState` should expose enough information for you to implement this.

**Comment by chrisbanes** [comment]
I'm going to close this here, as I don't think there's anything for us to do here.
