### ISSUE TITLE
[Pager] Navigation Drawer doesn't open by swiping if there's a HorizontalPager

### ISSUE THREAD

**Issue by ashar-7** [google/accompanist#327]
So I have a `Scaffold` with a drawer that opens from the left side. I have a `HorizontalPager` as the Scaffold's content. When I swipe from left from the first page to open the drawer, it doesn't open.

```
Scaffold(
    drawerContent = {
        MainDrawer()
    }
) {
    HorizontalPager(pagerState) { page ->
        ...
    }
}
```

## To Reproduce
1. Navigate to the first page
2. Swipe from left to right to open the drawer
3. Drawer doesn't open

## Expected behavior
The drawer should open when swiping from the first page.

## Environment:
 - Accompanist version: v0.7.1

**Comment by chrisbanes** [comment]
Pretty sure this is fixed by 8fb3644c9c54863d036fc556fb5756dd16de5c67, but I'll double check tomorrow.

**Comment by chrisbanes** [comment]
Hmmm, the commit above doesn't actually fix this. Looks like this is a bug in Compose's drawer implementation: https://issuetracker.google.com/167408603

Both `HorizontalPager` and `VerticalPager` use `Modifier.scrollable()` to detect drag events. The commit mentioned above (8fb3644) fixes our scroll state to return correct consuming of events. As far as Pager is concerned, we're doing all we should need to.

**Comment by ashar-7** [comment]
Still waiting for dependency
