### ISSUE TITLE
[Image] Image doesn't show loading content when data changes

### ISSUE THREAD

**Issue by ashar-7** [google/accompanist#328]
## Describe the bug
I have a `CoilImage` where I'm changing the data (network url) by clicking on a button. When the data changes, the `loading` content should be shown but that's not the case and it shows the old image until the new one is loaded. The `loading` content only shows up for the first image. This happens with both `Glide` and `Coil`.
```
CoilImage(
    data = imageData,
    modifier = Modifier.weight(1f),
    contentDescription = stringResource(R.string.template),
    contentScale = ContentScale.Inside,
    fadeIn = true,
    loading = {
        CircularProgressIndicator(
            modifier = Modifier
                .requiredSize(42.dp)
                .align(Alignment.Center)
        )
    },
    onRequestCompleted = { state ->
        canEdit = state is ImageLoadState.Success
    }
)
```

## To Reproduce
1. Create a `CoilImage` composable with some initial data.
2. Change the data by clicking on a button.
3. The old image appears instead of the loading bar until the new image is loaded.

## Expected behavior
`loading` content should be shown instead of the old image until the new one is loaded.

## Environment:
 - Accompanist version: v0.7.1

**Comment by chrisbanes** [comment]
All of the image loading composables are under going a big refactor right now (#321), and the current functions are going to be deprecated in the next release. Closing this as the `loading` parameter doesn't really existing in the new world.
