### ISSUE TITLE
java.lang.NoSuchFieldError: No static field Companion of type BoxScope$Companion

### ISSUE THREAD

**Issue by shiehnpin** [google/accompanist#329]
## Describe the bug
I'm using insets lib and it crashes all the time.

## To Reproduce
1. add `implementation 'com.google.accompanist:accompanist-insets:0.7.1'`
2. install app and run
3. crash

## Environment:
 - Android OS version: Android 11
 - Device: Pixel 3a
 - Accompanist version: 0.7.1

## Additional context
It is okay if I use `dev.chrisbanes.accompanist:accompanist-insets:0.6.2`

**Comment by chrisbanes** [comment]
Duplicate of #322
