### ISSUE TITLE
Documentation API pages 404

### ISSUE THREAD

**Issue by sudhirkhanger** [google/accompanist#330]
## Describe the bug
Glide, Coil, etc. API pages in the documentation are 404ing.

https://google.github.io/accompanist/api/glide/
https://google.github.io/accompanist/api/coil/

![Screenshot_20210413_141054](https://user-images.githubusercontent.com/841656/114523629-14863580-9c62-11eb-9279-1963d512c1fa.jpeg)

**Comment by chrisbanes** [comment]
Thanks for the heads-up, just redeployed the docs.

Looks like the docs action failed, but reported as successful. #331 should hopefully fix that.
