### ISSUE TITLE
[Idea] Content placeholder/skeleton UI

### ISSUE THREAD

**Issue by chrisbanes** [google/accompanist#336]
Something along the lines of https://www.smashingmagazine.com/2020/04/skeleton-screens-react/

I imagine that we can add a `Modifier.placeholder(enabled: Boolean)`, which will draw some skeleton color/shape in-front of the layout content.

**Comment by kosyak** [comment]
On the other hand - maybe we can have a `result: Drawable?` on `ImageState.Empty` and `ImageState.Loading`? This would be consistent with the current API, but I don't know about fancy stuff like animations (such a placeholder would fullfil my needs - I just need a ColorDrawable or BitmapDrawable to show while loading).

**Comment by chrisbanes** [comment]
Note: this API is not specific to the image loading libraries. This is a general purpose placeholder API.

**Comment by kosyak** [comment]
Oh, got it. Sure, skeletons are not only about images.

**Comment by moffpage** [comment]
Yes please! SwiftUI has **redacted** modifier which allows the view to be displayed with grey color like a placeholder. It'd be amazing having a native from-the-box one-liner solution for these types of cases! Before rewriting my app to Jetpack Compose, I used libraries like Facebook Shimmer: https://github.com/facebook/shimmer-android but I noticed that it uses shaders and it's a little GPU-heavy if I'm not mistaken (also I had to create the exact copies of my XML layout), so then I replaced it with Skelly: https://github.com/int02h/skelly, but it was still cumbersome, I don't think it needs to be that hard...
Thanks for your contribution Chris!)

**Comment by Kernald** [comment]
This is still relevant.
