### ISSUE TITLE
[Idea] better AnnotatedString API

### ISSUE THREAD

**Issue by FrancoisBlavoet** [google/accompanist#344]
**Is your feature request related to a problem? Please describe.**

The framework has an AnnotatedString API, which replaces Spans. To start end modified regions in the text, you need to call push and pop : 
```
pushStyle(SpanStyle(color = Color.Green))
    // append new text, this text will be rendered as green
    append(" World")
    // pop the green style
    pop()
    // append a string without style
    append("!")
    // then style the last added word as red, exclamation mark will be red
    addStyle(SpanStyle(color = Color.Red), "Hello World".length, this.length)

    toAnnotatedString()
```
which works well but is pretty verbose

I don't think compose will change this API since it is already in beta but Accompanist can make it more succinct. It is pretty easy to write some extensions in order to be able to write this : 
```
    val leadingLabel = annotatedString {
        append("You can click on spans as you wish, ")
        style(
            SpanStyle(
                color = myColor,
                textDecoration = TextDecoration.Underline,
            )
        ) {
            annotate("TAG", "myAnnotation") {
                append("here is one !")
            }
        }
```

is that something that might be useful to accompanist ? I would not mind removing this code from my integration and just consume it from Accompanist instead :)

**Comment by nickbutcher** [comment]
This already exists in compose as [`buildAnnotatedString`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-text/src/commonMain/kotlin/androidx/compose/ui/text/AnnotatedString.kt;l=835) ([usage](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-text/samples/src/main/java/androidx/compose/ui/text/samples/AnnotatedStringBuilderSamples.kt;l=125-138)).

**Comment by chrisbanes** [comment]
Thanks, closing due to @nickbutcher's comment
