### ISSUE TITLE
[Pager] HorizontalPager continues the fling started on LazyRow

### ISSUE THREAD

**Issue by micHar** [google/accompanist#347]
## Describe the bug
I have a HorizontalPager which also sometimes contains a LazyRow. When the contents of the LazyRow are longer than the width of the page, the LazyRow becomes scrollable. And if I fling on it, when it reaches the end, HorizontalPager continues the movement and jumps a bit to the scrolled side.

## To Reproduce
:
1. Have a HorizontalPager with LazyRow in it
2. Fling LazyRow

## Expected behavior
Like in a traditional viewpager + recyclerview, if LazyRow intercepts the fling, it should consume it entirely, the pager should not jump.

## Environment:
 - Android OS version: Android 11
 - Device: Samsung S21
 - Accompanist version: v0.7.1

**Comment by chrisbanes** [comment]
This is working as intended, and happens because this is the implicit behavior of `Modifier.scrollable()`.

This enables use-cases like integration with `SwipeRefresh` so we won't be disabling it.

**Comment by micHar** [comment]
Sure! Any way to disable it, though?

**Comment by chrisbanes** [comment]
Re-opening as per [Slack discussion](https://kotlinlang.slack.com/archives/CJLTWPH7S/p1618664603025500)

**Comment by rackami** [comment]
I noticed the same thing.
Is there any solution or workaround for that?
@chrisbanes

**Comment by micHar** [comment]
I'm on mobile so can't easy find the right snippet, but the workaround is in the slack discussion Chris linked above - basically you need to provide to the lazyrow a nestedscrollconnection which will consume postscroll.

**Comment by AbelToy** [comment]
I need to re-enable this feature for my specific use case. I would really appreciate a way to at least toggle whether flings will be ignored or not.

My specific case includes a custom component that allows the user to zoom and pan an image inside an image viewer. When the image reaches the edge of the viewer I participate in the nested scroll hierarchy appropriately. Right now when using this image viewer inside a Pager, swiping to the previous/next pages will cause the pager to just stop mid-page when the user releases the finger.
