### ISSUE TITLE
Window Insets Animations cause lag on Scaffold

### ISSUE THREAD

**Issue by wulkanat** [google/accompanist#349]
## Describe the bug
Trying to use the IME animations on a scaffold using `Modifier.navigationBarsWithImePadding()` causes severe
lag.

## To Reproduce

1. Enable window insets animation
2. Add a `Scaffold` with the `navigationBarsWithImePadding` modifier
3. Add a BottomAppBar and a text field

## Expected behavior
The animation should be just as smooth as manually animating it.

## Environment:
 - Android OS version: Android S DP2
 - Device: Google Pixel 3a
 - Accompanist version: v0.7.0
 - Jetpack Compose version: 1.0.0-beta04

## Example Video

[Example Video](https://youtu.be/LdvVdaS1hPU)

## Additional context

Example Project
```kotlin
class MainActivity : ComponentActivity() {
    @ExperimentalAnimatedInsets
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        WindowCompat.setDecorFitsSystemWindows(window, false)

        setContent {
            ScaffoldTestTheme {
                ProvideWindowInsets(windowInsetsAnimationsEnabled = true) {
                    HomeScreen()
                }
            }
        }
    }
}

@Composable
fun HomeScreen() {
    var isUp by remember { mutableStateOf(false) }
    val padding by animateDpAsState(if (isUp) 300.dp else 0.dp)

    Scaffold(
        Modifier
            .padding(bottom = padding)
            .navigationBarsWithImePadding(),
        bottomBar = {
            BottomAppBar(cutoutShape = CircleShape) {
            }
        },
        isFloatingActionButtonDocked = true,
        floatingActionButton = {
            FloatingActionButton(onClick = { isUp = !isUp }) {
                Icon(Icons.Filled.KeyboardArrowUp, contentDescription = null)
            }
        },
    ) {
        Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            PasswordInput()
        }
    }
}

@Composable
fun PasswordInput() {
    val text = remember { mutableStateOf(TextFieldValue("")) }

    OutlinedTextField(
        modifier = Modifier.fillMaxWidth(),
        value = text.value,
        onValueChange = {
            text.value = it
        },
        label = {
            Text("Password")
        },
    )
}
```

**Comment by chrisbanes** [comment]
This isn't really a bug on `navigationBarsWithImePadding()`. All it is doing is updating padding (via state reads which is pretty much optimal). My guess is that this is a performance issue with either Scaffold's layout, or subcomposition in general (which is a known issue). I'd raise a bug at https://goo.gle/compose-feedback.

Also, `navigationBarsWithImePadding()` isn't meant to be used on a top-level layout like `Scaffold`. Each animation change will trigger a layout, and if it's triggering a layout near the top, everything sibling and descendant layout needs to be re-laid out.
