### ISSUE TITLE
Inconsistent behaviour when swapping CoilImage for GlideImage using the same code

### ISSUE THREAD

**Issue by itsandreramon** [google/accompanist#353]
### The Problem
Loading an image using CoilImage works correctly, but not when using the exact same code using GlideImage. The GlideImage ignores the contentScale parameter.

(Don't worry, the people in the list are fictional)

### Using Coil
![Screenshot_20210421-121449](https://user-images.githubusercontent.com/17139385/115537857-892d2580-a29b-11eb-92b6-0991283fa969.png)

```kt
@Composable
fun CustomerAvatar(avatar: Bitmap?, modifier: Modifier) {
    CoilImage(
        data = avatar ?: R.drawable.ic_account_no_padding,
        contentDescription = null,
        contentScale = ContentScale.Crop,
        modifier = modifier.clip(CircleShape)
    )
}
```

![Screenshot_20210421-121525](https://user-images.githubusercontent.com/17139385/115537930-a19d4000-a29b-11eb-963b-71e7cfe96d32.png)

### Using Glide
```kt
@Composable
fun CustomerAvatar(avatar: Bitmap?, modifier: Modifier) {
    GlideImage(
        data = avatar ?: R.drawable.ic_account_no_padding,
        contentDescription = null,
        contentScale = ContentScale.Crop,
        modifier = modifier.clip(CircleShape)
    )
}
```

**Comment by chrisbanes** [comment]
I assume that `R.drawable.ic_account_no_padding` is a vector drawable? What size is set in the vector?

The fact that Glide and Coil are different isn't an issue, as they are different libraries and thus have different behaviors.

**Comment by chrisbanes** [comment]
Also, what modifier is passed into `CustomerAvatar`?

**Comment by itsandreramon** [comment]
Yes thats correct, its a vector drawable. The size is set to 24dp

```xml
<vector
    ...
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        .../>
</vector>
```

This is how I call it:

```kt
CustomerAvatar(
    avatar = avatar,
    modifier = Modifier.size(38.dp)
)
```

**Comment by itsandreramon** [comment]
I also tried to achieve the same behaviour in GlideImage using different contentScales but it didn‘t work out really well so I just used CoilImage.

**Comment by chrisbanes** [comment]
Hmmm, just tried this on HEAD and it seems to be working as expected. There has been a _lot_ of changes lately though, and the new release should be out tonight. 

There is a difference in how Coil and Glide handle drawables like this. Coil will draw vector drawables to a bitmap, whereas Glide does not. That is probably where some of the issues are coming from.

**Comment by chrisbanes** [comment]
Going to close this. Feel free to ping if there's still an issue after migrating to the new release.

**Comment by itsandreramon** [comment]
I have a new problem. After updating to 0.10.0 from 0.7.1 CoilPainter is not working for bitmaps. It works for a given url from the web for instance but fails to load the local bitmap. It works with the normal Coil library, so i suspect there is a problem present in this library here.

(I could probably use avatar ?: R.drawable... but I am not sure, currently trying different things to fix the problem)

```kt

@Composable
fun CustomerAvatar(avatar: Bitmap?, modifier: Modifier) {
    if (avatar != null) {
        Image(
            painter = rememberCoilPainter(
                request = avatar,
                requestBuilder = {
                    transformations(CircleCropTransformation())
                },
            ),
            contentScale = ContentScale.Crop,
            contentDescription = null,
            modifier = modifier
        )
    } else {
        Image(
            painter = painterResource(id = R.drawable.ic_account_no_padding),
            contentScale = ContentScale.Crop,
            contentDescription = null,
            modifier = modifier
        )
    }
}
```
