### ISSUE TITLE
[Pager] Modifier.aspectRatio() is not working in HorizontalPager for v0.8.0

### ISSUE THREAD

**Issue by crayonxiaoxin** [google/accompanist#361]
## Describe the bug
`Modifier.aspectRatio()` is not working in HorizontalPager for v0.8.0, it fills max size, but it works in v0.7.1.

## Screenshots?
![QQ截图20210422222824](https://user-images.githubusercontent.com/35017508/115731924-1b2b5000-a3ba-11eb-9f8b-c12ab9d7e65b.png)

## Environment:
 - Android OS version: Android 11
 - Device: Emulator,Pixel 3a
 - Accompanist version: v0.8.0

**Comment by chrisbanes** [comment]
I'm not sure what you're expecting? An `aspectRatio(0.55f)` means that the width = `0.55 * height` (i.e. it's likely to fill the screen shown). The background is displaying correctly from what I can see. I've just tested this locally and it's working as expected there too.

**Comment by crayonxiaoxin** [comment]
oh,thanks. it's my fault i'm sorry.
