### ISSUE TITLE
ViewPager-like smoke & mirrors animateScrollToPage

### ISSUE THREAD

**Issue by micHar** [google/accompanist#368]
**Is your feature request related to a problem? Please describe.**
This Pager seems to really try and scroll through all the pages and render them while doing so. In effect, when I `animateScrollToPage` from, say, page 1 to page 80, it looks very laggy. Old `ViewPager` is cheating here - it only really scrolls one page. So if I wanted it to scroll from page 1 to page 80, it would really only scroll from 79 to 80. It was fast enough to fool the eye, though - and thus looked smoother.

**Describe alternatives you've considered**
One might of course calculate that and use `scrollToPage` and then `animateScrollToPage` to achieve similar effect.

**Describe the solution you'd like**
To be honest I'm wondering what you think about it. Alternative doesn't seem too complicated, but maybe there should be some param passed to `animateScrollToPage` to control that behavior?

**Comment by chrisbanes** [comment]
> Old ViewPager is cheating here - it only really scrolls one page

Yep, but it's a bit more complex than that. It actually scrolls through any already laid out pages (i.e. the offscreen limit), and then adds the target page at the end. The issue with this is that it ties the state and layout logic together, resulting in the state being more complex, and less re-usable.

Basically we would need to move the list of 'pages to layout' logic to the state. Currently it is very simply computed based off the `currentPage`.

**Comment by micHar** [comment]
I think I kind of understand what you mean but I didn't look at the internals so only kind of ;). 

I wonder what it means that layout and state are tied - is it two way coupling in the old pager or is the layout still just a function of the state and never vice versa?

Doesn't it really mean that to do such things (I wonder if there are more than this faux scroll) there needs to be some intermediate layer that would add necessary transformations before deriving layout from the original pager state?

**Comment by chrisbanes** [comment]
#372 will fix this eventually

**Comment by micHar** [comment]
Works great, thanks!
