### ISSUE TITLE
import androidx.compose.ui.util.lerp not Found

### ISSUE THREAD

**Issue by Eng-AhmedShehata** [google/accompanist#375]
After trying to add Item scroll effects ..[here](https://google.github.io/accompanist/pager/)
I got this **error** -> import androidx.compose.ui.util.lerp not Found .     
**Hint:** 
I'm using       
**implementation 'androidx.compose.ui:ui:1.0.0-beta05'**

**Comment by chrisbanes** [comment]
This isn’t an issue in Accompanist.

**Comment by oas004** [comment]
For me it worked if I in addition to adding dependency on `androidx.compose.ui:ui:$version` added a dependency on `androidx.compose.ui:ui-util:$version`. Hope this might help :)

**Comment by Eng-AhmedShehata** [comment]
> For me it worked if I in addition to adding dependency on `androidx.compose.ui:ui:$version` added a dependency on `androidx.compose.ui:ui-util:$version`. Hope this might help :)

Thank you.. The problem was solved successfully after adding this dependency.

**Comment by rd-martin-jaeger** [comment]
I run into the same issue. 
I think this should be mentioned in the documentation since isn't so obvious for all compose newbies like me ;)
