### ISSUE TITLE
[Pager] Touch ripple skipped

### ISSUE THREAD

**Issue by KlassenKonstantin** [google/accompanist#384]
When using a HorizonalPager that consists of vertical LazyColumns with clickable items, the touch ripple animation is skipped. The background color just jumps to the final state and back.

```
binding.composeRoot.setContent {
    val pagerState = rememberPagerState(pageCount = 2)
    HorizontalPager(state = pagerState) { page ->
        LazyColumn {
            items((1..100).toList()) { item ->
                Text("$item", modifier = Modifier.fillMaxSize().clickable {}.padding(16.dp))
            }
        }
    }
}
```

**Comment by chrisbanes** [comment]
Can't reproduce this from `main`. The ripple is displayed correctly.

**Comment by KlassenKonstantin** [comment]
I am very sorry, I did not intent to skip the template. I clicked on "New issue" and could not pick one, I was directly directed to an templateless text field. Today there is the template picker and I look stupid 😅.

**Comment by KlassenKonstantin** [comment]
After testing with the current snapshot and still having the same problem, I realised I removed the `MaterialTheme` Composable, when I added `HorizontalPager`
