### ISSUE TITLE
[Idea] Add permissions request library

### ISSUE THREAD

**Issue by bvitaliyg** [google/accompanist#385]
It's now possible to start activities for result directly from Compose using activity-compose library.

With this in mind a library handling permission requests can be made.

The API might look like this:

```
WithPermissions(
    permissions = listOf(Manifest.permission.CAMERA),
    granted = {},
    denied = {},
    deniedPermanently = {},
    rational = "",
)
```

An overload with sealed PermissionResult lambda will also be userful:

```
WithPermissions(
    permissions = listOf(Manifest.permission.CAMERA),
    rational = "",
) { result ->
    when (result) {
        is PermissionResult.Granted -> {}
        is PermissionResult.Denied-> {}
        is PermissionResult.DeniedPermanently-> {}
    }
}
```

**Comment by chrisbanes** [comment]
This sounds like a good idea for a library! I won’t be writing this though.

Start a new project?

**Comment by bvitaliyg** [comment]
Would it make sense to make the library a part of accompanist?

**Comment by chrisbanes** [comment]
No, being in this repo means that we are then responsible for maintainance, etc.
