### ISSUE TITLE
Current page state is not getting updated immediately taking 4-5 sec delay after page is swiped

### ISSUE THREAD

**Issue by KittyDev18** [google/accompanist#387]
var pagerState = rememberPagerState(pageCount = 2)

        when (pagerState.currentPage) {
// This block is getting executed with a delay of 4-5 sec

            0 -> {
               //*b1*//               
            }
            1 -> {
               //*b2*//
            }
        }

        HorizontalPager(
            state = pagerState,
            modifier = Modifier.fillMaxSize()
        ) { page ->
            Card(
                Modifier
                    .fillMaxSize()
            ) {
                when (page) {
                    0 -> {
                        pG1)
                    }
                    1 -> {
                        pG2()
                    }
                }
            }
        }

**Comment by chrisbanes** [comment]
Read the doc of `currentPage`, it explains why. Related: #299
