### ISSUE TITLE
Currentpage flow is not emiting changes 

### ISSUE THREAD

**Issue by KittyDev18** [google/accompanist#388]
LaunchedEffect(pagerState) {
            pagerState.pageChanges.collect {
                Log.e("adad", "First -> $it")
            }
        }

 LaunchedEffect(pagerState) {
            snapshotFlow { pagerState.currentPage }.collect {
                Log.e("adad", "Second-> $it")
            }
        }

//they only emit once while app is starting but afterwords while change the pages nothing is happening

**Comment by chrisbanes** [comment]
1) `pageChanges` is deprecated.
2) Our tests are passing on all API levels.
3) This bug is not actionable in any way. The bug template is there for a reason.

**Comment by strevg** [comment]
I have a same problem for 
```
LaunchedEffect(pagerState) {
    snapshotFlow { pagerState.currentPage }.collect {
    Log.e("adad", "Second-> $it")
}
```
