### ISSUE TITLE
Current page in HorizontalPager

### ISSUE THREAD

**Issue by RomanPolach** [google/accompanist#395]
It looks like there is a bug in currentPage of HorizontalPager in PagerState. When i scroll to last page (for example i have 4 pages), the page is displayed correctly, but value of currentPage stays at 2. But when i try to drag it little further, currentPage value switches to correct value (3). 

Tested on: 
Android 8.1, 
Xiaomi Redmi Note 5,
 version: pager:0.9.0

**Comment by daespark** [comment]
Happening for me as well.

I think this makes the pager have a weird behavior where if you swipe to the last page, then try to swipe back a page, it immediately goes to the previous page as soon as drag starts. confirmed happening both on emulator and pixel 4 xl device.

JetCaster app exhibits the same behavior
