### ISSUE TITLE
[Bug]AlignByBaseLine does not work with FlowRow

### ISSUE THREAD

**Issue by KwabenBerko** [google/accompanist#401]
## Describe the bug
Unlike `Row`, child composables in `FlowRow` cannot be aligned using the `alignByBaseLine`  modifier or any of the `alignBy` modifiers.

For instance:

```kotlin
FlowRow {
   Text(
        text = "One",
        fontSize = 26.sp,
        modifier = Modifier.alignByBaseline()
    )

    Text(
        text = "Two",
        fontSize = 16.sp,
        modifier = Modifier.alignByBaseline()
    )
}
```
results in:

<img width="475" alt="Screenshot 2021-05-11 at 9 15 54 AM" src="https://user-images.githubusercontent.com/13765161/117794412-bdfa2000-b23c-11eb-8268-493e6e2bd10b.png">

whereas using a `Row` composable:
```kotlin
Row {
    Text(
        text = "One",
        fontSize = 26.sp,
        modifier = Modifier.alignByBaseline()
    )

    Text(
        text = "Two",
        fontSize = 16.sp,
        modifier = Modifier.alignByBaseline()
    )
}
```
results in:

<img width="486" alt="Screenshot 2021-05-11 at 9 43 00 AM" src="https://user-images.githubusercontent.com/13765161/117795015-4c6ea180-b23d-11eb-8f7e-cc9e46880246.png">

## Expected behavior
Using the `alignByBaseline` modifiers or any of the `alignBy` modifiers should correctly align the contents of `FlowRow`

## Environment:
 - Android OS version: Android 8.1
 - Device: Pixel 4 Emulator
 - Accompanist version: 0.9.1

**Comment by chrisbanes** [comment]
I'm afraid that `FlowRow` and `FlowColumn` are basically in maintenance mode. I'll happily look at PRs but I won't be adding features, etc.
