### ISSUE TITLE
SwipeRefresh does not work with a child of type Column()

### ISSUE THREAD

**Issue by thierryd** [google/accompanist#404]
## Describe the bug
I'm presenting a screen with data on it. This data is presented in a simple Column (*not* LazyColum) I want to allow the user to update the data using a swipe-to-refresh gesture

## To Reproduce
1. Create a screen like with then following content:

        val viewModel: MyViewModel = viewModel()
        val isRefreshing by viewModel.isRefreshing.collectAsState()

        SwipeRefresh(
            state = rememberSwipeRefreshState(isRefreshing),
            onRefresh = { viewModel.refresh() },
        ) {
            Column {
                Row(Modifier.padding(16.dp)) {
                    Text(
                        text = "Text",
                        style = MaterialTheme.typography.subtitle2,
                        modifier = Modifier
                            .weight(1f)
                            .align(Alignment.CenterVertically)
                    )
                }
                    ...
            }
        }

2. Run the code on a device and execute the "swipe-to-refresh" gesture
3. Error: viewmodel.refresh() is never called

## Expected behavior
viewmodel.refresh() is called

## Environment:
'com.google.accompanist:accompanist-swiperefresh:0.9.1'

## Additional context
It works fine if I use a LazyColumn with an item count of 1

**Comment by vipulyaara** [comment]
Is there no way to use `SwipeRefresh` without a scrollable layout? We don't want our layout to scroll but still want to use a `SwipeRefresh` to refresh the page. Is it possible for me to copy the source code and easily remove the scrollable requirement?
