### ISSUE TITLE
[Pager] currentPage flowSnapshot is not reliable

### ISSUE THREAD

**Issue by Poliziano** [google/accompanist#408]
## Describe the bug
Swiping quickly when using a `HorizontalPager` does not always invoke the `snapshotFlow.collect` callback. Originally identified on a Samsung A5 (2017), and reproduced in the emulator using a simplified project.

## To Reproduce
1. Download my simplified project: [MyApplication.zip](https://github.com/google/accompanist/files/6468344/MyApplication.zip).
2. Run the emulator (in my recording I'm using a Nexus 5 API 22).
3. Swipe forward and backward quickly.
4. Notice the dots do not always match the number after swiping quickly. The coloured dots are based on the latest `currentPage` capture in a `snapshotFlow`.

## Expected behavior
Using the pager `currentPage` in a `snapshotFlow` (as recommended by the documentation), results in reliable callbacks.

## Screenshots?
![pager](https://user-images.githubusercontent.com/5665458/118025144-669ca280-b357-11eb-8e8e-fcee54381303.gif)

## Environment:
 - Android OS version: Android 5.1 (Emulator) and Android 8.0 (Samsung A5)
 - Device: Emulator and Samsung A5 (2017)
 - Accompanist version: 0.9.1

## Additional context
My application is designed in a way that relies on the `currentPage` being accurate and consistent, so this is a big problem for me. Not sure if this should be reported elsewhere.

**Comment by chrisbanes** [comment]
Pretty sure that this is fixed by #400, which will be released in the next version. You can use the [snapshot version](https://google.github.io/accompanist/using-snapshot-version/) if you'd like to try it out.

**Comment by Tom-Alphero** [comment]
I can confirm this is fixed on the 0.10.0 snapshot.
