### ISSUE TITLE
[Idea] Replacement for AndroidX Preferences

### ISSUE THREAD

**Issue by sproctor** [google/accompanist#411]
Compose is missing a replacement for `androidx.preference`.

I think this might be a good place to provide a replacement.

There is an incomplete alternative at https://github.com/Sh4dowSoul/ComposePreferences

This seems similar to the other features of this repository. Thank you for your consideration.

**Comment by chrisbanes** [comment]
We have no plans to work on this in Accompanist at the moment. As there are already a few external libraries which support this, I'm going to close this.

**Comment by sproctor** [comment]
OK. Can you tell me which ones you found? I only found the one I listed above which I had to modify pretty heavily to work for my purposes.

**Comment by chrisbanes** [comment]
https://github.com/alorma/Compose-Settings and https://github.com/Sh4dowSoul/ComposePreferences are the two that I'm aware of. I haven't looked deeply at either implementations though so don't take this as a recommendation.

**Comment by sproctor** [comment]
Thanks. Hopefully one of them eventually provides an adequate replacement.

**Comment by bvitaliyg** [comment]
@chrisbanes still no plans to support this?
