### ISSUE TITLE
`ImageLoadState.Loading` does not have a companion object, and thus must be initialized here

### ISSUE THREAD

**Issue by Michael-MF** [google/accompanist#412]
## Describe the bug
In the [Glide for Jetpack Compose](https://google.github.io/accompanist/glide/) documentation, the following example is provided for showing a loading spinner

```kotlin
val painter = rememberGlidePainter("https://picsum.photos/300/300")

Box {
    Image(
        painter = painter,
        contentDescription = stringResource(R.string.image_content_desc),
    )

    when (painter.loadState) {
        ImageLoadState.Loading -> {
            // Display a circular progress indicator whilst loading
            CircularProgressIndicator(Modifier.align(Alignment.Center))
        }
        is ImageLoadState.Error -> {
            // If you wish to display some content if the request fails
        }
    }
}
```

This doesn't work, as the following error is produced

<img width="761" alt="Screenshot 2021-05-14 at 12 45 32" src="https://user-images.githubusercontent.com/77275576/118266581-b93ea180-b4b2-11eb-9182-de145a22210e.png">

## Environment:
 - Android OS version: API 30
 - Device: N/A
 - Accompanist version: `0.9.1`

**Comment by chrisbanes** [comment]
Ah, that should be `is ImageLoadState.Loading ->`. I'll update the docs

**Comment by Michael-MF** [comment]
> Ah, that should be `is ImageLoadState.Loading ->`. I'll update the docs

Thanks 😄
