### ISSUE TITLE
[Pager] java.lang.IllegalArgumentException: currentPageOffset must be >= 0 and <= 1 after restoring the state

### ISSUE THREAD

**Issue by ln-12** [google/accompanist#417]
## Describe the bug
I am using the `HorizontalPager` component. Sometimes when the state is restored, the exception ` java.lang.IllegalArgumentException: currentPageOffset must be >= 0 and <= 1 ` occurs . With some debugging I found out, that this is caused by the `Saver` object.

When the state of the pager is restored internally at [this line](https://github.com/google/accompanist/blob/1a181943e697d662785c7f2584ac940cd9ccf707/pager/src/main/java/com/google/accompanist/pager/PagerState.kt#L635), the value for `currentPageOffset` sometimes is `-1.0` or `-2.0`. This causes the test in [this line](https://github.com/google/accompanist/blob/1a181943e697d662785c7f2584ac940cd9ccf707/pager/src/main/java/com/google/accompanist/pager/PagerState.kt#L621) to fail and results in the mentioned crash. The values for `pageCount` and `currentPage` are always correct when saving the state.

## To Reproduce
Unfortunately, I can't deterministically reproduce the crash. It occurs from time to time when I scroll forth and back, save the state by going to another screen and returning. If I can provide a 100% crashing example, I add it below.

## Expected behavior
The restored value should meet the required range of `(0.0f ... 1.0f)`.

## Environment:
 - Android OS version: 11
 - Device: Xiaomi Mi Mix 2S
 - Accompanist version: 0.9.1

**Comment by chrisbanes** [comment]
Good catch. To be honest we shouldn't be storing/restoring the offset anyway. I'll quickly remove that.

**Comment by ln-12** [comment]
Great, so I can stop playing around with that. For now it seems to be crashing most of the time when I go to my last page, try to scroll further (which doesn't do anything as it's the last page) and then scroll back. A text label above like `Text(text = pagerState.currentPageOffset.toString())` helps to see when it's wrong. But your solution might be the easiest, thanks for the fast response! 👍

**Comment by chrisbanes** [comment]
> Great, so I can stop playing around with that. For now it seems to be crashing most of the time when I go to my last page, try to scroll further (which doesn't do anything as it's the last page) and then scroll back.

Yeah, this could happen currently if the pager state is stored while an animation/drag is in progress. We only want to store the current 'stable' state anyway, so the offset isn't needed.

Thanks for reporting.
