### ISSUE TITLE
[Pager] When scrolling back, the internal state is sometimes buggy which leads to page jumping and glitches

### ISSUE THREAD

**Issue by ln-12** [google/accompanist#420]
## Describe the bug
I discovered this bug when reporting #417. The applied fix avoids crashes when saving and restoring the state but I think the underlying problem of some broken internal calculation is still present.

## To Reproduce
Setup a HorizontalPager and scroll around.
```
val pagerState = rememberPagerState(pageCount = 3)

Column {
    Text(text = "currentPageOffset: ${pagerState.currentPageOffset}")
    Text(text = "currentPage: ${pagerState.currentPage}")
    Text(text = "targetPage: ${pagerState.targetPage}")
    Text(text = "pageCount: ${pagerState.pageCount}")

    HorizontalPager(state = pagerState) { page ->
        Surface(
            shape = MaterialTheme.shapes.small,
            border = BorderStroke(
                width = 1.dp,
                color = MaterialTheme.colors.onSurface.copy(alpha = 0.12f)
            ),
            modifier = modifier
                .fillMaxWidth()
                .padding(8.dp),
        ) {
            Text("I am page #$page", modifier = Modifier.padding(8.dp))
        }
    }
}
```

## Expected behavior
Consistent internal state.

## Screenshots?
Scrolling forward seems to be fine. When scrolling backwards, the internal state is sometimes not updated correctly. As a result, the pager is "jumping" between pages when recomposing. Please refer to the video below. You can see this e.g. at second 4 and 5 (and also multiple times afterwards, but it is not always refreshed immediately). I scroll back to page 0, but `currentPage = 2` and `currentPageOffset = -2.0`. Technically after calculating `currentPage - currentPageOffset`, this also leads to page 0, but as you see in the video, it jumps to `currentPage = 2` and `currentPageOffset = 0.0` after recomposing (?). I think in this case currentPage is not updating to the correct page.

https://user-images.githubusercontent.com/36760115/118521268-282e2b80-b73b-11eb-8031-de4fc8a01dff.mp4

## Environment:
 - Android OS version: 11
 - Device: Xiaomi Mi Mix 2S
 - Accompanist version: 0.9.1

**Comment by chrisbanes** [comment]
Pretty sure this is already fixed by #400. You can try out the snapshots if you'd like to try out the fix.

**Comment by ln-12** [comment]
Alright, I'll give it a try, thanks!

**Comment by chrisbanes** [comment]
Marking this as closed for now. Feel free to ping if the snapshot doesn't work.
