### ISSUE TITLE
[Glide] Crashing during init of Preview

### ISSUE THREAD

**Issue by DtechLabs** [google/accompanist#424]
## Describe the bug
use `remeberGlidepainter` crash rendering preview

## To Reproduce
```
val painter = rememberGlidePainter(
	request = avatarRef,
        previewPlaceholder = placeholder
)
Image(
     painter = painter,
     contentDescription = null,
     modifier = modifier
	        .size(75.dp)
		.clip(AvatarShape)
		.clickable { onClick?.let { it() } }
)
.....
```

`
java.lang.IllegalStateException: You cannot call Glide.get() in registerComponents(), use the provided Glide instance instead   at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:205)   at com.bumptech.glide.Glide.get(Glide.java:191)   at com.bumptech.glide.Glide.getRetriever(Glide.java:774)   at com.bumptech.glide.Glide.with(Glide.java:801)
`
  

## Environment:
 - Android OS version: Android 9.0
 - Device: Emulator, Google Pixel 4
 - Accompanist version:  v0.9.1

**Comment by chrisbanes** [comment]
Not much we can do here to be honest. `Glide.with()` doesn't seem to work in layoutlib which is used by Android Studio previews, as that doesn't fake out the manifest API

```
java.lang.NullPointerException   at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:38)
   at com.bumptech.glide.Glide.initializeGlide(Glide.java:278)
   at com.bumptech.glide.Glide.initializeGlide(Glide.java:266)
   at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:210)
   at com.bumptech.glide.Glide.get(Glide.java:191)
   at com.bumptech.glide.Glide.getRetriever(Glide.java:774)
   at com.bumptech.glide.Glide.with(Glide.java:801)
   at com.google.accompanist.glide.GlidePainterDefaults.defaultRequestManager(Glide.kt:71)
   at com.google.accompanist.glide.GlideKt.rememberGlidePainter(Glide.kt:94)
```

**Comment by chrisbanes** [comment]
Closing this as there's nothing we can do here.

Apps can disable the manifest parsing in Glide, which _should_ make previews work. See here: https://bumptech.github.io/glide/doc/configuration.html#manifest-parsing
