### ISSUE TITLE
[Pager] Supports infinite loop

### ISSUE THREAD

**Issue by fornewid** [google/accompanist#429]
**Is your feature request related to a problem? Please describe.**
Infinite loop is a commonly used UX in apps.
In View System, both ViewPager and ViewPager2 had a demand for infinite loop feature,
and currently each developers are implement it individually.
Even in the world of Compose, it would be nice if there was official support! :bow:

**Comment by chrisbanes** [comment]
I'm not sure whether this should be provided by the library 🤔. It's trivial to implement yourself, using `Int.MAX_VALUE` items and a `mod` on the page.

**Comment by fornewid** [comment]
That's a good suggestion. Thanks for the advice.

**Comment by fornewid** [comment]
I tried the way you suggested.
But, when used with `PagerIndicator` or `PagerTab`, there is a problem that items are created infinitely.

So, I think, it would be nice to have the code implemented inside PagerState.
What do you think?

**Comment by chrisbanes** [comment]
I'm afraid this is a low priority for me, but I'd happily review a PR.

Marking this as help wanted.
