### ISSUE TITLE
[Pager][Question] How can I controll the height when I have different page sizes in HorizontalPager?

### ISSUE THREAD

**Issue by X1opya** [google/accompanist#430]
I have two page with different content size and scrollable behaviour. The page that is smaller have empty scrollable space

From another issue. `HorizontalPager will wrap the contents height. Content == current page + any offscreen pages.`

As i can see, it's expected behaviour. Do you know any solutions for solve this case? (content creates dinamicaly)

**Comment by chrisbanes** [comment]
Got a sample project? Hard to say what a solution would be without seeing an example

**Comment by X1opya** [comment]
I'll post it a little later

**Comment by X1opya** [comment]
sample

https://gist.github.com/X1opya/8a42ee671759db0ad98e42e10517cba5

**Comment by chrisbanes** [comment]
I don't really see what `HorizontalPager` can do differently here to be honest. I don't have a solution other than what is currently provided.
