### ISSUE TITLE
[Pager] after refresh() random order page in fun load

### ISSUE THREAD

**Issue by keygenqt** [google/accompanist#439]
## Describe the bug
Is this normal behavior? Why is refresh random? (Swipe Refresh & Paging)

## Expected behavior
Observance of order

## Screenshots
![screenshot-112](https://user-images.githubusercontent.com/9665914/119374411-38f21a80-bcc2-11eb-8575-011d5662902b.png)
![screenshot-113](https://user-images.githubusercontent.com/9665914/119374400-34c5fd00-bcc2-11eb-917d-14eca9a02a28.png)

## Environment:
- paging = "3.0.0"
- pagingCompose = "1.0.0-alpha09"
- compose = "1.0.0-beta07"
- accompanist = "0.10.0"

## Additional context
https://kotlinlang.slack.com/archives/CJLTWPH7S/p1621870941282100

**Comment by chrisbanes** [comment]
Is the app source available anywhere? We only call `onRefresh` after a scroll has happened (in `onPreFling`) so my guess is that this is an issue in `LazyColumn`

**Comment by keygenqt** [comment]
- [Repo](https://github.com/keygenqt/android-stack_2021/)
- [PageSourceRepo](https://github.com/keygenqt/android-stack_2021/blob/master/app/src/main/kotlin/com/keygenqt/stack_2021/network/PageSourceRepo.kt)
- [View](https://github.com/keygenqt/android-stack_2021/blob/master/app/src/main/kotlin/com/keygenqt/stack_2021/ui/home/Repos.kt)

**Comment by chrisbanes** [comment]
I'm not sure I see the issue here. `onRefresh` seems to be only called when the user drags on the list, which is correct.

What do you mean by 'Why is refresh random?'

**Comment by keygenqt** [comment]
The "load" function on refresh does not execute requests sequentially 1, 2, 3, 4. This seems strange to me. This can be seen in the log.

**Comment by chrisbanes** [comment]
Ah, I think that's just the fact that Coroutines are asynchronous. Feel free to raise a bug on the Paging library at https://issuetracker.google.com/
