### ISSUE TITLE
[Insets] systemBarsPadding

### ISSUE THREAD

**Issue by GuilhE** [google/accompanist#448]
## Describe the bug
I was using `systemBarsPadding()` version 0.8.0 with 1.0.0-beta05. Now I’m using 0.10.0 with beta07 and no `systemPadding()` is applied. Did I miss any change? 

## To Reproduce
Just a simple:
```
    AppTheme {
        Surface(modifier = Modifier.fillMaxSize().systemBarsPadding(), color = MaterialTheme.colors.background) {
            Scaffold(
                topBar = { ... },
                bottomBar = { ... }
            ) { ... }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
            super.onCreate(savedInstanceState)
            WindowCompat.setDecorFitsSystemWindows(window, false)
    }
```
**note:** same happens if padding is applied to `Scaffold`.

## Expected behavior
A working `systemBarsPadding()` in `topbar` and `bottombar`

## Environment:
 - Android OS version: Android 11
 - Device: Google Pixel 3a
 - Accompanist version: 0.10.0

## Additional context
Last time working correctly:
Accompanist: 0.8.0
Compose: 1.0.0-beta05

**Comment by chrisbanes** [comment]
Weird, this should be working. #409 actually make a big change to how the padding modifiers work underneath, along with some _actual_ [tests](https://github.com/google/accompanist/blob/13624390f273098ad860cfec78c9977119d2fea4/insets/src/androidTest/java/com/google/accompanist/insets/InsetsTest.kt). The tests check that the new `PaddingValues` impl underneath update then the insets are updated, and includes testing the `systemBars` insets.

I'll quickly test out the modifier in a Scaffold now, but I think this is probably fixed by #409.

**Comment by GuilhE** [comment]
Thanks! Any release ETA?

**Comment by chrisbanes** [comment]
It should be going in today, released next week.

**Comment by chrisbanes** [comment]
Just tried this on `0.10.0` and it is working as expected for me.

```
Surface(
    modifier = Modifier.fillMaxSize().systemBarsPadding(),
    color = MaterialTheme.colors.background
) {
    Box(Modifier.fillMaxSize()) {
        TopAppBar(
            title = {
                Text(stringResource(R.string.insets_title_basic))
            },
            backgroundColor = MaterialTheme.colors.surface,
            modifier = Modifier.fillMaxWidth()
        )

        FloatingActionButton(
            onClick = { /* */ },
            modifier = Modifier
                .align(Alignment.BottomEnd)
                .padding(16.dp)
        ) {
            Icon(
                imageVector = Icons.Default.Face,
                contentDescription = "Face icon"
            )
        }
    }
}
```

In fact, all of the samples which use `systemBars` are working as expected. If you can provide a reproducing sample I'll take a look, but I can't see an issue right now.

**Comment by GuilhE** [comment]
Just copied and pasted your code and this is the output:
![device-2021-05-28-095543](https://user-images.githubusercontent.com/2677139/119958415-f028b300-bf9a-11eb-9959-32182192f9ad.png)

This is the full setup I'm using:

```
override fun onCreate(savedInstanceState: Bundle?) {
        activityTransitionDefault.onCreateTransitions(window)
        super.onCreate(savedInstanceState)
        WindowCompat.setDecorFitsSystemWindows(window, false)

        setContent {
            NavHost(navController, startDestination = NavRouting.Home.destination) {
                composable(NavRouting.Home.destination) {
                    ShowScreen(navigationManager, navItems) { ... }
                }
               ...
           }
      }
}
```

```
@Composable
fun ShowScreen(... , content: @Composable () -> Unit) {
    AppTheme {
        Surface(
            modifier = Modifier.fillMaxSize().systemBarsPadding(),
            color = MaterialTheme.colors.background
        ) {
            Box(Modifier.fillMaxSize()) {
                TopAppBar(
                    title = {
                        Text("insets_title_basic")
                    },
                    backgroundColor = MaterialTheme.colors.surface,
                    modifier = Modifier.fillMaxWidth()
                )

                FloatingActionButton(
                    onClick = { /* */ },
                    modifier = Modifier
                        .align(Alignment.BottomEnd)
                        .padding(16.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.Face,
                        contentDescription = "Face icon"
                    )
                }
            }
        }
    }
}
```

**Comment by chrisbanes** [comment]
You seem to be missing a `ProvideWindowInsets`? https://google.github.io/accompanist/insets/#usage

**Comment by GuilhE** [comment]
God damn it! 🤦 I'm sorry for this mistake, I guess I must have wrongly deleted it (because I've it in other screens)!
Thanks for your time @chrisbanes
