### ISSUE TITLE
Insets statusBarHeight wrongly reported after comming out of PiP

### ISSUE THREAD

**Issue by rozPierog** [google/accompanist#461]
## Describe the bug
If app comes out of PiP by expand button in PiP. Top padding of systemBars isn't updated to reflect that change.

## To Reproduce
1. use`Modifier.statusBarsPadding()`
2. go to PiP
3. go back out of PiP

Here I have my app source code https://github.com/rozPierog/Cofi/blob/main/app/src/main/java/com/omelan/cofi/components/PipAwareAppBar.kt#L68
## Expected behavior
After coming out of PiP systemBar top should report height

## Screenshots?

https://user-images.githubusercontent.com/23499434/120518796-3e421a00-c3d2-11eb-8d42-3900b8392c6a.mov

## Environment:
 - Android OS version: [10,12]
 - Device: [Emulator, Google Pixel 4]
 - Accompanist version: v0.10

## Additional context
It seems to worked fine before (on version 0.7.0)

**Comment by chrisbanes** [comment]
Woops, took me a while to debug this from your app but we're missing a `remember { ... }` on the root window insets. Fixing now.

**Comment by chrisbanes** [comment]
As a workaround for now, you can use the `ProvideWindowInsets(windowInsetsAnimationsEnabled = false) { ... }` overload. That version of the function properly remembers the insets.

**Comment by rozPierog** [comment]
Thanks! Glad to hear that you managed to find and fix the issue.
Can confirm that `ProvideWindowInsets(windowInsetsAnimationsEnabled = false)` works fine

**Comment by chrisbanes** [comment]
Thanks for reporting! Would have taken me a while to find this.
