### ISSUE TITLE
[Idea][Pager] Allow peaking of next/previous items with first item left aligned and last item right aligned.

### ISSUE THREAD

**Issue by Stuart-campbell** [google/accompanist#464]
With the HorizontalPager having items less than full width, so you can peak the next/previous items, works really well with centre alignment but it would be great if it worked with align start so the first item is left aligned allowing you can see there is another item but you don't have large left padding. Then next items are centre aligned showing a bit of the previous and next items, then the last item is right-aligned just peaking the previous item without large right padding. Great libraries though!

**Comment by MarcelReiter** [comment]
I have the same issue;
I hope the video helps to understand the issue(beginning) and what would be a cool result(end).
https://user-images.githubusercontent.com/60610643/124882832-0df12b00-dfd1-11eb-98bd-2688122fdcc9.mp4

**Comment by guohao-xero** [comment]
Any solution sir?

**Comment by guohao-xero** [comment]
Do we have any solution? @MarcelReiter @Stuart-campbell

**Comment by Tornaco** [comment]
Do we got any solution sir @MarcelReiter @Stuart-campbell

**Comment by ana-ilies** [comment]
This would be a nice feature, any new thoughts on this? or ways to implement with the current version? Thanks!
