### ISSUE TITLE
[Pager] continue fling even if it jams

### ISSUE THREAD

**Issue by micHar** [google/accompanist#480]
## Describe the bug
Okay, this one is subtle. When I have a heavy page in the pager and a slower device there is a difference in fling behavior between the old ViewPager and the Pager composable. 
Consider a fling of length X which is long enough to trigger page change. 
For a heavy page, the old one will jam for a few frames, but then will continue the fling and eventually reach the page user flinged to. The Pager composable on the other hand, will jam and then snap back to the original page as if the fling wasn't long enough to trigger page change (it was, same fling on a lighter page works just fine).
This is subtle but can be really annoying in use, we are not talking about very heavy jams, just a tiny fraction of a second of jam seems to "break" the fling and user needs to make a much longer move to go to the next page.

## To Reproduce
Create a Pager with some light and heavy pages (e.g. several dozens of composables inside). Do short flings on these pages to see the difference in behavior.

## Expected behavior
Expecting the fling to continue, even if ui jams for a few frames. Just like the old the old ViewPager.

## Environment:
 - Android OS version: 9 / 11
 - Device: Huawei P20 Lite and Samsung S20 with some heavier pages, too.
 - Accompanist version: 0.11.1

**Comment by chrisbanes** [comment]
What do you mean by ‘heavy’ here? I’m not sure what ‘jam’ means either?

Do you have an of a layout where this happens? Maybe a screen record?

**Comment by micHar** [comment]
Sorry, not precise enough with my English ;). 

On a lower end device, if I have a page composable with many, many composables inside or some other "heavy" composable, e.g. bunch of large bitmaps which were not properly reduced in size, the scrolling is not so smooth anymore, by "jamming" I mean dropping frames. Obviously I should look for ways to optimise the layout further, but this issue is not about it.

I will prepare something to reproduce it or a screen record to show you what I mean.

**Comment by chrisbanes** [comment]
Have you tried increasing the offscreenLimit to 2? That would allow Pager to layout more items, which helps with complex content.

I’m not sure there’s much else that Pager can do here to be honest. It sounds like you need to optimise your content.

**Comment by micHar** [comment]
This is enough to trigger the behavior on Galaxy S20

```
@OptIn(ExperimentalPagerApi::class)
@Composable
fun PagerIssueShowcase(){

    val pagerState = rememberPagerState(pageCount = 50)

    HorizontalPager(
        state = pagerState,
        modifier = Modifier.fillMaxSize()
    ) { pageNo ->
        val childrenCount = if(pageNo % 10 == 0) 2000 else 10
        PotentiallyHeavyLayout(childrenCount)
    }

}

@Composable
fun PotentiallyHeavyLayout(children: Int){

    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.fillMaxSize().padding(32.dp)
    ) {
        repeat(children) { Text("\uD83E\uDD16") }
    }

}
```

On this video you should be able to see, that if I scroll to the left (away from the "heavy screen"), even though the fling is long enough, the page snaps back instead of scrolling to the left.

It happens every time logcat says something like "Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.".

https://user-images.githubusercontent.com/1609815/121640657-7d393500-ca8e-11eb-85b9-e460ae9cbb8f.mp4

**Comment by chrisbanes** [comment]
Yeah, that’s not something Pager can fix. You would likely get the same behaviour if you put 3 `PotentiallyHeavyLayout`s in a `Row`

**Comment by micHar** [comment]
So I should report to google issue tracker, right?

**Comment by chrisbanes** [comment]
Sure, feel free.

I’m not sure there’s anything to fix to be honest. The tool to fix this already exists: `LazyColumn`

**Comment by micHar** [comment]
I mean, sure, this is just a very simple example to show the issue, but there are lots of low end android devices and some layouts are just gonna skip a few frames now and then. The fling in old views did not break on them so I suppose it should not break in compose either. That being said, let's close this issue :).

**Comment by chrisbanes** [comment]
Sure, but that example is telling Compose to lay out 2000 separate pieces of Text. Text is actually one of the most complex things to lay out and draw.

Compose can’t magically make things fast for you if you’re using the wrong tools to begin with. Similar for Pager, it literally just lays out items at specific offset points, so the layout performance of your pages is crucial.

**Comment by micHar** [comment]
I only used 2000, because to record the video I had to use my S20 which is pretty fast. **But on a Huawei P20 Lite the problem begins at ~50 views**. I'm not saying it's a huge problem and obviously nobody should be laying out 2000 composables on a single screen, but skipped frames will just happen on low end devices, they even happen in system applications like launcher or settings there. 

https://issuetracker.google.com/issues/190788866
