### ISSUE TITLE
[DataTable] a DataTable component

### ISSUE THREAD

**Issue by dovahkiin98** [google/accompanist#486]
I've recently tried to migarate some UI elements of my application to Compose, and have faced an issue.

![image](https://user-images.githubusercontent.com/8161112/121802990-12335e00-cc48-11eb-8625-62b917e8b159.png)
![image](https://user-images.githubusercontent.com/8161112/121802992-18c1d580-cc48-11eb-819d-6935352b8e06.png)

In these UI elements, I used a `androidx.gridlayout.widget.GridLayout` to achieve the grid look of the UI. However, something like this does not currently exist in Compose (Or no longer exists).

`LazyVerticalGrid` only works if all the cells have matching dimensions. And Row of Columns and Column of Rows both have flaws that make them unable to achieve this behavior.

The Row of Columns situation is unable to set the height of each `row`

And Column of Rows is unable to set the width of each `column`.

---

In Material Components, there exists a [DataTable ](https://material.io/components/data-tables) component that does exactly this behavior, and it actually existed in Compose in the `dev` versions, but was removed and no longer exists.

What is the possibility of implementing a DataTable component in accompist? Maybe some light at why it was removed from main Compose? Or is it coming back at maybe compose 1.1.0?

It doesn't have to be exactly a DataTable. A simple Table would be enough, with Rows and Columns, as a start.

**Comment by chrisbanes** [comment]
Accompanist probably isn’t the right place for this. I recommend raising this on the Compose issue tracker: https://goo.gle/compose-feedback
