### ISSUE TITLE
[Placeholder] Failed to resolve: com.google.accompanist:accompanist-placeholder:0.11.1

### ISSUE THREAD

**Issue by ernestoyaquello** [google/accompanist#487]
## Bug description
For some reason, Gradle is unable to find the [Placeholder](https://github.com/google/accompanist/blob/main/docs/placeholder.md) library. This is what I have added to my Gradle file:

```gradle
implementation "com.google.accompanist:accompanist-placeholder:0.11.1"
```

And this is the error I get:

```
Failed to resolve: com.google.accompanist:accompanist-placeholder:0.11.1

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.accompanist:accompanist-placeholder:0.11.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/accompanist/accompanist-placeholder/0.11.1/accompanist-placeholder-0.11.1.pom
       - https://repo.maven.apache.org/maven2/com/google/accompanist/accompanist-placeholder/0.11.1/accompanist-placeholder-0.11.1.pom
       - https://jcenter.bintray.com/com/google/accompanist/accompanist-placeholder/0.11.1/accompanist-placeholder-0.11.1.pom
     Required by:
         project :app
```

## To Reproduce
1. Add the Placeholder library to your dependencies
2. Try to sync the project in Android Studio
3. Observe that the dependency cannot be resolved

## Expected behavior
The dependency should be resolvable.

## Environment:
 - Android Studio version: Artic Fox | 2020.3.1 Beta 3
 - Accompanist version: 0.11.1
 - Repositories: `google` and `mavenCentral`

## Additional context
I have added some other libraries from this repository without any issues.

**Comment by chrisbanes** [comment]
It hasn't been released yet. You'll need to use the [snapshot](https://google.github.io/accompanist/using-snapshot-version/) if you want to use it now.

**Comment by chrisbanes** [comment]
[`0.12.0-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/com/google/accompanist/accompanist-placeholder-material/0.12.0-SNAPSHOT/) is definitely available:

1) You need to add it to the `dependencies` block of the module, not the `buildscript`.
2) Remove this.
3) This is correct after fixing 1.

**Comment by d-luk** [comment]
@chrisbanes Thanks so much for the clarification! I got confused because the documentation mentions `classpath` instead of `implementation` and doesn't reference which files these changes should happen in.

And apparently my `repositories` block exists in the `settings.gradle.kts` file instead of `build.gradle.kts`, so once I put it there it worked. Thanks again!

**Comment by chrisbanes** [comment]
> @chrisbanes Thanks so much for the clarification! I got confused because the documentation mentions `classpath` instead of `implementation` and doesn't reference which files these changes should happen in.
> 
> And apparently my `repositories` block exists in the `settings.gradle.kts` file instead of `build.gradle.kts`, so once I put it there it worked.

Yeah, there's so many different ways to set this stuff up that providing support is mostly impossible 🤦 . Glad you got it working.
