### ISSUE TITLE
[Pager] How to do infinite pager?

### ISSUE THREAD

**Issue by halilozercan** [google/accompanist#507]
## Describe the bug
This is not exactly a bug but a discussion around how to do infinite pagination using Pager.

I used to give Int.MAX_VALUE to pageCount to make sure I have _almost_ an infinite pager in which I can generate pages according to their index. However, this no longer works due to this line of code in `PagerState.kt#215`

```
_currentPage = value.floorMod(pageCount)
``` 

`floorMod` does not calculate correctly when `pageCount` is at Integer's limit.

## To Reproduce
1. Create a pager state where page count is `Int.MAX_VALUE`
2. Simply apply it to any kind of Pager composable

## Expected behavior
Using this value shouldn't cause any crashes

## Environment:
 - Android OS version: Android 11
 - Device: Emulator
 - Accompanist version: 0.12.0

## Additional context

A simple workaround is using `Int.MAX_VALUE / 2`.

**Comment by fornewid** [comment]
At #429, infinite loop pager was implemented.
Please check out [`VerticalPagerLoopSample`](https://github.com/google/accompanist/blob/a3767023b63d16c2d915cddea14b28e11079137d/sample/src/main/java/com/google/accompanist/sample/pager/VerticalPagerLoopSample.kt#L74) or [`HorizontalPagerLoopSample`](https://github.com/google/accompanist/blob/a3767023b63d16c2d915cddea14b28e11079137d/sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerLoopSample.kt#L86) samples. 

Here is a simple example code:
```kt
val pagerState = rememberPagerState(
  pageCount = pages.size,
  // Allows infinite loop
  infiniteLoop = true
)
HorizontalPager( // or VerticalPager
  state = pagerState,
  modifier = Modifier
) { page ->
  ...
}
```

**Comment by halilozercan** [comment]
I'm not looking to loop the pages though. What I need is an endless pager that increments or decrements the page index everytime the user scrolls.

> I'm not sure whether this should be provided by the library 🤔. It's trivial to implement yourself, using `Int.MAX_VALUE` items and a `mod` on the page.

_Originally posted by @chrisbanes in https://github.com/google/accompanist/issues/429#issuecomment-846377090_

I did exactly as Chris told here. However, that suggestion now crashes due to `floorMod`.

**Comment by chrisbanes** [comment]
> I'm not looking to loop the pages though. What I need is an endless pager that increments or decrements the page index everytime the user scrolls.

You're better off creating your own layout. We won't be implementing something like this.

**Comment by halilozercan** [comment]
Hey @chrisbanes as your previous comment that I quoted here, it was fine to use `Pager` for a use case like this until `floorMod` was added. I believe a small fix to implementation of that function would solve this problem.
