### ISSUE TITLE
[Bug][Insets] Animated IME support is broken

### ISSUE THREAD

**Issue by danielesegato** [google/accompanist#512]
## Describe the bug
Trying to follow the [insets documentation](https://google.github.io/accompanist/insets/#controlling-the-ime-on-screen-keyboard) did not produce the expected results:

- the IME pop up when I overscroll at the bottom of my screen, even if there's no text field selected
- there's a lot of padding at the bottom when you select the `TextField`
- and in the whole thing act weirdly.

I've tried to follow the documentation, but it is outdated (the [example](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/insets/ImeAnimationSample.kt) doesn't even compile in the compose `1.0.0-beta08`). The doc still refers to `ScrollableColumn` which has been deprecated in compose `1.0.0-alpha11` (and later removed). Maybe this part simply doesn't work or there's something else to do?

In my App I've a `Scaffold` with a `NavHost` containing several screens, some of those have `TextField` and I'd like to integrate with the IME animation and I couldn't achieve it.

## To Reproduce
I've adjusted the official example just enough to make it compile (well I used Coin instead of Glide but whatever).

Comments show where I had to do something to make it compile

Try it yourself:

```kotlin
@AndroidEntryPoint
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Turn off the decor fitting system windows, which means we need to through handling
        // insets
        WindowCompat.setDecorFitsSystemWindows(window, false)

        setContent {
            Content()
        }
    }
}

@Composable
fun Content() {
    // Update the system bars to be translucent
    val systemUiController = rememberSystemUiController()
    val useDarkIcons = MaterialTheme.colors.isLight
    SideEffect {
        systemUiController.setSystemBarsColor(Color.Transparent, darkIcons = useDarkIcons)
    }

    MaterialTheme {
        ProvideWindowInsets(windowInsetsAnimationsEnabled = true) {
            Main()
        }
    }
}

@OptIn(ExperimentalAnimatedInsets::class)
@Composable
fun Main() {
    val listItems = remember {
        List(40) {
            "https://picsum.photos/seed/$it/300/300"
        }
    }
    Scaffold(
        topBar = {
            // We use TopAppBar from accompanist-insets-ui which allows us to provide
            // content padding matching the system bars insets.
            TopAppBar(
                title = { Text("Whatever") },
                backgroundColor = MaterialTheme.colors.surface,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding( // <---- this padding was a contentPadding attribute in the TopAppBar, which doesn't exist anymore
                        rememberInsetsPaddingValues(
                            LocalWindowInsets.current.statusBars,
                            applyBottom = false,
                        )
                    ),
            )
        },
        bottomBar = {
            Surface(elevation = 1.dp) {
                val text = remember { mutableStateOf(TextFieldValue()) }
                OutlinedTextField(
                    value = text.value,
                    onValueChange = { text.value = it },
                    placeholder = { Text(text = "Watch me animate...") },
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 16.dp, vertical = 8.dp)
                        .navigationBarsWithImePadding()
                )
            }
        },
        modifier = Modifier.fillMaxSize()
    ) { contentPadding ->
        Column {
            // We apply the contentPadding passed to us from the Scaffold
            LazyColumn(
                contentPadding = contentPadding,
                reverseLayout = true,
                modifier = Modifier
                    .weight(1f)
                    .nestedScroll(connection = rememberImeNestedScrollConnection())
            ) {
                items(listItems) { imageUrl ->
                    ListItem(imageUrl, Modifier.fillMaxWidth())
                }
            }
        }
    }
}

@Composable
fun ListItem(
    imageUrl: String,
    modifier: Modifier = Modifier
) {
    Row(modifier.padding(horizontal = 16.dp, vertical = 8.dp)) {
        Image(
            painter = rememberCoilPainter(imageUrl),
            contentDescription = null,
            modifier = Modifier
                .size(64.dp)
                .clip(RoundedCornerShape(4.dp)),
        )

        Spacer(Modifier.width(16.dp))

        Text(
            text = "Text",
            style = MaterialTheme.typography.subtitle2,
            modifier = Modifier.weight(1f)
                .align(Alignment.CenterVertically)
        )
    }
}
```

## Expected behavior
I would expect the following
- updated documentation on how to integrate in a project (possibly not with the textfield in the bottom bar but with it in the actual content of the app)
- The IME keyboard DO NOT show up when scrolling to the bottom
- No extra padding when selecting an IME field
- Scroll is not messed up but just work as you expect

## Screenshots
Just opened the textfield, can't scroll, I can only close the keyboard

![device-2021-06-21-184733](https://user-images.githubusercontent.com/469948/122798777-43073900-d2c1-11eb-81b1-6202c25e74eb.png)

Scrolled to the bottom of the screen and I keep scrolling up (why is the keyboard showing? what's the black? why the padding?)

![device-2021-06-21-184753](https://user-images.githubusercontent.com/469948/122798808-4ac6dd80-d2c1-11eb-8306-0d3fcf805d0f.png)

## Environment:
 - Android OS version: Android 11
 - Device: Pixel 2
 - Accompanist version: `0.12.0`

## Additional context
Well if I didn't give you enough information just ask :)

And before you ask: yes I did add `android:windowSoftInputMode="adjustResize"` to the manifest

**Comment by chrisbanes** [comment]
The sample you linked to definitely does compile, as it's part of the library's build. I recommend that you take a careful look at the imports, as the sample is now using the new Insets UI module: https://google.github.io/accompanist/insets/#inset-aware-layouts-insets-ui
