### ISSUE TITLE
I use compose Coil in Paging LazyColumn, and it often fails to load

### ISSUE THREAD

**Issue by luhuanxml** [google/accompanist#519]
## Environment:
 - Android OS version: [e.g. Android 5.0]
 - Device: [e.g. Emulator, Google Pixel 4]
 - Accompanist version: [e.g. v0.X]

**Comment by chrisbanes** [comment]
Without a reproducible sample this is impossible to debug. I use a similar setup in Tivi and it works as expected.

**Comment by beworker** [comment]
I had this bug today while trying out [examples from "Layouts in Jetpack Compose - Working with Lists"](https://developer.android.com/codelabs/jetpack-compose-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fcompose%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-layouts#5). 

Exactly the code from the CodeLab showed the list with no images on emulator, while on the real device (Honor FRD-L09, Android 7.0) the code worked as expected and the icons were visible.

Emulator screenshot:
<img width="360" alt="Screenshot 2021-07-17 at 18 38 12" src="https://user-images.githubusercontent.com/768721/126043786-af98428b-2ece-40ed-84a8-23c8e29183b6.png">

Emulator: Pixel 2, API 29, 
Android Studio Bumblebee | 2021.1.1 Canary 3
Build #AI-211.7442.40.2111.7518594, built on July 2, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Registry: ide.instant.shutdown=false, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.5.21-release-317-AS7442.40)

**Comment by chrisbanes** [comment]
As Accompanist-Coil is [now deprecated](https://github.com/google/accompanist/releases/tag/v0.14.0), I'm going to close this. Please try out the new official Coil support!
