### ISSUE TITLE
[Insets] Text Goes Below The IME

### ISSUE THREAD

**Issue by wakaztahir** [google/accompanist#527]
**Is your feature request related to a problem? Please describe.**
Yes , Using insets works , unless you use it in a Column that can scroll (LazyColumn & Column with Vertical Scroll Modifier) , What happens is insets work but the moment the IME is opened the scroll changes which causes the text field inside lazy column to keep the same scroll state even when  you keep typing and eventually text goes below the keyboard

### Problem 
Now we have the content padding on bottom in the LazyColumn but scroll has changed and the **text on the Text Field goes below the keyboard** , **If you put a Text Field inside Lazy Column or Column that has vertical Scroll modifier**  insets don't really help because the text would go below the keyboard !!

**Describe the solution you'd like**
An easy way to integrate insets into the LazyColumn so text does not go below the keyboard

**Describe alternatives you've considered**
https://stackoverflow.com/questions/67138999/textfield-ime-padding-in-lazycolumn-compose
I created this detailed question on stackoverflow , The only solution is scrolling the page every time the text changes so that the text remains above the keyboard (scroll state should follow the cursor)

**Comment by chrisbanes** [comment]
Not much else that Accompanist can do. I'll follow your [issue](https://issuetracker.google.com/issues/192043120)
