### ISSUE TITLE
[Coil] Cannot disable cache to force refetching of the image with the same url

### ISSUE THREAD

**Issue by VitaliyDoskoch** [google/accompanist#539]
**Is your feature request related to a problem? Please describe.**
Hi! I can't disable a Coil cache strategy. If the url of the image is the same, Coil doesn't load the image again (but images are different). It doesn't matter if I use `memoryCacheKey` or `memoryCachePolicy` methods.  I guess, the issue is in `rememberCoilPainter`, because it doesn't recompose when a new image arrives. To force a recomposition of the `Banner` I've created the `ImageUpdate` class, which contains a modification timestamp, that differs every time. But still, nothing happens. Here's my code to display a banner:
```
data class ImageUpdate(val url: String?, val modificationTimestamp: Long)

@Composable
private fun Banner(banner: ImageUpdate) {
    Timber.e("Banner: $banner")

    val painter = rememberCoilPainter(
        request = banner.url,
        requestBuilder = {
            Timber.e("requestBuilder")
            memoryCacheKey(banner.toString())
        },
        shouldRefetchOnSizeChange = { _, _ ->
            Timber.e("shouldRefetchOnSizeChange")
            true
        }
    )

    Image(
        painter = painter,
        contentDescription = null
    )
}
```

Here are the logs of the first image request and the following image update (the same url, but different images):
```
E/BannerContainerKt: Banner: ImageUpdate(url=content://com.file_provider/Banner.jpg, modificationTimestamp=1625232753481)
E/BannerContainerKt$Banner$painter: requestBuilder
E/BannerContainerKt$Banner$painter: requestBuilder
E/BannerContainerKt$Banner$painter: shouldRefetchOnSizeChange
E/BannerContainerKt$Banner$painter: requestBuilder
E/BannerContainerKt: Banner: ImageUpdate(url=content://com.file_provider/Banner.jpg, modificationTimestamp=1625232759917)
```

**Describe the solution you'd like**
Please, allow to set a key to the `rememberCoilPainter` function or make `CoilLoader` public.

**Comment by chrisbanes** [comment]
Please raise this on the Coil issue tracker. The Accompanist Coil library is currently in the process of being upstreamed.

/cc @colinrtwhite

**Comment by colinrtwhite** [comment]
@VitaliyDoskoch You can add a parameter to the image request to change its `equals`/`hashCode` and force it to be re-executed:

```kotlin
val painter = rememberCoilPainter(
        request = banner.url,
        requestBuilder = {
            Timber.e("requestBuilder")
            memoryCacheKey(banner.toString())
            setParameter("image_update", banner, cacheKey = null)
        },
        shouldRefetchOnSizeChange = { _, _ ->
            Timber.e("shouldRefetchOnSizeChange")
            true
        }
    )
```

**Comment by VitaliyDoskoch** [comment]
@colinrtwhite Sorry, but this solution doesn't work. `requestBuilder` is not called, because the recomposition of the painter is skipped.

**Comment by colinrtwhite** [comment]
@VitaliyDoskoch Hmm can you append a fake query parameter to the URL? It's not out yet, but I've made some changes in the upstream version of Accompanist [here](https://github.com/coil-kt/coil/pull/790) that will make `requestBuilder` be re-called.

**Comment by VitaliyDoskoch** [comment]
Sorry for the late response. The new version of coil-kt works just fine, thank you.
