### ISSUE TITLE
[Pager] The initialOffscreenLimit value becomes default if you switch between tabs using the bottom navigation

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [google/accompanist#545]
## Describe the bug
I use a pager with several items visible on the screen at the same time, so the value in the `initialOffscreenLimit` is large (e.g. 7). If I open the screen for the first time everything is OK, All elements are visible, but if I switch between tabs and go back I only see 2 items

## To Reproduce
1. Go to the screen with a pager that has few simultaneously visible items on the screen
2. Switch navigation tab.
3. Go back.
4. See error.

## Expected behavior
After switching back, all expected elements should be visible.

## Screenshots
Example:

https://user-images.githubusercontent.com/36794185/124895173-fe7bdd00-dfe4-11eb-9f0d-736db8bc9fbb.mov

## Environment:
 - Android OS version: Android 10.0
 - Device: Emulator, Google Pixel 4
 - Accompanist version: v0.13.0

**Comment by wthee** [comment]
@chrisbanes Maybe initialOffscreenLimit also needs to be added to   `PagerState.Saver`
