### ISSUE TITLE
[Idea] create composables to handle BottomSheet in the toolkit itself

### ISSUE THREAD

**Issue by mslalith** [google/accompanist#567]
When using `ModalBottomSheetLayout` within a page in `HorizontalPager`, I can still scroll to a different page even when the BottomSheet is visible. This does not comply with the Android (using layouts) behavior

**Proposal**
Create `showBottomSheet` & `showModelBottomSheet` composables to show BottomSheet's and expose a `LocalXXX` provider or any other alternative which best suits this scenario for us to control it

**Comment by chrisbanes** [comment]
>  This does not comply with the Android (using layouts) behavior

There is nothing in `ViewPager[2]` to stop this happening so I'm not sure how you are seeing that.

Pager should not know anything about other composables, so adding the parameters you mentioned isn't going to happen. Also, this isn't specific to `HorizontalPager` and will happen with any horizontally scrolling layout.

If you want to stop horizontal scrolls while the bottom sheet is expanded, you can add a [`Modifier.nestedScroll()`](https://developer.android.com/reference/kotlin/androidx/compose/ui/input/nestedscroll/package-summary) to your content to consume those events. You could also use the [`dragEnabled`](https://google.github.io/accompanist/api/pager/pager/com.google.accompanist.pager/-horizontal-pager.html) parameter.
