### ISSUE TITLE
[SwipeRefresh] Hidden indicator is visible on screen when using padding and clip is disabled

### ISSUE THREAD

**Issue by dimsuz** [google/accompanist#572]
## Describe the bug
When using `SwipeRefresh` like this

```kotlin
    SwipeRefresh(
      state =  rememberSwipeRefreshState(isRefreshing = isRefreshing,
      onRefresh = { ... },
      indicatorPadding = PaddingValues(top = 52.dp),
      clipIndicatorToPadding = false,
      content
    )
```

After releasing the tap I am left with this picture.
Follow the arrow to see the empty shell of once great swipe to refresh indicator.
I kinda understand why it's there, but it still seems like it should hide completely.

![image](https://user-images.githubusercontent.com/42920/126323548-75a00aa4-6d86-4b56-9966-5fbebcc25189.png)

## Environment:
 - Android OS version: 28
 - Device: Emulator
 - Accompanist version: 0.14.0

**Comment by chrisbanes** [comment]
I can't get the indiciator to remain there after a 'tap', so if could provide a reproducible sample that would be great.

For this specific use-case, the `scale` parameter is very important. This [sample](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshContentPaddingSample.kt#L110) demonstrates this.

We could possible fade the indicator in over the first 5% or something, but I'm not sure that we want to expose that as an API.

**Comment by dimsuz** [comment]
Thanks for the scale hint, will try it.
Also I'll try to reproduce in a minimum sample project and attach it.

**Comment by dimsuz** [comment]
I can reproduce it only when I add `PaddingValues(top = 52.dp)` + `clipIndicatorToPadding = false`. Didn't mention this explicitly.
Still will try to isolate and attach. Perhaps it's still my setup which somehow matters.

**Comment by chrisbanes** [comment]
We could possibly default `scale` to true if `contentPadding.top` > 0.dp, but it feels a little magic and undiscoverable

**Comment by FilippoVigani** [comment]
@chrisbanes this is still an issue with the default `SwipeRefreshIndicator`

**Comment by mars885** [comment]
I'm using the 0.25.1 version and have experienced this today.

@chrisbanes Has this been fixed as of some version because I see that the status is closed?
