### ISSUE TITLE
[Permissions] PermissionsRequired component doesn't support preview

### ISSUE THREAD

**Issue by ntoskrnl** [google/accompanist#576]
## Describe the bug
When I use `PermissionsRequired` composable it doesn't show up in the preview. In fact, the preview crashes.

## To Reproduce
1. Create a preview with content with `PermissionsRequired` composable
2. Open preview screen in Android Studio

## Expected behavior
If `PermissionsRequired` is rendered from preview context, display "Permissions not granted" composable?

## Environment:
- Android Studio Arctic Fox RC1
 - Accompanist version: [0.14.0]

**Comment by manuelvicnt** [comment]
This is working as intended as Preview doesn't work with Android lifecycle at the moment. Since permissions need to check for the current state of the permission, the preview breaks.

**Comment by t1u1** [comment]
This is unfortunate as it breaks preview for top-level components that include sub-components that need permissions.

Wouldn't it be OK to assume that Permissions have not been granted when running outside of an Activity context?

The exception is being thrown from [this line](https://github.com/google/accompanist/blob/main/permissions/src/main/java/com/google/accompanist/permissions/PermissionsUtil.kt#L105).

**Comment by ln-12** [comment]
I can strongly  support @t1u1 as I have an entire screen which is dependent on a permission. Is there a possible solution/workaround planned for the future @manuelvicnt?

**Comment by manuelvicnt** [comment]
👋  hello! The `PermissionsRequired` APIs have been removed in the upcoming version of Accompanist, read more about it in #990
