### ISSUE TITLE
[Idea] Add Support for Firebase Storage Reference

### ISSUE THREAD

**Issue by madhurgupta10** [google/accompanist#579]
**Is your feature request related to a problem? Please describe.**
We use Firebase Storage (https://firebase.google.com/docs/storage/android/start) for our images, we used Glide which has built-in support for Firebase Storage Reference.

**Describe the solution you'd like**
It would be great if accompanist can load Images from a Firebase Storage Reference automatically.

**Describe alternatives you've considered**
We currently use https://github.com/skydoves/Landscapist as alternative.

**Comment by chrisbanes** [comment]
Accompanist Coil and Glide is now deprecated, so no chance of this happening unfortunately. Closing
