### ISSUE TITLE
[Insets] Keyboard bottom padding when using only imePadding()

### ISSUE THREAD

**Issue by mslalith** [google/accompanist#584]
When I use `imePadding()`, the padding is a bit weird and not having the correct height as the keyboard.
This works with `navigationBarsWithImePadding()`
<br>

![ime_inset_animation_bug](https://user-images.githubusercontent.com/15076234/127150067-07f442d9-5972-4fa5-8ece-1039fef57815.gif)
<br>

## Code
```kotlin
@OptIn(ExperimentalMaterialApi::class)
@Composable
fun ImeInsetsAnimationIssue() {
    var text by remember { mutableStateOf("") }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .statusBarsPadding()
            .navigationBarsPadding(),
    ) {
        Column(
            modifier = Modifier
                .imePadding(),
        ) {
            LazyColumn(
                modifier = Modifier.weight(weight = 1f),
            ) {
                items(count = 60) {
                    ListItem(
                        text = {
                            Text(
                                text = "Item $it",
                                style = TextStyle(color = MaterialTheme.colors.onBackground)
                            )
                        }
                    )
                }
            }
            TextField(
                value = text,
                onValueChange = { text = it },
            )
        }
    }
}
```

**Comment by chrisbanes** [comment]
Have you followed the checklist? https://google.github.io/accompanist/insets/#something-not-working

**Comment by mslalith** [comment]
yeah, I followed all those

**Comment by chrisbanes** [comment]
`imePadding()` works for me on various API levels (tried 24, 26 and 30).

Looking at your sample, I think the issue is that `Box` by default does not propagate the minimum constraints to it's content, and therefore the `Column` is implicitly wrapping it's content's height, which breaks the `imePadding()` and `weight(1f)`. You can fix that by calling `Box(propagateMinConstraints = true, ...)`

**Comment by mslalith** [comment]
@chrisbanes Calling `Box(propagateMinConstraints = true, ...)` didn't help

**Comment by chrisbanes** [comment]
I'm afraid that's as much help as I can provide right now. I've verified that `imePadding()` is working fine. 

Your issue is a general layout issue, which worked fine for me locally when  using the `Box` thing I mentioned above.

**Comment by mslalith** [comment]
Okay, I'll try with different layouts

**Comment by iamutkarshtiwari** [comment]
@chrisbanes I am facing a similar issue on Android 10 with `imePadding()`. 
`Box(propagateMinConstraints = true, ...)` didn't help either.

Keyboard hidden | Keyboard active
:--: | :--:
<img src="https://user-images.githubusercontent.com/6258810/127735080-1dfa29a5-b7a9-4c51-99fb-2830e4757e8b.png" width="300" /> | <img src="https://user-images.githubusercontent.com/6258810/127735086-afc9d35c-5076-4879-9f25-198e31ab18d1.png" width="300" />

**Comment by iamutkarshtiwari** [comment]
@mslalith Setting this attribute to my activity solved this issue:
`android:windowSoftInputMode="adjustResize"`
