### ISSUE TITLE
[Pager] Can't be scrolled to previous page while observing isScrollInProgress state

### ISSUE THREAD

**Issue by kefasjwiryadi** [google/accompanist#585]
## Describe the bug

Pager can't be scrolled to previous page while observing `PagerState.isScrollInProgress` state. Scrolling to the next page doesn't have any problem.

## To Reproduce
1. Observe `PagerState.isScrollInProgress` state
2. Scroll the pager to the previous page

## Expected behavior
Pager should be able to scroll to the previous page

## Video

https://user-images.githubusercontent.com/11681703/127167341-0233a6b8-2cf1-4226-802e-4e87da9c50da.mp4

## Environment:
 - Android OS version: Android 10
 - Device: Emulator
 - Accompanist version: v0.14.0

## Code

```
import android.os.Bundle
import androidx.activity.compose.setContent
import androidx.appcompat.app.AppCompatActivity
import androidx.compose.foundation.layout.*
import androidx.compose.material.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import com.google.accompanist.pager.ExperimentalPagerApi
import com.google.accompanist.pager.HorizontalPager
import com.google.accompanist.pager.rememberPagerState


class MainActivity : AppCompatActivity() {

    @ExperimentalPagerApi
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface {
                    val state = rememberPagerState(
                        pageCount = 5,
                        infiniteLoop = true
                    )
                    Column {
                        Text(text = "${state.isScrollInProgress}")
                        HorizontalPager(
                            state = state
                        ) { page ->
                            Text(
                                text = "page $page",
                                Modifier
                                    .fillMaxWidth()
                                    .height(500.dp),
                                textAlign = TextAlign.Center,
                                style = MaterialTheme.typography.h1
                            )
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by chrisbanes** [comment]
Thanks for the report. Here's my very rough guess at what is happening:

It seems that reading `isScrollInProgress` in the same block as the `HorizontalPager` is causing issues, as it will cause the block to be recomposed whenever `isScrollInProgress` changes. That recomposition happens at the end of the scroll, but it seems that `HorizontalPager` doesn't finish it's internal scroll if this happens.

**Comment by kefasjwiryadi** [comment]
> It seems that reading isScrollInProgress in the same block as the HorizontalPager is causing issues

Yeah, if I move the reader into another composable, the pager can be scrolled to the previous page.

```
@Composable
fun PagerStateText(state: PagerState) {
    Text(text = "${state.isScrollInProgress}")
}
```

**Comment by chrisbanes** [comment]
Yep, that sounds consistent then. Just need to work out what is stopping the scroll from finishing
