### ISSUE TITLE
[Pager] Scrolling offset when used in a scrollable Column inside a ComposeView

### ISSUE THREAD

**Issue by danielkap** [google/accompanist#589]
## Describe the bug
When using a horizontal pager inside a scrollable Column which is part of a ComposeView inside a relative layout, the vertical scrolling jumps to a slight offset, when switching pages. Offset seems to match the toolbar-height.

## To Reproduce
1. Create a new Non-Compose Project  and add Compose support
2. Display a relative layout with a Toolbar and add a `ComposeView` positioned below that Toolbar
3. Fill the ComposeView with a Scrollable Column and fill that column with a Spacer and a `HorizontalPager`

## Expected behavior
The Pager is scrolling as expected without affecting the scrollposition of its surrounding Column

# Screenshots?
Recording below
https://user-images.githubusercontent.com/47595434/127519987-54de2227-40e9-4e01-89eb-7ee4a122cef1.mov

## Environment:
 - Device: Emulator (Pixel 3 API 30) as well as Xiaomi Redmi Note 8
 
## Additional context
The relative layout
https://github.com/danielkap/scrollbug/blob/main/app/src/main/res/layout/activity_main.xml
The MainActivity containing the Composables
https://github.com/danielkap/scrollbug/blob/main/app/src/main/java/com/example/scrollbug/MainActivity.kt

So far I've only had this problem using Pager, hence this issue. However I'm not entirely sure if this is actually a Pager issue since I wouldn't expect the ComposeView contents to be influenced by the RelativeLayout in the first place.
If this is outside of Accompanists scope but you have an Idea on what might cause it,  I'd be happy if you could pinpoint me to  the relevant project/issue platform.

**Comment by chrisbanes** [comment]
Hard to exactly say what the issue is, but I don't think this is a `Pager` issue.

- Your `<ComposeView>` to set to `wrap_content` height, which means that your composable has unbounded layout constraints.
- You're using `Column` with `verticalScroll()`, which means that the content also has unbounded layout constraints. 

Basically there's so much unbounded-ness in that layout that I'm not surprised that things are jumping around.

**Comment by danielkap** [comment]
Thanks for the quick reply.

The bug also occurs when using `match_parent` is set as well as when the `HorizontalPager` and the `Column` have a fixed height modifier. Sorry, the example was thrown together rather quickly. I've now added some height constraints to the example as well.
Thats why I would have suspected a problem in the relation between the  `HorizontalPager` and `verticalScroll()`

Anyway, I'm gonna give the Google Issues a shot then.

Have a nice Weekend
