### ISSUE TITLE
StatusBar cannot be collapse

### ISSUE THREAD

**Issue by Nthily** [google/accompanist#591]
## Describe the bug

Status bar cannot be collapsed after expand
![demo](https://user-images.githubusercontent.com/31311826/127726101-1736bc51-e640-49cd-82df-2570165ef7ac.gif)

## To Reproduce
``` kotlin
  setContent {
      MaterialTheme {
          val systemUiController = rememberSystemUiController()
          systemUiController.isStatusBarVisible = false
          ControlUI(controlViewModel)
      }
  }
```

## Environment:
 - Device: Pixel 5 API 30
 - Accompanist version: 0.15.0

**Comment by chrisbanes** [comment]
I don't see a bug here. That sample obviously isn't enough to recreate this as you haven't included `ControlUI()`.

**Comment by Nthily** [comment]
But it is the same for a new project
![demo](https://user-images.githubusercontent.com/31311826/127880527-ee8f3ab4-0d2f-466b-83c1-343bce820ead.gif)

info:
* composeVersion: 1.0.0
* Accompanist version: 0.15.0
* Device: Pixel 5 API 30
* compileSdk 30
* minSdk 21
* targetSdk 30
* kotlinVersion: 1.5.10
* com.android.tools.build:gradle:7.1.0-alpha03
