### ISSUE TITLE
[HorizontalPagerIndicator] Active bullet draws outside of the max width

### ISSUE THREAD

**Issue by timrijckaert** [google/accompanist#593]
## Describe the bug

When using the `HorizontalPagerIndicator` with a lot of items inside the _active bullet_ is drawn outside of the required width defined by the `Modifier`.

Consider following example

```kotlin
Column(Modifier.fillMaxSize()) {
    // Display 10_000 items
    val pagerState = rememberPagerState(
        pageCount = 10_000,
        // We increase the offscreen limit, to allow pre-loading of images
        initialOffscreenLimit = 2,
    )

    HorizontalPager(
        state = pagerState,
        modifier = Modifier
            .weight(1f)
            .fillMaxWidth(),
    ) { page ->
        Text(
            "hello",
            modifier = Modifier
                .fillMaxWidth(0.8f)
                .aspectRatio(1f)
        )
    }

    HorizontalPagerIndicator(
        pagerState = pagerState,
        modifier = Modifier
            .fillMaxWidth(.3f)
            .align(Alignment.CenterHorizontally)
            .padding(16.dp),
    )
}
```

It renders 

<img width="515" alt="Screen Shot 2021-08-02 at 11 45 50" src="https://user-images.githubusercontent.com/6739443/127842025-3fc1ec0a-1d91-4ff3-afa2-3f4396eb42d1.png">

## Expected behavior
The _active bullet_ should **NEVER** draw outside of the max width.  
Ideally we want to have similar behavior to Instagram's implementation.  

![Screenshot_20210802-115146](https://user-images.githubusercontent.com/6739443/127842538-7ef1d4dd-086f-4a1c-a512-7e50b508e870.jpg)

## Environment:
 - Android OS version: All
 - Device: All
 - Accompanist version: 0.15.0

**Comment by chrisbanes** [comment]
The current indicators were never meant to be a perfect implementation, and were mostly there as a demonstration of the basic API. I don't have the time to implement a version which works like Instragram, but would gladly accept a PR.

**Comment by RotBolt** [comment]
Hello @chrisbanes 
I could pick up this issue. But I could take time to work on it frankly speaking. I am new to compose actually 😅
