### ISSUE TITLE
Pager - Can't customise semantics

### ISSUE THREAD

**Issue by ThomasArtProcessors** [google/accompanist#599]
Unless there is a way I am not aware of, Talkback currently reads extra information on each page of the Pager due to the semantics being set internally in the Pager's code.
It reads things like "Selected [...] double tap to toggle", which does not fit my actual designs.
Each page has a button, which is the clickable action. 
I would like to remove this extra semantics and let the content of each Page figure itself out, but I couldn't figure out a way.

**Comment by chrisbanes** [comment]
Thanks for the report. Thinking about it`selected` probably isn't the right semantic property to use here (which is more for things like radio buttons). I'll remove this for now and asking the accessibility team what the right approach is.
