### ISSUE TITLE
Navigator com.google.accompanist.navigation.animation.AnimatedComposeNavigator@1b25ab is replacing an already attached com.google.accompanist.navigation.animation.AnimatedComposeNavigator@9c08e21   

### ISSUE THREAD

**Issue by ln-12** [google/accompanist#610]
## Describe the bug
When using the new `Navigation-Animation` component, I come across the following crash:

```bash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxxxx.androidApp, PID: 22863
    java.lang.IllegalStateException: Navigator com.google.accompanist.navigation.animation.AnimatedComposeNavigator@1b25ab is replacing an already attached com.google.accompanist.navigation.animation.AnimatedComposeNavigator@9c08e21
        at androidx.navigation.NavigatorProvider.addNavigator(NavigatorProvider.kt:109)
        at androidx.navigation.NavigatorProvider.addNavigator(NavigatorProvider.kt:87)
        at com.google.accompanist.navigation.animation.NavHostControllerKt.rememberAnimatedNavController(NavHostController.kt:40)
        at xxxxx.androidApp.MainActivity$onCreate$1.invoke(MainActivity.kt:68)
        at xxxxx.androidApp.MainActivity$onCreate$1.invoke(MainActivity.kt:49)
```

## To Reproduce
The sample [here](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/navigation/animation/AnimatedNavHostSample.kt) works fine, so I tried to find the reason for the crash. I found that passing my viewmodel inside a composable is the reason. I have multiple viewmodels for my screens, but I also have one viewmodel which sets up Broadcast receivers for my activity that need to be accessed across multiple screen for the whole runtime of the app. So for example when I do this, it crashes:
```kotlin
@OptIn(ExperimentalAnimationApi::class)
@Composable
fun MainLayout() {
    val appViewModel: AppViewModel = viewModel()
    val navController = rememberAnimatedNavController()
    
    AppTheme {
        Surface {
            AnimatedNavHost(navController, startDestination = "start") {
                composable("start") {
                    StartScreen(appViewModel = appViewModel) {
                        when (it) {
                            StartScreen.SignIn -> navController.navigate("SignIn")
                            StartScreen.SignUp -> navController.navigate("SignUp")
                        }
                    }
                }
            }
        }
    }
}
```

But when I remove the appViewModel as argument, it works fine (except that I don't got a reference to it in my StartScreen composable). When using the normal `NavHost`, it also works without any issue. What am I missing?

## Expected behavior
No crash.

## Environment:
 - Android OS version: Android 11 (Pixel Experience)
 - Device: Xiaomi Mi Mix 2S
 - Accompanist version: 0.16.0

**Comment by jossiwolf** [comment]
@jbw0033 I think we should memoize the `AnimatedComposeNavigator` instance for this, currently, we create a new one on every composition.

@ln-12 In the meantime you can use this to obtain a `NavController` with an `AnimatedComposeNavigator`:

```kotlin
@ExperimentalAnimationApi
@Composable
public fun rememberAnimatedNavController(): NavHostController {
    val navController = rememberNavController()
    val animatedNavigator = remember(navController) { AnimatedComposeNavigator() }
    return navController.apply {
        navigatorProvider += animatedNavigator
    }
}
```

**Comment by ln-12** [comment]
@jossiwolf Thanks for your super fast reply, that's awesome! With your code, it works fine now, thank you :)
