### ISSUE TITLE
Jetpack Compose 1.1.0-alpha01

### ISSUE THREAD

**Issue by b95505017** [google/accompanist#612]
Should we use snapshot version of this library, or will you publish another release for `1.1.0-alpha01`?

**Comment by chrisbanes** [comment]
Accompanist v0.16.0 works with both Compose v1.0 and v1.1.x, so there's no need to diverge right now.

The only reason to update would be to use new 1.1.x APIs, but we don't need to do right now.

**Comment by b95505017** [comment]
@chrisbanes It would be nice to note it in change log. (e.g. support 1.0~1.1.x)

**Comment by chrisbanes** [comment]
Good idea, updated.
