### ISSUE TITLE
Using a BottomSheetNavigator.Destination route as startDestination produces IllegalArgumentException

### ISSUE THREAD

**Issue by chrisfillmore** [google/accompanist#617]
## Describe the bug
If you use a bottom sheet destination as the `startDestination` in your nav graph, you will get IllegalArgumentException:
```
java.lang.IllegalArgumentException: The initial value must have an associated anchor.
```

## To Reproduce
I have uploaded a sample project here: https://github.com/chrisfillmore/navigation_material_bug

The exception can be produced with the following simple code:

```Kotlin
class MainActivity : ComponentActivity() {
  @ExperimentalMaterialNavigationApi
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContent {
      val bottomSheetNavigator = rememberBottomSheetNavigator()
      val navController = rememberNavController().apply {
        navigatorProvider += bottomSheetNavigator
      }
      ModalBottomSheetLayout(bottomSheetNavigator = bottomSheetNavigator) {
        NavHost(
          navController = navController,
          startDestination = "myBottomSheet",
        ) {
          composable("myComposable") {

          }

          bottomSheet("myBottomSheet") {

          }
        }
      }
    }
  }
}
```

## Expected behavior
Navigation should navigate to the bottom sheet as the initial destination.

## Environment:
- Android OS version: Android 11
- Device: Samsung A51
- Versions:
```
compose_version = '1.0.1'
navigation_compose_version = '2.4.0-alpha06'
accompanist_version = '0.16.0'
```

**Comment by jossiwolf** [comment]
Thank you for the report! The workaround is pretty simple: just add some content to your sheet.
Not sure if we're going to provide a fix for this, the underlying issue comes from ModalBottomSheetLayout, see https://issuetracker.google.com/issues/178529942.

**Comment by chrisfillmore** [comment]
Thanks for responding! You're right, I managed to miss this. In case anyone is wondering what went wrong for me, I had code like:

```Kotlin
bottomSheet(...) {
  val list = /* get list from somewhere */
  for (item in list) {
    // call composables
  }
}
```
But in my case, `list` was empty, so the bottom sheet was empty. Hence the exception.
