### ISSUE TITLE
Compose Navigation App Crashes with an Exception

### ISSUE THREAD

**Issue by Pitam-Poudel** [google/accompanist#621]
java.lang.IllegalStateException: Navigator com.google.accompanist.navigation.animation.AnimatedComposeNavigator@2c4301a0 is replacing an already attached com.google.accompanist.navigation.animation.AnimatedComposeNavigator@31048ba3

Don't know why but I am getting this error when used rememberAnimatedNavController() in my project.

**Comment by Pitam-Poudel** [comment]
@EddieRingle @cdibona @chrisbanes @handstandsam  please help

**Comment by jossiwolf** [comment]
See #610. The fix has been implemented but not released yet, feel free to grab a snapshot build in the meantime.
