### ISSUE TITLE
FlowRow affects Modifier.height(IntrinsicSize)

### ISSUE THREAD

**Issue by C5FR7Q** [google/accompanist#622]
## Describe the bug
`FlowRow` somehow affects `Modifier.height(IntrinsicSize.Max)`, that's so resulting height is wrong

## To Reproduce
Use `LazyColumn` the items of which are some containers with `Modifier.height(IntrinsicSize.Max)` and including `FlowRow` with different items count.

Example:
```
@Composable
fun Screen() {
	val items = listOf<List<String>>(
		listOf("a", "b", "c"),
		listOf("a", "b", "c", "d"),
		listOf("a"),
		listOf("a", "b"),
		listOf("c")
	)
	LazyColumn {
		items(items) {
			Item(it)
		}
	}
}

@Composable
fun Item(strings: List<String>) {
	Box(
		modifier = Modifier
			.fillMaxWidth()
			.height(IntrinsicSize.Max)
	) {
		Spacer(
			modifier = Modifier
				.background(Color(Random.nextInt(), Random.nextInt(), Random.nextInt()))
				.width(4.dp)
				.fillMaxHeight()
				.align(Alignment.CenterStart)
		)
		FlowRow {
			strings.forEach {
				Text(text = it)
			}
		}
	}
}
```

## Expected behavior
(In accordance with example code) Resulting height of `Item` is equal to the height of `FlowRow`

## Actual behavior
`Item`'s height somehow depends on `FlowRow` items count.
![image](https://user-images.githubusercontent.com/17059563/128628156-099da8e2-b4b7-4b97-824b-ed7a9cfa3a66.png)

## Environment:
 - Android OS version: Android 10
 - Device: Nokia 5.3
 - Accompanist version: 0.16.0
 - Compose version: 1.0.0

**Comment by C5FR7Q** [comment]
Waiting for https://github.com/google/accompanist/pull/650 to be merged

**Comment by mihirrai** [comment]
Facing a similar issue where FlowRow is somehow adding extra height to the layout.

**Comment by PaulWoitaschek** [comment]
Remove the stale label please, this forced us to create our own flowlayout.

**Comment by 6uilhermeAlmeida** [comment]
@C5FR7Q Any way you could re-open the issue? The PR that was supposed to fix it seems abandoned

**Comment by C5FR7Q** [comment]
Waiting for #650 to be merged or any other fix

**Comment by PaulWoitaschek** [comment]
@bentrengrove 
Could you re-open this ticket please?

**Comment by bentrengrove** [comment]
We are currently working on an official version of Flow Layouts in Compose as seen on the [Compose roadmap](goo.gle/compose-roadmap), as such I don't think we will get to fixing this bug in Accompanist. Flow Layouts in Accompanist will soon be deprecated with the release of Flow Layouts in Compose main.
