### ISSUE TITLE
Question: Is there a reason why Pager is implemented with Layout instead of SubcomposeLayout?

### ISSUE THREAD

**Issue by archiegq21** [google/accompanist#626]
https://github.com/google/accompanist/blob/de24ffa68cd1c465e817d019bf799126ca98d3b7/pager/src/main/java/com/google/accompanist/pager/Pager.kt#L263

Just wondering why `Pager` implementation is based on `Layout` instead of `SubcomposeLayout` and whether transforming it to `SubcomposeLayout` would be better?

**Comment by chrisbanes** [comment]
We have no need for subcomposition in `Pager` so there's no need to incur the 'cost'. Is there a reason why you think we need subcomposition?

**Comment by archiegq21** [comment]
This is actually just a complete curiosity question. I was just wondering about using the Pager with a Large Data Set.. I've always thought that using SubcomposeLayout would be better in that instance? Am I wrong?
