### ISSUE TITLE
imePadding doesn't update properly

### ISSUE THREAD

**Issue by sproctor** [google/accompanist#637]
## Describe the bug
Using `imePadding()` to adjust content size gets the wrong value if the keyboard was opened/closed after the first compose.

## To Reproduce
Use `imePadding()` on an element. open/close the keyboard programatically (I haven't tried doing it manual, so I can't verify)

## Expected behavior
`imePadding` should change the value to reflect the new state, but it doesn't. Using `LocalWindowInsets.current.ime` works as expected. `ime` at https://github.com/google/accompanist/blob/bbcc378a92da207a220922f15e000c8f341ad692/insets/src/main/java/com/google/accompanist/insets/Padding.kt#L107 is mutable and so it's not a good key for remember.

## Environment:
 - Android OS version: Android 10
 - Device: Emulator
 - Accompanist version: v0.16.1

**Comment by chrisbanes** [comment]
I've just checked `imePadding()` and it's working as expected. If you can provide a working example showing the issue I'll take a look.

> is mutable and so it's not a good key for remember.

Yes it's mutable, but it's also `@Stable` and isn't a `data` class, which means that `remember` ends up doing a referential check. This means that it's perfectly fine to use as a key.

**Comment by sproctor** [comment]
Thanks.

It seems some relation between fullscreen, the drawer, and ime padding. If remember is doing a referential check, is it sure that the backing values don't change? I made a fairly simple example. I'd gladly admit that there could be a completely different issue here.

To reproduce:
Open the drawer, click a button. The screen with the keyboard loses the FAB, the screen without the keyboard doesn't resize the scaffold correctly and the FAB is way out of position. 

https://github.com/sproctor/AccompanistBug

replacing `imePadding` with the value directly from `LocalWindowInsets` works correctly.
