### ISSUE TITLE
Navigation Animation composable issue

### ISSUE THREAD

**Issue by Vivecstel** [google/accompanist#639]
## Describe the bug
When using androidx.navigation.compose.composable instead of com.google.accompanist.navigation.animation.composable, there is an empty screen.

## To Reproduce
Use AnimatedNavHost & rememberAnimatedNavController and not replace the import for the composable. Run the app and see empty screen.

## Expected behavior
Expected behavior is animated navigation library should handle this case also. Or update the documentation to replace this import also..

## Screenshots?
Not available.

## Environment:
 - Android OS version: Android 11
 - Device: Xiaomi mi a3
 - Accompanist version: 0.16.1

## Additional context
Not needed.

**Comment by jeanraymonddaher** [comment]
i get the same black empty screen when i tried to use that

**Comment by ianhanniballake** [comment]
This is explicitly called out in the [Animations in Navigation Compose blog post](https://medium.com/androiddevelopers/animations-in-navigation-compose-36d48870776b#9a94). We can add a 'Migrating to Accompanist Navigation Animation' section to the docs here though.

**Comment by Vivecstel** [comment]
Yes this would be helpful as i saw only the github update and not the blog post.

**Comment by jbw0033** [comment]
The additional documentation was added as part of #664

**Comment by chrisbanes** [comment]
Closing this as I don't think there's anything left to do
