### ISSUE TITLE
Feature Request: Expose offset in ModalBottomSheetState

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#640]
I'm using accompanist to navigate to a bottom sheet. A request from my designer is to animate a value while the bottom sheet is dragged up or down.  I don't see a way of doing so since the location/offset isn't available. Thanks

**Comment by jossiwolf** [comment]
Thanks for the request, we'll expose the offset of the `ModalBottomSheetState` through `BottomSheetNavigatorSheetState`!

**Comment by joshuamking** [comment]
Yea this is kinda frustrating. I know this is experimental.. but this is kinda necessary for some screens!
Any suggested workarounds? Please?
