### ISSUE TITLE
There's a space between content and keyboard when using imePadding

### ISSUE THREAD

**Issue by adwardwolf** [google/accompanist#644]
## Describe the bug
There's a space between content and keyboard when using `imePadding` and `navigationBarsWithImePadding`

## To Reproduce
1. When TextField is full I hid the keyboard
2. When pressed again it pushed the TextField up, but the there's a weird space between them

## Screenshots?
My TextField is `wrapContentHeight` and this is when i paste a long text

<img src="https://user-images.githubusercontent.com/79896470/129370827-71264d28-44fa-4c06-aa8e-4a4ed7f41b77.png" width=30% height=30%>

When i pressed back:

<img src="https://user-images.githubusercontent.com/79896470/129373668-54c389cb-0a1e-47ca-8b35-902f261be60a.jpg" width=30% height=30%>

Pressed on TextField again:

<img src="https://user-images.githubusercontent.com/79896470/129373684-304c8754-c996-4df8-9962-085ec52ee549.jpg" width=30% height=30%>

## Environment:
 - Android OS version: [Android 8.0.0]
 - Device: [LG V30 and Emulator Pixel 4XL]
 - Accompanist version: [v0.15.0]

On this screen i have `bottomSheetLayout` and `bottomBar`. It worked fine in another screen, but i couldn't find sth wrong it my code tho.

**Comment by chrisbanes** [comment]
Impossible to know what the cause is here without an example to debug. Please attach some code to help reproduce the issue.

**Comment by adwardwolf** [comment]
I found out that half of the space is `paddingValues`

```kotlin
ModalBottomSheetLayout(
        sheetState = modalSheetState,
        sheetBackgroundColor = MaterialTheme.colors.onSecondary,
        sheetContent = {
            PrivacySheetContent(
                currentPrivacy = currentPrivacy,
                onClick = {
                    currentPrivacy = it
                    hideBottomSheet()
                }
            )
        }
    ) {
        Scaffold(
            topBar = {
                WritePostTopBar(
                    onPostClick = {
                        viewModel.addPost(postBody = postBody, privacy = currentPrivacy)
                    },
                    onDiscardClick = {
                        if (postBody.isNotBlank()) {
                            setDiscardDialog(true)
                        } else backToHome()
                    }
                )
            },
            bottomBar = {
                WritePostBottomBar(currentPrivacy = currentPrivacy) {
                    coroutinesScope.launch { modalSheetState.show() }
                }
            },
            content = { paddingValues ->
                WritePostContent(
                    postBody = postBody,
                    paddingValues = paddingValues,
                    onPostBodyChange = { postBody = it }
                )
                if (discardDialog) {
                    DiscardPostAlertDialog(
                        text = "Want to discard post?",
                        onConfirmButton = backToHome,
                        onDismissButton = { setDiscardDialog(false) },
                    )
                }
            }
        )
    }
}
@Composable
private fun WritePostContent(
    postBody: String,
    paddingValues: PaddingValues,
    onPostBodyChange: (String) -> Unit,
) {
    Surface(modifier = Modifier.fillMaxSize().imePadding()) {
        Column(
            modifier = Modifier
                .fillMaxSize().border(1.dp, Color.Blue)
//                .padding(paddingValues = paddingValues)
        ) {
            Card(
                modifier = Modifier
                    .padding(16.dp),
                elevation = 6.dp
            ) {
                TextField(
                    modifier = Modifier
                        .fillMaxWidth()
                        .wrapContentHeight(),
                    value = postBody,
                    enabled = true,
                    onValueChange = onPostBodyChange,
                    placeholder = {
                        Text(
                            text = "Wanna write something?",
                            style = MaterialTheme.typography.h4
                        )
                    },
                    keyboardOptions = KeyboardOptions(
                        keyboardType = KeyboardType.Text,
                        imeAction = ImeAction.Default,
                    ),
                    colors = TextFieldDefaults.textFieldColors(
                        textColor = MaterialTheme.colors.onBackground,
                        backgroundColor = MaterialTheme.colors.background,
                        cursorColor = MaterialTheme.colors.secondary,
                        focusedLabelColor = MaterialTheme.colors.secondary
                    ),
                    textStyle = MaterialTheme.typography.h4,
                )
            }
        }
    }
}
```
That's the left

<img src="https://user-images.githubusercontent.com/79896470/129828678-4619456f-edea-458c-8716-bf464c40169d.png" width=30% height=30%>

**Comment by svenjacobs** [comment]
@chrisbanes I can reproduce this with a very simple piece of Compose code. The different behaviour of `navigationBarsPadding()`, `imePadding()` and `navigationBarsWithImePadding()` is confusing.

```kotlin
@Composable
fun Example(
    modifier: Modifier = Modifier,
) {
    Box(
        modifier = modifier
            .navigationBarsPadding()
            .fillMaxSize(),
        contentAlignment = Alignment.BottomCenter,
    ) {

        TextField(
            modifier = modifier
                .imePadding()
                .padding(8.dp)
                .fillMaxWidth(),
            value = "Hello world",
            onValueChange = {}
        )
    }
}
```

![screenshot1](https://user-images.githubusercontent.com/255313/152301410-254a8220-1b1e-4a87-a6ad-a7e69b3aa582.png)

![screenshot2](https://user-images.githubusercontent.com/255313/152301475-fbd066ce-7f35-412f-b8cc-6b555d77b357.png)

As you can see there is an additional padding below the `TextField` that seems to be the height of the navigation bar. My understanding was that `imePadding()` is **just** the height of the keyboard, so using `navigationBarsPadding()` + `imePadding()` separately should be the same as `navigationBarsWithImePadding()`. However if I change `navigationBarsPadding()` on the `Box` to `navigationBarsWithImePadding()` and remove `imePadding()` on the `TextField` I get the expected result.

```kotlin
@Composable
fun Example(
    modifier: Modifier = Modifier,
) {
    Box(
        modifier = modifier
            .navigationBarsWithImePadding()
            .fillMaxSize(),
        contentAlignment = Alignment.BottomCenter,
    ) {

        TextField(
            modifier = modifier
                .padding(8.dp)
                .fillMaxWidth(),
            value = "Hello world",
            onValueChange = {}
        )
    }
}
```

![screenshot3](https://user-images.githubusercontent.com/255313/152301952-dd9abd7c-fed5-4c55-8b7f-38dffc0e8f94.png)

Now this is a very simple example and the solution is illustrated above. However in a more complex setup the contents of `Box` might change during runtime, for instance via navigation, and there might be a good reason for splitting up the paddings into `imePadding()` and `navigationBarsPadding()`.

Note that `WindowCompat.setDecorFitsSystemWindows(window, false)` is set on the Activity.

Compose: `1.1.0-rc03`
Accompanist: `0.22.1-rc`
Device: Google Pixel with Android 10

**Comment by svenjacobs** [comment]
I forgot to add a state. When Box has `navigationBarsPadding()` and `TextField` no padding, this is the result:

![screenshot4](https://user-images.githubusercontent.com/255313/152308907-88461a95-5b9c-4839-8dc5-83665a36aa07.png)

**Comment by alexvanyo** [comment]
Thanks for the simple example! This is expected, but as you pointed out somewhat confusing behavior.

How insets are combined is in a `maxOf` sense, rather than a strict `additive` sense.

So putting some numbers to it:
Let's say the navigation bar inset is `20` pixels from the bottom of the screen, and the top of the IME is `100` pixels from the bottom of the screen.

Then `navigationBarPadding()` will have a bottom value of `20` pixels, and `imePadding()` will have the bottom value of `100` pixels. If both are applied, then the total padding will be `120` pixels, but this is `20` pixels too high: the top of the IME is only `100` pixels from the bottom of the screen.

`navigationBarsWithImePadding()` "combines" these two types of insets, but it doesn't do so just by adding them. Instead it takes the `max` of each. So the bottom padding of `navigationBarsWithImePadding` will be just `100` pixels.

If you wanted to split up the paddings, you will have to do that subtraction calculation yourself with the current accompanist APIs, since there isn't communication from the parent to the child saying "I've already handled this portion of the insets".

That communication is currently being experimented with insets support in `androidx.compose`, which would allow both approaches to work as you'd expect.

**Comment by svenjacobs** [comment]
Thanks Alex for this detailed explanation. I know understand why Accompanist insets work that way 👍🏼

**Comment by umardev500** [comment]
just add cosumeWindowInset

```kotlin
Scaffold(
        topBar = {
            MessageHeader()
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .consumeWindowInsets(innerPadding)
        ) {
...... rest of your application
```

**Comment by Tuyose** [comment]
> just add cosumeWindowInset
> 
> Scaffold(
>         topBar = {
>             MessageHeader()
>         }
>     ) { innerPadding ->
>         Column(
>             modifier = Modifier
>                 .fillMaxSize()
>                 .padding(innerPadding)
>                 .consumeWindowInsets(innerPadding)
>         ) {
> ...... rest of your application

THANK YOU

**Comment by adshrs** [comment]
I have found a fix for my case. Since none of the options in the comments worked for me, i tried my own fix:

- I checked the main entry point of my app,  MainActivity.kt. Inside setContent { } of the MainActivity, I already had a Scaffold in which all the screens were getting composed. Then again inside each screen composable, I had another Scaffold with topbars.

- The issue was fixed after I removed the outer Scaffold (the MainActivity.kt one).

So, the main issue in my case was the nesting of Scaffolds.

Further, after removing the outer Scaffold, if the content is overlapped by the system notification bar and navigation bar, just put a Surface{} with Modifier.fillMaxSize() and inside it, a Box{} with Modifier.systemBarsPadding(). Then, place  the rest of your content inside it.

IMPLEMENTATION:

            Surface(
                modifier = Modifier.fillMaxSize()
            ) {
                Box(
                    modifier = Modifier.systemBarsPadding()
                ){
                    if (isSessionInitialized) {
                        MainNavigation()
                    } else {
                        WelcomeSplashScreen()
                    }
                }
            }

**Comment by jayesh1995-bhadegadi** [comment]
In my case , It was bottomtab bar height was getting consumed on keyboard open.  I hope it will work for someone.
