### ISSUE TITLE
[idea] Feature Request : Ability to control bottomSheet state

### ISSUE THREAD

**Issue by theapache64** [google/accompanist#646]
**Problem**

AFAIK, currently, there's no way to control `bottomSheet` state. The `bottomSheetNavigator.navigatorSheetState.currentValue` is immutable. 

**Solution**

Provide method to control state.Something like `bottomSheetNavigator.navigatorSheetState.expand()` or `bottomSheetNavigator.navigatorSheetState.collapse()`

**Comment by ianhanniballake** [comment]
The state of the bottom sheet is tied to whether the bottom sheet is on the `NavController` back stack - you'd want to `navigate()` to a bottom sheet destination or call `navController.popBackStack()` if you want to show or hide a destination that is displayed as a bottom sheet.

If you want to directly change the bottom sheet state and use that as your source of truth  (and not the `NavController`), you should not be using `BottomSheetNavigator`, but instead just using `ModalBottomSheetLayout` and its state directly.

**Comment by theapache64** [comment]
@ianhanniballake What if I want to show `bottomSheet` "destination" expanded by default when `navigate`d?

**Comment by ianhanniballake** [comment]
You'd want to star [b/186669820](https://issuetracker.google.com/issues/186669820), which tracks the adding of a `skipCollapsed` flag to `ModalBottomSheetLayout`. Once that is available, we'd also make it available in Navigation Material.

**Comment by theapache64** [comment]
okay 👍

**Comment by jossiwolf** [comment]
Thanks, Ian! @theapache64, for more historical reasons/discussion on this: https://github.com/androidx/androidx/pull/173#discussion_r676056715

Consider the `ModalBottomSheetState` an implementation detail of the navigator :)
