### ISSUE TITLE
[Idea] Add PagerState API to distinguish between programatic vs. touch scrolls

### ISSUE THREAD

**Issue by alexjlockwood** [google/accompanist#651]
`ViewPager` and `ViewPager2` have an API called [`OnPageChangeCallback#onPageScrollStateChanged()`](https://developer.android.com/reference/androidx/viewpager2/widget/ViewPager2.OnPageChangeCallback#onPageScrollStateChanged(int)) which allows you to determine whether the current scroll is settling, programatically initiated (i.e. part of a "fake drag" using `ViewPager2#fakeDragBy()`), or part of an active gesture.

Currently there doesn't seem to be a similar API for `PagerState`, as `PagerState#isScrollInProgress` returns whether there is an active scroll. but provides no information about how it was initiated or whether there is still an active gesture happening.

This API would be ideal as in some cases you want to react to a view pager page change, but only once the user has finished interacting with the screen and the next target page is known for certain.

**Comment by alexjlockwood** [comment]
A quick update... I did end up finding a workaround that seems to work, but it wasn't very intuitive. Essentially it required creating a custom `FlingBehavior` that wraps around the default:

```

@Stable
internal class CustomFlingBehavior(
    // Can just be `PagerDefaults#defaultPagerFlingConfig()`
    private val flingBehavior: FlingBehavior,
) : FlingBehavior {
    var isSettling by mutableStateOf(false)
        private set

    override suspend fun ScrollScope.performFling(initialVelocity: Float) = try {
        isSettling = true
        with(flingBehavior) { performFling(initialVelocity) }
    } finally {
        isSettling = false
    }
}
```

Then pass this `FlingBehavior` to `HorizontalPager(flingBehavior = myFlingBehavior)`. Then in order to determine whether a scroll was initiated via a scroll vs. a fling, you would just use `myFlingBehavior.isSettling`.

Like I said, it works... but not very straightforward and would be nice if this extra fling state could be consolidated under `PagerState` somehow.

**Comment by chrisbanes** [comment]
This is more of a question for `ScrollableState` since all of that API comes from there.

/cc @matvei-g

**Comment by matvei-g** [comment]
We [expose InteractionSource](https://cs.android.com/androidx/platform/tools/dokka-devsite-plugin/+/master:testData/compose/source/androidx/compose/foundation/lazy/LazyListState.kt;l=106?q=LazyListState) as a part of `LazyListState` and `ScrollState`. This InteractionSource emmits DragInteraction.Start when drag started allowing developers to react to this emission or to the fact that's it's gone (DragInteraction.Stop emitted). 

Does it make sense to provide the same InteractionSource in the Pager as well?

**Comment by alexjlockwood** [comment]
@chrisbanes Yeah that's fair, I was thinking that as well. Makes sense for accompanist to stay consistent with whatever API `ScrollableState` uses.

@matvei-g That's an interesting idea! Seems like it would also be consistent with `LazyListState` too (which exposes a public `val interactionSource: InteractionSource` [here](https://cs.android.com/androidx/platform/tools/dokka-devsite-plugin/+/master:testData/compose/source/androidx/compose/foundation/lazy/LazyListState.kt;l=106;drc=6fed3de7a56143de954d55e508a7449deb9af582).

```
    /**
     * [InteractionSource] that will be used to dispatch drag events when this
     * list is being dragged. If you want to know whether the fling (or animated scroll) is in
     * progress, use [isScrollInProgress].
     */
    val interactionSource: InteractionSource get() = internalInteractionSource
```

**Comment by chrisbanes** [comment]
`InteractionSource` looks good to me, I'll whip up a quick PR now. Should this be part of the `ScrollableState` contract?
