### ISSUE TITLE
navigatorProvider is a restricted api

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#655]
I used Jossi's article to implement a bottom sheet but it's now failing lint.

```
NavController.setNavigatorProvider can only be called from within the same library group (referenced groupId=androidx.navigation from groupId=src)
          val navController = rememberNavController()
          val bottomSheetNavigator = rememberBottomSheetNavigator()
          navController.navigatorProvider += bottomSheetNavigator                                     

This API has been flagged with a restriction that has not been met.

Examples of API restrictions:
* Method can only be invoked by a subclass
* Method can only be accessed from within the same library (defined by the Gradle library group id)
* Method can only be accessed from tests.

You can add your own API restrictions with the @RestrictTo annotation.
To suppress this error, use the issue id "RestrictedApi" as explained in the Suppressing Warnings and Errors section.

RestrictedApi Correctness Error Priority 4/10
```

Should I be using a different api or something?

**Comment by chrisbanes** [comment]
I think you must be missing the import to [`androidx.navigation.plusAssign`](https://developer.android.com/reference/androidx/navigation/NavigatorProviderKt#(androidx.navigation.NavigatorProvider).plusAssign(androidx.navigation.Navigator)).

**Comment by ColtonIdle** [comment]
@chrisbanes thanks! I'm not sure if that's the issue though?

Unless I'm doing something wrong?

Currently if I command click on the += I drill into

`androidx/navigation/NavigatorProvider.kt`

```
@Suppress("NOTHING_TO_INLINE")
public inline operator fun NavigatorProvider.plusAssign(navigator: Navigator<out NavDestination>) {
    addNavigator(navigator)
}
```

and if I add `import androidx.navigation.plusAssign` I get `Unused import directive `

**Comment by chrisbanes** [comment]
Not sure, this works without errors/warnings for me in Tivi

**Comment by ColtonIdle** [comment]
The warnings aren't in the IDE. Only when you run lint and we have lint warnings to fail as errors, so I'm not sure if it's an error or warning.

**Comment by ianhanniballake** [comment]
You aren't even using the `setNavigatorProvider` method in that code, so it is a bit concerning that Lint is complaining about _that_. Like you saw, the `+=` is just a shorthand for calling `addNavigator`:
```
val navController = rememberNavController()
val bottomSheetNavigator = rememberBottomSheetNavigator()
navController.navigatorProvider.addNavigator(bottomSheetNavigator)
```

If that code, which is functionally identical, doesn't cause a Lint error, then the problem is with that Lint check not handling the `+=` correctly. Generally, the first thing you'd want to do is upgrade your Android Gradle Plugin (as Lint is intrinsically tied into that) and see if Lint has gotten any smarter.

**Comment by ColtonIdle** [comment]
I'm using the latest version of AGP alpha (so 7.1.0-alpha07). I will file a bug for Tor/Lint team.

I can confirm that using your snippet above @ianhanniballake that the lint error does go away!

**Comment by ColtonIdle** [comment]
Lint issue filed: https://issuetracker.google.com/issues/197123294

Going to close this since it seems like it's nothing related to accompanist.
