### ISSUE TITLE
[Idea] Add contentPadding to HorizontalPager

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#667]
I'm trying to recreate this carousel

![image (4)](https://user-images.githubusercontent.com/31751141/129948744-af03cb41-3e9a-4f2c-bf72-3cfbb20d2e8f.png)

Seems easy enough 

```
HorizontalPager(
    state = pagerState,
    horizontalAlignment = Alignment.Start,
    modifier = Modifier.fillMaxWidth(),
    itemSpacing = 16.dp) { i ->
    Box(modifier = Modifier.fillMaxWidth(0.9f)) { content[i]() }
}
```

If I add padding(start = 16.dp) to the HP modifier then I DO get the padding on the left side BUT when scrolling, all of the items get clipped when paging to the next item.

contentPadding was the recommended solution by Chris Banes.

**Comment by ColtonIdle** [comment]
Thank you @chrisbanes!

**Comment by chrisbanes** [comment]
Woops, didn't mean to push that to main. New PR at #669
