### ISSUE TITLE
Feature Request: Expose percentage in ModalBottomSheetState

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#673]
Related to: https://github.com/google/accompanist/issues/640

but it seems like I didn't want "offset" but I more-so want a progress/completion percentage. To throw another wrench into it, I want the progress to be based from the open semi-expanded state to the expanded state.

For example, I'm trying to get this state as 0%
<img width="177" alt="Screen Shot 2021-08-21 at 12 28 06 PM" src="https://user-images.githubusercontent.com/31751141/130328539-c4d0113c-45d6-466f-a90a-36b09ee79051.png">

 and then I want the "open" state to be 100%

<img width="196" alt="Screen Shot 2021-08-21 at 12 28 57 PM" src="https://user-images.githubusercontent.com/31751141/130328553-d0d0b476-5425-4308-ba80-35a681aa29e8.png">

I think I can derive this myself using offset if I knew the collapsedOffsetValue and semiExpandedOffset.

Example: 
Offset = 0 when I'm fully expanded (on any device) If I KNEW that the semiExpandedOffset is 1000, then I can figure out that 50% is 500. But the problem is that the offset value when the sheet is closed on my pixel 5 ranges from 0-2280. So I'm assuming this offset changes per device which basically makes things a lot more difficult when trying to animate in relation from the semi-expanded to expanded state. Thanks!

**Comment by ColtonIdle** [comment]
Maybe it would just be better to file a feature request to just expose sheet state (or all of it's vals) directly?

**Comment by jossiwolf** [comment]
> Maybe it would just be better to file a feature request to just expose sheet state (or all of it's vals) directly?

I've thought that about that too and think we should do that. I'm not super happy about mirroring `Swipeable`'s and `ModalBottomSheetState`'s APIs but I don't think there's anything we can do.

CC @ianhanniballake, do you have a different idea maybe?
