### ISSUE TITLE
PagerState.targetPage scrolling bug

### ISSUE THREAD

**Issue by Edmko** [google/accompanist#679]
## Describe the bug
On scrolling left target page is equal current page

## Screenshots?
now it looks like
![image](https://user-images.githubusercontent.com/55951401/130781618-ac85af9b-93f7-4e38-a990-c7c1e78e4ca7.png)
but on scrolling left: offset < 0f so target page is equal current page.
So need to change to(or absolute value of currentPageOffset<0.001f):
![image](https://user-images.githubusercontent.com/55951401/130781860-d33fc23a-bc99-417c-9fac-96b185bd43bc.png)

## Environment:
 - Accompanist version: [e.g. v0.17.0]

**Comment by jemshit** [comment]
i was expecting this to get fixed on v0.18.0 🤔

**Comment by chrisbanes** [comment]
This is already fixed in the re-write: #678
