### ISSUE TITLE
PagerScope.calculateCurrentOffsetForPage(page: Int) for infinite loop pager returns wrong value for edge items

### ISSUE THREAD

**Issue by seanoh1989** [google/accompanist#692]
## Describe the bug
If infinite loop is enabled for `pagerState`, the scroll effect between first - last item of the pager is not correct. This is caused by calculation from `PagerScope.calculateCurrentOffsetForPage(page: Int)`

For example, if there are 3 items in the page, with index 0, 1, 2,
scrolling from 0 -> 2 or 2 -> 0 will not have correct offset values from the above function.

## To Reproduce
1. Create an infinite loop pager with pageCount > 0
2. Scroll between first - last items
3. See error

## Expected behavior
`PagerScope.calculateCurrentOffsetForPage(page: Int)` should return correct offset value for first and last items when `pagerState.infiniteLoop` is `true`

## Environment:
 - Android OS version: Android 11
 - Device: Samsung Galaxy S20 FE
 - Accompanist version:  `com.google.accompanist:accompanist-pager:0.17.0`

## Additional context
Also easily reproducible if pageCount is 1 or 2

**Comment by seanoh1989** [comment]
This implementation solves the problem only when `pageCount > 2`
```
@ExperimentalPagerApi
private fun PagerScope.calculateCurrentOffsetForPage(page: Int): Float {
    var calculatedOffset = ((currentPage + currentPageOffset) - page)

    val isOnEdge = pageCount - 1 == (page - currentPage).absoluteValue
    val isCalculatingOffsetForCurrentPage = currentPage == page

    if (isInfiniteLoop &&
        isOnEdge &&
        !isCalculatingOffsetForCurrentPage
    ) {
        calculatedOffset = pageCount - calculatedOffset.absoluteValue
    }

    return calculatedOffset
}
```

It'd be a lot easier if we can somehow know which way user is scrolling, but I can't seem to figure that out at the moment

**Comment by chrisbanes** [comment]
`infiniteLoop` is likely to be removed in #678 so this probably won't be fixed.
