### ISSUE TITLE
[Pager] Offset screens are not recomposed when their state change

### ISSUE THREAD

**Issue by offvanHooijdonk** [google/accompanist#706]
Hi!
I'm using HorizontalPager to make a DatePicker. When I start Pager layout, I already have a value picked, so I have a color mark for it. What happens next:
## To Reproduce
* scroll forward (initialOffscreenLimit can be any)
* Select another date and have a color mark on it
* Scroll back and still have color mark on initial pick date - **no recomposition happens**. Sure thing I use State for the date picked and change its value
* If then scroll forward out of initialOffscreenLimit and then scroll back to the first screen - recomposition **does** happen and my color mark is removed from the initial date.

So I wonder if there's a built-in way to force recomposition on pre-fetch screens (I assume no), any workaround you can advise, or either please add such a feature 🙏 Thank you

## Environment:
 - Accompanist version: 0.18.0

**Comment by chrisbanes** [comment]
This is likely to be fixed by #678

**Comment by offvanHooijdonk** [comment]
> This is likely to be fixed by #678

Thank you! Sounds promising. Any clue on version and its release date?

**Comment by chrisbanes** [comment]
> Thank you! Sounds promising. Any clue on version and its potential release date?

Soon hopefully 🤞
