### ISSUE TITLE
SystemUiController.isNavigationBarVisible always returns true on Samsung when Swipe Gestures is enabled

### ISSUE THREAD

**Issue by ouattararomuald** [google/accompanist#713]
## Describe the bug
On some phones you can use Swipe Gestures to navigate.

When I call [SystemUiController.isNavigationBarVisible](https://google.github.io/accompanist/api/systemuicontroller/com.google.accompanist.systemuicontroller/-system-ui-controller/index.html#19546870%2FProperties%2F-2105613612) on a **Samsung S21 Ultra** with **Swipe Gestures enabled** (*which means that the navigation bar is not visible from a user point of view*), `SystemUiController.isNavigationBarVisible` always returns `true`.

I tried with a **OnePlus 6** and it returns `false` when Swipe Gestures is enabled and `true` otherwise.

## To Reproduce
1. Use a Samsung S21 Ultra (*I don't know if other samsung have the same behavior*)
1. Go in Phone Settings
1. Turn on Swipe Gesture
1. Call `SystemUiController.isNavigationBarVisible`

## Expected behavior
I expect `SystemUiController.isNavigationBarVisible` to return `false` when Swipe Gestures is enabled. And `true` otherwise.

## Environment:
 - Android OS version: Android 11
 - Device: Samsung S21 Ultra 5G
 - Accompanist version: `0.18.0`

**Comment by chrisbanes** [comment]
Sounds like a bug in `WindowInsetsCompat`. I recommend raising a bug at https://issuetracker.google.com
