### ISSUE TITLE
Dismiss bottom sheet navigation by swiping or touch scrim area, not removed from navigation stack

### ISSUE THREAD

**Issue by wisnukurniawan** [google/accompanist#720]
## Describe the bug
Dismiss bottom sheet navigation by swiping or touch scrim area, not removed from navigation stack. 

## To Reproduce
Let say we have 2 bottom sheet.
1. Show first bottom sheet, dismiss it by swiping
2. Repeat step 1 for second bottom sheet
3. First bottom sheet will pop up

## Expected behavior
First bottom sheet should be not pop up

## Screenshots?
<img src="https://user-images.githubusercontent.com/16729158/133418272-eab07199-5fb3-4c21-88ee-759ee7ae3194.gif" width="180">

## Environment:
 - Accompanist version: v0.18.0

## Additional context
Not happen in accompanist **v0.17.0**.

**Comment by jossiwolf** [comment]
See #700 - fix is in progress. Sorry for the inconvenience!

**Comment by chrisbanes** [comment]
Will be fixed in the next release (probably today)

**Comment by wisnukurniawan** [comment]
yey! thanks a lot @jossiwolf @chrisbanes
