### ISSUE TITLE
Update imports for NamedNavArgument

### ISSUE THREAD

**Issue by muthuraj57** [google/accompanist#723]
`NamedNavArgument` import is changed in the latest compose navigation release ([2.4.0-alpha09](https://developer.android.com/jetpack/androidx/releases/navigation#2.4.0-alpha09)) from `androidx.navigation.compose.NamedNavArgument` to `androidx.navigation.navArgument`

## Environment:
 - Accompanist version: 0.18.0

**Comment by muthuraj57** [comment]
Just saw that there is a PR to fix this.
https://github.com/google/accompanist/pull/722

**Comment by wisnukurniawan** [comment]
Temporary fix https://github.com/wisnukurniawan/Compose-ToDoList/blob/main/app/src/main/java/com/wisnu/kurniawan/composetodolist/foundation/uiextension/NavGraphBuilderExt.kt

**Comment by ianhanniballake** [comment]
Yep, this was fixed in #722. [Snapshot builds](https://github.com/google/accompanist/blob/main/docs/using-snapshot-version.md) should already have the fix and it'll be in the next release.
