### ISSUE TITLE
Provide a method to make the bottom sheet non-cancellable for some use-cases.

### ISSUE THREAD

**Issue by dilraj-singh1997** [google/accompanist#730]
## Describe the bug
Provide a method to make the bottom sheet non-cancellable for some use-cases.

## Expected behaviour
When a user clicks the back button or the outside content of the bottom sheet, then it dismisses. However, there should be a way to control that behaviour based on a flag that the bottom sheet should not dismiss. It should only dismiss via calling ```navGraph.navigateBack()```.

## Environment:
 - Android OS version: [Android 11.0]
 - Device: [Samsung M20]
 - Accompanist version: [0.17.0]

**Comment by ravitejasc** [comment]
```
@OptIn(ExperimentalMaterialNavigationApi::class, ExperimentalMaterialApi::class)
@Composable
fun rememberBottomSheetNavigator(
    animationSpec: AnimationSpec<Float> = SwipeableDefaults.AnimationSpec,
    confirmStateChange: (ModalBottomSheetValue) -> Boolean = { true }
): BottomSheetNavigator {
    val sheetState = rememberModalBottomSheetState(
        ModalBottomSheetValue.Hidden,
        animationSpec, confirmStateChange
    )
    return remember(sheetState) {
        BottomSheetNavigator(sheetState = sheetState)
    }
}
```
try this, toggle `confirmStateChange` as per your use case

**Comment by jossiwolf** [comment]
@dilraj-singh1997 Thanks for the feature request. The bottom sheet will always be dismissed when the associated destination is popped of the back stack (such as is the case when going back). I will look into exposing a flag that mirrors `ModalBottomSheetLayout'`s `gesturesEnabled` flag to disable dismissal by touching outside of the sheet.

@ravitejasc Please don't do this - `BottomSheetNavigator` relies on implementation details of `ModalBottomSheetState` to work. Overriding `confirmStateChange` does not guarantee this to work and is a good way to get the navigator out of sync. This constructor of `BottomSheetNavigator` might be made `internal` in the future.

**Comment by dilraj-singh1997** [comment]
Thanks for the quick reply @jossiwolf.

**Comment by TheValyrianKnight** [comment]
Any update on this ?

**Comment by micHar** [comment]
Not stale

**Comment by hiteshchopra11** [comment]
Any update on this?

**Comment by dimitriz09** [comment]
Any update on this?

**Comment by hiteshchopra11** [comment]
@dimitriz09 As a workaround, I used returned false in `confirmStateChange ` of `rememberModalBottomSheetState` and it worked for me. 

```
    val confirmStateChange: (ModalBottomSheetValue) -> Boolean = remember {
        { false }
    }

    val sheetState = rememberModalBottomSheetState(
        initialValue = ModalBottomSheetValue.Hidden,
        animationSpec = SwipeableDefaults.AnimationSpec,
        confirmStateChange = confirmStateChange
    )
```

**Comment by amitrandhawa1** [comment]
" I will look into exposing a flag that mirrors ModalBottomSheetLayout's gesturesEnabled flag to disable dismissal by touching outside of the sheet."

Any update on this @dimitriz09 @jossiwolf

**Comment by mortenholmgaard** [comment]
Great with a PR for this issue! 

Any update to the state of the PR?

**Comment by UKMIITB** [comment]
@jossiwolf 
Is there an update on this issue or on this PR
https://github.com/google/accompanist/pull/1642

@jossiwolf Can you suggest any temporary workaround for this ?

**Comment by UKMIITB** [comment]
@jossiwolf Any update here

**Comment by amanv8060** [comment]
I think the system back could be handled by BackHandler, and the swipe could be handled using this PR: https://github.com/google/accompanist/pull/1642.

**Comment by sidbamba** [comment]
Any updates??

**Comment by paulfrankallan** [comment]
Hi, is planned/ in progress?

**Comment by ianhanniballake** [comment]
With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: `androidx.compose.material:material-navigation`, which fully replaces Accompanist Navigation Material.

As such, we are closing all issues here on Accompanist and will be fully deprecating Accompanist Navigation Material in an upcoming release.

This issue was not fixed as part of the migration, so if you're still interested in this, please [file an issue](https://issuetracker.google.com/issues/new?component=742043) and the Material team will take a look.

Include the link here so that others can star it!
