### ISSUE TITLE
[navigator-animation] `popEnterTransition` drawn on top of `popExitTransition`

### ISSUE THREAD

**Issue by brianwernick** [google/accompanist#731]
## Describe the bug
In `navigator-animation` when I pop a `NavBackStackEntry` off the graph and the `popExitTransition` and `popEnterTransition` is called the destinations `popEnterTransition` is drawn over the current (popping) entry's `popExitTransition`.

## To Reproduce
Construct an `AnimatedNavHost` with a customized `popEnterTransition` that has an initial offset > 0, e.g.
```kotlin
AnimatedNavHost(
  navController, 
  startDestination = "Blue",
  popEnterTransition = { _, _, ->
    slideInHorizontally(initialOffsetX = { -it / 5 }, animationSpec = tween(durationMillis = 700))
  }
)
```

**NOTE:**
If modifying the `AnimatedNavHostSample` make sure to `null` out the `popEnterTransition`  of the destination `composable`, I updated the "Blue" `composable` to `popEnterTransition = null`

## Expected behavior
The `popEnterTransition` for the destination `NavBackStackEntry` should be drawn underneath (lower z-index) the `popExitTransition` of the current `NavBackStackEntry` during a pop.

## Screenshots?
![navigator-animation pop issue](https://user-images.githubusercontent.com/8961257/134015864-abb6789d-7606-4206-a9fa-2b9c1f7712c6.gif)

## Environment:
 - Android OS version: [Android 10]
 - Device: [Emulator]
 - Accompanist version: [`0.18.0`]

**Comment by kikasik** [comment]
Same issue

**Comment by DonnyRozendal** [comment]
I have this issue with both entering and popping. This issue is still present on version `0.19.0` and has been an issue since the beginning I believe. This is the only thing that keeps me from using Compose navigation for production...

**Comment by alexducatti** [comment]
Also confirmed this issue on `0.21.2-beta`

**Comment by brianwernick** [comment]
Ping for stale bot

**Comment by codingfd** [comment]
Also confirmed this issue on 0.23.0

**Comment by theGlenn** [comment]
Quite connected to #1001
