### ISSUE TITLE
Remove Napier dependency

### ISSUE THREAD

**Issue by gabrielittner** [google/accompanist#732]
**Is your feature request related to a problem? Please describe.**

The pager library depends on a logging library called `Napier` to log the current page when it changes. However the log is guarded by a boolean that is hardcoded to false. https://github.com/google/accompanist/blob/main/pager/src/main/java/com/google/accompanist/pager/Pager.kt#L51 So the dependency on napier that users of pager will get is completely unneeded. 

**Describe the solution you'd like**

Remove the dependency. For a single log statement it's enough to use `android.util.Log`.

**Describe alternatives you've considered**

You could also wrap it in a method that uses napier in the debug source set and is just empty in the release source set. That way the dependency could be changed to debug only.

**Comment by chrisbanes** [comment]
> For a single log statement it's enough to use android.util.Log.

Not quite, as I want libraries to stay non-Android.

Considering Compose practically requires the usage of R8 (which will strip all of those log calls), I'm not sure this is really an issue.

**Comment by ansman** [comment]
This causes issues for us because we have to get every 3rd party dependency approved and vetted.

I have some other possible solutions:
* Allow passing your own logger and add a default artifact for napier
* Change the dependency type to `compileOnly`.
