### ISSUE TITLE
[Insets] Laggy animation with navigationBarsWithImePadding

### ISSUE THREAD

**Issue by kikasik** [google/accompanist#734]
## To Reproduce
1. Create a project in AS with compose activity
2. Change Greeting function like this: 
```
@Composable
fun Greeting(name: String) {
    Column(
        modifier = Modifier
            .navigationBarsWithImePadding()
            .fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Bottom
    ) {
        Text(text = "Hello $name!")
        TextField(
            value = "",
            onValueChange = {},
            modifier = Modifier.padding(bottom = 20.dp),
            placeholder = { Text(text = "some text") }
        )
    }
}
```
3. Add **WindowCompat.setDecorFitsSystemWindows(window, false)** in onCreate
4. Wrap your Greeting in ProvideWindowInsets 
5. See laggy animation when keyboard appears

## Expected behavior
Smooth animations

## Video
Video [example](https://youtu.be/MCpC79q7MHs)

## Environment:
 - Android OS version: 11
 - Device: Samsung Galaxy s10e
 - Accompanist version: com.google.accompanist:accompanist-insets:0.18.0

**Comment by chrisbanes** [comment]
Are you running your app in release build with R8? This seems more like a general Compose performance issue rather than something specific to Accompanist Insets. There's much more we can do in insets in terms of performance.
