### ISSUE TITLE
[Insets] imePadding don't work on API 29 and lower

### ISSUE THREAD

**Issue by IvanKashtelyan** [google/accompanist#736]
## To Reproduce
1. Create a project in AS with compose activity
2. Change Greeting function like this:
```
@Composable
fun Greeting(name: String) {
    Column(
    ) {
        Text(text = "Hello $name!", modifier = Modifier.statusBarsPadding())
        Spacer(modifier = Modifier.weight(1f))
        TextField(
            value = "",
            onValueChange = {},
            modifier = Modifier
        )
        Spacer(modifier = Modifier.weight(1f))
        Button(onClick = { /*TODO*/ }, modifier = Modifier
            .padding(20.dp)
            .navigationBarsWithImePadding()
            .fillMaxWidth()) {
            Text(text = "test")
        }
    }
}
```

3. Add WindowCompat.setDecorFitsSystemWindows(window, false) in onCreate
4. Wrap your Greeting in ProvideWindowInsets
5. Launch on API 29 and lower
6. Tap to TextField
7. See the result

## Environment:
 - Android API version: 29 and lover
 - Accompanist version: 0.18.0
 - Compose version: 1.0.2

## Video

https://user-images.githubusercontent.com/52675018/134868977-7ea60156-1d07-41cf-ac86-9be8205e451a.mp4

**Comment by chrisbanes** [comment]
Have you followed all of the steps here? https://google.github.io/accompanist/insets/#something-not-working. I'm guessing that you've missed the `windowSoftInputMode` step.

**Comment by IvanKashtelyan** [comment]
@chrisbanes yes thank you it helps to solve this issue I had a default value, in this case what reason normally work in API 30 but don't work properly on lower API?

**Comment by chrisbanes** [comment]
All of the insets APIs were re-written in Android 11, which is why it works there.
