### ISSUE TITLE
Click on a bottom sheet when it's opening will cause the bottom sheet to appear after the user dismisses

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#762]
## To Reproduce
1. Open a bottom sheet destination via whatever method (button click, etc)
2. While it's opening, click on the bottom sheet
3. Close the bottom sheet, and it will open again

## Screenshots?
Will try to follow up with a video

## Environment:
0.19

**Comment by jossiwolf** [comment]
Thanks for the report! This was broken while working around `ModalBottomSheetLayout`'s synchronization issues. I will take a look at providing a fix, but it is unlikely that it will be fixed before reworking the sheet implementation.

**Comment by ColtonIdle** [comment]
COOOL. To me this is not that important to me. Mo' of a FYI

**Comment by jossiwolf** [comment]
Not stale, I hope this will be fixed with an upcoming refactoring - @ianhanniballake can you remove the stale label, please? :)

**Comment by alitafreshi** [comment]
this is a realy important feature please fix it  !!!!!

**Comment by jossiwolf** [comment]
I agree - we're getting closer and doing our best :)

**Comment by jossiwolf** [comment]
v0.28.1 addresses this issue. Please let us know if you can still reproduce it with this version.
