### ISSUE TITLE
Bottomsheet state isn't updated

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#763]
## Describe the bug
I used to track the bottom sheet offset via `Text(bottomSheetNavigator.navigatorSheetState.offset.value.toString())`. This worked in 0.17, but no longer works in 18. I know bottom sheet state was being touched a bunch in .18 and .19, so maybe a this is a new regression?

## To Reproduce
1. Text(bottomSheetNavigator.navigatorSheetState.offset.value.toString())

## Environment:
0.19 (it used to work with 0.17)

**Comment by ColtonIdle** [comment]
@jossiwolf worth removing the stale label here too?

**Comment by ColtonIdle** [comment]
Not stale 😄

**Comment by jossiwolf** [comment]
Hi, finally doing a bit of a bug bash. I just tried to repro this but wasn't able to. Can you recheck and, if you are still able to repro, send the steps here, please?

**Comment by ColtonIdle** [comment]
Will check at some point this week.

**Comment by ColtonIdle** [comment]
Still haven't gotten to this. Feel free to close if you'd like. But basically all I was doing was trying to hook into the bottom sheets scroll state to update an animation based off that state and it used to work like I said in the original message, but no longer it does.

**Comment by ColtonIdle** [comment]
Confirmed that this is fixed in v0.24.9-beta. Guess something else must've fixed it since 0.18
