### ISSUE TITLE
HorizontalPager 0.19.0 enforce verticalAlignment

### ISSUE THREAD

**Issue by NitroG42** [google/accompanist#779]
## Describe the bug
The verticalAlignment parameters is not working with the HorizontalPager (and the horizontalAlignment for the VerticalPager might not be working too)

## To Reproduce
```
@OptIn(ExperimentalPagerApi::class)
@Composable
fun PagerContent() {
    HorizontalPager(
        count = 10,
        contentPadding = PaddingValues(start = 20.dp, end = 20.dp),
        itemSpacing = 16.dp,
        verticalAlignment = Alignment.Top,
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Green)
    ) {
        Box(
            Modifier
                .requiredHeight(100.dp)
                .background(Brush.verticalGradient(colors = listOf(Color.Blue, Color.Red)))
                .fillMaxWidth()
        )
    }
}
```
This code should display a box of 100.dp at the top of the pager. Instead they are centered.

## Expected behavior
The item of the pager should be vertically aligned.

## Screenshots?

Expected :
![image](https://user-images.githubusercontent.com/1549495/136917258-ba90b0b4-bf93-42be-8f6d-9b32375043b8.png)
What we got now : 
![image](https://user-images.githubusercontent.com/1549495/136581835-9738c205-53d0-40bd-b000-95932ef20b43.png)

## Environment:
 - Accompanist version: 0.19.0
 - Compose version : 1.0.3 and 1.1.0-alpha05

## Additional context
The issue seems to be that deep down :

```kotlin
items(
                count = count,
                key = key,
            ) { page ->
                Box(
                    Modifier
                        // We don't any nested flings to continue in the pager, so we add a
                        // connection which consumes them.
                        // See: https://github.com/google/accompanist/issues/347
                        .nestedScroll(connection = ConsumeFlingNestedScrollConnection)
                        // Constraint the content to be <= than the size of the pager.
                        .fillParentMaxSize()
                        .wrapContentSize()
                ) {
                    pagerScope.content(page)
                }
            }
```

Each items of our pager is wrapped into a Box taking the full size of the parent, meaning the verticalAlignement cannot behave correctly here.

Not sure what the best way to handle this should be. Maybe just passing a Box Alignement through the pager ?

**Comment by karan4c6** [comment]
Could use VerticalPager perhaps instead for this usecase ?

**Comment by dmitrytavpeko** [comment]
I believe the PR #844 can fix this issue too
