### ISSUE TITLE
Window insets misbehaving across android versions

### ISSUE THREAD

**Issue by dilraj-singh1997** [google/accompanist#781]
## Bug description 
Window insets are behaving differently across android versions. 
**Use case**- We want to show app content in full screen, so we hide the navigation bar and status bar using the following snippet.
```
WindowCompat.setDecorFitsSystemWindows(window, false)
requestWindowFeature(Window.FEATURE_NO_TITLE)
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
    window.attributes.layoutInDisplayCutoutMode =
        WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
}
WindowInsetsControllerCompat(window, findViewById(R.id.parent)).apply {
    hide(WindowInsetsCompat.Type.systemBars())
    systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
}
```

After this, to reposition some of the UI elements below the status bar, we are using `Modifier.statusBarsPadding()`.
This is working fine in Android SDK version 28 (Android 9).

But this is not working in Android SDK version 30 (Android 11).

If we log the `LocalWindowInsets.current.statusBars.top`, then it starts from its original value, and linearly decreases to 0. This can be seen in the screen-shots below.

<img width="1792" alt="Android API 30 insets" src="https://user-images.githubusercontent.com/87430699/136657169-57925cdb-be9c-414f-b720-1b06ab808852.png">

<img width="1792" alt="Android API 28 insets png" src="https://user-images.githubusercontent.com/87430699/136657369-3f83df13-385b-4c81-a402-af8ce8b5ed99.png">

<img width="1792" alt="Original result" src="https://user-images.githubusercontent.com/87430699/136657227-6a2f7dc7-28d6-486c-a81b-2bbf685a43b3.png">

As you can see in the above image, the emulator having Android SDK version 28 is working fine, but the emulator on the right having Android SDK version 30 is displaying both the texts at the same place. `Modifier.statusBarsPadding()` is not working in Android SDK version 30.

Code snippet for the `Text`s:
```
Text(modifier = Modifier, text = "Hello 1 $name!")
Text(modifier = Modifier.statusBarsPadding(), text = "Hello 2 $name!")
```

To solve this, we are storing the max value of `LocalWindowInsets.current.statusBars.top`, and keeping its max value in a local variable. See the following snippet,

```
val topBarPadding: Dp
    @Composable
    get() {
        var _topBarPadding by remember {
            mutableStateOf(0)
        }
        _topBarPadding = max(_topBarPadding, LocalWindowInsets.current.statusBars.top)
        return with(LocalDensity.current) { _topBarPadding.toDp() }
    }
```

This fixes the issue, now we can see the UI elements which have been given the padding of `topBarPadding` below the status bar. 

```
Modifier.padding(top = topBarPadding)
```

<img width="1792" alt="Modifier result" src="https://user-images.githubusercontent.com/87430699/136657310-443a05bf-304a-447d-8192-16a148fff8f2.png">

Now both the emulators are having the same behaviour. Code snippet for both the emulators:
```
Text(modifier = Modifier, text = "Hello 1 $name!")
Text(modifier = Modifier.padding(top = topBarPadding), text = "Hello 2 $name!")
```

Please check this issue, keeping this hack in production is not an option.

Please find the activity code attached [here](https://pastebin.com/WEnjBupH).

Thanks.

## Expected behaviour
On all Android versions, we should be able to set the status bar padding using `Modifier.statusBarsPadding()`

**Comment by bentrengrove** [comment]
I was looking at something similar recently. Because you are animating out the status bar, I believe this is working as intended. I think you will need the cutout padding which was only recently added in https://github.com/google/accompanist/pull/696 

It's not released yet I don't believe but you could build against the snapshot to try it out.
