### ISSUE TITLE
[HorizontalPager]: layout direction of HorizontalPager content doesn't change

### ISSUE THREAD

**Issue by beigirad** [google/accompanist#787]
## Describe the bug
When I apply layout direction via window.decorView.layoutDirection in activity, the content of HorizontalPager ignores the direction for initial pages (for third page and later it will apply).

When I provide Rtl in CompositionLocalProvider, it works correctly.

## To Reproduce
Just create new project and: 
```
class MainActivity : ComponentActivity() {
    @OptIn(ExperimentalPagerApi::class)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        window.decorView.layoutDirection = LayoutDirection.RTL

        setContent {
            MyApplicationTheme {
                // A surface container using the 'background' color from the theme
                Surface(color = MaterialTheme.colors.background) {
                    Greeting("Android")
                    HorizontalPager(count = 4) {
                        Row {
                            (0..3).forEach {
                                Text(
                                    text = "$it",
                                    textAlign = TextAlign.Center,
                                    modifier = Modifier.weight(1f)
                                )
                            }
                        }
                    }
                }
            }
        }
    }
}
```

## Actual bevavior
Page1: [0 1 2 3]
Page2: [0 1 2 3]
Page3: [3 2 1 0]
Page4: [3 2 1 0]

## Expected behavior
Page1: [3 2 1 0]
Page2: [3 2 1 0]
Page3: [3 2 1 0]
Page4: [3 2 1 0]

## Screenshots?
No screenshot

## Environment:
 - Android OS version: All version. but I tried Android 11
 - Device: Mi 9T
 - Accompanist version: 0.19.0

**Comment by andkulikov** [comment]
Hey. I just tested and there is a first frame when the layout is displayed as Ltr and then it is correctly updated with Rtl, seems like it is like it works in Views, the value is not immediately resolved when you update it on the decor view.
However I wasn't able to reproduce the case when the first page stays on the wrong layout direction forever. Could you please test it again on the latest version on the lib? Thanks
