### ISSUE TITLE
404 error in doc

### ISSUE THREAD

**Issue by LouisCAD** [google/accompanist#788]
## Describe the bug

Hello! I found a link pointing to a 404 status page: https://google.github.io/accompanist/api/insets-ui/insets-ui/com.google.accompanist.insets.ui/

## To Reproduce

1. Go to this page: https://google.github.io/accompanist/insets/
2. Find the text "API docs" in the page
3. Click on the link under that text
4. See the 404 status of the destination page

## Expected behavior
Link to API docs.

## Screenshot

<img width="803" alt="Screenshot 2021-10-13 at 16 24 34" src="https://user-images.githubusercontent.com/6975237/137152668-d4ac0546-9dc5-42fd-99d3-1a80638d7052.png">

I hope my report is helpful.
Have a great day!

**Comment by alexvanyo** [comment]
Thanks! I believe these should all be fixed with #784 getting merged in.

**Comment by alexvanyo** [comment]
Docs with correct link should now be live, please let us know if you find more!
