### ISSUE TITLE
IME and side effect

### ISSUE THREAD

**Issue by baole** [google/accompanist#792]
Is there a way to trigger a LaunchedEffect when the soft-keyboard is opened/closed?

**Comment by alexvanyo** [comment]
Does `LocalWindowInsets.current.ime.isVisible` let you achieve what you need to do?

That is an observable value that you could use to perform some other action depending on when the `ime` is open or closed?

**Comment by baole** [comment]
Thanks @alexvanyo, I was aware of that and tried already, but it didn't work. Here is my code snippet

```
//top level composable
MaterialTheme()  { 
    ProvideWindowInsets(consumeWindowInsets = false, windowInsetsAnimationsEnabled = false) {
     // few composable UIs go here
    LaunchedEffect(LocalWindowInsets.current.ime.isVisible) {
            Log.e(TAG, "LaunchedEffect")
           //this log is executed only one time doesn't matter how many time the soft keyboard is open/closed
    }
   /// TextField go here
   }
}
```

I also tried with `consumeWindowInsets=true` or `LaunchedEffect(LocalWindowInsets.current.ime)` but it also didn't work as expected
