### ISSUE TITLE
Not properly settling after fling (or animateScrollToPage()) when adding itemSpacing on Pager

### ISSUE THREAD

**Issue by StylianosGakis** [google/accompanist#793]
## Describe the bug
When specifying itemSpacing that is not 0.dp, the pager doesn't seem to properly settle on the item selected.
Aside from not settling properly, it feels like it doesn't snap to the item exactly, and there is some room for micro-movements really close to where the item would be centred, which makes the indicator break and just show that it's on the first page.

Note that when using `animateScrollToPage` it also doesn't settle properly, the indicator jumps to the first position for a frame and then goes back to the appropriate position again.

## To Reproduce
Implement a HorizontalPager (haven't tested with vertical) with a non-zero itemSpacing (I tried with 12.dp and 16.dp) and more than 1 item inside it (I had 4)

## Expected behavior
The pager to settle properly with the selected item in the centre of the screen, and the indicator to settle as well with it.

## Screenshots?
https://user-images.githubusercontent.com/44558292/137334007-6e09e31b-694b-4c87-8277-c855aa93c7b9.mp4

## Environment:
 - Android OS version: Android 11.0
 - Device: Samsung S20 FE 5g
 - Accompanist version: v0.19.0 (notably, the version that changed the pager behaviour to use LazyColumn/Row under the hood)

## Additional context
More discussion on the topic took place on the Kotlin Slack channel here: https://kotlinlang.slack.com/archives/CJLTWPH7S/p1634217747155600

**Comment by joharei** [comment]
Related to #758
