### ISSUE TITLE
[Idea] Add support for multiline placeholders

### ISSUE THREAD

**Issue by FrangSierra** [google/accompanist#805]
**Is your feature request related to a problem? Please describe.**
While using the library for a long time(which is awesome!), I have been facing the issue about how to show placeholders for texts with multiple lines. The actual code from the library only draws a placeholder around the whole content of the given Composable. Which sometimes can look a bit ugly. For example:
![378bd770863154ea7c23c4c385dfab93](https://user-images.githubusercontent.com/15856437/137925921-b429dca1-6757-416d-85e9-817f70a57749.png)

While the desired effect would look a bit more like:
![26d48132575c791c83e3c4336fa69e09](https://user-images.githubusercontent.com/15856437/137925873-86ef12e7-2107-4158-b725-a3b788477d4e.png)

**Describe the solution you'd like**
I would like some option to allow this customization for `Text`, `TextField`... composable methods and so on. It could be in form of a different method(like the one I propose below) ir just some more custom parameters to the actual `placeholder` modifier.

**Describe alternatives you've considered**
I have code down this solution based on the actual code from the `placeholder()` method. In case you guys like the idea I would adapt it to the actual code and open a PR. [I have added the code of my solution in this gist](https://gist.github.com/FrangSierra/6ad8de7c4d637e7035471aaf015da6c9)

I understand that maybe this is not the desired behaviour for the library, but I think that most of users who uses this library over long texts or custom spannable texts would make use of a feature like this!

Thank you so much for your time!

**Comment by FrangSierra** [comment]
Any new about this? I keep waiting for some confirmation about if this is going to be introduce into the library or if its ok for the team for me to open a PR

**Comment by tadfisher** [comment]
```kotlin
/**
 * Generate a shape consisting of rounded rectangles approximating
 * the positions of lines of text.
 *
 * @param style Text style used to calculate size and offset metrics.
 * @param widthFraction Fraction of the width to use relative to the container.
 * @param randomizeFraction Modifies [widthFraction] by a random factor between `0`
 *     and this number.
 * @param alignment Specifies how to align the shape horizontally if [widthFraction]
 *     is less than `1`.
 * @param cornerSize Corner radius if each rounded rectangle in dp.
 */
@Composable
fun TextShape(
    style: TextStyle = LocalTextStyle.current,
    widthFraction: Float = 1f,
    randomizeFraction: Float = 0.25f * widthFraction,
    alignment: Alignment.Horizontal = Alignment.Start,
    cornerSize: CornerSize = CornerSize(4.dp),
): Shape = TextShape(
    density = LocalDensity.current,
    style = style,
    widthFraction = widthFraction,
    randomizeFraction = randomizeFraction,
    alignment = alignment,
    cornerSize = cornerSize
)

/**
 * Generate a shape consisting of rounded rectangles approximating
 * the positions of lines of text.
 *
 * @param density Density used to resolve text sizes.
 * @param style Text style used to calculate size and offset metrics.
 * @param widthFraction Fraction of the width to use relative to the container.
 * @param randomizeFraction Modifies [widthFraction] by a random factor between `0`
 *     and this number.
 * @param alignment Specifies how to align the shape horizontally if [widthFraction]
 *     is less than `1`.
 * @param cornerSize Corner radius if each rounded rectangle in dp.
 */
@Composable
fun TextShape(
    density: Density,
    style: TextStyle,
    widthFraction: Float = 1f,
    randomizeFraction: Float = 0.25f * widthFraction,
    alignment: Alignment.Horizontal = Alignment.Start,
    cornerSize: CornerSize = CornerSize(4.dp),
): Shape = with(density) {
    val lineHeight = style.lineHeight.toPx()
    val fontSize = style.fontSize.toPx()
    val verticalOffset = (lineHeight - fontSize) / 2

    val randomizedWidthFraction = widthFraction - Random.nextFloat() * randomizeFraction

    return GenericShape { size, layoutDirection ->
        val lineSize = size.copy(
            height = fontSize,
            width = size.width * randomizedWidthFraction
        )
        val lines = floor(size.height / lineHeight).toInt()
        val rect = RoundRect(
            Rect(
                offset = Offset(
                    x = alignment.align(
                        size = lineSize.width.roundToInt(),
                        space = size.width.roundToInt(),
                        layoutDirection = layoutDirection
                    ).toFloat(),
                    y = verticalOffset
                ),
                size = lineSize
            ),
            CornerRadius(cornerSize.toPx(lineSize, density))
        )
        for (i in 0 until lines) {
            addRoundRect(rect.translate(Offset(0f, lineHeight * i)))
        }
    }
}
```
