### ISSUE TITLE
[Pager] CurrentPage is wrong after dataset change

### ISSUE THREAD

**Issue by zoltish** [google/accompanist#808]
## Describe the bug
If my dataset consists of A, B, C and I tap a button on page B which re-orders the dataset into B, A, C; I will continue seeing B and scrolling right shows A as expected. However the currentPage will still point to 1, immediately upon touching/scrolling the pager, it will update to 0. This happens using a HorizontalPager, although I would guess that the same thing applies for VerticalPager.

## To Reproduce
I think the description makes this clear, let me know if you want any additional information! 

This is what my logs look like. A SideEffect logs currentPage, and a snapshotFlow captures and logs the selected page whenever it changes.

(dataset is A,B,C)
Page: 0
Selected 1
Page: 1
(dataset changes to B,A,C)
Page: 1
Page: 1
(when I start scrolling the pager, I immediately see this call)
Selected 0 

## Expected behavior
The currentPage should be 0 since thats the page Im looking at.

## Environment:
 - Android OS version: API 30
 - Device: Emulator, Pixel 3a
 - Accompanist version: 0.20.0

## Additional context
A temporary workaround is to scroll to the selected page whenever it changes.

    LaunchedEffect(currentPage) {
        if (currentPage != state.targetPage) {
            state.animateScrollToPage(currentPage)
        }
    }

**Comment by qbasso** [comment]
This still happens even using keys. When I open screen and add one item, so data looks like [ C ], I have `currentPage` value = 0. Now I update data set to [A, B, C, D, E, F], and current page is still 0. `currentPage` value is set correctly after scrolling. Is there a way to force pager to recompute it's current page?

**Comment by zoltish** [comment]
@qbasso Please try the workaround I wrote about in my post above. It should fix the issue, at least until an official one is available :)
