### ISSUE TITLE
IME padding not getting applied in bottom sheet

### ISSUE THREAD

**Issue by rubenquadros12** [google/accompanist#818]
## Describe the bug
IME padding is not getting applied in the bottomsheet. The bottomsheet is always in `HalfExpanded` state. Have used accompanist navigation material for bottom sheet navigation.

You can check this [repo](https://github.com/rubenquadros12/Accompanist-Navigator)

## Expected behavior
Expecting the bottomsheet to expand to apply IME padding.

## Screenshots
![Screenshot_20211025-231210](https://user-images.githubusercontent.com/88183788/138745832-636c538c-29bb-4253-a59a-ae61b0e56972.jpg)

![Screenshot_20211025-231154](https://user-images.githubusercontent.com/88183788/138745844-135ea047-079b-4fe7-8410-4bd0083fd395.jpg)

![Screenshot_20211025-231204](https://user-images.githubusercontent.com/88183788/138745848-df09a102-6077-4a50-a265-d8678fdc7e98.jpg)

## Environment:
 - Android OS version: 11
 - Device: Emulator + OnePlus
 - Accompanist version: 0.20.0

**Comment by rubenquadros12** [comment]
@jossiwolf Is this the expected behaviour? Not the best experience from an end user perspective. Eagerly waiting for your inputs. Thanks!

**Comment by jossiwolf** [comment]
@rubenquadros12 Thanks for the report - please excuse the delay in reply; Droidcon and a cold had me beat😄 This seems to be the same issue as #813, correct?

**Comment by rubenquadros12** [comment]
Hi @jossiwolf, thanks for the reply. I hope you are doing good now. Yes, it looks similar but not sure if it is same. Please take a look at the recording.

https://user-images.githubusercontent.com/88183788/140702768-a1f5fde9-4cd6-4ede-abb1-ae448e506dca.mp4

**Comment by alexmaryin** [comment]
I have the same trouble. A long list of items, input field for text at bottom with ime padding, without bar, when soft keyboard appears the field is not scrolling to view.  AdjustResize option in manifest doesn't help.

**Comment by powilliam** [comment]
Hey there. Just sharing. I found a workaround that fits my needs using the `accompanist/insets` library. I provided a modifier with `navigationBarsWithImePadding`. I can show an example of how it looks in my app

![Screen Shot 2021-11-30 at 10 08 38 PM](https://user-images.githubusercontent.com/55867831/144153345-d3be7558-c463-45ce-9dc3-0954c1ba47af.png)
.

**Comment by rubenquadros12** [comment]
@jossiwolf any update on this?

**Comment by Zeliret** [comment]
My workaround here:
```kotlin
val stateProperty = BottomSheetNavigator::class
        .members
        .firstOrNull { it.name == "sheetState" }
            as? KProperty1<BottomSheetNavigator, *>
        ?: return
    ModalBottomSheet(
        sheetState = stateProperty.get(bottomSheetNavigator) as ModalBottomSheetState,
        sheetContent = {
            bottomSheetNavigator.sheetContent(this)
        }
    ) {
        NavHost(
            navController = navController,
            startDestination = "home"
        ) {
            // routes
        }
    }

@ExperimentalMaterialApi
@Composable
fun ModalBottomSheet(
    sheetState: ModalBottomSheetState = rememberModalBottomSheetState(Hidden),
    sheetContent: @Composable() (ColumnScope.() -> Unit),
    content: @Composable () -> Unit
) {
    ModalBottomSheetLayout(
        sheetState = sheetState,
        sheetContent = {
            Column(
                modifier = Modifier
                    .navigationBarsWithImePadding() // HERE WE APPLY INSETS
            ) {
                sheetContent()
            }
        }
    ) {
        content()
    }
}
```

**Comment by rubenquadros12** [comment]
@jossiwolf Any idea when this will be done? Its been quite a while now 😅

**Comment by Nek-12** [comment]
@jossiwolf should this be reopened?

**Comment by aabolfazl** [comment]
Do you know if there is any progress or how to fix this problem? I have a kind of problem with BottomSheetScaffold.

**Comment by aabolfazl** [comment]
Does anybody know if there is any progress or how to fix this problem? I have a problem with BottomSheetScaffold in this context.

**Comment by daniel-iroka** [comment]
Has anyone found a fix for this issue? I am having the same problem as well

**Comment by hrach** [comment]
@daniel-iroka Use M3-based bottomsheets in navigation compose - the integration part is here: https://github.com/hrach/navigation-compose-ext
