### ISSUE TITLE
How to change the status bar color when the app still booting

### ISSUE THREAD

**Issue by ifnyas** [google/accompanist#845]
## Describe the bug
I believe it is the intended behavior because I put the `SideEffect { ... }` inside onCreate, but I need to change the status bar color when the app is booting too. Right now it's using the color from XML when booting. Do you have any workaround on how to achieve this without editing XML?

## To Reproduce
Just put the sample code inside the onCreate of MainActivity

## Expected behavior
The status bar color is also applied when the app still booting

## Screenshots?
![Screenshot_1635591441](https://user-images.githubusercontent.com/34657831/139530170-151ea8f6-9885-49f6-94f9-531682e88f48.png)

## Environment:
 - Android OS version: SDK 29
 - Device: Emulator, Pixel
 - Accompanist version: 0.21.0-beta

## Additional context
-

**Comment by re-ovo** [comment]
You need to edit the theme in xml, because compose is not fully loaded yet 

But it is better to use splash screen to avoid the white screen: https://developer.android.com/guide/topics/ui/splash-screen/migrate
