### ISSUE TITLE
Issue spacing items with max width in HorizontalPager

### ISSUE THREAD

**Issue by jeffreyfhow23** [google/accompanist#849]
## Explanation
Using Jetpack Compose and the [accompanist][1] pager, I'm trying to create a [`HorizontalPager`][2] where:

 1. Edges of items to the left and right of current item are shown
 2. There is a max width to the `Pager` items

As an example, I wrote the following code (for simplicities sake, I made `Text` items, but in reality, I'm actually making more complex `Card` items):

```
@Composable
fun MyText(modifier: Modifier) {
  Text(
    text = LOREM_IPSUM_TEXT,
    modifier = modifier
      .wrapContentHeight()
      .border(BorderStroke(1.dp, Color.Red))
  )
}

@ExperimentalPagerApi
@Composable
fun MyPager(pagerItem: @Composable () -> Unit = {}) {
  Scaffold {
    Column(
      modifier = Modifier
        .fillMaxSize()
        // In case items in the VP are taller than the screen -> scrollable
        .verticalScroll(rememberScrollState())
    ) {
      HorizontalPager(
        contentPadding = PaddingValues(32.dp),
        itemSpacing = 16.dp,
        count = 3,
      ) {
        pagerItem()
      }
    }
  }
}

@ExperimentalPagerApi
@Preview
@Composable
fun MyPager_200dpWidth() {
  MyPager { MyText(modifier = Modifier.widthIn(max = 200.dp)) }
}

@ExperimentalPagerApi
@Preview
@Composable
fun MyPager_500dpWidth() {
  MyPager { MyText(modifier = Modifier.widthIn(max = 500.dp)) }
}

@ExperimentalPagerApi
@Preview
@Composable
fun MyPager_FillMaxWidth() {
  MyPager { MyText(modifier = Modifier.fillMaxWidth()) }
}

```

The issue I'm having is that when I make the item have a max width that seems to be smaller than the screen width (see `MyPager_200dpWidth`), I no longer see the items on the side anymore. On the other hand, using items with **larger** max widths (See `MyPager_500dpWidth`) or `fillMaxWidth` (See `MyPager_FillMaxWidth`) allows me to see the items on the side. 

It seems weird to me that items with the **smaller** max width are actually taking up more horizontal space than the items with the **larger** max width. This can be shown in the Preview section...

[![Preview Comparison][3]][3]

See how the images on the left (`MyPager_500dpWidth) and middle (`MyPager_FillMaxWidth`) show the next item, while the image on the right (`MyPager_200dpWidth`) takes up the whole screen? Here's another comparison when hovering my mouse over the items to see the skeleton boxes...

[![Preview Comparison with skeleton][4]][4]

Just wondering if someone could help me figure out how I can solve this use case. Is it possible that there's a bug in Compose?

  [1]: https://github.com/google/accompanist
  [2]: https://google.github.io/accompanist/pager/#horizontalpager
  [3]: https://i.stack.imgur.com/2LyFN.png
  [4]: https://i.stack.imgur.com/hOSkn.png

## To Reproduce
1. Copy and paste above code into an Android project
2. Note the preview of the `MyPager_200dpWidth` composable
3. Edges of next item is not shown (Same happens if running a build that uses this composable). It appears as the item is taking up the entire width of the screen.

## Expected behavior
Similar to `MyPager_500dpWidth` or `MyPager_FillMaxWidth` composables, the `MyPager_200dpWidth` composable should still show the edges of items to the left/right of the current item.

## Environment:
 - Accompanist version: `0.21.0-beta`
 - compileSdkVersion = 31
 - minSdkVersion = 24
 - targetSdkVersion = 30

**Comment by yacine-ser** [comment]
Try setting the content padding to a higher value. It makes sense that tems with a width of 200dp don't appear as they're too narrow.

**Comment by andkulikov** [comment]
Yes, you need to not change the size of your text - the item bounds are not getting smaller because of it - but instead provide larger contentPadding to Pager. This will make it look as you need
