### ISSUE TITLE
No navigation bar scrim is rendered on Android 7.0 Nougat and all versions pre 29

### ISSUE THREAD

**Issue by spacecowboy** [google/accompanist#852]
## Describe the bug
When requesting transparent navigation bar, and using the default logic for darkIcons:

```
val systemUiController = rememberSystemUiController()
SideEffect {
  systemUiController.setSystemBarsColor(
    Color.Transparent,
  )
}
```
then no scrim is applied on Android Nougat, rendering the navigation icons almost invisible. See attached screenshot:

<img height=50% width=50% src="https://user-images.githubusercontent.com/223655/140321778-d05fb899-0ba9-472e-a0a2-9eb7fffa0632.png">

## To Reproduce
1. Start an emulator running Android 7.0 Nougat
1. Use a light material theme and request transparent system bars, and let the default code set `darkIcons` to `false`
2. No scrim is rendered on Android Nougat

## Expected behavior
A scrim should be rendered, just as it is on later version of Android (for example Android R).

## Environment:
 - Android OS version: 7.0, but all versions are affected below API29
 - Device: Emulator
 - Accompanist version: 0.17.0

**Comment by alexvanyo** [comment]
If I'm understanding correctly, are you expecting `isNavigationBarsContrastEnforced` backported to API versions 28 and below?

**Comment by spacecowboy** [comment]
> If I'm understanding correctly, are you expecting `isNavigationBarsContrastEnforced` backported to API versions 28 and below?

I've since solved it, but what I expected was for the example to actually work as advertised on all Android versions it supports.
