### ISSUE TITLE
[Idea] Bottom sheet blur effect color should be based on theme (dark / light)

### ISSUE THREAD

**Issue by alwa** [google/accompanist#853]
When the modal bottom sheet is opened the blurring effect of the background is whitish.
When I switch to dark mode and open the modal bottom sheet I would like the blur effect to be darker but in fact it's the same effect as in light mode.

I'm using version 0.21.0-beta of navigation-material.

**Comment by ianhanniballake** [comment]
All Accompanist does is pass the `scrimColor` you add its `ModalBottomSheetLayout` to the Material [`ModalBottomSheetLayout`](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#ModalBottomSheetLayout(kotlin.Function1,androidx.compose.ui.Modifier,androidx.compose.material.ModalBottomSheetState,androidx.compose.ui.graphics.Shape,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,kotlin.Function0)). That means you have full control over what scrim (i.e., background dimming) you want and could change it based on whether you are in dark mode or not.

You can, of course, [file a bug against Compose](https://issuetracker.google.com/issues/new?component=742043&template=1590761) if you'd like the default `ModalBottomSheetDefaults.scrimColor` to take dark mode into consideration when choosing the default color - that's not something we're ever going to independently change at the Accompanist level.

**Comment by alwa** [comment]
FYI: I reported my suggestion here: https://issuetracker.google.com/issues/205344336
