### ISSUE TITLE
[navigator-animation] NullPointerException in AnimatedNavHost

### ISSUE THREAD

**Issue by alexander-kalnoy** [google/accompanist#856]
In `AnimatedNavHost` there is allowed to set `enterTransition` and `exitTransition` and others as null. But then, when `finalEnter` and `finalExit` are defining, there is a strange non-null cast. But it could be null. Example: 
```
initialDestination.popExitTransition?.invoke(this, initialEntry, targetEntry) ?: popExitTransitions[(initialDestination.hierarchy.first {popExitTransitions.containsKey(it.route)}).route]?.invoke(this, initialEntry, targetEntry) as ExitTransition
```
It actually happens 4 times per each combination enter, exit, popEnter and popExit. Either there should not be possibility to define animations as null or need to do something with this cast. Personally I want to see possibility to disable screen animations when I don't want to use it. Now, it always take default animation from AnimatedNavHost even if I set null in `compose` method.

**Comment by ianhanniballake** [comment]
No, it can never be null as the transitions defined at the `AnimatedNavHost` level are lambdas that must return a non-null value (and if you define `null` at a `composable` level, it walks up the navigation graph hierarchy until you return a non-null transition).

You'd want to use `EnterTransition.None` or `ExitTransition.None`, respectively, if you don't want any screen animation, not null.

**Comment by alexander-kalnoy** [comment]
So you would change the `AnimatedNavHost `? Because now, if I setup it like this:
```
AnimatedNavHost(
    navController = navController,
    startDestination = firstScreen,
    enterTransition = null,
    exitTransition = null
) {
    composable(
        route = Screens.WidgetGuideScreen,
        enterTransition = null,
        exitTransition = null,
    ) {
        WidgetGuide(navController)
    }
}
```
the application would crash, because of the code I sent in question. Composable animation is null, so the host search for high level animation and it finds it, actually, but it is a null lambda too. In this code then `?.invoke(this, initialEntry, targetEntry) as EnterTransition` the invoke method would never be called and the lib tries to cast null lambda to non-null EnterTransition. If you remove cast when the lib defines `finalEnter` and `finalExit` you can see that code looks wrong)) cause everything inside it might be null and everything in the end force casts to Transition, which throws the exception.

If there always should be non-null default animation, then AnimatedNavHost should never allow to use null lambdas for `enterTransition` and `exitTransition`. Thats what bothering me. But thanks for a tip about `EnterTransition.None` I didn't see it, will check.

**Comment by ianhanniballake** [comment]
You're right, the `AnimatedNavHost` APIs should not accept a null value. We can fix that.
