### ISSUE TITLE
[navigator-animation] No ability to set per transaction animation

### ISSUE THREAD

**Issue by alexander-kalnoy** [google/accompanist#857]
In android fragment transactions when we use `setCustomAnimations` in transaction the animations we set applying to both target and destination fragments. So I can say that when fragment A is open or closed it should not use animations or use default animation. But when the fragment B is opening, fragment A should use a slide animation e.g. to go out and then enter after popBackStack operation. So basically I set per transaction animation.

In current `AnimatedNavHost` API we can set animations like this:
```
composable(
  route = Screens.A,
  enterTransition = FadeEnter(),
  exitTransition = FadeExit(),
  popEnterTransition = FadeEnter(),
  popExitTransition = FadeExit()
)
composable(
  route = Screens.B,
  enterTransition = SlideEnter(),
  exitTransition = SlideExit(),
  popEnterTransition = SlideEnter(),
  popExitTransition = SlideExit()
)
```
This would mean that screen A always will use fade transition animation in transactions, and fragment B will use slide animations. So that means if I go from A to B. The A would perform fade animation to go out and B slide to go in. But if I use the android fragment transactions analogue:
```
...setCustomAnimations(R.anim.fade_in, R.anim.fade_out, R.anim.fade_in, R.anim.fade_out).replace(R.id.container, FragmentA())
...setCustomAnimations(R.anim.slide_in, R.anim.slide_out, R.anim.slide_in, R.anim.slide_out).replace(R.id.container, FragmentB())
```
I would receive another effect when I go from fragment A to B. The A would perform the slide animation to go out and B the slide animation to go in. If we go from B to A, both B and A would use fade animations.

It is very useful that we can set animations per transactions, more useful than set an animation per screen. Sometimes we need to change screen animation, depends which one opens next.

So, I guess the question is this intentional? or it is a bug? Because it fixes very easy, when `AnimatedNavHost` calculates `finalEnter` is should use `initialDestination.popEnterTransition` for pop operations and `targetDestination.enterTransition` for simple enter. And for `finalExit` need to use `initialDestination.popExitTransition` for pop operation and `targetDestination.exitTransition` for simple exit.

I don't know if this a bug or feature request. But I think it would be better to use same approach in native android and compose.

**Comment by ianhanniballake** [comment]
The `enterTransition`, `exitTransition`, `popEnterTransition`, and `popExitTransition` aren't static transitions defined at the screen level - they are lambda methods that give you what screen you are coming from (the A) and what screen you are coming from (the B) and additionally let you reference any mutable state you want inside those lambdas for infinitely more customization than the fragment system.

You might take a look at the [`AnimatedNavHost` sample](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/navigation/animation/AnimatedNavHostSample.kt), which shows exactly how you can use the `initialState` (the screen you are coming from) and the `targetState` (the screen you are going to) to customize exactly what transitions are ran.
