### ISSUE TITLE
[Idea] Support bottom sheet default half/full expanded configuration

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#858]
Taken from https://github.com/google/accompanist/issues/657 but marked as stale

The twist on my idea is that each bottom sheet can be configured to be either half expanded or fully expanded instead of in the feature request above, it seems to be on the `ModalBottomSheetLayout` level.

Use case:
Right now I have one bottom sheet in one context that I want to "half open" and then in another context I want to call a different bottom sheet modal, but I want it to open fully.

**Comment by jossiwolf** [comment]
Thanks! We can certainly consider configuring this on a per-destination basis as soon as the upstream issue in Compose Material (https://issuetracker.google.com/issues/186669820) is fixed. Can you please add your idea as a comment on #657? :)
