### ISSUE TITLE
Pager Tab Indicator Offset begins moving right and then jumps to the left when swiping HorizontalPager to the right?

### ISSUE THREAD

**Issue by TobiasEdqvist** [google/accompanist#862]
## Describe the bug
Pager Tab Indicator Offset begins moving right and then jumps to the left when swiping Pager to the right in a HorizontalPager. See attached screenshots for the four steps that occur.

## To Reproduce
1. Create a ScrollableTabRow that uses an indicator with a modifier pagerTabIndicatorOffset.
2. Connect a HorizontalPager to the ScrollableTabRow according to examples given.
3. Set an initialPage > 0 for the pagerState.
4. Run app.
5. Slow scroll in the horionztal pager with a motion -> Right to switch to a previous tab.
6. See the indicator offset moving "with the motion" at first, then after halfway behave correctly and move against the user motion.

## Expected behavior
The indicator should move towards the left all the time, not start to the right and then jump to the left (It does not start left when scrolling -> Left, so it is only one direction that is incorrect).

## Screenshots
Start position:
![image](https://user-images.githubusercontent.com/9076528/140606476-1d7e6afd-75e9-4112-927a-cd4d1df51f3e.png)

Begin scrolling the HorizontalPager with a motion -> Right to intend to scroll to day "Wed 3" from current "Thu 4".
![image](https://user-images.githubusercontent.com/9076528/140606485-5fe8d18d-bf23-4af3-9aed-6f3fc586e02b.png)

Get over half-way of the scrolling, the indicator will move to the correct target side:
![image](https://user-images.githubusercontent.com/9076528/140606492-e199d9d1-154f-4a42-b6a8-ebd983875cc2.png)

Complete the scrolling and changing day to "Wed 3":
![image](https://user-images.githubusercontent.com/9076528/140606495-bc9fd7cc-351c-426f-bc41-c05232d0aab0.png)

## Environment:
 - Android OS version: Android 11.0
 - Device: Emulator, Google Pixel 4
 - Accompanist version: 0.21.2-beta

**Comment by geekykant** [comment]
Can you try on '0.20.2'.

**Comment by TobiasEdqvist** [comment]
> Can you try on '0.20.2'.

Same issue on 0.20.2, and 0.19.0. I tried 0.17.0 (had to make some code changes with page count) and there I get a different behavior, however still not correct. Instead of moving the indicator during scroll -> Right of the HorizontalPager it is "Stuck" and when the pager change is complete it moves to "Wed 3". scroll -> Left of the HorizontalPager still works though. We are using 1.1.0-beta02 of Compose but also tried with 1.0.5 and have the same issue...

**Comment by Edmko** [comment]
Here is the problem. Can be fixed by change currentPageOffset<-0.5 to 0 [#755]
![image](https://user-images.githubusercontent.com/55951401/135462286-6604531e-7f4f-417e-a789-a88faccab13e.png)

**Comment by TobiasEdqvist** [comment]
> Here is the problem. Can be fixed by change currentPageOffset<-0.5 to 0 [#755]
> ![image](https://user-images.githubusercontent.com/55951401/135462286-6604531e-7f4f-417e-a789-a88faccab13e.png)
> I just waiting for fix from start of fall.

Definitely looks like you've found the issue, missed your issue since it was closed... I wonder why this was changed to -0.5f when moving to LazyRow|Column since this was "currentPageOffset < 0 -> (currentPage - 1).coerceAtLeast(0)" before in the previous solution? Did that result in any other issues?

**Comment by Edmko** [comment]
Yes. This is result of fix for [#679] in scope of rewriting to LazyRow

**Comment by andkulikov** [comment]
Hello. Feel free to create a PR with a fix, I will be happy to review it. Thanks!

**Comment by andkulikov** [comment]
Fixed by https://github.com/google/accompanist/pull/815

**Comment by jakoss** [comment]
@andkulikov Can this be backported to non-beta version and released for those that are still using stable compose versions?

**Comment by andkulikov** [comment]
> @andkulikov Can this be backported to non-beta version and released for those that are still using stable compose versions?

0.20.3 was just released which includes the fix
