### ISSUE TITLE
Question: Dismiss bottom sheet programmatically?

### ISSUE THREAD

**Issue by alwa** [google/accompanist#864]
Hi, In non-compose bottom sheets you have state object that you can manipulate by calling expand()/collapse() but com.google.accompanist.navigation.material.BottomSheetNavigatorSheetState doesn't have that.

My current workaround:
- The bottom sheet content is defined to be a column with clickable menu options. One of the menu options is "Close".
- The temporary hack consists of calling the nav controller to re-route to a new destination.

Surely there must be a better way... 
Is there a recommended way to dismiss the bottom sheet programmatically?

**Comment by jossiwolf** [comment]
Accompanist Navigation Material provides a way to use bottom sheets as navigation destinations. As such, the only programmatic control you have over the sheet is with any other navigation destination, i.e. navigating to or away from a bottom sheet destination. When you want to close the bottom sheet, you can pop the back stack entry or navigate to the destination you want to navigate to, similar to what you are doing currently.
