### ISSUE TITLE
SystemUiController throws NullPointerException on FairPhone3

### ISSUE THREAD

**Issue by zoltish** [google/accompanist#865]
## Describe the bug
Im seeing this crash happening for users with FairPhone3. 

```
Fatal Exception: java.lang.NullPointerException
       at com.google.accompanist.systemuicontroller.AndroidSystemUiController.<init>(AndroidSystemUiController.java:177)
       at com.google.accompanist.systemuicontroller.SystemUiControllerKt.rememberSystemUiController(SystemUiControllerKt.java:164)
```

## Environment:
 - Android OS version: 10
 - Device: Fairphone3
 - Accompanist version: 0.21.2-beta

Edit 1: This happens on Huawei as well. Seems to mostly happen when the screen is being turned off.
HUAWEI MediaPad T3 10 & Mate 20

Edit 2: This is probably my own fault. The code is being called in an overlay (`WindowManager.addView`) inside a `ForegroundService`, I dont believe it actually has a window? Im not sure why the crash is only happening on the select devices though.

**Comment by alexvanyo** [comment]
RE: Edit 2: `SystemUiController` is only intended to be used in the context of an `Activity` with a `Window`, so if you try to use it elsewhere a crash would be expected. In the most recent release, the error message for this was improved, so you should be able to see if that's the case.

If you're still experiencing a crash while within an `Activity` with a `Window`, please open another issue!
