### ISSUE TITLE
Background content should not be interactable in bottomsheet.

### ISSUE THREAD

**Issue by Abhilash-Viswa** [google/accompanist#868]
## Describe the bug
Background content of bottomsheet is interactable when bottomsheet is scrolled and held down

## To Reproduce
1. Go to any bottomsheet
2. Scroll down and hold it down.
3. Background content is interactable.

Edit:  Code to Reproduce
```
@OptIn(ExperimentalMaterialNavigationApi::class)
@Composable
fun Navigation() {
    val navController = rememberNavController()
    val bottomSheetNavigator = rememberBottomSheetNavigator()
    navController.navigatorProvider += bottomSheetNavigator
    ModalBottomSheetLayout(
        bottomSheetNavigator = bottomSheetNavigator,
        sheetElevation = 8.dp,
        sheetShape = RoundedCornerShape(topStart = 8.dp,topEnd = 8.dp)
    ) {
        NavHost(navController = navController, startDestination = "Home") {
            composable("Home") {
                Home(navController = navController)
            }

            bottomSheet("bottomSheet") {
                BottomSheetContent()
            }
        }
    }
}

@Composable
fun Home(navController: NavController) {
    LazyColumn(
        modifier = Modifier
            .height(3000.dp)
            .fillMaxWidth(),
        verticalArrangement = Arrangement.SpaceBetween,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        items(10) {
            Button(
                onClick = {
                    navController.navigate("bottomSheet")
                },
                modifier = Modifier
                    .height(100.dp)
                    .padding(vertical = 25.dp)
            ) {
                Text(text = "${it + 1}")
            }
        }
    }
}

@OptIn(ExperimentalMaterialNavigationApi::class)
@Composable
fun BottomSheetContent() {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .height(500.dp)
            .background(Color.LightGray.copy(alpha = 0.5f)),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text(text = "This is Bottom Sheet Content")
    }
}

```
## Expected behavior
Background content should not be interactable until bottom sheet is out of backstack.

## Screenshots?
https://user-images.githubusercontent.com/84134817/141067175-c44e36e1-9ded-4506-8b75-7487c6449162.mp4

## Environment:
 - Android OS version: Android 10
 - Device: Redmi K20 Pro
 - Accompanist version: 0.20.2

**Comment by jossiwolf** [comment]
Thanks for the report! This is the default behavior of Material's `ModalBottomSheetLayout`'s scrim. To explain a little more: The scrim blocks clicks and is only shown when the sheet's target state is `HalfExpanded` or `Expanded`/when the sheet is visible. Therefore, when pausing the animation when the target state is `Hidden`, the scrim isn't in the composition anymore and doesn't block clicks. 

The desired behavior might be that the scrim is invisible but still blocks clicks until the sheet is completely hidden but we'd need to get that confirmed and possibly by the Material team.

Please file an issue with the Material folks here: https://issuetracker.google.com/issues?q=componentid:742043
