### ISSUE TITLE
[Pager] Page before last hint sometimes disappears when swiping to last page

### ISSUE THREAD

**Issue by juliemovify** [google/accompanist#875]
## Describe the bug
In `HorizontalPager`, when using contentPadding, page before last hint sometimes disappears when swiping to last page.  
When that happens, slightly swiping the last page will show before to last page.

## To Reproduce
1. List with 3 elements (see code below)
2. Swipe to last page
3. See that the before to last page hint disappears on the left of the screen
4. If the issue doesn't occur, you can swipe to previous page and retry from 2.

````
@OptIn(ExperimentalPagerApi::class)
@Composable
private fun Sample() {
    Column(Modifier.fillMaxSize()) {
        val colorPages = remember {
            listOf(Color.Cyan, Color.Magenta, Color.Yellow)
        }
        val pagerState = rememberPagerState()

        HorizontalPager(
            state = pagerState,
            count = colorPages.size,
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(horizontal = 26.dp),
        ) { page ->
            Text(
                text = "hello",
                modifier = Modifier
                    .fillMaxSize()
                    .background(colorPages[page])
            )
        }
    }
}

````
## Expected behavior
Page before last hint should be displayed consistently on last page. 

## Screenshots?
<img src="https://user-images.githubusercontent.com/48796265/141768858-f4638682-fb9c-4a75-b8e5-e24e2002d9a8.gif" width="40%" height="40%"/>

## Environment:
 - Android OS version: Tested on Android 28
 - Device: Emulator
 - Accompanist version: 0.20.2 and 0.21.2-beta

**Comment by andkulikov** [comment]
It was a bug in LazyRow and is now fixed in the main Compose repository - https://android-review.googlesource.com/c/platform/frameworks/support/+/1900422.
Thanks for the report
