### ISSUE TITLE
[Pager] animateScrollToPage tries to render all pages after changing to LazyRow

### ISSUE THREAD

**Issue by micHar** [google/accompanist#876]
## Describe the bug
This is a regression of https://github.com/google/accompanist/issues/368 after Pager has been reimplemented with LazyRow / LazyColumn.
> Pager seems to really try and scroll through all the pages and render them while doing so. In effect, when I animateScrollToPage from, say, page 1 to page 80, it looks very laggy. Old ViewPager is cheating here - it only really scrolls one page. So if I wanted it to scroll from page 1 to page 80, it would really only scroll from 79 to 80. It was fast enough to fool the eye, though - and thus looked smoother.

## Environment:
```
val composeVersion = "1.1.0-beta02"
val accompanistVersion = "0.21.2-beta"
```

**Comment by jari-kuipers** [comment]
I was trying this out and we are experiencing this issue as well. The first method was definitely superior and Google Maps does it that way too. We're still stuck on 0.18.0 because of these issues.

I hope we can migrate soon...

**Comment by micHar** [comment]
Is there any update here?

**Comment by micHar** [comment]
Well, copying 0.18 version is very easy and after a quick test I don't see any issues, so as a quick workaround it's fine.
https://github.com/google/accompanist/tree/v0.18.0/pager/src/main/java/com/google/accompanist/pager

**Comment by jari-kuipers** [comment]
Well glad that helped. Have you tried the latest version already? Did it fix anything?

**Comment by micHar** [comment]
No, I'm on `1.1.0-beta02` right now, but I don't think new version was fixed, @andkulikov would let us know or cross referenced a pull request if he started working on that. I hope it's going to be properly fixed at some point.

@andkulikov is there maybe a Compose / LazyRow blocker issue on google issue tracker that we could follow or you don't know yet how to tackle this issue?

**Comment by andkulikov** [comment]
There is no clear strategy what to do with this issue yet. I will explore how that was handled in ViewPager2 which is based on RecyclerView which is pretty similar
