### ISSUE TITLE
SystemUiController.setStatusbarColor not changed icons color in status bar

### ISSUE THREAD

**Issue by AndreiRoze** [google/accompanist#881]
## Describe the bug
SystemUiController.setStatusbarColor not changed icons color in status bar if android:windowLightStatusBar is "true" in themes.xml. If  android:windowLightStatusBar is "false" SystemUiController.setStatusbarColor works correct. Is it correct behavior?
## To Reproduce
1. Go to themes.xml and add `<item name="android:windowLightStatusBar">true</item>` to current theme which selected in AndroidManifiest.xml
2. Try to change icons color in status bar to light:
```
SideEffect {
        systemUiController.setStatusBarColor(
            color = statusBarColor,
            darkIcons = false
        )
    }
```
3. Icons in status bar still dark.
## Expected behavior
Icons color should be light

## Screenshots?
![examplecolor](https://user-images.githubusercontent.com/53582576/142771523-a3a65c04-8c14-4d6f-9c75-63bbb48357fd.jpg)

## Environment:
 - Android OS version: Android 11
 - Device: OnePlus 9R, OnePlus 3
 - Accompanist version: v0.21.2-beta

**Comment by jemshit** [comment]
In my case, i set statusBarColor Transparent, and no extra xml setting, but icons are always white.
```
systemUiController.setSystemBarsColor(color = Color.Transparent,
                                      darkIcons = true)
```

Android 11

**Comment by jayesh83** [comment]
> In my case, i set statusBarColor Transparent, and no extra xml setting, but icons are always white.
> 
> ```
> systemUiController.setSystemBarsColor(color = Color.Transparent,
>                                       darkIcons = true)
> ```
> 
> Android 11 v0.20.2

were you able to get it worked? I'm still facing this issue. I'm also having status bar transparent.
