### ISSUE TITLE
Regression: NavHost ignores the user specified transition animation.

### ISSUE THREAD

**Issue by tyeen** [google/accompanist#882]
## Describe the bug
The transitions specified in the `build` block of `AnimatedNavHost` function are completely ignored.

As the document says, we could pass transition blocks like `exitTransition` or `popEnterTransition` to `AnimatedNavHost` composable function to specify the animation transitions when navigate to a target or navigate back.

However as the change of #873 , the user specified transitions are totally ignored.
Take enter transition for example, when `AnimatedNavHost` is actually built, the `finalEnter` transition is no longer looking for `targetDestination.enterTransition` value, but determined by the global `enterTransitions` map, which is empty by default and then fallback to the `enterTransition` parameter which has default value of `fadeIn` animation.

The `finalExit` transition has the same issue.

## To Reproduce
Creating a simple test app using `accompanist-navigation-animation:0.21.3-beta` would produce.
I've attached a sample app.

## Expected behavior
User specified transitions should not be ignored.

## Environment:
 - Accompanist version: accompanist-navigation-animation:0.21.3-beta

## Additional context
0.21.2-beta does not have this issue.

## Sample app
[MyApplication.zip](https://github.com/google/accompanist/files/7577994/MyApplication.zip)

**Comment by tyeen** [comment]
As the code suggests, `enterTransitions` is used by creating nested nav-graph. So skipping the `targetDestination.enterTransition` checking does not seem reasonable.

Code position:
https://github.com/google/accompanist/blob/76ab3e954177e7e99ffde0d322cd563287bdb970/navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedNavHost.kt#L176

**Comment by ianhanniballake** [comment]
Yeah, it seems like we have two source of truths for the transitions - graphs use [the AnimatedNavHost level maps](https://github.com/google/accompanist/blob/76ab3e954177e7e99ffde0d322cd563287bdb970/navigation-animation/src/main/java/com/google/accompanist/navigation/animation/NavGraphBuilder.kt#L109), but individual destinations do not.

We should consolidate down to just a single source of truth (and given the structural limitations with how nested graphs are set up, that probably means to use the maps for all destinations, which will automatically fix the code AnimatedNavHost uses).
