### ISSUE TITLE
[Idea] `NavGraphBuilder.bottomSheet()` should support actions to take after onSheetDismissed

### ISSUE THREAD

**Issue by colintheshots** [google/accompanist#889]
**Is your feature request related to a problem? Please describe.**
I need to be able to support navigating or performing other actions after the user taps away from the bottom sheet, not only when they tap on a close or action button inside the bottom sheet.

**Describe the solution you'd like**
I would like to have an optional callback parameter I could pass to `NavGraphBuilder.bottomSheet()` to be able to perform custom actions after the bottom sheet has been dismissed.

**Describe alternatives you've considered**
I considered writing a custom `BottomSheetNavigator` class and `rememberBottomSheetNavigator()` function which accepts a parameter that controls what actions to perform at the end of `onSheetDismissed()` for a given route.

**Additional context**

**Comment by colintheshots-meetup** [comment]
Ideally, the callback should also pass in the backstackEntry's arguments.

**Comment by ianhanniballake** [comment]
You already get a callback within the bottom sheet when it is disposed (via `DisposableEffect`) or outside of the bottom sheet (via changes in the state of the `NavController`). Can you explain your use case?

**Comment by colintheshots-meetup** [comment]
I may be wrong, but I'm guessing DisposableEffect may work for my case. I had heard about it in another context, but hadn't thought of it for this purpose. I'll give it a try. Thanks!
