### ISSUE TITLE
Navigation Animation module doesn't support passing arguments for startDestination

### ISSUE THREAD

**Issue by ShuaiZhangXero** [google/accompanist#897]
## Describe the bug
`accompanist-navigation-animation` module not support add arguments/path for `startDestination`
We have a requirement for set up `startDestination` dynamically, for e.g, our first page is dependent on user login status, if user is log out, we will go to sign up page, otherwise we will go to dashboard.

## To Reproduce
We found that we can set path or arguments for `NavController.navigation(args)` method to jump page with arguments, so we want use the same way for `startDestination` in `AnimatedNavHost(startDestination="xxx with dynamic args")`, we will get an error `navigation destination $dest is not a direct child of this NavGraph`

Here is the sample code: 
```
AnimatedNavHost(
                navController = LocalNavController.current,
                startDestination = "main?login=true", // if we change to main?login={login} it will match hashcode, but we dont know how to pass args to start destination
                enterTransition = { _, _ ->
                    slideInHorizontally(
                        initialOffsetX = { fullWidth -> fullWidth },
                        tween(SMALL_TRANSITION_DURATION)
                    )
                }) {
                composable(
                    route = "main?login={login}",
                    arguments = listOf(navArgument("login") {
                        defaultValue = true
                    })
                ) {
                    MainScreenContainer()
                }
            }
```

## Expected behavior
We can parse navigation args correctly.

## Environment:
 - Android OS version: Android 11.0
 - Device: Google Pixel 4
 - Accompanist version: (We current use version: `0.20.0`, when I upgrade it to the lastest one `0.21.3-beta`, it is still not work yet)

## Additional context(Some look up in source code)
I found that when we set the `startDestination`, then the lib will call `NavGraphNavigator` to do the `navigate` job, it will use `NavGraph.findNode()`, the findNode logic dependent on `hashCode`, that's why we set the path with dynamic args, it will change the `hashCode`, so we can't find the destination in `NavGraph`.
I compared the logic between `NavGraphNavigator.navigate` and `NavController.navigation`, the second one use `matchDeepLink` method, it will match `uri pattern` rather than `hashCode`

**I just wonder that why we use `hashCode` instead of `deeplink pattern` matcher?**

**Comment by ianhanniballake** [comment]
First of all, that isn't the right approach for login when in Navigation at all. As per the [Conditional Navigation](https://developer.android.com/guide/navigation/navigation-conditional) page and explained in the [Navigating Navigation talk](https://www.youtube.com/watch?v=09qjn706ITA&t=273s), you need to conditionally `navigate()` to your login screen when your business logic detects that you need to login.

Even then, you don't pass arguments via `startDestination`. As explained in [this issue](https://issuetracker.google.com/issues/200065981#comment2), you can simply change the `defaultValue` based on your logic, rather than hardcoding it to `true`.

**Comment by ShuaiZhangXero** [comment]
> First of all, that isn't the right approach for login when in Navigation at all. As per the [Conditional Navigation](https://developer.android.com/guide/navigation/navigation-conditional) page and explained in the [Navigating Navigation talk](https://www.youtube.com/watch?v=09qjn706ITA&t=273s), you need to conditionally `navigate()` to your login screen when your business logic detects that you need to login.
> 
> Even then, you don't pass arguments via `startDestination`. As explained in [this issue](https://issuetracker.google.com/issues/200065981#comment2), you can simply change the `defaultValue` based on your logic, rather than hardcoding it to `true`.

Good idea, when I set the `defaultValue`, it works.
