### ISSUE TITLE
Navigation Animation: transitions don't work for separate composable 

### ISSUE THREAD

**Issue by AlexeyTernopolsky** [google/accompanist#898]
## Describe the bug
Transitions provided to simple composable in NavGraphBuilder are not work anymore. 

## To Reproduce
1. Try to use your sample project and open "Navigation: Transitions"
2. Try to navigate between the screens.

## Expected behavior
The screens should use the provided transitions while navigation, but this doesn't work anymore.

## Environment:
 - Accompanist version: 0.21.3

## Additional context
This is a regression issue due to changes in https://github.com/google/accompanist/commit/cbac154f68a141fe7c44b1e6b0e2940635491c67

**Comment by ianhanniballake** [comment]
This is being tracked already in #882
