### ISSUE TITLE
[Pager] Support offscreenPageLimit

### ISSUE THREAD

**Issue by lsuski** [google/accompanist#899]
**Is your feature request related to a problem? Please describe.**
Currently to achieve with `HorizontalPager` displaying partially next/previous page we have to define `contentPaddings`. However it is not always desirable. With `ViewPager2` we can manipulate page in page transformer (e.g set transalationX) along with `offscreenPageLimit = 1`

**Describe the solution you'd like**
`HorizontalPager` and `VerticalPager` should support `offscreenPageLimit` the same as `ViewPager2` does

**Comment by lsuski** [comment]
Is this closed just because of inactivity?

**Comment by Nek-12** [comment]
On what exact dependency are we waiting for in this issue?

**Comment by andkulikov** [comment]
https://issuetracker.google.com/issues/172029355

**Comment by mtotschnig** [comment]
@andkulikov The linked issue is fixed since October 17. By "new Pager for Compose UI", do you mean a different component than this library's pager? If yes, is there any information on a roadmap for this component? If no, is there any information when Accompanist's pager will take up the new LazyList offscreen capacity?

**Comment by andkulikov** [comment]
@mtotschnig hey, we are currently designing a new Pager component which will live right in compose.foundation and it will be a replacement for Accompanist's Pager. We are planning to provide an experimental version of this component in Compose 1.4. It will have an api for setting offscreenPageLimit

**Comment by dazza5000** [comment]
The referenced implementation is here:

https://github.com/androidx/androidx/blob/androidx-main/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/pager/Pager.kt

**Comment by arnaudlvq** [comment]
@andkulikov in 2024, how can we set offscreenpagelimit ? seems like it has been removed

**Comment by arnaudlvq** [comment]
thank you @andkulikov, you helped me persevere, for those who are lost : 

It has been renamed : **beyondBoundsPageCount**

https://www.composables.com/foundation/horizontalpager
