### ISSUE TITLE
[Pager][Question] Show pager items as deck of cards

### ISSUE THREAD

**Issue by iTruff** [google/accompanist#911]
Hi there, I'm new in Compose and I'm wondering is it possible to show pager items like this:

![2cur](https://user-images.githubusercontent.com/6223322/145012804-35bd711e-44d0-4821-8233-403055a5a317.gif)

If yes, please tell me where to start? Should I use `Modifier.graphicsLayer` to do so, or something else?
Thanks in advance.

**Comment by andkulikov** [comment]
Given that there is no support for offscreenPageLimit in Pager yet I think you will not be able to build it with Pager or LazyColumn. I think you will have to write a completely custom layout which controls its children positions. You will need Modifier.scrollable on it to react on scroll events which you later be using in your layout logic.
I understand that it could be too complex for the beginner in Compose world so you instead just use Views to implement it and add it into Compose view AndroidView composable
