### ISSUE TITLE
[Pager] ContentPadding on a horizontalPager seems to add additional padding

### ISSUE THREAD

**Issue by ColtonIdle** [google/accompanist#913]
**Description**
Even though I'm only setting content padding on `start` it seems to inset some characters. Here is a video of it in action.

https://user-images.githubusercontent.com/31751141/145171400-a4b75666-fc7e-48a0-8904-53cda6333329.mp4

Why does it do this? Is this a bug?
<img width="79" alt="Screen Shot 2021-12-08 at 3 04 03 AM" src="https://user-images.githubusercontent.com/31751141/145171273-6308db33-dd08-4a06-9ea4-2ccf16f093cc.png">

**Steps to reproduce**
```
        Card(modifier = Modifier.fillMaxWidth().align(BottomCenter).padding(16.dp), elevation = 8.dp) {
          Column(Modifier.padding(vertical = 16.dp)) {
            val pagerState = rememberPagerState()

            HorizontalPager(
                count = 3,
                state = pagerState,
                modifier = Modifier.fillMaxWidth(),
                contentPadding = PaddingValues(start = 16.dp),
            ) { page ->
              Column(modifier = Modifier.fillMaxWidth()) {
                val title = arrayOf("One", "Two", "Three")
                val body =
                    arrayOf(
                        "Middle item but it's sorta long and maybe will go onto two lines. We'll have to see.".repeat(1),
                        "Middle item but it's sorta long and maybe will go onto two lines. We'll have to see.".repeat(2),
                        "Middle item but it's sorta long and maybe will go onto two lines. We'll have to see.".repeat(4))
                Text(title[page], fontSize = 14.sp, fontWeight = FontWeight.W600)
                Text(
                    body[page],
                    fontSize = 13.sp,
                    fontWeight = FontWeight.W400)
                VerticalSpacer8()
              }
            }
            HorizontalPagerIndicator(
                pagerState = pagerState,
                modifier = Modifier.align(Alignment.CenterHorizontally),
            )
          }
        }
```

Version: 1.1.0-beta04 of compose and accompanist v0.21.4-beta

Bonus question, I assume theres no "supported" way to get around this resizing issue you can see when switching between 1 and 2?

**Comment by andkulikov** [comment]
It works as expected. ContentPadding makes each item size smaller. You are not only adding the padding for the first item, but also making the maximum item size smaller. It is basically a mechanism to make nearest items to the current one to be partially visible. It is exactly what you see. Probably you just wanted to instead apply padding modifier for the pager content - Column.

For Bonus question I think we were already discussing it with you here https://github.com/google/accompanist/pull/678#issuecomment-919964435

**Comment by ColtonIdle** [comment]
@andkulikov thanks. That solved it! Thanks about the bonus question. I forget that we discussed it already. sorry!
