### ISSUE TITLE
[Placeholder] Coil callbacks are never called when a placeholder modifier is applied to the image

### ISSUE THREAD

**Issue by mfspooner** [google/accompanist#920]
## Describe the bug
When the Accompanist `placeholder` modifier is added to a Coil image, the Coil callbacks ( `onSuccess`, `onError`, `onStart`, `onCancel` ) are never called only on API28. They keep correctly working on the other APIs. We also found out that adding the `clickable` modifier, makes the callbacks work on API28.

## To Reproduce
1. Clone this [repo](https://github.com/mfspooner/placeholderexample)
2. Run the example on an emulator/device based on API28
3. In the first screen of the sample app, you will see an endless placeholder that never disappear. This happens because the Coil callbacks are never called, and the placeholder visibility state never change.
4. In the example there's this piece of code:
```KOTLIN
// Uncomment the following line for making it work
//.clickable(enabled = false) {}
```
Uncomment the `clickable` modifier to make the callbacks work again.

## Expected behavior
The Coil callbacks should be called, and the placeholder should disappear.

## Screenshots?
Video of the issue
https://user-images.githubusercontent.com/83952728/145565033-ecc8813d-30ea-47a9-8a2d-41c32549aade.mov
Video of the expected behaviour
https://user-images.githubusercontent.com/83952728/145565090-5c708ebd-1c3d-4ac7-a320-cfdf01aefa3d.mov

## Environment:
 - It happens on a Pixel 5 emulator with Android 9 ( API 28 )
 - The issue has been reproduced with the following Accompanist versions: `v0.18.0`, `v0.20.2`, `0.21.4-beta`

**Comment by marcouberti** [comment]
I'd keep it open since this is a quite annoying bug.

**Comment by mfspooner** [comment]
I would like to keep it open.
