### ISSUE TITLE
[Navigation] Try avoid hard-coded values on Example

### ISSUE THREAD

**Issue by kareemradwan** [google/accompanist#921]
**Description**
I see you put screen name with hard-coded way. so when some user want change screen name and forget change it on other places app will not work fine or may be crash. 

**Steps to reproduce**
on `AnimatedNavHostSample` you can see hard-coded values

**Expected behavior** 
declare enum or static values for screens name

**Additional context**

**Comment by ianhanniballake** [comment]
This is definitely a good practice, but it makes it harder to understand what types the APIs actually use (an extra level of indirection) and it makes it harder for someone new to the API surface to understand exactly what is going on.

Generally, as per the [Navigation Compose documentation](https://developer.android.com/jetpack/compose/navigation#testing), you should to co-locating **all** references to the routes of a navigation graph in one file (and removing all references to Navigation from other parts of your code), thus making it much harder to miss 'forgetting to change screen names' if you do need do that after the fact.

Of course, you are free to make as many constants as you want in your own code.

**Comment by kareemradwan** [comment]
I make a PR for this point 
you can check it if you have a free time #922
