### ISSUE TITLE
[Pager] Animating to last but one page animates to last page

### ISSUE THREAD

**Issue by WonderCsabo** [google/accompanist#924]
```kotlin
val pages = listOf("0", "1", "2", "3")

val pagerState = rememberPagerState()
val coroutineScope = rememberCoroutineScope()

Column {
    TabRow(
        // Our selected tab is our current page
        selectedTabIndex = pagerState.currentPage,
        // Override the indicator, using the provided pagerTabIndicatorOffset modifier
        indicator = { tabPositions ->
            TabRowDefaults.Indicator(
                Modifier.pagerTabIndicatorOffset(pagerState, tabPositions)
            )
        }
    ) {
        // Add tabs for all of our pages
        pages.forEachIndexed { index, title ->
            Tab(
                text = { Text(title) },
                selected = pagerState.currentPage == index,
                onClick = {
                    coroutineScope.launch {
                        pagerState.animateScrollToPage(index)
                    }
                },
            )
        }
    }

    HorizontalPager(
        count = pages.size,
        state = pagerState,
    ) { page ->
        Text(text = "content: $page")
    }
}
```

When the user clicks the last but one tab, it animates to the last tab instead of animating to the tab before. Not 100% reproducible, you have to restart the app for a couple of times to reproduce this.

`scrollToPage()` does not reproduce the same issue.

Accompanist versions `0.20.2` and `0.21.4-beta`

**Comment by WonderCsabo** [comment]
This is still happening.

**Comment by andkulikov** [comment]
Unfortunately I wasn't able to reproduce it on multiple devices. I will need more information from you. What device you are testing on? Is it a complete reproducible sample?

**Comment by MrMPN** [comment]
I thought I was going crazy until I found this issue, but I think I'm also seeing this. I'll try to make a sample, but as @WonderCsabo said it's not 100% reproducible.

I'm seeing this on a Pixel 6, and `0.20.3` but I haven't tested on anything else.

**Comment by andkulikov** [comment]
Cool, thanks for confirming! I am going to close this issue then
