### ISSUE TITLE
[Pager] HorizontalPager + LazyRow is not consuming nested scroll correctly

### ISSUE THREAD

**Issue by Andreu35** [google/accompanist#935]
Hi guys, I think this was already commented but I would like to know the progress to fix this bug.

**Description**
If we use a LazyRow inside HorizontalPager, when the LazyRow scrolls to the first item and continue scrolling, the previous page of Pager is starting to show, that can be good I think.
But if the scroll change to the other way, the Pager is not going back.
Video attached to see what I am talking about:

https://user-images.githubusercontent.com/21697825/146852186-d7360bfc-b534-456e-bf45-122c15762888.mp4

**Steps to reproduce**
Create a new HorizontalPager and add LazyRow inside any page.
Code example:
```kotlin
@ExperimentalPagerApi
@Composable
private fun HorizontalPagerBugDemo(
    list: List<String>
) {
    HorizontalPager(
        modifier = Modifier.fillMaxSize(),
        count = 2,
        state = rememberPagerState(initialPage = 0),
        verticalAlignment = Alignment.CenterVertically
    ) { pageIndex ->
        when (pageIndex) {
            0, 1 -> LazyRow(
                modifier = Modifier,
                contentPadding = PaddingValues(10.dp),
                verticalAlignment = Alignment.Top,
                horizontalArrangement = Arrangement.spacedBy(20.dp)
            ) {
                itemsIndexed(list) { index, item ->
                    Text(
                        modifier = Modifier
                            .background(color = if (pageIndex == 0) Color.Green else Color.Red),
                        text = "$item\nPage $pageIndex\nIndex $index",
                        style = TextStyle(textAlign = TextAlign.Center)
                    )
                }
            }
        }
    }
}
```

**Expected behavior** 
Pager: Go back if the scroll change and disable scroll if LazyRow is scrolling and not at the first or last item.
LazyRow: Disable scroll if the pager is scrolling

**Additional context**
Android version tested: 9, 10, 11, 12
Compose version: 1.0.5 ... 1.1.0-X
Accompanist version: 0.20.3 ... 0.22.0-rc

**Comment by andkulikov** [comment]
As it is not really a Pager specific issue could you please file this bug as the one for the Compose UI here https://issuetracker.google.com/issues?q=componentid:612128

**Comment by Andreu35** [comment]
Hi @andkulikov , thank you very much for your reply.
This is not a Pager issue? 
Ok, I will open a new issue track.
Thank you very much and happy merry christmas!!

**Comment by andkulikov** [comment]
What I meant is Pager is essentially just LazyRow and it is the issue with nested scrolling which can be reproduced even with just a LazyRow so it is better file a regular Compose bug

**Comment by andkulikov** [comment]
The bug was filed as https://issuetracker.google.com/issues/211793934
