### ISSUE TITLE
[Insets] imePadding() leaves extra space due to BottomNavigation

### ISSUE THREAD

**Issue by FishHawk** [google/accompanist#938]
**Description**

I'm not sure if this is considered a bug. When calling `imePadding()` in a component in `BottomNavigation()`, it leaves extra white space between the component and the keyboard.
Is it possible to have `imePadding()` subtract the bottom padding from the parent component?

**Comment by alexvanyo** [comment]
It sounds like `imePadding()` is working as expected?

One thing that might be helpful for your case is that `imePadding()` is just a shortcut for specific values of the insets.
`navigationBarsWithImePadding()` might also be useful, or you can look at the exact values from `LocalWindowInsets.current.ime` to perform any necessary math for your use case.

**Comment by FishHawk** [comment]
Thank you. I must have missed that function.

**Comment by FishHawk** [comment]
It still doesn't work. The problem is the padding from the parent component, not the systemBar, The simplified code is as follows
``` kotlin
Scaffold(bottomBar = { BottomNavigation() }) { innerPadding ->
    NavHost(modifier = Modifier.padding(innerPadding)) {
        LazyColumn(modifier = Modifier.imePadding())
    }
}
```
A dirty solution:
``` kotlin
    modifier = Modifier.imePadding().padding(
        rememberInsetsPaddingValuesX(
            insets = LocalWindowInsets.current.ime,
            additionalBottom = (-56).dp
        )
    ),
```
This requires overriding the `calculateBottomPadding` method of the `InsetsPaddingValues` class:
``` kotlin
    override fun calculateBottomPadding(): Dp = (additionalBottom + when {
        applyBottom -> with(density) { insets.bottom.toDp() }
        else -> 0.dp
    }).coerceAtLeast(0.dp)
```

**Comment by alexvanyo** [comment]
I'm not sure if there is anything that needs to be changed in the `InsetsPaddingValues`, I think you have all of the information you need.

It sounds like you want the `LazyColumn` to have additional content padding of the difference between the IME insets and the inner padding, if that difference is larger than 0.

Instead of using `imePadding`, you just setup the padding directly:

```kotlin
LazyColumn(
    contentPadding = PaddingValues(
        bottom = with(LocalDensity.current) {
            LocalWindowInsets.current.ime.bottom.toDp() - innerPadding.bottom
        }.coerceAtLeast(0.dp)
    )
) { ... }
```

**Comment by FishHawk** [comment]
I see. I will close this issue later.

**Comment by svenjacobs** [comment]
Please also see my comment [here](https://github.com/google/accompanist/issues/644#issuecomment-1028698371).
