### ISSUE TITLE
[Pager] How can I disable drag to move to the next screens?

### ISSUE THREAD

**Issue by eglogis** [google/accompanist#939]
**Description**
I need to disable drag, because the pages will only change when I click a button. how can I fix this? I see that the dragEnabled parameter has been removed.

**Comment by andkulikov** [comment]
You can find a workaround for it here: https://b.corp.google.com/issues/201150093#comment4
Once we release Compose 1.2-alpha and migrate Accompanist to it I will add this param for the Pager

**Comment by eglogis** [comment]
Great, thank you very much. I can't access the link, can you provide me the solution here?

**Comment by andkulikov** [comment]
Ah, sorry. Copied the internal corporate link. https://issuetracker.google.com/issues/201150093#comment4

**Comment by eglogis** [comment]
Thank you very much!

**Comment by ssSFrankSss** [comment]
Hi, I have the same issue. Well it works but I have a children scrollable item on a view pager which stops scrolling too. The ideal solution would be to disable drag of view pager only and not on his children...

**Comment by andkulikov** [comment]
Note that this fix will only be available in v0.24.x and not backported to older versions as it requires Compose 1.2
