### ISSUE TITLE
[Pager] Update scrollToPage pageOffset range  to -1..1

### ISSUE THREAD

**Issue by PhilipDukhov** [google/accompanist#941]
I'd like to sync two pager scroll positions. When I'm trying the following code:
```
LaunchedEffect(scrollingState.currentPage, scrollingState.currentPageOffset) {
    followingState.scrollToPage(
        scrollingState.currentPage,
        scrollingState.currentPageOffset
    )
}
```
It crashes when scrolling backward, as `currentPageOffset` returns negative value in this case.

I can calculate a positive offset value and pass a prev page, but even in this case I can't sync bouncing, when user tries to scroll backward from the first page, and forward from the last one.

**Comment by andkulikov** [comment]
Yes, we can allow passing negative offsets. But unfortunately it will not help to solve the issue with bouncing effect as it is produced by the separate overscroll logic implemented via the nested scroll mechanism, not via the pager scrolling

**Comment by andkulikov** [comment]
Closing it as there is a simple workaround to pass previous page instead of the current one. And synching bouncing is not possible
