### ISSUE TITLE
[Insets] navigationBarsWithImePadding does not work for API < 30

### ISSUE THREAD

**Issue by nak411** [google/accompanist#942]
**Description**
IME padding behaves differently for different OSs.   

**Steps to reproduce**
The following setup has a simple text field and a button.  When a user clicks on the text field it brings up the keyboard.  On API 30 the button is moved up correctly with the keyboard.  On API 29, the button gets hidden behind the keyboard.

How the screen looks with the keyboard hidden
![default](https://user-images.githubusercontent.com/4589745/147374686-4e3a61c6-5b55-410a-8a5c-64db75a0658c.png)
| API 29  with keyboard up |  api 30 with keyboard up |
| -------------|-----------|
| ![api_29](https://user-images.githubusercontent.com/4589745/147374692-b4356c24-a96e-4841-a6cc-79e5130783da.png) | ![api_30](https://user-images.githubusercontent.com/4589745/147374694-6c7af6f6-2a38-4231-837a-a95b70df292f.png) |

From the images above you can see that on API 29 the keyboard is hiding the button instead of moving it up.  The following code is used for the setup:

```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        WindowCompat.setDecorFitsSystemWindows(window, false)
        setContent {
            InsetTestTheme {
                ProvideWindowInsets {
                    Scaffold(
                        topBar = {
                            TopAppBar(
                                title = { Text(text = "Inset Test") },
                                contentPadding = rememberInsetsPaddingValues(
                                    insets = LocalWindowInsets.current.statusBars,
                                    applyBottom = false
                                )
                            )
                        },
                        content = { Greeting() }
                    )
                }
            }
        }
    }
}

@Composable
fun Greeting() {
    Column(Modifier
        .fillMaxSize()
        .navigationBarsWithImePadding()) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .weight(1f)
        ) {
            val state = remember { mutableStateOf("") }
            TextField(
                value = state.value,
                onValueChange = { state.value = it },
                modifier = Modifier.align(Alignment.Center)
            )
        }
        Button(
            onClick = { },
            modifier = Modifier
                .padding(16.dp)

        ) {
            Text(text = "Button 1")
        }
    }
}
```

**Expected behavior** 
The button should be moved  above  the keyboard  on all supported APIs

**Comment by alexvanyo** [comment]
Hi, for your sample, are you using `adjustResize` for your Activity's `windowSoftInputMode` as suggested [here](https://google.github.io/accompanist/insets/#something-not-working)?

If you're using `adjustPan` or leave it as the default, it's known that you might get different behavior on different API versions (https://issuetracker.google.com/issues/176400965 seems related).

**Comment by nak411** [comment]
Thank you for your response.  The sample above is a simplified version of the issue.  I am using a single activity architecture and in my actual app there are many screens.  `adjustResize` is applied to the activity and it causes unwanted behavior in some of the other screens.  
I will keep an eye out on the issue that you linked since that seems to root of the problem.

In the meantime, I can close this issue.
