### ISSUE TITLE
[Navigation] Bottom sheet scrim still visible after using navigateUp from BottomSheet destination

### ISSUE THREAD

**Issue by FunkyMuse** [google/accompanist#946]
**Description**
Bottom sheet scrim still visible after using `navigateUp` from BottomSheet destination

**Steps to reproduce**
```kotlin
val bottomSheetNavigator = rememberBottomSheetNavigator()
val navController = rememberAnimatedNavController()
navController.navigatorProvider += bottomSheetNavigator
```
also using
```kotlin
 ModalBottomSheetLayout(
            bottomSheetNavigator
        ) {
            AnimatedNavHost(
                navController = navController,
                startDestination = "home"
            ) {
                //added the bottomSheet and composable destinations here
            }
        }
```

https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/navigation/material/BottomSheetNavSample.kt

inside `BottomSheet` function call `navController.navigateUp`

**Expected behavior**
The scrim should not be visible once you navigate up 

**Additional context**
compose_version = '1.1.0-rc01'
accompanist_version = '0.22.0-rc'

**Comment by FunkyMuse** [comment]
Temporary fix:
```kotlin
 val sheetState = rememberModalBottomSheetState(ModalBottomSheetValue.Hidden, SwipeableDefaults.AnimationSpec)
 val bottomSheetNavigator = rememberBottomSheetNavigatorFix(sheetState)

@Composable
fun rememberBottomSheetNavigatorFix(
    sheetState: ModalBottomSheetState
): BottomSheetNavigator {
    return remember(sheetState) {
        BottomSheetNavigator(sheetState = sheetState)
    }
}
```

Whenever you call navigateUp just call `sheetState.hide()` too
```kotlin
LaunchedEffect(navController) {
        navigator.destinations.collect { navigatorEvent ->
            when (navigatorEvent) {
                is NavigatorEvent.NavigateUp -> {
                    bottomSheetNavigator.hide()
                    navController.navigateUp()
                }
            }
        }
    }
```

**Comment by FunkyMuse** [comment]
Huh, seems to be fixed with `v0.24.1-alpha`

**Comment by jossiwolf** [comment]
That would be very surprising but awesome😄 Let us know!

**Comment by FunkyMuse** [comment]
> That would be very surprising but awesome😄 Let us know!

This is now a workaround for #978

**Comment by jscti** [comment]
@jossiwolf Could this be reopened although the workaround works ?

Bug still ocurring on 0.26.5-rc.

`naVController.navigateUp` doesn't do anything. Nothing in logcat either.

Thanks

**Comment by robbysmeticapps** [comment]
I have the same issue, is there any progress on this issue or should we still use the temporary fix?

**Comment by mattiaferigutti** [comment]
I'm still experiencing this issue today, even with the stable version of Compose. It's frustrating that it hasn't been addressed yet. However, I’ve found a workaround in the meantime. I added a `resetState()` function to my `ViewModel`, which, as the name suggests, resets all the state within the `ViewModel`. I then call this function inside the composable using `DisposableEffect`, like this:

```kotlin
DisposableEffect(Unit) {
  onDispose { viewModel.resetState() }
}
```
