### ISSUE TITLE
[System UI Controller] statusbar color changing but not darkIcons

### ISSUE THREAD

**Issue by jayesh83** [google/accompanist#949]
I've Xiaomi POCO X2 android 11, I'm facing issue in status bar icon color. I've applied transparent and set darkIcons=true but icons remain white which lead to complete white status status bar.

**Additional context**
The same method worked in Pixel device android 10

**Comment by alexvanyo** [comment]
Hi, thanks for the report! Which version of Compose are you using and seeing this issue?

**Comment by jayesh83** [comment]
> Hi, thanks for the report! Which version of ~Compose~ Accompanist are you using and seeing this issue?
> 
> Edit: Whoops, wrong library name 😄
I'm using 
implementation "com.google.accompanist:accompanist-systemuicontroller:0.22.0-rc"
implementation 'com.google.accompanist:accompanist-insets:0.22.0-rc'

**Comment by costular** [comment]
> > Hi, thanks for the report! Which version of ~Compose~ Accompanist are you using and seeing this issue?
> > Edit: Whoops, wrong library name 😄
> 
> I'm using the latest implementation "com.google.accompanist:accompanist-systemuicontroller:0.22.0-rc" implementation 'com.google.accompanist:accompanist-insets:0.22.0-rc'

I'm experiencing a similar issue using same version `0.22.0-rc`

```kotlin
val systemUiController = rememberSystemUiController()
            val useDarkIcons = MaterialTheme.colors.isLight

            SideEffect {
                systemUiController.setSystemBarsColor(
                    Color.Transparent,
                    darkIcons = useDarkIcons
                )
            }
```

✅  Shows like this on light theme:
![Light theme](https://i.imgur.com/AeYt3bD.png)

🚫  and like this on dark theme:
![Dark theme](https://i.imgur.com/PdOZ10S.png)

**Comment by jayesh83** [comment]
> > > Hi, thanks for the report! Which version of ~Compose~ Accompanist are you using and seeing this issue?
> > > Edit: Whoops, wrong library name 😄
> > 
> > 
> > I'm using the latest implementation "com.google.accompanist:accompanist-systemuicontroller:0.22.0-rc" implementation 'com.google.accompanist:accompanist-insets:0.22.0-rc'
> 
> I'm experiencing a similar issue using same version `0.22.0-rc`
> 
> ```kotlin
> val systemUiController = rememberSystemUiController()
>             val useDarkIcons = MaterialTheme.colors.isLight
> 
>             SideEffect {
>                 systemUiController.setSystemBarsColor(
>                     Color.Transparent,
>                     darkIcons = useDarkIcons
>                 )
>             }
> ```
> 
> ✅ Shows like this on light theme: ![Light theme](https://camo.githubusercontent.com/d5b32d4979c4618d9a69f72e4d2d13c3ecb83847d1b76b8fe0de8290e2c79026/68747470733a2f2f692e696d6775722e636f6d2f416559743362442e706e67)
> 
> 🚫 and like this on dark theme: ![Dark theme](https://camo.githubusercontent.com/e2034e988298bb1b83ccbf882b28e546ff4f4aeff34f08e4e5f97f0afc31a741/68747470733a2f2f692e696d6775722e636f6d2f50644f5a3130532e706e67)


Till then I'm using window insets directly provided by android

`private fun changeStatusBarIconsColor(window: Window, darkIcons: Boolean) {
        val statusBar = WindowCompat.getInsetsController(window, window.decorView)
        statusBar?.isAppearanceLightStatusBars = darkIcons
    }

    private fun changeSystemBarsIconsColor(window: Window, darkIcons: Boolean) {
        val windowController = WindowCompat.getInsetsController(window, window.decorView)
        windowController?.isAppearanceLightStatusBars = darkIcons
        windowController?.isAppearanceLightNavigationBars = darkIcons
    }`

**Comment by alexvanyo** [comment]
Thank you for the reports, I was able to reproduce and I believe I have a fix as well.

**Comment by jayesh83** [comment]
> Thank you for the reports, I was able to reproduce and I believe I have a fix as well.

Excellent, thanks

**Comment by alexvanyo** [comment]
@jayesh83 does the video I posted in #977 look like it's your issue?

**Comment by jayesh83** [comment]
> @jayesh83 does the video I posted in #977 look like it's your issue?

Yes I guess this solves the issue.

**Comment by alexvanyo** [comment]
The underlying issue here was a problem with `androidx.core`, so the fix has been upstreamed there.

It is immediately available with `androidx.core` at snapshot 8139767
Once a new alpha is released with the changes, we will update the version that accompanist uses to ensure that consumers also get the fix.

**Comment by costular** [comment]
Thanks for the info @alexvanyo ❤️

**Comment by alexvanyo** [comment]
No problem! And if you have chance to verify that 8139767 will fix your issue, or if you're still running into it, that'd be great!

**Comment by costular** [comment]
Sure! I'll check it out later and will let you know 👍🏼

**Comment by 52541** [comment]
gmail/git hub

**Comment by alexvanyo** [comment]
`androidx.core` `1.8.0-alpha04` contains the upstream fix, so updating to that (independently of accompanist) will fix this issue.

I just bumped accompanist to depends on `1.8.0-alpha04`, so the next version of accompanist will also ensure that this issue isn't encountered.

**Comment by costular** [comment]
You're right @harry248. I've tested it and it's still happening

**Comment by harry248** [comment]
@costular I've changed the code from the example to `val useDarkIcons = !isSystemInDarkTheme()` and now it works. `MaterialTheme.colors.isLight` always returned `true`.

**Comment by costular** [comment]
Nice @harry248! It worked 🎉  thanks!
`MaterialTheme.colors.isLight` is not working properly. Should we change the documentation @alexvanyo?

**Comment by alexvanyo** [comment]
If `MaterialTheme.colors.isLight` isn't working properly, that'd be a bug to raise on https://issuetracker.google.com.

Are you using `isSystemInDarkTheme()` to set your `MaterialTheme`, similar to what's specified here?
https://developer.android.com/jetpack/compose/themes/material#dark-theme

```kotlin
@Composable
fun MyTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit
) {
    MaterialTheme(
        colors = if (darkTheme) DarkColors else LightColors,
        /*...*/
        content = content
    )
}
```

**Comment by costular** [comment]
> If `MaterialTheme.colors.isLight` isn't working properly, that'd be a bug to raise on [issuetracker.google.com](https://issuetracker.google.com).
> 
> Are you using `isSystemInDarkTheme()` to set your `MaterialTheme`, similar to what's specified here? [developer.android.com/jetpack/compose/themes/material#dark-theme](https://developer.android.com/jetpack/compose/themes/material#dark-theme)
> 
> ```kotlin
> @Composable
> fun MyTheme(
>     darkTheme: Boolean = isSystemInDarkTheme(),
>     content: @Composable () -> Unit
> ) {
>     MaterialTheme(
>         colors = if (darkTheme) DarkColors else LightColors,
>         /*...*/
>         content = content
>     )
> }
> ```

Exactly! I'm doing it like that. I'll raise a bug on [issuetracker](https://issuetracker.google.com/)

**Comment by alexvanyo** [comment]
Sounds good!

Only other thing I can think of to check is that the `MaterialTheme.colors.isLight` call is happening somewhere within the content block passed to `MyTheme`.

**Comment by costular** [comment]
That's my bad 🤦🏼  you were right @alexvanyo , actually I was calling `MaterialTheme.colors.isLight` outside of th econtent block passed to `MyTheme` in the `Activity`'s `setContent()` so this is working as expected now.

Just FYI @harry248
