### ISSUE TITLE
[Pager] HorizonalPager elevation disappear during overscroll

### ISSUE THREAD

**Issue by michalkierasinski** [google/accompanist#955]
**Description**
I used Card as a Page body for HorizontalPager. During over scrolling the elevation on the bottom and top disappear.
version: 0.22.0-rc

**Steps to reproduce**
Add 3 pages to Pager and try to overscroll on the first or last page.

**Expected behavior** 
Elevation should be visible always

**Additional context**
The elevation is changing during scrollin

https://user-images.githubusercontent.com/25001811/149517228-67b0691b-1001-4652-91be-24f609e289fe.mp4

**Comment by andkulikov** [comment]
Seems like this issue is not Pager specific and could be reproduced with just LazyRow. Don't you mind filing a bug for it here https://issuetracker.google.com/issues?q=componentid:612128?

**Comment by michalkierasinski** [comment]
You are right, link to created issue -> https://issuetracker.google.com/issues/214957971.

That issue can be closed.
