### ISSUE TITLE
[System UI Controller] Provide way to set layoutInDisplayCutoutMode

### ISSUE THREAD

**Issue by giaesp** [google/accompanist#964]
Actually calling

```
val systemUiController = rememberSystemUiController()
SideEffect {
     systemUiController.isStatusBarVisible = false
}
```

hides correctly the status bar, but content doesn't fit the status bar empty space.
I have this weird behavior with all version 0.20.0+ (including alphas and RCs)

Compose version is 1.1.0-rc01
Tested on Samsung SM G780G

**Comment by alexvanyo** [comment]
Hi, could you share a bit more info? Are you using `WindowCompat.setDecorFitsSystemWindows(window, false)`?

**Comment by DalilaSilva** [comment]
Same issue here. 
I use `WindowCompat.setDecorFitsSystemWindows(window, false)`

**Comment by alexvanyo** [comment]
Hi, querying for a bit more info here.

Are you using `SystemUiController` in combination with insets (either the deprecated accompanist/insets, or the new version built into `androidx.foundation`)?

**Comment by Tolriq** [comment]
Facing the same issue. 

```
                val systemUiController = rememberSystemUiController()
                SideEffect {
                    systemUiController.setSystemBarsColor(color = Color.Transparent, darkIcons = false)
                }
```

Works and have the content draw under the status bar.

```
                val systemUiController = rememberSystemUiController()
                SideEffect {
                    systemUiController.isSystemBarsVisible = false
                    systemUiController.setSystemBarsColor(color = Color.Transparent, darkIcons = false)
                }
```
or
```
                val systemUiController = rememberSystemUiController()
                SideEffect {
                    systemUiController.isSystemBarsVisible = false
                }
```

Does not work the status bar content is hidden but the insets for the status bar are now at 0 and nothing is drawn under the status bar.

**Comment by alexvanyo** [comment]
I think I might have a lead. It looks like OP's device has a pinhole cutout, is that true for others in this thread as well?

**Comment by alexvanyo** [comment]
The thread I'm pulling at is [`layoutInDisplayCutoutMode`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#layoutInDisplayCutoutMode)

If you change that via `window.attributes.layoutInDisplayCutoutMode`, does that change the behavior you're seeing?

**Comment by Tolriq** [comment]
Yes P6 Pro and all my emulator images have it too.

**Comment by Tolriq** [comment]
So after quite a few tests, for whatever reason layoutInDisplayCutoutMode only works when set via the theme.xml not by code. (Android 12 P6 pro)

When setting `layoutInDisplayCutoutMode` to always in theme and `systemUiController.isStatusBarVisible = false` it will recompose 3 to 4 times the screen by moving up and down the content below / under / below / under / below / under the status bar.
Please note that I have migrated to Compose 1.2 alpha 7 insets handling.

**Comment by alexvanyo** [comment]
Could you attach a video of that and provide a sample? In my testing I wasn't seeing the jumping behavior.

This could be something worth adding to accompanist, or at the least exposing the correct `Window` to change.

**Comment by Tolriq** [comment]
Here's the video. 

Theme
```
<resources>
    <!-- Base application theme. -->
    <style name="Theme.Symfonium" parent="android:Theme.Material">
        <item name="android:windowActionBar">false</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">always</item>
    </style>

</resources>
```

Code is relatively simple
```
setContent {
CustomTheme { 
                SideEffect {
                    systemUiController.isStatusBarVisible = false
                    systemUiController.setSystemBarsColor(color = Color.Transparent, darkIcons = useDarkIcons)
                }

```

The theme is an M3 theme that wrap an M2 theme

https://user-images.githubusercontent.com/932609/163030594-7a07de02-3727-4504-b8d6-a93407adbac7.mp4

The app is huge and private, and currently fighting with Android Auto validation team that refuse the app because it does not work when they don't purchase a paid app .... So tons of loose energy and time preventing me to try to build a full small repro.

**Comment by Tolriq** [comment]
Unstale, still need a way to hide status bar properly as request by my users :(

**Comment by Tolriq** [comment]
Another one :) Is there a workaround / ugly way to get the proper window for layoutInDisplayCutoutMode? 

For my use case asked by users the need to hide the the status bar fully is only for one screen.

**Comment by Tolriq** [comment]
Unstale we still need a way to do layoutInDisplayCutoutMode from code.

**Comment by Tolriq** [comment]
Another one :)
The need for me at least, is that the user can enable a setting to have a part of the app full screen.

**Comment by Tolriq** [comment]
Is there anyway to add some kind of label to this issue to avoid the stale ?

**Comment by Tolriq** [comment]
Unstale :)

**Comment by Tolriq** [comment]
Unstale :)

**Comment by moretanjames** [comment]
I am facing the same issue. As described above, I am setting 
`WindowCompat.setDecorFitsSystemWindows(window, false)` in My Activity. Setting the status bar color to Transparent allows content to be visible through the status bar, but `systemUiController.isStatusBarVisible = false` leaves a black bar at the top of my screen through which content cannot be viewed. I am using a Galaxy Z Fold 4. The issue occurs on my outer screen which has the so-called "Pinhole" cutout (though I had always heard "hole-punch" to refer to that style of camera cutout) but not on my inner screen which has an under-display camera and therefore no cutout.

**Comment by Tolriq** [comment]
Unstale :)

**Comment by moretanjames** [comment]
Seriously though, unless this part of accompanist is going to be deprecated and replaced by something in one of the standard compose libraries soon, I think this issue deserves some love.

**Comment by alexvanyo** [comment]
As a direct solution, you can manually set `layoutInDisplayCutoutMode` via setting the window attributes, either from an `Activity` where you have the `Window` already, or using the same method to find the window that `systemuicontroller`.

**Comment by Tolriq** [comment]
@alexvanyo 
```window?.attributes?.layoutInDisplayCutoutMode = LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS``` from the activity works.

But copy pasting the findWindow() and calling from compose does not, reasons of all the bumps since I can't find the reason and a workaround.

**Comment by Tolriq** [comment]
Actually in main activity : 

1) Works
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    window?.attributes?.layoutInDisplayCutoutMode = LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS
    setContent {
    }
}
```

2) Does not works
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContent {
        window?.attributes?.layoutInDisplayCutoutMode = LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS
    }
}
```

3) Does not works
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    val theWindow = window
    setContent {
        theWindow ?.attributes?.layoutInDisplayCutoutMode = LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS
    }
}
```

Even stranger part, is that if I log the mode in the second/third case it's properly updated and return the new value, there's no null window.
My guess would be that Compose add some kind of wrapper and does not pass the changes?

**Comment by Tolriq** [comment]
And to return on the blinking:

```
setContent {
            val statusBarPadding = WindowInsets.statusBars.asPaddingValues()
            logError("AAA") { "Pad: ${statusBarPadding.calculateTopPadding()}" }
}
```
Logs:
```
10:01:36.052 AAA                        E  StartActivity$onCreate$1.invoke@345: Pad: 0.0.dp
10:01:36.941 AAA                        E  StartActivity$onCreate$1.invoke@345: Pad: 24.0.dp
10:01:37.126 AAA                        E  StartActivity$onCreate$1.invoke@345: Pad: 24.0.dp
```

But
```
setContent {
            val systemUiController = rememberSystemUiController()
            systemUiController.isStatusBarVisible = false
            val statusBarPadding = WindowInsets.statusBars.asPaddingValues()
            logError("AAA") { "Pad: ${statusBarPadding.calculateTopPadding()}" }
}
```
Logs:

```
10:01:52.350 AAA             E  StartActivity$onCreate$1.invoke@345: Pad: 0.0.dp
10:01:53.186 AAA             E  StartActivity$onCreate$1.invoke@345: Pad: 0.0.dp
10:01:53.455 AAA             E  StartActivity$onCreate$1.invoke@345: Pad: 0.0.dp
10:01:53.577 AAA             E  StartActivity$onCreate$1.invoke@345: Pad: 24.0.dp
10:01:55.083 AAA             E  StartActivity$onCreate$1.invoke@345: Pad: 0.0.dp
```

So as you can see at some point the statusbar top padding value is back and stays for 1,5 seconds (The duration of the animation to actually hide the status bar)

**Comment by alexvanyo** [comment]
Interesting, it's possible that timing is important here. The code within `setContent` runs at composition time, which is run at a later point in time then when calling it directly in `onCreate`. It's possible the API doesn't support being modified later than that? That would also complicate being able to add an API like this in accompanist.

For the status bar values, can you report an upstream issue in androidx since the inset APIs have been upstreamed? Thank you!

**Comment by Tolriq** [comment]
@alexvanyo For the status bar, I fear that since the API to toggle it is here, they ask me to toggle via theme and it will work.
Anyway created https://issuetracker.google.com/issues/267194796 maybe you can help triage it.


For the displaycutout this is something specific to Compose I never needed to change that in my other app to go edge to edge and draw under the cutout.

But yes adding a launch and delay does not work, so Compose definitively read that value and configure itself based on that, then do not update on value change, maybe a side effect of how ```systemUiController.isStatusBarVisible = false``` is implemented?

Is `SystemUiController` planned to be upstream anytime soon?

I think both are more or less tied.

**Comment by Tolriq** [comment]
Unstaleeeeeeeeeee :)

No answer on the Compose tracker either :(

**Comment by Tolriq** [comment]
And unstale :) 

Can you please at least see for someone to jump in https://issuetracker.google.com/issues/267194796 ? If the insets do not jumps like that then I can try workaround this by always applying the cutout and playing with insets.

**Comment by Tolriq** [comment]
@alexvanyo Seems it's not automatic can you reopen?

**Comment by Tolriq** [comment]
If you don't want this as a setting configure all in the themes.xml.
Else no workaround for this and for the status bar hiding leading to broken insets.

**Comment by Tolriq** [comment]
Unstale :)

**Comment by bentrengrove** [comment]
Unfortunately Accompanist SystemUIController has been deprecated and won't be supported going forwards. I am closing this issue. For more information please see our [update blog](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)

**Comment by Tolriq** [comment]
@bentrengrove 

And how do we get Compose team to actually look into the remaining bugs ?
Like https://issuetracker.google.com/issues/267194796 ? Or the many settings that can't be changed at runtime ?

Compose currently does not properly support changing edge to edge during runtime making the user experience awful for any app that needs to provide this as an option.
