### ISSUE TITLE
[Insets] Insets don't apply immediately 

### ISSUE THREAD

**Issue by Abdulrahman-N** [google/accompanist#966]
**Description**
The status bar padding insets don't apply immediately which results in unpleasant visual artifact

**Steps to reproduce**
I'm using a compose View inside a fragment. 
`  override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ) = ComposeView(requireContext()).apply {
        setContent {
            AppTheme {
                ProvideWindowInsets {
                    Screen()
                }
            }
        }
    }
}`

The insets are then consumed inside the screen  composable
`
@Composable
fun Screen() {
    Column(
        Modifier
            .statusBarsPadding()
            .fillMaxSize()
    ) {
        Text(modifier = Modifier.fillMaxWidth().background(Color.Red).padding(vertical = 48.dp), text = "")
    }
}`
 
**Expected behavior** 
The insets should be applied fast enough that no artifacts are seen

**Additional context**

[Video for context](https://youtu.be/vLQTmu78g3A)
You can see the red background takes time until it's padding are applied

Version: 0.24.0-alpha

**Comment by Abdulrahman-N** [comment]
Seems to be related to this issue 
https://github.com/google/accompanist/issues/155

Which provides a hack that is not optimal. 

Any updated on an official solution?

**Comment by chrisbanes** [comment]
There is no 'solution', that's just how insets work.
