### ISSUE TITLE
[Navigation] Type mismatch with composable animation parameters

### ISSUE THREAD

**Issue by MaxMichel2** [google/accompanist#967]
**Description**
Adding the accompanist-navigation-animation:0.24.0-alpha dependency and importing the following:

```
import com.google.accompanist.navigation.animation.AnimatedNavHost
import com.google.accompanist.navigation.animation.composable
```

works fine but once I follow the guide and add a transition such as: 

```
enterTransition = { initial, _ ->
    when (initial.destination.route) {
        "Red" ->
            slideInHorizontally(initialOffsetX = { 1000 }, animationSpec = tween(700))
        else -> null
    }
},
```

Gives a `Type mismatch` error:

```
Type mismatch.
Required:
(AnimatedContentScope<NavBackStackEntry>.() → EnterTransition?)?
Found:
AnimatedContentScope<NavBackStackEntry>.(Any?, Any?) → EnterTransition?
```

**Steps to reproduce**

Create an AnimatedNavHost and copy the example in the accompanist guide with the accompanist-navigation-animation version 0.24.0-alpha.

**Expected behavior** 

The addition of the animations should work as described in the documentation.

**Additional context**

**Comment by ianhanniballake** [comment]
It looks like [the sample](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/navigation/animation/AnimatedNavHostSample.kt) was updated in #829, when the API was changed to using the `AnimatedContentScope` receiver scope, but the guide wasn't updated in that same CL.

The correct syntax, as seen in the sample, is:

```
enterTransition = {
    when (initialState.destination.route) {
        "Red" ->
            slideInHorizontally(initialOffsetX = { 1000 }, animationSpec = tween(700))
        else -> null
    }
},
```

**Comment by jbw0033** [comment]
Which guide are you using? The docs attached to accompanist (https://google.github.io/accompanist/navigation-animation/) are correct and were updated in https://github.com/google/accompanist/commit/760050ebdaf67649d002496c5b1a0f27c4bd784c
