### ISSUE TITLE
[Idea] Add visible modifier

### ISSUE THREAD

**Issue by fornewid** [google/accompanist#968]
> If you are officially denying a feature request, I would like to apologize first. 😅 

### Is your feature request related to a problem? Please describe.

There has been a request for a long time on how to implement invisible in Compose.
https://issuetracker.google.com/issues/158837937

If this issue doesn't appear to be going on and is unlikely to be officially added to Compose,
then Accompanist appears to be a good place to provide a feature.
I'd like to get your opinion on whether it's okay to add this feature.

### Describe the solution you'd like

I would like to add the code below as a new module.

```kt
fun Modifier.visible(visible: Boolean): Modifier {
    return if (visible) {
        this
    } else {
        this.then(InvisibleModifier)
    }
}

fun Modifier.invisible(invisible: Boolean): Modifier {
    return if (invisible) {
        this.then(InvisibleModifier)
    } else {
        this
    }
}

private object InvisibleModifier : LayoutModifier, DrawModifier {

    override fun MeasureScope.measure(
        measurable: Measurable,
        constraints: Constraints
    ): MeasureResult {
        val placeable: Placeable = measurable.measure(constraints)
        return layout(placeable.width, placeable.height) {
            placeable.placeRelative(0, 0)
        }
    }

    override fun ContentDrawScope.draw() {
        // only measures but not draws content.
    }
}
```

### Describe alternatives you've considered

There seems to be a way to add `Visibility` composable,
`Modifier` extension function seems to be a simpler way.

**Comment by alexvanyo** [comment]
One of the biggest issues here is the interaction between a general invisible modifier and intractability and semantics for accessibility.

I believe that the `invisible` modifier as proposed would still result in the content being interactable and available to accessibility.

**Comment by fornewid** [comment]
Thanks for your comment on accessibility.
That's the part I overlooked. :bow:

But when I think about it simply...
it seems possible to clear semantics information using `clearAndSetSemantics()` in invisible state only. 👀 

```kt
fun Modifier.visible(visible: Boolean): Modifier {
    return if (visible) {
        this
    } else {
        then(InvisibleModifier).clearAndSetSemantics {}
    }
}
```

Is there something I'm missing out on?
Or are there any other issues besides this?
