### ISSUE TITLE
[Pager]: Expose lazyListState to share state between LazyColumn LazyRow and Pager 

### ISSUE THREAD

**Issue by rustamsmax** [google/accompanist#979]
I've used Pager for portrait mode and LazyColumn for landscape mode
When I change device orientation the state must be restored thus the state must be shared between them

**Comment by rustamsmax** [comment]
We can add LazyListState as a PagerState constructor parameter

**Comment by andkulikov** [comment]
Hey. I don't think it is possible, sorry. The fact that Pager is implemented as LazyRow internally is purely an implementation detail, we will not be exposing it.
However maybe you just want to use LazyRow directly with applying the snapping fling behaviour from the Snapper library, exactly how the pager is doing that. Most of the extra code added into Pager is the one responsible of converting LazyListState into PagerState. And if you want to work with LazyListState directly you don't need it

**Comment by rustamsmax** [comment]
Ok. Can you suggest a workaround to share restorable data between different types of state?

**Comment by andkulikov** [comment]
Maybe something like this

val currentPage = rememberSaveable { mutableStateOf(0) }
if (needList) {
    val listState = rememberSaveable(saver = LazyListState.Saver) {
        LazyListState(currentPage.value)
    }
    LaunchedEffect(listState) {
        snapshotFlow { listState.firstVisibleItemIndex }
            .collect {
                currentPage.value = it
            }
    }

} else {
    val pagerState = rememberSaveable(saver = PagerState.Saver) {
        PagerState(currentPage.value)
    }
    LaunchedEffect(pagerState) {
        snapshotFlow { pagerState.currentPage }
            .collect {
                currentPage.value = it
            }
    }
}

Note that I am not using rememberLazyListState() directly as I don't want to use currentPage.value inside the composable function as otherwise it would be recomposed on every page change
