### ISSUE TITLE
[Pager] List of HorizontalPager inside a LazyColumn are not rendered correctly 

### ISSUE THREAD

**Issue by GaryLaurenceau** [google/accompanist#984]
**Description**
I want to display a list of list represented with `LazyColumn` and `HorizontalPager`.
When I scroll up and down, wrong items are displayed, because HorizontalPager is not recompose according to the current collection.

**Steps to reproduce**

```
val collections = listOf(
    listOf("A: 1", "A: 2", "A: 3", "A: 4", "A: 5"),
    listOf("B: 1", "B: 2", "B: 3", "B: 4"),
    listOf("C: 1", "C: 2", "C: 3"),
    listOf("D: 1", "D: 2", "D: 3", "D: 4", "D: 5"),
    listOf("E: 1", "E: 2"),
    listOf("F: 1", "F: 2", "F: 3", "F: 4", "F: 5", "F: 6"),
    listOf("G: 1", "G: 2"),
    listOf("H: 1", "H: 2")
)
LazyColumn() {
    items(collections) { collection ->
        val pagerState: PagerState = rememberPagerState()
        HorizontalPager(
            count = collection.count(),
            state = pagerState,
        ) { page ->
            val item = collection[page]
            Text(
                modifier = Modifier.fillMaxWidth().height(250.dp),
                text = item,
                textAlign = TextAlign.Center
            )
        }
    }
}
```

This will render something like:

```
A:1
B:1
C:1
D:1
E:1
A:1
A:1
B:1
```
**Expected result**
```
A:1
B:1
C:1
D:1
E:1
F:1
G:1
H:1
```

**Additional context**

I found a workaround to this problem by adding a key function to `HorizontalPager`

```key = { collection.hashCode() + it.hashCode() }```

**Comment by andkulikov** [comment]
What version of accompanist do you use?

**Comment by GaryLaurenceau** [comment]
Compose version 1.2.0-alpha02 and accompanist version 0.24.1-alpha

**Comment by andkulikov** [comment]
Thanks for reporting it! It is not directly related to Pager and is reproducible with just LazyRow so I filed a Compose bug - https://issuetracker.google.com/issues/217365788.
There is temporary workaround you can use - wrap your HorizontalPager into
```
key(rememberSaveable { Random.nextInt() }) {
   ...
}
```

**Comment by GaryLaurenceau** [comment]
Ok, it works. Thanks
