### ISSUE TITLE
[SwipeRefresh] Add possibility to display progress.

### ISSUE THREAD

**Issue by tteichma** [google/accompanist#989]
Compose's `CircularProgressIndicator` provides the possibility to pass a parameter `progress` (Float between 0.0 and 1.0) that is used to display how much of a task is already done.

I would like to have this possibility in `SwipeRefresh` as well. For my use case it would be most beneficial if progress was a `Float?` where `null` would be the current behavior.

I had a look quick at the source code and to me it seems that I would need to copy/paste large blocks of library code with small modifications to get that behavior (at least `SwipeRefreshIndicator` for customizing the indicator, `SwipeRefreshState` to pass the progress and `SwipeRefresh`, because it depends on `SwipeRefreshState`). 

Is it likely that such a feature would be added in the near future? If not: Is my estimation of which parts of the library code I would need to duplicate correct or is there an easier and cleaner way?

**Comment by sitatec** [comment]
Hi @tteichma, the `SwipeRefresh` API provides the flexibility to achieve that through a custom indicator without duplicating code or adding a new feature :
```kotlin
SwipeRefresh(
    state = rememberSwipeRefreshState(isRefreshing = refreshing),
    indicator = { state, trigger ->
        // YOUR CUSTOM INDICATOR HERE
       // You can create a wrapper of `CircularProgressIndicator` if you want.
    },
) {
       //...
}
```

You can refer to this [sample](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshCustomIndicatorSample.kt) for custom indicator implementation.

**Comment by tteichma** [comment]
Hi @sitatec,

I saw this sample and was aware that custom indicators are possible. I did not think it was helpful for my use case, because it did not occur to me that I could pass the progress using closures instead of including it in a modified `SwipeRefreshState` class.

That said, I am not really interested in implementing my own wrapper for `CircularProgressIndicator`, because the default one (`SwipeRefreshIndicator`) does exactly what I want -- except for actually indicating progress after the refresh has been started. Knowing that I can use closures, I will only have to duplicate and modify `SwipeRefreshIndicator.kt` which seems okay to me.

I expected this implementation of `SwipeRefresh` to be able to display progress by default, because I knew `CircularProgressInidcator` can handle it. After more reading of the docs I noticed, that `SwipeRefreshLayout` does not seem to be able to do it either.

Feel free to close this issue if you see no need for any change.

**Comment by sitatec** [comment]
@Zhuinden I don't call that copy-past, if you look at the [sample](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshCustomIndicatorSample.kt), it's fully customized without copy-past. The API gives the user the possibility to use his own `indicator`, it up to him to copy-past or use a custom one.

In the case of the `contentColor`, I suppose that you would like to have something like this:
```kotlin
SwipeRefresh(
    state = rememberSwipeRefreshState(isRefreshing = refreshing),
    indicatorContentColor = Color.Green,
) {
       //...
}
```
The fact is, if we do something like that, the API of `SwipeRefresh` will depend on the API of `SwipeRefreshIndicator`:
Let say in the future we remove `contentColor` or change its type to hexadecimal number, or we make it nullable, that will affect both APIs. It's better to keep them independent.

**Comment by sitatec** [comment]
After I reviewed the code, I realized that we can add an optional `progress` parameter to `SwipeRefreshState` (but not to `SwipeRefresh`) without making one API depend on another or introducing breaking changes.
I have made a PR, if it gets merged you will be able to show the progress like below in the next release:
``` kotlin
    var refreshing by remember {
        mutableStateOf(false)
    }
    var progress: Float? by remember {
        mutableStateOf(null)
    }
    val swipeRefreshState = rememberSwipeRefreshState(isRefreshing = refreshing, progress = progress)

    SwipeRefresh(
        state = swipeRefreshState,
        onRefresh = {
            refreshing = true
            progress = 0.3F // Update in your ViewModel (or similar) depending on the load progress.
        },
    ) {
        LazyColumn {
            items(30) { index ->
                // TODO: list items
            }
        }
    }
```
@tteichma you can keep track of the PR to stay up to date.
