### ISSUE TITLE
[Navigation] ViewModel often re-instantiates when clicking bottom-bar menu items.

### ISSUE THREAD

**Issue by kasem-sm** [google/accompanist#999]
**Version**
0.24.1-alpha (navigationAnimation & navigationMaterial)

**Description**
The Screen's ViewModel instantiates again when bottom navigation items are clicked. Though this happens sometimes but not rarely.

**Steps to reproduce**
I have attached the code and the screen recording of the same.
Code -> https://gist.github.com/kasem-sm/d0ee9e6e7e6c698e26c56e6187f79a4f

**Expected behavior** 
The ViewModel should Instantiate only for the first time.

**Additional context**

https://user-images.githubusercontent.com/83884225/152945157-cd5c9891-3d38-4bee-a31e-6d1acea71ae7.mp4

**Comment by ianhanniballake** [comment]
Can you please include your entire navigation graph in your gist or include a link to a full sample project that reproduces this?

This looks like you are popping the start destination of your graph (i.e., incorrectly using login, etc. as your start destination rather than your actual main screen that is one of your tabs as your start destination, going specifically against the [Principles of Navigation](https://developer.android.com/guide/navigation/navigation-principles#fixed_start_destination)).

**Comment by kasem-sm** [comment]
Hey @ianhanniballake, the gist didn't included my whole navigation graph and just a sample & all the other screens are added in to the graph in the same way. I'm using my profile Screen [as the start destination](https://gist.github.com/kasem-sm/d0ee9e6e7e6c698e26c56e6187f79a4f#file-navigation-kt-L4) which also checks if the user is logged in or not. (Please let me know if there is any better solution to check/verify this kind of stuffs).
I can certainly add you to my repo. 👍

**Comment by ianhanniballake** [comment]
Is the profile screen one of your tabs? Again, you haven't included that in your gist. These things actually make a huge difference, hence why providing a complete set of code that actually reproduces your problem is so important.

**Comment by kasem-sm** [comment]
I can totally understand what you are trying to say. My bad!
I have invited you as a collaborator, Please have a look inside of app module's navigation package.

**Comment by ianhanniballake** [comment]
It is exactly like I said. You use `startDestination = ProfileScreen.route`, but then you immediately pop the Profile destination off your back stack when you navigate to your login screen:

```
navigateTo = { route ->
    navController.navigate(route) {
        popUpTo(Routes.MainRoute.route)
    }
}
```

Thus popping the start destination of your graph off the back stack - exactly what the Principles of Navigation say you should not do and what breaks the `popUpTo(navController.graph.findStartDestination().id)` your bottom nav uses.

As per those Principles of Navigation, the start destination of your graph should be a fixed destination in your app and the very last screen the user sees before they go back to your launcher. That is *not* the Profile screen in your app (it very much looks like it should be your main screen).

The same techniques of [Conditional Navigation](https://developer.android.com/guide/navigation/navigation-conditional) also apply to Navigation Compose: your actual start destination should be checking for login (just like your Profile screen does), redirecting the user to the login screen.

The technique used in the docs *do not* pop any destination off the back stack (as that would cause any state the user had to be lost), but instead uses the APIs to return a result to provide information back to the start destination on whether the user chose to login (i.e., you are now set up and ready to go) or if the user cancelled logging in (i.e., by hitting the back button - of which your main screen can then choose to finish the activity if login is required).

The topic of login as also been covered in video form in the previous video [Navigating Navigation](https://youtu.be/09qjn706ITA?t=273) where the reasoning behind this technique is explained in more detail and why it is so critical when it comes to cases of process death and recreation and deep links.

Once you are following the Principles of Navigation and not popping the start destination of your graph off of the back stack, you'll find that your bottom nav works exactly as you expect.
